"""
USCIS Civics Test Question Bank

Complete question bank for the US Citizenship (USCIS Naturalization) Civics Test
with all 100 official questions. Supports quiz generation, category filtering,
and the 65/20 rule for older applicants.
"""

import random

CATEGORIES = {
    "principles": {"name": "Principles of American Democracy", "emoji": "🗽", "questions": "1-12"},
    "system": {"name": "System of Government", "emoji": "🏛️", "questions": "13-47"},
    "rights": {"name": "Rights & Responsibilities", "emoji": "⚖️", "questions": "48-57"},
    "colonial": {"name": "Colonial Period & Independence", "emoji": "📜", "questions": "58-70"},
    "1800s": {"name": "1800s", "emoji": "⚔️", "questions": "71-77"},
    "recent": {"name": "Recent American History", "emoji": "🌎", "questions": "78-87"},
    "geography": {"name": "Geography", "emoji": "🗺️", "questions": "88-95"},
    "symbols": {"name": "Symbols", "emoji": "🇺🇸", "questions": "96-98"},
    "holidays": {"name": "Holidays", "emoji": "🎆", "questions": "99-100"},
}

QUESTION_BANK = [
    {"id": 1, "category": "principles", "question": "What is the supreme law of the land?",
     "correct_answers": ["the Constitution"],
     "wrong_answers": ["the Declaration of Independence", "the Bill of Rights", "the Articles of Confederation", "the Emancipation Proclamation", "Federal Law"],
     "is_65_20": False},
    {"id": 2, "category": "principles", "question": "What does the Constitution do?",
     "correct_answers": ["sets up the government", "defines the government", "protects basic rights of Americans"],
     "wrong_answers": ["creates the military", "establishes the economy", "declares war on Britain", "sets tax rates"],
     "is_65_20": False},
    {"id": 3, "category": "principles", "question": "The idea of self-government is in the first three words of the Constitution. What are these words?",
     "correct_answers": ["We the People"],
     "wrong_answers": ["In God We Trust", "Life, Liberty, and", "United We Stand", "One Nation Under", "Freedom and Justice"],
     "is_65_20": False},
    {"id": 4, "category": "principles", "question": "What is an amendment?",
     "correct_answers": ["a change to the Constitution", "an addition to the Constitution"],
     "wrong_answers": ["a law passed by Congress", "a presidential order", "a Supreme Court ruling", "a state regulation", "a treaty"],
     "is_65_20": False},
    {"id": 5, "category": "principles", "question": "What do we call the first ten amendments to the Constitution?",
     "correct_answers": ["the Bill of Rights"],
     "wrong_answers": ["the Declaration of Rights", "the Articles of Freedom", "the Amendments of Liberty", "the Constitutional Codes", "the Freedom Amendments"],
     "is_65_20": False},
    {"id": 6, "category": "principles", "question": "What is one right or freedom from the First Amendment?",
     "correct_answers": ["speech", "religion", "assembly", "press", "petition the government"],
     "wrong_answers": ["bear arms", "right to vote", "right to a fair trial", "right to privacy", "right to own property"],
     "is_65_20": True},
    {"id": 7, "category": "principles", "question": "How many amendments does the Constitution have?",
     "correct_answers": ["twenty-seven (27)"],
     "wrong_answers": ["ten (10)", "twenty-five (25)", "thirty-three (33)", "twenty (20)", "fifteen (15)"],
     "is_65_20": False},
    {"id": 8, "category": "principles", "question": "What did the Declaration of Independence do?",
     "correct_answers": ["announced our independence from Great Britain", "declared our independence from Great Britain", "said that the United States is free from Great Britain"],
     "wrong_answers": ["freed the slaves", "established the Constitution", "ended the Civil War", "created the Bill of Rights"],
     "is_65_20": False},
    {"id": 9, "category": "principles", "question": "What are two rights in the Declaration of Independence?",
     "correct_answers": ["life and liberty", "liberty and pursuit of happiness", "life and pursuit of happiness"],
     "wrong_answers": ["speech and religion", "vote and bear arms", "education and healthcare", "property and privacy"],
     "is_65_20": False},
    {"id": 10, "category": "principles", "question": "What is freedom of religion?",
     "correct_answers": ["You can practice any religion, or not practice a religion."],
     "wrong_answers": ["You must follow one religion", "The government picks the national religion", "Religion is not allowed in public", "Only Christianity is allowed"],
     "is_65_20": False},
    {"id": 11, "category": "principles", "question": "What is the economic system in the United States?",
     "correct_answers": ["capitalist economy", "market economy"],
     "wrong_answers": ["socialist economy", "communist economy", "command economy", "feudal economy", "mixed economy"],
     "is_65_20": True},
    {"id": 12, "category": "principles", "question": "What is the \"rule of law\"?",
     "correct_answers": ["Everyone must follow the law.", "Leaders must obey the law.", "Government must obey the law.", "No one is above the law."],
     "wrong_answers": ["The President makes all laws", "Only citizens must follow the law", "Laws apply only to criminals", "States decide which laws to follow"],
     "is_65_20": False},
    {"id": 13, "category": "system", "question": "Name one branch or part of the government.",
     "correct_answers": ["Congress", "legislative", "President", "executive", "the courts", "judicial"],
     "wrong_answers": ["the military", "the police", "the Federal Reserve", "the media", "the United Nations"],
     "is_65_20": True},
    {"id": 14, "category": "system", "question": "What stops one branch of government from becoming too powerful?",
     "correct_answers": ["checks and balances", "separation of powers"],
     "wrong_answers": ["the military", "the Constitution alone", "the President's veto only", "public opinion", "state governments"],
     "is_65_20": False},
    {"id": 15, "category": "system", "question": "Who is in charge of the executive branch?",
     "correct_answers": ["the President"],
     "wrong_answers": ["the Vice President", "the Speaker of the House", "the Chief Justice", "Congress", "the Secretary of State"],
     "is_65_20": False},
    {"id": 16, "category": "system", "question": "Who makes federal laws?",
     "correct_answers": ["Congress", "Senate and House of Representatives", "U.S. legislature", "national legislature"],
     "wrong_answers": ["the President", "the Supreme Court", "state governors", "the Vice President", "the military"],
     "is_65_20": False},
    {"id": 17, "category": "system", "question": "What are the two parts of the U.S. Congress?",
     "correct_answers": ["the Senate and House of Representatives"],
     "wrong_answers": ["the Supreme Court and Congress", "the President and Vice President", "the House and the Cabinet", "Democrats and Republicans"],
     "is_65_20": True},
    {"id": 18, "category": "system", "question": "How many U.S. Senators are there?",
     "correct_answers": ["one hundred (100)"],
     "wrong_answers": ["fifty (50)", "four hundred thirty-five (435)", "seventy-five (75)", "two hundred (200)", "fifty-two (52)"],
     "is_65_20": False},
    {"id": 19, "category": "system", "question": "We elect a U.S. Senator for how many years?",
     "correct_answers": ["six (6)"],
     "wrong_answers": ["two (2)", "four (4)", "eight (8)", "ten (10)", "five (5)"],
     "is_65_20": False},
    {"id": 20, "category": "system", "question": "Who is one of your state's U.S. Senators now?",
     "correct_answers": ["Answers will vary by state"],
     "wrong_answers": ["The President", "The Governor", "The Mayor", "The Vice President"],
     "is_65_20": True},
    {"id": 21, "category": "system", "question": "The House of Representatives has how many voting members?",
     "correct_answers": ["four hundred thirty-five (435)"],
     "wrong_answers": ["one hundred (100)", "two hundred (200)", "five hundred (500)", "three hundred fifty (350)", "fifty (50)"],
     "is_65_20": False},
    {"id": 22, "category": "system", "question": "We elect a U.S. Representative for how many years?",
     "correct_answers": ["two (2)"],
     "wrong_answers": ["four (4)", "six (6)", "eight (8)", "three (3)", "five (5)"],
     "is_65_20": False},
    {"id": 23, "category": "system", "question": "Name your U.S. Representative.",
     "correct_answers": ["Answers will vary by district"],
     "wrong_answers": ["The President", "The Governor", "The Senator", "The Vice President"],
     "is_65_20": False},
    {"id": 24, "category": "system", "question": "Who does a U.S. Senator represent?",
     "correct_answers": ["all people of the state"],
     "wrong_answers": ["only people who voted for them", "only their political party", "only one city", "only citizens"],
     "is_65_20": False},
    {"id": 25, "category": "system", "question": "Why do some states have more Representatives than other states?",
     "correct_answers": ["because of the state's population", "because they have more people", "because some states have more people"],
     "wrong_answers": ["because of the state's size", "because of the state's age", "because of the state's wealth", "because of the state's location"],
     "is_65_20": False},
    {"id": 26, "category": "system", "question": "We elect a President for how many years?",
     "correct_answers": ["four (4)"],
     "wrong_answers": ["two (2)", "six (6)", "eight (8)", "five (5)", "three (3)"],
     "is_65_20": False},
    {"id": 27, "category": "system", "question": "In what month do we vote for President?",
     "correct_answers": ["November"],
     "wrong_answers": ["January", "July", "October", "December", "September"],
     "is_65_20": True},
    {"id": 28, "category": "system", "question": "What is the name of the President of the United States now?",
     "correct_answers": ["Donald Trump", "Trump"],
     "wrong_answers": ["Joe Biden", "Barack Obama", "George W. Bush", "Bill Clinton"],
     "is_65_20": True},
    {"id": 29, "category": "system", "question": "What is the name of the Vice President of the United States now?",
     "correct_answers": ["JD Vance", "J.D. Vance"],
     "wrong_answers": ["Kamala Harris", "Mike Pence", "Tim Walz", "Joe Biden"],
     "is_65_20": False},
    {"id": 30, "category": "system", "question": "If the President can no longer serve, who becomes President?",
     "correct_answers": ["the Vice President"],
     "wrong_answers": ["the Speaker of the House", "the Secretary of State", "the Chief Justice", "the Senate Majority Leader"],
     "is_65_20": False},
    {"id": 31, "category": "system", "question": "If both the President and the Vice President can no longer serve, who becomes President?",
     "correct_answers": ["the Speaker of the House"],
     "wrong_answers": ["the Secretary of State", "the Chief Justice", "the Senate Majority Leader", "the Secretary of Defense"],
     "is_65_20": False},
    {"id": 32, "category": "system", "question": "Who is the Commander in Chief of the military?",
     "correct_answers": ["the President"],
     "wrong_answers": ["the Secretary of Defense", "the Chairman of the Joint Chiefs", "the Vice President", "Congress"],
     "is_65_20": False},
    {"id": 33, "category": "system", "question": "Who signs bills to become laws?",
     "correct_answers": ["the President"],
     "wrong_answers": ["the Vice President", "the Speaker of the House", "the Chief Justice", "Congress"],
     "is_65_20": False},
    {"id": 34, "category": "system", "question": "Who vetoes bills?",
     "correct_answers": ["the President"],
     "wrong_answers": ["Congress", "the Supreme Court", "the Vice President", "the Speaker of the House"],
     "is_65_20": False},
    {"id": 35, "category": "system", "question": "What does the President's Cabinet do?",
     "correct_answers": ["advises the President"],
     "wrong_answers": ["makes laws", "interprets the Constitution", "elects the Vice President", "commands the military"],
     "is_65_20": False},
    {"id": 36, "category": "system", "question": "What are two Cabinet-level positions?",
     "correct_answers": ["Secretary of State and Secretary of Defense", "Secretary of Education and Secretary of Energy", "Secretary of the Treasury and Attorney General", "Secretary of Homeland Security and Secretary of Labor"],
     "wrong_answers": ["Senator and Representative", "Governor and Mayor", "President and Vice President only", "Chief Justice and Attorney"],
     "is_65_20": False},
    {"id": 37, "category": "system", "question": "What does the judicial branch do?",
     "correct_answers": ["reviews laws", "explains laws", "resolves disputes", "decides if a law goes against the Constitution"],
     "wrong_answers": ["makes laws", "enforces laws", "collects taxes", "commands the military"],
     "is_65_20": False},
    {"id": 38, "category": "system", "question": "What is the highest court in the United States?",
     "correct_answers": ["the Supreme Court"],
     "wrong_answers": ["the Court of Appeals", "the District Court", "the Federal Court", "the Constitutional Court"],
     "is_65_20": False},
    {"id": 39, "category": "system", "question": "How many justices are on the Supreme Court?",
     "correct_answers": ["nine (9)"],
     "wrong_answers": ["seven (7)", "eleven (11)", "twelve (12)", "five (5)", "fifteen (15)"],
     "is_65_20": False},
    {"id": 40, "category": "system", "question": "Who is the Chief Justice of the United States now?",
     "correct_answers": ["John Roberts"],
     "wrong_answers": ["Clarence Thomas", "Samuel Alito", "Sonia Sotomayor", "Neil Gorsuch"],
     "is_65_20": False},
    {"id": 41, "category": "system", "question": "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
     "correct_answers": ["to print money", "to declare war", "to create an army", "to make treaties"],
     "wrong_answers": ["to provide schooling", "to issue driver's licenses", "to provide police", "to approve zoning"],
     "is_65_20": False},
    {"id": 42, "category": "system", "question": "Under our Constitution, some powers belong to the states. What is one power of the states?",
     "correct_answers": ["provide schooling and education", "provide protection (police)", "provide safety (fire departments)", "give a driver's license", "approve zoning and land use"],
     "wrong_answers": ["print money", "declare war", "create an army", "make treaties"],
     "is_65_20": False},
    {"id": 43, "category": "system", "question": "Who is the Governor of your state now?",
     "correct_answers": ["Answers will vary by state"],
     "wrong_answers": ["The President", "The Mayor", "The Senator", "The Representative"],
     "is_65_20": False},
    {"id": 44, "category": "system", "question": "What is the capital of your state?",
     "correct_answers": ["Answers will vary by state"],
     "wrong_answers": ["Washington D.C.", "New York City", "Los Angeles", "The largest city"],
     "is_65_20": True},
    {"id": 45, "category": "system", "question": "What are the two major political parties in the United States?",
     "correct_answers": ["Democratic and Republican"],
     "wrong_answers": ["Libertarian and Green", "Federalist and Anti-Federalist", "Conservative and Liberal", "Whig and Tory"],
     "is_65_20": True},
    {"id": 46, "category": "system", "question": "What is the political party of the President now?",
     "correct_answers": ["Republican"],
     "wrong_answers": ["Democratic", "Independent", "Libertarian", "Green"],
     "is_65_20": False},
    {"id": 47, "category": "system", "question": "What is the name of the Speaker of the House of Representatives now?",
     "correct_answers": ["Mike Johnson"],
     "wrong_answers": ["Nancy Pelosi", "Kevin McCarthy", "Mitch McConnell", "Chuck Schumer"],
     "is_65_20": False},
    {"id": 48, "category": "rights", "question": "There are four amendments to the Constitution about who can vote. Describe one of them.",
     "correct_answers": ["Citizens eighteen (18) and older can vote.", "You don't have to pay a poll tax to vote.", "Any citizen can vote. (Women and men can vote.)", "A male citizen of any race can vote."],
     "wrong_answers": ["Only property owners can vote", "Only men can vote", "You must pass a test to vote", "Only people over 21 can vote"],
     "is_65_20": False},
    {"id": 49, "category": "rights", "question": "What is one responsibility that is only for United States citizens?",
     "correct_answers": ["serve on a jury", "vote in a federal election"],
     "wrong_answers": ["pay taxes", "obey the law", "attend school", "serve in the military"],
     "is_65_20": True},
    {"id": 50, "category": "rights", "question": "Name one right only for United States citizens.",
     "correct_answers": ["vote in a federal election", "run for federal office"],
     "wrong_answers": ["freedom of speech", "freedom of religion", "right to a trial", "right to an attorney"],
     "is_65_20": False},
    {"id": 51, "category": "rights", "question": "What are two rights of everyone living in the United States?",
     "correct_answers": ["freedom of expression and freedom of speech", "freedom of assembly and freedom of religion", "freedom of speech and the right to bear arms", "freedom to petition the government and freedom of religion"],
     "wrong_answers": ["vote in elections and run for office", "own a business and vote", "carry a passport and vote", "run for president and vote"],
     "is_65_20": False},
    {"id": 52, "category": "rights", "question": "What do we show loyalty to when we say the Pledge of Allegiance?",
     "correct_answers": ["the United States", "the flag"],
     "wrong_answers": ["the President", "the Constitution", "the military", "Congress"],
     "is_65_20": False},
    {"id": 53, "category": "rights", "question": "What is one promise you make when you become a United States citizen?",
     "correct_answers": ["give up loyalty to other countries", "defend the Constitution and laws of the United States", "obey the laws of the United States", "serve in the U.S. military (if needed)", "be loyal to the United States"],
     "wrong_answers": ["pay higher taxes", "never leave the country", "vote in every election", "learn a second language"],
     "is_65_20": False},
    {"id": 54, "category": "rights", "question": "How old do citizens have to be to vote for President?",
     "correct_answers": ["eighteen (18) and older"],
     "wrong_answers": ["sixteen (16)", "twenty-one (21)", "twenty-five (25)", "thirty (30)"],
     "is_65_20": True},
    {"id": 55, "category": "rights", "question": "What are two ways that Americans can participate in their democracy?",
     "correct_answers": ["vote and join a political party", "help with a campaign and join a civic group", "give an elected official your opinion and vote", "run for office and write to a newspaper"],
     "wrong_answers": ["pay taxes and obey the law", "join the military and pay taxes", "watch the news and obey the law", "go to school and pay taxes"],
     "is_65_20": False},
    {"id": 56, "category": "rights", "question": "When is the last day you can send in federal income tax forms?",
     "correct_answers": ["April 15"],
     "wrong_answers": ["January 1", "March 15", "July 4", "December 31", "May 1"],
     "is_65_20": True},
    {"id": 57, "category": "rights", "question": "When must all men register for the Selective Service?",
     "correct_answers": ["at age eighteen (18)", "between eighteen (18) and twenty-six (26)"],
     "wrong_answers": ["at age sixteen (16)", "at age twenty-one (21)", "at age twenty-five (25)", "when they graduate high school"],
     "is_65_20": False},
    {"id": 58, "category": "colonial", "question": "What is one reason colonists came to America?",
     "correct_answers": ["freedom", "political liberty", "religious freedom", "economic opportunity", "practice their religion", "escape persecution"],
     "wrong_answers": ["to find gold only", "to build railroads", "to trade with China", "to fight Native Americans"],
     "is_65_20": False},
    {"id": 59, "category": "colonial", "question": "Who lived in America before the Europeans arrived?",
     "correct_answers": ["American Indians", "Native Americans"],
     "wrong_answers": ["the British", "the Spanish", "the Africans", "the Pilgrims", "the French"],
     "is_65_20": False},
    {"id": 60, "category": "colonial", "question": "What group of people was taken to America and sold as slaves?",
     "correct_answers": ["Africans", "people from Africa"],
     "wrong_answers": ["Europeans", "Asians", "Native Americans", "South Americans"],
     "is_65_20": False},
    {"id": 61, "category": "colonial", "question": "Why did the colonists fight the British?",
     "correct_answers": ["because of high taxes (taxation without representation)", "because the British army stayed in their houses", "because they didn't have self-government"],
     "wrong_answers": ["because of religious differences", "because of a border dispute", "because they wanted to join France", "because of trade with China"],
     "is_65_20": False},
    {"id": 62, "category": "colonial", "question": "Who wrote the Declaration of Independence?",
     "correct_answers": ["Thomas Jefferson"],
     "wrong_answers": ["George Washington", "Benjamin Franklin", "John Adams", "James Madison", "Alexander Hamilton"],
     "is_65_20": False},
    {"id": 63, "category": "colonial", "question": "When was the Declaration of Independence adopted?",
     "correct_answers": ["July 4, 1776"],
     "wrong_answers": ["July 4, 1774", "July 4, 1789", "July 4, 1800", "March 4, 1776", "January 1, 1776"],
     "is_65_20": False},
    {"id": 64, "category": "colonial", "question": "There were 13 original states. Name three.",
     "correct_answers": ["Virginia, Massachusetts, and New York", "Pennsylvania, Maryland, and Georgia", "New Hampshire, Connecticut, and Delaware", "New Jersey, Rhode Island, and North Carolina", "South Carolina, Virginia, and Maryland"],
     "wrong_answers": ["California, Texas, and Florida", "Ohio, Kentucky, and Vermont", "Maine, Alabama, and Tennessee", "Oregon, Washington, and Louisiana"],
     "is_65_20": False},
    {"id": 65, "category": "colonial", "question": "What happened at the Constitutional Convention?",
     "correct_answers": ["The Constitution was written.", "The Founding Fathers wrote the Constitution."],
     "wrong_answers": ["The Declaration of Independence was signed", "The Bill of Rights was adopted", "Slavery was abolished", "The President was elected"],
     "is_65_20": False},
    {"id": 66, "category": "colonial", "question": "When was the Constitution written?",
     "correct_answers": ["1787"],
     "wrong_answers": ["1776", "1789", "1800", "1791", "1774"],
     "is_65_20": False},
    {"id": 67, "category": "colonial", "question": "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
     "correct_answers": ["James Madison", "Alexander Hamilton", "John Jay", "Publius"],
     "wrong_answers": ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "John Adams", "Samuel Adams"],
     "is_65_20": False},
    {"id": 68, "category": "colonial", "question": "What is one thing Benjamin Franklin is famous for?",
     "correct_answers": ["U.S. diplomat", "oldest member of the Constitutional Convention", "first Postmaster General of the United States", "writer of Poor Richard's Almanac", "started the first free libraries"],
     "wrong_answers": ["writing the Declaration of Independence", "being the first President", "leading the Continental Army", "inventing the telephone"],
     "is_65_20": False},
    {"id": 69, "category": "colonial", "question": "Who is the \"Father of Our Country\"?",
     "correct_answers": ["George Washington"],
     "wrong_answers": ["Thomas Jefferson", "Abraham Lincoln", "Benjamin Franklin", "John Adams", "James Madison"],
     "is_65_20": False},
    {"id": 70, "category": "colonial", "question": "Who was the first President?",
     "correct_answers": ["George Washington"],
     "wrong_answers": ["Thomas Jefferson", "John Adams", "Abraham Lincoln", "Benjamin Franklin"],
     "is_65_20": True},
    {"id": 71, "category": "1800s", "question": "What territory did the United States buy from France in 1803?",
     "correct_answers": ["the Louisiana Territory", "Louisiana"],
     "wrong_answers": ["Alaska", "Florida", "Texas", "California", "Oregon"],
     "is_65_20": False},
    {"id": 72, "category": "1800s", "question": "Name one war fought by the United States in the 1800s.",
     "correct_answers": ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"],
     "wrong_answers": ["World War I", "Revolutionary War", "Vietnam War", "Korean War"],
     "is_65_20": False},
    {"id": 73, "category": "1800s", "question": "Name the U.S. war between the North and the South.",
     "correct_answers": ["the Civil War", "the War between the States"],
     "wrong_answers": ["the Revolutionary War", "the War of 1812", "World War I", "the Mexican-American War"],
     "is_65_20": False},
    {"id": 74, "category": "1800s", "question": "Name one problem that led to the Civil War.",
     "correct_answers": ["slavery", "economic reasons", "states' rights"],
     "wrong_answers": ["taxation", "British invasion", "gold rush", "immigration"],
     "is_65_20": False},
    {"id": 75, "category": "1800s", "question": "What was one important thing that Abraham Lincoln did?",
     "correct_answers": ["freed the slaves (Emancipation Proclamation)", "saved (or preserved) the Union", "led the United States during the Civil War"],
     "wrong_answers": ["wrote the Constitution", "was the first President", "discovered America", "ended World War I"],
     "is_65_20": True},
    {"id": 76, "category": "1800s", "question": "What did the Emancipation Proclamation do?",
     "correct_answers": ["freed the slaves", "freed slaves in the Confederacy", "freed slaves in the Confederate states", "freed slaves in most Southern states"],
     "wrong_answers": ["ended the Civil War", "gave women the right to vote", "established the Constitution", "declared independence"],
     "is_65_20": False},
    {"id": 77, "category": "1800s", "question": "What did Susan B. Anthony do?",
     "correct_answers": ["fought for women's rights", "fought for civil rights"],
     "wrong_answers": ["freed the slaves", "wrote the Constitution", "invented the telephone", "discovered America"],
     "is_65_20": False},
    {"id": 78, "category": "recent", "question": "Name one war fought by the United States in the 1900s.",
     "correct_answers": ["World War I", "World War II", "Korean War", "Vietnam War", "Persian Gulf War"],
     "wrong_answers": ["the Civil War", "the War of 1812", "the Revolutionary War", "the Mexican-American War"],
     "is_65_20": True},
    {"id": 79, "category": "recent", "question": "Who was President during World War I?",
     "correct_answers": ["Woodrow Wilson"],
     "wrong_answers": ["Theodore Roosevelt", "Franklin Roosevelt", "Abraham Lincoln", "Harry Truman", "Herbert Hoover"],
     "is_65_20": False},
    {"id": 80, "category": "recent", "question": "Who was President during the Great Depression and World War II?",
     "correct_answers": ["Franklin Roosevelt", "Franklin D. Roosevelt", "FDR"],
     "wrong_answers": ["Herbert Hoover", "Harry Truman", "Woodrow Wilson", "Dwight Eisenhower"],
     "is_65_20": False},
    {"id": 81, "category": "recent", "question": "Who did the United States fight in World War II?",
     "correct_answers": ["Japan, Germany, and Italy"],
     "wrong_answers": ["England, France, and Spain", "Russia, China, and Japan", "Germany, France, and Spain", "Mexico, Canada, and Cuba"],
     "is_65_20": False},
    {"id": 82, "category": "recent", "question": "Before he was President, Eisenhower was a general. What war was he in?",
     "correct_answers": ["World War II"],
     "wrong_answers": ["World War I", "Korean War", "Vietnam War", "Civil War"],
     "is_65_20": False},
    {"id": 83, "category": "recent", "question": "During the Cold War, what was the main concern of the United States?",
     "correct_answers": ["Communism"],
     "wrong_answers": ["Terrorism", "Fascism", "Imperialism", "Nuclear weapons only"],
     "is_65_20": False},
    {"id": 84, "category": "recent", "question": "What movement tried to end racial discrimination?",
     "correct_answers": ["civil rights movement"],
     "wrong_answers": ["women's suffrage movement", "labor movement", "temperance movement", "environmental movement"],
     "is_65_20": False},
    {"id": 85, "category": "recent", "question": "What did Martin Luther King, Jr. do?",
     "correct_answers": ["fought for civil rights", "worked for equality for all Americans"],
     "wrong_answers": ["was the first Black President", "freed the slaves", "wrote the Constitution", "invented something important"],
     "is_65_20": True},
    {"id": 86, "category": "recent", "question": "What major event happened on September 11, 2001, in the United States?",
     "correct_answers": ["Terrorists attacked the United States."],
     "wrong_answers": ["A hurricane hit New York", "The stock market crashed", "An earthquake struck California", "A war was declared"],
     "is_65_20": False},
    {"id": 87, "category": "recent", "question": "Name one American Indian tribe in the United States.",
     "correct_answers": ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Hopi", "Inuit"],
     "wrong_answers": ["Aztec", "Maya", "Inca", "Viking", "Celtic"],
     "is_65_20": False},
    {"id": 88, "category": "geography", "question": "Name one of the two longest rivers in the United States.",
     "correct_answers": ["Missouri River", "Mississippi River"],
     "wrong_answers": ["Colorado River", "Ohio River", "Hudson River", "Rio Grande"],
     "is_65_20": False},
    {"id": 89, "category": "geography", "question": "What ocean is on the West Coast of the United States?",
     "correct_answers": ["Pacific Ocean"],
     "wrong_answers": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Gulf of Mexico"],
     "is_65_20": False},
    {"id": 90, "category": "geography", "question": "What ocean is on the East Coast of the United States?",
     "correct_answers": ["Atlantic Ocean"],
     "wrong_answers": ["Pacific Ocean", "Indian Ocean", "Arctic Ocean", "Gulf of Mexico"],
     "is_65_20": False},
    {"id": 91, "category": "geography", "question": "Name one U.S. territory.",
     "correct_answers": ["Puerto Rico", "U.S. Virgin Islands", "American Samoa", "Northern Mariana Islands", "Guam"],
     "wrong_answers": ["Hawaii", "Alaska", "Washington D.C.", "Cuba", "Mexico"],
     "is_65_20": False},
    {"id": 92, "category": "geography", "question": "Name one state that borders Canada.",
     "correct_answers": ["Maine", "New Hampshire", "Vermont", "New York", "Pennsylvania", "Ohio", "Michigan", "Minnesota", "North Dakota", "Montana", "Idaho", "Washington", "Alaska"],
     "wrong_answers": ["California", "Texas", "Florida", "Georgia", "Louisiana"],
     "is_65_20": False},
    {"id": 93, "category": "geography", "question": "Name one state that borders Mexico.",
     "correct_answers": ["California", "Arizona", "New Mexico", "Texas"],
     "wrong_answers": ["Florida", "Louisiana", "Colorado", "Nevada", "Oregon"],
     "is_65_20": False},
    {"id": 94, "category": "geography", "question": "What is the capital of the United States?",
     "correct_answers": ["Washington, D.C."],
     "wrong_answers": ["New York City", "Philadelphia", "Boston", "Los Angeles"],
     "is_65_20": True},
    {"id": 95, "category": "geography", "question": "Where is the Statue of Liberty?",
     "correct_answers": ["New York Harbor", "Liberty Island", "New Jersey", "New York City", "on the Hudson River"],
     "wrong_answers": ["Washington, D.C.", "Philadelphia", "Boston", "Los Angeles", "San Francisco"],
     "is_65_20": True},
    {"id": 96, "category": "symbols", "question": "Why does the flag have 13 stripes?",
     "correct_answers": ["because there were 13 original colonies", "because the stripes represent the original colonies"],
     "wrong_answers": ["because there were 13 Presidents", "because of the 13 amendments", "because of 13 wars", "because there are 13 territories"],
     "is_65_20": False},
    {"id": 97, "category": "symbols", "question": "Why does the flag have 50 stars?",
     "correct_answers": ["because there is one star for each state", "because each star represents a state", "because there are 50 states"],
     "wrong_answers": ["because of the 50 original colonies", "because of 50 presidents", "because of 50 amendments", "because of 50 territories"],
     "is_65_20": True},
    {"id": 98, "category": "symbols", "question": "What is the name of the national anthem?",
     "correct_answers": ["The Star-Spangled Banner"],
     "wrong_answers": ["America the Beautiful", "God Bless America", "My Country Tis of Thee", "Battle Hymn of the Republic"],
     "is_65_20": False},
    {"id": 99, "category": "holidays", "question": "When do we celebrate Independence Day?",
     "correct_answers": ["July 4"],
     "wrong_answers": ["June 4", "July 14", "November 4", "January 1", "December 25"],
     "is_65_20": True},
    {"id": 100, "category": "holidays", "question": "Name two national U.S. holidays.",
     "correct_answers": ["Independence Day and Thanksgiving", "Christmas and New Year's Day", "Memorial Day and Veterans Day", "Martin Luther King Jr. Day and Presidents' Day", "Labor Day and Columbus Day"],
     "wrong_answers": ["Valentine's Day and Easter", "Halloween and St. Patrick's Day", "Mother's Day and Father's Day", "Super Bowl Sunday and Election Day"],
     "is_65_20": False},
]

STATE_SPECIFIC_IDS = {20, 23, 43, 44}


def generate_quiz(num_questions=10, category=None, state=None):
    """
    Generate a quiz with the specified number of questions.

    Args:
        num_questions: Number of questions to include (default 10).
        category: Optional category ID to filter questions. If None, uses full bank.
        state: Optional dict with state-specific answers for questions 20, 23, 43, 44.
               If None, those questions are skipped.

    Returns:
        List of dicts with: id, category, question, options (4 strings), answer (0-based index),
        all_correct (all valid answers for display).
    """
    pool = [q for q in QUESTION_BANK if q["id"] not in STATE_SPECIFIC_IDS or state is not None]

    if category is not None:
        pool = [q for q in pool if q["category"] == category]

    if len(pool) < num_questions:
        num_questions = len(pool)

    selected = random.sample(pool, num_questions)
    quiz = []

    state_keys = {20: "senator", 23: "representative", 43: "governor", 44: "capital"}

    for q in selected:
        if q["id"] in STATE_SPECIFIC_IDS and state:
            state_key = state_keys.get(q["id"])
            if state_key and state_key in state:
                correct = state[state_key]
                all_correct = [state[state_key]]
            else:
                correct = random.choice(q["correct_answers"])
                all_correct = q["correct_answers"]
        else:
            correct = random.choice(q["correct_answers"])
            all_correct = q["correct_answers"]

        wrong_pool = q["wrong_answers"].copy()
        random.shuffle(wrong_pool)
        wrong = wrong_pool[:3]

        options = [correct] + wrong
        random.shuffle(options)
        answer_idx = options.index(correct)

        quiz.append({
            "id": q["id"],
            "category": q["category"],
            "question": q["question"],
            "options": options,
            "answer": answer_idx,
            "all_correct": all_correct,
        })

    return quiz


def get_passing_score(num_questions=10):
    """
    Return the number of correct answers needed to pass the civics test.

    For 10 questions: 6 correct.
    For 20 questions: 12 correct.
    """
    if num_questions == 20:
        return 12
    return 6


CATEGORY_COLORS = {
    "principles": "#4A90D9",
    "system": "#7B68EE",
    "rights": "#50C878",
    "colonial": "#D4A574",
    "1800s": "#CD5C5C",
    "recent": "#20B2AA",
    "geography": "#4682B4",
    "symbols": "#B22222",
    "holidays": "#FF8C00",
}
