"""
Logo Identifier — brand logo recognition quiz for Arjun.

Uses Google's free favicon API for logo images (no auth required).
Only includes brands with ICONIC SYMBOL logos (no readable text)
so the quiz requires genuine recognition, not just reading the name.
"""

import random

CATEGORIES = {
    "tech": {
        "name": "Tech & Apps",
        "emoji": "💻",
        "color": "#3b82f6",
        "description": "Technology companies and popular apps",
    },
    "food": {
        "name": "Food & Drinks",
        "emoji": "🍔",
        "color": "#ef4444",
        "description": "Restaurants, snacks & beverage brands",
    },
    "sports": {
        "name": "Sports & Outdoors",
        "emoji": "⚽",
        "color": "#10b981",
        "description": "Athletic brands and sports organisations",
    },
    "cars": {
        "name": "Cars & Transport",
        "emoji": "🚗",
        "color": "#f59e0b",
        "description": "Automobile and transportation brands",
    },
    "entertainment": {
        "name": "Entertainment & Media",
        "emoji": "🎮",
        "color": "#8b5cf6",
        "description": "Games, streaming & media companies",
    },
    "fashion": {
        "name": "Fashion & Lifestyle",
        "emoji": "👟",
        "color": "#ec4899",
        "description": "Clothing, shoes & lifestyle brands",
    },
}

LOGO_SIZE = 256


def get_logo_url(domain: str) -> str:
    return f"https://www.google.com/s2/favicons?domain={domain}&sz={LOGO_SIZE}"


# Only brands with recognisable SYMBOL / ICON favicons.
# Excluded: brands whose favicon is just their name in text (LinkedIn, Honda, etc.)
QUESTION_BANK = [
    # ========== TECH & APPS (symbol-based favicons) ==========
    {
        "id": 1, "category": "tech",
        "company": "Apple", "domain": "apple.com",
        "hint": "A fruit with a bite taken out of it",
        "options": ["Apple", "Huawei", "BlackBerry", "LG"],
        "fun_fact": "The Apple logo was designed by Rob Janoff in 1977. The bite was added so it wouldn't be confused with a cherry!",
        "image": "apple",
    },
    {
        "id": 2, "category": "tech",
        "company": "Instagram", "domain": "instagram.com",
        "hint": "A gradient camera icon on a purple-orange background",
        "options": ["Instagram", "VSCO", "Snapchat", "Flickr"],
        "fun_fact": "Instagram's camera icon was redesigned in 2016 from a retro Polaroid-style camera to a modern gradient!",
        "image": "instagram",
    },
    {
        "id": 3, "category": "tech",
        "company": "Spotify", "domain": "spotify.com",
        "hint": "Three curved lines on a green circle",
        "options": ["Spotify", "SoundCloud", "Shazam", "Deezer"],
        "fun_fact": "Spotify's green logo has three sound waves — representing music streaming to your ears!",
        "image": "spotify",
    },
    {
        "id": 4, "category": "tech",
        "company": "Snapchat", "domain": "snapchat.com",
        "hint": "A white ghost outline on a yellow background",
        "options": ["Snapchat", "Discord", "Waze", "Bumble"],
        "fun_fact": "Snapchat's ghost logo was hand-drawn by co-founder Evan Spiegel — it represents disappearing messages!",
        "image": "snapchat",
    },
    {
        "id": 5, "category": "tech",
        "company": "WhatsApp", "domain": "whatsapp.com",
        "hint": "A white phone inside a speech bubble on a green background",
        "options": ["WhatsApp", "Signal", "Telegram", "Viber"],
        "fun_fact": "WhatsApp was created by two ex-Yahoo employees and bought by Facebook for $19 billion in 2014!",
        "image": "whatsapp",
    },
    {
        "id": 6, "category": "tech",
        "company": "Reddit", "domain": "reddit.com",
        "hint": "An alien face with an antenna on an orange background",
        "options": ["Reddit", "Alien Blue", "Quora", "Tumblr"],
        "fun_fact": "Reddit's alien mascot is called Snoo — short for 'what's new'!",
        "image": "reddit",
    },
    {
        "id": 7, "category": "tech",
        "company": "GitHub", "domain": "github.com",
        "hint": "A cat with octopus tentacles silhouette",
        "options": ["GitHub", "GitLab", "Bitbucket", "SourceForge"],
        "fun_fact": "GitHub's mascot is the Octocat — a cat with octopus tentacles. Its original name was Octopuss!",
        "image": "github",
    },
    {
        "id": 8, "category": "tech",
        "company": "Discord", "domain": "discord.com",
        "hint": "A smiling game controller face on purple/indigo",
        "options": ["Discord", "TeamSpeak", "Slack", "Guilded"],
        "fun_fact": "Discord's mascot is called Clyde — the smiling game controller face was designed to feel friendly!",
        "image": "discord",
    },
    {
        "id": 9, "category": "tech",
        "company": "Twitch", "domain": "twitch.tv",
        "hint": "A speech bubble with eyes on a purple background",
        "options": ["Twitch", "Kick", "Mixer", "YouTube Gaming"],
        "fun_fact": "Twitch's 'Glitch' logo represents live chat bubbles while watching game streams!",
        "image": "twitch",
    },
    {
        "id": 10, "category": "tech",
        "company": "Dropbox", "domain": "dropbox.com",
        "hint": "An open blue box made of diamond shapes",
        "options": ["Dropbox", "Box", "Google Drive", "OneDrive"],
        "fun_fact": "Dropbox's open box logo was designed to look like an unfolded cardboard box from above!",
        "image": "dropbox",
    },
    {
        "id": 11, "category": "tech",
        "company": "Airbnb", "domain": "airbnb.com",
        "hint": "A rounded symbol that looks like a letter A or a heart on a red/coral background",
        "options": ["Airbnb", "Booking.com", "Vrbo", "Trivago"],
        "fun_fact": "Airbnb's logo is called the Bélo — it combines people, places, love, and the letter A!",
        "image": "airbnb",
    },
    {
        "id": 12, "category": "tech",
        "company": "Slack", "domain": "slack.com",
        "hint": "A hashtag-like shape made of colourful rounded bars",
        "options": ["Slack", "Trello", "Asana", "Notion"],
        "fun_fact": "Slack originally stood for 'Searchable Log of All Conversation and Knowledge'!",
        "image": "slack",
    },
    {
        "id": 13, "category": "tech",
        "company": "Microsoft", "domain": "microsoft.com",
        "hint": "Four coloured squares arranged in a 2×2 grid (red, green, blue, yellow)",
        "options": ["Microsoft", "Google", "Slack", "Samsung"],
        "fun_fact": "Microsoft's four-coloured window logo represents the diversity of their products and users!",
        "image": "microsoft",
    },
    {
        "id": 14, "category": "tech",
        "company": "TikTok", "domain": "tiktok.com",
        "hint": "A 3D-looking musical note in neon pink/blue on a dark background",
        "options": ["TikTok", "Musical.ly", "Triller", "Dubsmash"],
        "fun_fact": "TikTok's logo looks like a 3D musical note with neon colors inspired by concert stage lighting!",
        "image": "tiktok",
    },
    {
        "id": 15, "category": "tech",
        "company": "Pinterest", "domain": "pinterest.com",
        "hint": "A stylised letter that looks like a map pin on a red background",
        "options": ["Pinterest", "Pinboard", "Yelp", "Foursquare"],
        "fun_fact": "Pinterest's 'P' logo is shaped like a map pin — because you 'pin' your interests to boards!",
        "image": "pinterest",
    },
    {
        "id": 16, "category": "tech",
        "company": "YouTube", "domain": "youtube.com",
        "hint": "A white play-button triangle inside a red rounded rectangle",
        "options": ["YouTube", "Vimeo", "Dailymotion", "Rumble"],
        "fun_fact": "The first YouTube video, 'Me at the zoo', was uploaded on April 23, 2005 by co-founder Jawed Karim!",
        "image": "youtube",
    },
    {
        "id": 17, "category": "tech",
        "company": "Shazam", "domain": "shazam.com",
        "hint": "A stylised 'S' shape on a blue gradient circle",
        "options": ["Shazam", "SoundHound", "Spotify", "Deezer"],
        "fun_fact": "Shazam can identify a song in just a few seconds by matching its audio fingerprint to a database of millions!",
        "image": "shazam",
    },
    {
        "id": 18, "category": "tech",
        "company": "Zoom", "domain": "zoom.us",
        "hint": "A white video camera icon on a blue background",
        "options": ["Zoom", "Skype", "Google Meet", "WebEx"],
        "fun_fact": "Zoom usage jumped from 10 million to 300 million daily users during the 2020 pandemic!",
        "image": "zoom",
    },

    # ========== FOOD & DRINKS (symbol-based favicons) ==========
    {
        "id": 19, "category": "food",
        "company": "Starbucks", "domain": "starbucks.com",
        "hint": "A green circle with a two-tailed mermaid (siren) in the centre",
        "options": ["Starbucks", "Dunkin'", "Peet's Coffee", "Costa Coffee"],
        "fun_fact": "The Starbucks logo features a two-tailed mermaid (siren) inspired by a 16th-century Norse woodcut!",
        "image": "starbucks",
    },
    {
        "id": 20, "category": "food",
        "company": "McDonald's", "domain": "mcdonalds.com",
        "hint": "Golden arches forming an 'M' shape on a red background",
        "options": ["McDonald's", "Burger King", "Wendy's", "In-N-Out"],
        "fun_fact": "The Golden Arches were originally part of the restaurant's actual building architecture before becoming the logo!",
        "image": "mcdonalds",
    },
    {
        "id": 21, "category": "food",
        "company": "Pepsi", "domain": "pepsi.com",
        "hint": "A circle divided into red, white, and blue wavy sections",
        "options": ["Pepsi", "Coca-Cola", "RC Cola", "Dr Pepper"],
        "fun_fact": "Pepsi has redesigned its globe logo over 10 times since 1898!",
        "image": "pepsi",
    },
    {
        "id": 22, "category": "food",
        "company": "Red Bull", "domain": "redbull.com",
        "hint": "Two red bulls charging at each other with a golden sun behind them",
        "options": ["Red Bull", "Monster", "Rockstar", "Celsius"],
        "fun_fact": "Red Bull's logo shows two bulls charging at each other — inspired by the Thai energy drink Krating Daeng!",
        "image": "redbull",
    },
    {
        "id": 23, "category": "food",
        "company": "KFC", "domain": "kfc.com",
        "hint": "A man's face with glasses, a goatee, and a bow tie",
        "options": ["KFC", "Popeyes", "Church's Chicken", "Boston Market"],
        "fun_fact": "Colonel Sanders' face in the KFC logo is based on the real founder who started his chicken recipe at age 65!",
        "image": "kfc",
    },
    {
        "id": 24, "category": "food",
        "company": "Domino's", "domain": "dominos.com",
        "hint": "A red and blue domino tile with dots",
        "options": ["Domino's", "Pizza Hut", "Papa John's", "Little Caesars"],
        "fun_fact": "The three dots on the Domino's logo represent the first three stores. They planned to add a dot per store but grew too fast!",
        "image": "dominos",
    },
    {
        "id": 25, "category": "food",
        "company": "Taco Bell", "domain": "tacobell.com",
        "hint": "A bell shape in purple and pink tones",
        "options": ["Taco Bell", "Chipotle", "Del Taco", "Qdoba"],
        "fun_fact": "Taco Bell was named after its founder, Glen Bell, and the bell logo is a play on his last name!",
        "image": "tacobell",
    },
    {
        "id": 26, "category": "food",
        "company": "Chick-fil-A", "domain": "chick-fil-a.com",
        "hint": "A red icon with a chicken silhouette hidden in a letter",
        "options": ["Chick-fil-A", "Raising Cane's", "Zaxby's", "Wingstop"],
        "fun_fact": "The 'C' in Chick-fil-A's logo is cleverly shaped like a chicken — look closely at the curve!",
        "image": "chickfila",
    },
    {
        "id": 27, "category": "food",
        "company": "Wendy's", "domain": "wendys.com",
        "hint": "A girl with red pigtails on a blue background",
        "options": ["Wendy's", "Dairy Queen", "Arby's", "Jack in the Box"],
        "fun_fact": "The Wendy's logo is based on the founder Dave Thomas's daughter, Melinda Lou 'Wendy' Thomas!",
        "image": "wendys",
    },

    # ========== SPORTS & OUTDOORS (symbol-based favicons) ==========
    {
        "id": 28, "category": "sports",
        "company": "Nike", "domain": "nike.com",
        "hint": "A simple curved checkmark shape (swoosh)",
        "options": ["Nike", "Adidas", "New Balance", "Reebok"],
        "fun_fact": "The Nike Swoosh was designed by graphic design student Carolyn Davidson for just $35 in 1971!",
        "image": "nike",
    },
    {
        "id": 29, "category": "sports",
        "company": "Adidas", "domain": "adidas.com",
        "hint": "Three parallel diagonal stripes forming a mountain/triangle shape",
        "options": ["Adidas", "Puma", "Fila", "Kappa"],
        "fun_fact": "Adidas' three stripes were originally just to hold the shoe together — they accidentally became the logo!",
        "image": "adidas",
    },
    {
        "id": 30, "category": "sports",
        "company": "Puma", "domain": "puma.com",
        "hint": "A leaping big cat (cougar/puma) silhouette",
        "options": ["Puma", "Jaguar", "Adidas", "Lacoste"],
        "fun_fact": "Puma was founded by Rudolf Dassler — the brother of Adidas founder Adi Dassler! The brothers had a falling out.",
        "image": "puma",
    },
    {
        "id": 31, "category": "sports",
        "company": "Under Armour", "domain": "underarmour.com",
        "hint": "Two overlapping letters that form an interlocking shape",
        "options": ["Under Armour", "Champion", "Reebok", "ASICS"],
        "fun_fact": "Under Armour's logo is two overlapping U's that also cleverly form an A!",
        "image": "under_armour",
    },
    {
        "id": 32, "category": "sports",
        "company": "Lacoste", "domain": "lacoste.com",
        "hint": "A small green crocodile/alligator",
        "options": ["Lacoste", "Polo Ralph Lauren", "Fred Perry", "Puma"],
        "fun_fact": "The Lacoste crocodile logo was inspired by founder René Lacoste's nickname 'The Crocodile' from tennis!",
        "image": "lacoste",
    },
    {
        "id": 33, "category": "sports",
        "company": "The North Face", "domain": "thenorthface.com",
        "hint": "Three curved lines forming a quarter-dome shape",
        "options": ["The North Face", "Patagonia", "Columbia", "Arc'teryx"],
        "fun_fact": "The North Face logo represents Half Dome, the famous rock formation in Yosemite National Park!",
        "image": "north_face",
    },

    # ========== CARS & TRANSPORT (symbol-based favicons) ==========
    {
        "id": 34, "category": "cars",
        "company": "Tesla", "domain": "tesla.com",
        "hint": "A stylised letter that also looks like a cross-section of an electric motor",
        "options": ["Tesla", "Rivian", "Lucid", "Polestar"],
        "fun_fact": "Tesla's 'T' logo is actually a cross-section of an electric motor — design meets engineering!",
        "image": "tesla",
    },
    {
        "id": 35, "category": "cars",
        "company": "BMW", "domain": "bmw.com",
        "hint": "A circle divided into four quadrants — two blue and two white",
        "options": ["BMW", "Volkswagen", "Audi", "Volvo"],
        "fun_fact": "BMW's blue and white quarters represent the colors of the Bavarian flag in Germany!",
        "image": "bmw",
    },
    {
        "id": 36, "category": "cars",
        "company": "Mercedes-Benz", "domain": "mercedes-benz.com",
        "hint": "A three-pointed star inside a circle",
        "options": ["Mercedes-Benz", "Lexus", "Infiniti", "Acura"],
        "fun_fact": "The three-pointed star represents Mercedes' ambition to motorise land, sea, and air transport!",
        "image": "mercedes",
    },
    {
        "id": 37, "category": "cars",
        "company": "Ferrari", "domain": "ferrari.com",
        "hint": "A prancing horse on a yellow shield background",
        "options": ["Ferrari", "Porsche", "Lamborghini", "Maserati"],
        "fun_fact": "Ferrari's prancing horse was originally a symbol painted on a World War I Italian fighter plane!",
        "image": "ferrari",
    },
    {
        "id": 38, "category": "cars",
        "company": "Lamborghini", "domain": "lamborghini.com",
        "hint": "A charging bull on a dark shield",
        "options": ["Lamborghini", "Ferrari", "Bugatti", "McLaren"],
        "fun_fact": "Lamborghini's bull logo reflects founder Ferruccio Lamborghini's zodiac sign — Taurus the bull!",
        "image": "lamborghini",
    },
    {
        "id": 39, "category": "cars",
        "company": "Audi", "domain": "audi.com",
        "hint": "Four interlocking rings in a horizontal row",
        "options": ["Audi", "Olympic Committee", "Volkswagen", "Volvo"],
        "fun_fact": "Audi's four rings represent the four companies that merged to create it in 1932!",
        "image": "audi",
    },
    {
        "id": 40, "category": "cars",
        "company": "Porsche", "domain": "porsche.com",
        "hint": "An ornate crest with a horse, antlers, and red/black stripes",
        "options": ["Porsche", "Ferrari", "Aston Martin", "Bentley"],
        "fun_fact": "Porsche's crest features the horse from Stuttgart's coat of arms and the antlers from Württemberg!",
        "image": "porsche",
    },
    {
        "id": 41, "category": "cars",
        "company": "Volkswagen", "domain": "volkswagen.com",
        "hint": "Two letters stacked vertically inside a circle",
        "options": ["Volkswagen", "Volvo", "Vauxhall", "Vinfast"],
        "fun_fact": "Volkswagen means 'people's car' in German — it was originally designed to be affordable for everyone!",
        "image": "volkswagen",
    },
    {
        "id": 42, "category": "cars",
        "company": "Toyota", "domain": "toyota.com",
        "hint": "Three overlapping ovals forming a symmetrical pattern",
        "options": ["Toyota", "Mazda", "Subaru", "Nissan"],
        "fun_fact": "Toyota's overlapping ovals logo secretly contains every letter of 'TOYOTA' hidden within it!",
        "image": "toyota",
    },
    {
        "id": 43, "category": "cars",
        "company": "Chevrolet", "domain": "chevrolet.com",
        "hint": "A golden cross / bowtie shape",
        "options": ["Chevrolet", "Ford", "Dodge", "Chrysler"],
        "fun_fact": "The Chevy bowtie logo's origin is debated — one theory says it was inspired by wallpaper in a Paris hotel!",
        "image": "chevrolet",
    },
    {
        "id": 44, "category": "cars",
        "company": "Subaru", "domain": "subaru.com",
        "hint": "A cluster of stars on a blue oval background",
        "options": ["Subaru", "Mitsubishi", "Mazda", "Suzuki"],
        "fun_fact": "Subaru means 'unite' in Japanese. Its star logo represents the Pleiades star cluster!",
        "image": "subaru",
    },
    {
        "id": 45, "category": "cars",
        "company": "Mitsubishi", "domain": "mitsubishi.com",
        "hint": "Three red diamond shapes arranged in a triangle/pinwheel",
        "options": ["Mitsubishi", "Suzuki", "Subaru", "Isuzu"],
        "fun_fact": "Mitsubishi means 'three diamonds' in Japanese — exactly what the logo shows!",
        "image": "mitsubishi",
    },

    # ========== ENTERTAINMENT & MEDIA (symbol-based favicons) ==========
    {
        "id": 46, "category": "entertainment",
        "company": "PlayStation", "domain": "playstation.com",
        "hint": "A 'P' standing up with an 'S' lying flat, creating a 3D-looking icon",
        "options": ["PlayStation", "Xbox", "Steam", "Atari"],
        "fun_fact": "The PS logo cleverly hides the letters P and S — the P stands upright while the S lies flat behind it!",
        "image": "playstation",
    },
    {
        "id": 47, "category": "entertainment",
        "company": "Xbox", "domain": "xbox.com",
        "hint": "A green sphere with a white X across it",
        "options": ["Xbox", "GeForce", "Razer", "Steam"],
        "fun_fact": "Xbox got its name from DirectX, Microsoft's graphics technology — 'DirectX Box' became 'Xbox'!",
        "image": "xbox",
    },
    {
        "id": 48, "category": "entertainment",
        "company": "Steam", "domain": "store.steampowered.com",
        "hint": "A circular gear with a piston/lever shape inside, in dark blue/steel tones",
        "options": ["Steam", "GOG", "Epic Games", "Origin"],
        "fun_fact": "Steam was launched in 2003 and now has over 120 million monthly active users!",
        "image": "steam",
    },
    {
        "id": 49, "category": "entertainment",
        "company": "Roblox", "domain": "roblox.com",
        "hint": "A tilted grey/dark square with a circular hole in it",
        "options": ["Roblox", "Minecraft", "Fortnite", "Among Us"],
        "fun_fact": "Roblox has over 70 million daily active users and the name is a mix of 'robots' and 'blocks'!",
        "image": "roblox",
    },
    {
        "id": 52, "category": "entertainment",
        "company": "Nintendo", "domain": "nintendo.com",
        "hint": "A bold red rounded rectangle with a white letter inside",
        "options": ["Nintendo", "Netflix", "Namco", "Naughty Dog"],
        "fun_fact": "Nintendo was founded in 1889 as a playing card company — they made cards for 75 years before making games!",
        "image": "nintendo",
    },
    {
        "id": 54, "category": "entertainment",
        "company": "Netflix", "domain": "netflix.com",
        "hint": "A bold red letter on a dark/black background",
        "options": ["Netflix", "Hulu", "HBO Max", "Paramount+"],
        "fun_fact": "Netflix started as a DVD-by-mail service in 1997 — they mailed their first DVD in 1998!",
        "image": "netflix",
    },
    {
        "id": 55, "category": "entertainment",
        "company": "Disney", "domain": "disney.com",
        "hint": "A castle silhouette or a cursive script signature",
        "options": ["Disney", "Universal", "Paramount", "Warner Bros."],
        "fun_fact": "Walt Disney's personal signature inspired the famous Disney logo script!",
        "image": "disney",
    },
    {
        "id": 56, "category": "entertainment",
        "company": "Epic Games", "domain": "epicgames.com",
        "hint": "A dark icon with a stylised face/side profile",
        "options": ["Epic Games", "Valve", "Riot Games", "Rockstar Games"],
        "fun_fact": "Epic Games was founded by Tim Sweeney when he was in college — now they make Fortnite and Unreal Engine!",
        "image": "epic_games",
    },

    # ========== FASHION & LIFESTYLE (symbol-based favicons) ==========
    {
        "id": 57, "category": "fashion",
        "company": "Target", "domain": "target.com",
        "hint": "A red and white bullseye (concentric circles)",
        "options": ["Target", "CVS", "Walgreens", "Kmart"],
        "fun_fact": "Target's bullseye logo is one of the most recognised in the US — their dog mascot is named Bullseye too!",
        "image": "target",
    },
    {
        "id": 58, "category": "fashion",
        "company": "IKEA", "domain": "ikea.com",
        "hint": "A blue and yellow colour scheme with bold letters in an oval",
        "options": ["IKEA", "Wayfair", "Ashley", "Crate & Barrel"],
        "fun_fact": "IKEA's name comes from founder Ingvar Kamprad's initials plus the farm and village where he grew up in Sweden!",
        "image": "ikea",
    },
    {
        "id": 60, "category": "fashion",
        "company": "Converse", "domain": "converse.com",
        "hint": "A star inside a circle — the classic All Star emblem",
        "options": ["Converse", "Vans", "DC Shoes", "Skechers"],
        "fun_fact": "Chuck Taylor All Stars were originally basketball shoes designed in 1917 — now they're a fashion icon!",
        "image": "converse",
    },
    {
        "id": 61, "category": "fashion",
        "company": "Ralph Lauren", "domain": "ralphlauren.com",
        "hint": "A polo player on horseback swinging a mallet",
        "options": ["Ralph Lauren", "U.S. Polo Assn.", "Lacoste", "Tommy Hilfiger"],
        "fun_fact": "Ralph Lauren's real name was Ralph Lifshitz — he changed it in high school and built a fashion empire!",
        "image": "ralph_lauren",
    },
    {
        "id": 62, "category": "fashion",
        "company": "Crocs", "domain": "crocs.com",
        "hint": "A cartoon crocodile/alligator wearing sunglasses, smiling",
        "options": ["Crocs", "Birkenstock", "Keen", "Teva"],
        "fun_fact": "Crocs were originally designed as boat shoes but became a worldwide fashion phenomenon!",
        "image": "crocs",
    },

    # ========== ADDITIONAL TRICKY ONES ==========
    {
        "id": 63, "category": "tech",
        "company": "Evernote", "domain": "evernote.com",
        "hint": "A green elephant head with a folded ear",
        "options": ["Evernote", "Notion", "OneNote", "Bear"],
        "fun_fact": "Evernote's elephant logo represents that elephants never forget — just like the app remembers your notes!",
        "image": "evernote",
    },
    {
        "id": 64, "category": "tech",
        "company": "Firefox", "domain": "mozilla.org",
        "hint": "A fox curled around a blue/purple globe",
        "options": ["Firefox", "Chrome", "Opera", "Vivaldi"],
        "fun_fact": "Firefox's logo shows a fox wrapping around the Earth — but it's actually a red panda, not a fox!",
        "image": "firefox",
    },
    {
        "id": 65, "category": "tech",
        "company": "Android", "domain": "android.com",
        "hint": "A green robot with antenna on top of its head",
        "options": ["Android", "Chrome OS", "Linux", "HarmonyOS"],
        "fun_fact": "The Android robot mascot is called 'Bugdroid' and was inspired by bathroom door symbols!",
        "image": "android",
    },
    {
        "id": 66, "category": "food",
        "company": "Pringles", "domain": "pringles.com",
        "hint": "A man with a large moustache and a bow-shaped hairstyle",
        "options": ["Pringles", "Lay's", "Doritos", "Cheetos"],
        "fun_fact": "The Pringles mascot is called Julius Pringles — his iconic moustache has been there since 1968!",
        "image": "pringles",
    },
    {
        "id": 67, "category": "cars",
        "company": "Jaguar", "domain": "jaguar.com",
        "hint": "A leaping big cat (jaguar) silhouette",
        "options": ["Jaguar", "Puma", "Bentley", "Aston Martin"],
        "fun_fact": "The Jaguar 'leaper' mascot was banned from car hoods in some countries due to pedestrian safety concerns!",
        "image": "jaguar_car",
    },
    {
        "id": 68, "category": "entertainment",
        "company": "LEGO", "domain": "lego.com",
        "hint": "Bold white letters on a bright red rounded square",
        "options": ["LEGO", "Mega Bloks", "K'NEX", "Playmobil"],
        "fun_fact": "LEGO comes from the Danish words 'leg godt' meaning 'play well' — and it sells about 75 billion bricks a year!",
        "image": "lego",
    },
    {
        "id": 69, "category": "food",
        "company": "Dunkin'", "domain": "dunkindonuts.com",
        "hint": "Orange and pink colours with a coffee cup shape",
        "options": ["Dunkin'", "Tim Hortons", "Krispy Kreme", "Starbucks"],
        "fun_fact": "Dunkin' dropped 'Donuts' from its name in 2019 — they wanted to be known for coffee, not just donuts!",
        "image": "dunkin",
    },
    {
        "id": 70, "category": "tech",
        "company": "Duolingo", "domain": "duolingo.com",
        "hint": "A bright green owl with large round eyes",
        "options": ["Duolingo", "Babbel", "Rosetta Stone", "Memrise"],
        "fun_fact": "Duolingo's owl mascot is named Duo — and he's famous for guilt-tripping users who miss lessons!",
        "image": "duolingo",
    },
    {
        "id": 72, "category": "tech",
        "company": "Waze", "domain": "waze.com",
        "hint": "A smiling white ghost-like character with a blue speech bubble",
        "options": ["Waze", "Google Maps", "Apple Maps", "HERE"],
        "fun_fact": "Waze uses crowdsourced data — real drivers report traffic, accidents, and police in real time!",
        "image": "waze",
    },
    {
        "id": 73, "category": "food",
        "company": "Monster Energy", "domain": "monsterenergy.com",
        "hint": "A green claw scratch mark on a black background",
        "options": ["Monster Energy", "Red Bull", "Rockstar", "G Fuel"],
        "fun_fact": "Monster's 'M' logo is actually three claw scratches that form the letter M — it looks like a monster attacked the can!",
        "image": "monster_energy",
    },
    {
        "id": 74, "category": "fashion",
        "company": "Versace", "domain": "versace.com",
        "hint": "A Greek mythological head (Medusa) in gold on a dark background",
        "options": ["Versace", "Gucci", "Dolce & Gabbana", "Prada"],
        "fun_fact": "Versace's Medusa head logo was chosen because Gianni Versace loved Greek mythology and its power symbolism!",
        "image": "versace",
    },
    {
        "id": 75, "category": "tech",
        "company": "Opera", "domain": "opera.com",
        "hint": "A red 'O' shape on a dark background",
        "options": ["Opera", "Firefox", "Brave", "Vivaldi"],
        "fun_fact": "Opera was one of the first browsers to include a built-in VPN and ad blocker for free!",
        "image": "opera",
    },

    # ========== NEW BRANDS (76-205) ==========
    {
        "id": 76, "category": "tech",
        "company": "Telegram", "domain": "telegram.org",
        "hint": "A paper airplane on a blue circle",
        "options": ["Telegram", "Signal", "WhatsApp", "Viber"],
        "fun_fact": "Telegram was created by the same brothers who founded Russia's largest social network, VKontakte!",
        "image": "telegram",
    },
    {
        "id": 77, "category": "tech",
        "company": "Signal", "domain": "signal.org",
        "hint": "A speech bubble with a diagonal line through it on blue",
        "options": ["Signal", "Telegram", "Wire", "Wickr"],
        "fun_fact": "Signal's encryption protocol is so good that WhatsApp and Skype adopted it too!",
        "image": "signal",
    },
    {
        "id": 78, "category": "tech",
        "company": "Skype", "domain": "skype.com",
        "hint": "A cloud-like S shape on blue",
        "options": ["Skype", "Zoom", "Teams", "Slack"],
        "fun_fact": "Skype's name comes from 'Sky peer-to-peer' shortened to Skyper then Skype!",
        "image": "skype",
    },
    {
        "id": 79, "category": "tech",
        "company": "Google", "domain": "google.com",
        "hint": "A multicoloured G in blue red yellow green",
        "options": ["Google", "Bing", "Yahoo", "DuckDuckGo"],
        "fun_fact": "Google's name comes from 'googol' the number 1 followed by 100 zeros!",
        "image": "google",
    },
    {
        "id": 80, "category": "tech",
        "company": "Amazon", "domain": "amazon.com",
        "hint": "An arrow from A to Z under the name forming a smile",
        "options": ["Amazon", "eBay", "Alibaba", "Flipkart"],
        "fun_fact": "Amazon's arrow goes from A to Z meaning they sell everything from A to Z!",
        "image": "amazon",
    },
    {
        "id": 81, "category": "tech",
        "company": "Uber", "domain": "uber.com",
        "hint": "A simple U shape in black on white",
        "options": ["Uber", "Lyft", "Grab", "Bolt"],
        "fun_fact": "Uber started as UberCab in 2009 and originally only offered black luxury cars!",
        "image": "uber",
    },
    {
        "id": 82, "category": "tech",
        "company": "Lyft", "domain": "lyft.com",
        "hint": "A pink/magenta rounded shape",
        "options": ["Lyft", "Uber", "Via", "Juno"],
        "fun_fact": "Lyft drivers originally had giant pink moustaches on the front of their cars!",
        "image": "lyft",
    },
    {
        "id": 83, "category": "tech",
        "company": "PayPal", "domain": "paypal.com",
        "hint": "Two overlapping P letters in blue",
        "options": ["PayPal", "Venmo", "Stripe", "Square"],
        "fun_fact": "PayPal's overlapping Ps represent person-to-person payments!",
        "image": "paypal",
    },
    {
        "id": 84, "category": "tech",
        "company": "Shopify", "domain": "shopify.com",
        "hint": "A green shopping bag with an S shape",
        "options": ["Shopify", "Etsy", "WooCommerce", "BigCommerce"],
        "fun_fact": "Shopify was created because its founder couldn't find good software to sell snowboards online!",
        "image": "shopify",
    },
    {
        "id": 85, "category": "tech",
        "company": "Adobe", "domain": "adobe.com",
        "hint": "A red stylised A shape",
        "options": ["Adobe", "Autodesk", "Canva", "Figma"],
        "fun_fact": "Adobe is named after Adobe Creek which ran behind co-founder John Warnock's house!",
        "image": "adobe",
    },
    {
        "id": 86, "category": "tech",
        "company": "IBM", "domain": "ibm.com",
        "hint": "Horizontal striped letters in blue",
        "options": ["IBM", "Intel", "HP", "Cisco"],
        "fun_fact": "IBM is over 100 years old — it was founded in 1911 as a tabulating machine company!",
        "image": "ibm",
    },
    {
        "id": 87, "category": "tech",
        "company": "Intel", "domain": "intel.com",
        "hint": "A circle with a swoosh around it in blue",
        "options": ["Intel", "AMD", "Qualcomm", "ARM"],
        "fun_fact": "Intel's famous jingle 'bum ba da bum bum' is one of the most recognised sounds in advertising!",
        "image": "intel",
    },
    {
        "id": 88, "category": "tech",
        "company": "AMD", "domain": "amd.com",
        "hint": "A pointed arrow shape in black/green",
        "options": ["AMD", "Intel", "NVIDIA", "Qualcomm"],
        "fun_fact": "AMD stands for Advanced Micro Devices — they make the chips inside PlayStation and Xbox!",
        "image": "amd",
    },
    {
        "id": 89, "category": "tech",
        "company": "NVIDIA", "domain": "nvidia.com",
        "hint": "A green eye-shaped swirl",
        "options": ["NVIDIA", "AMD", "Intel", "Qualcomm"],
        "fun_fact": "NVIDIA's name comes from 'invidia' the Latin word for envy!",
        "image": "nvidia",
    },
    {
        "id": 90, "category": "tech",
        "company": "Figma", "domain": "figma.com",
        "hint": "Colourful interlocking shapes in a vertical arrangement",
        "options": ["Figma", "Sketch", "Adobe XD", "Canva"],
        "fun_fact": "Figma was the first professional design tool that worked entirely in a web browser!",
        "image": "figma",
    },
    {
        "id": 91, "category": "tech",
        "company": "Notion", "domain": "notion.so",
        "hint": "A black and white N-like shape",
        "options": ["Notion", "Evernote", "OneNote", "Obsidian"],
        "fun_fact": "Notion nearly went bankrupt in 2015 before becoming one of the most popular productivity apps!",
        "image": "notion",
    },
    {
        "id": 92, "category": "tech",
        "company": "Brave", "domain": "brave.com",
        "hint": "An orange and red lion head silhouette",
        "options": ["Brave", "Firefox", "Chrome", "Edge"],
        "fun_fact": "Brave browser was created by Brendan Eich the same person who invented JavaScript!",
        "image": "brave",
    },
    {
        "id": 93, "category": "tech",
        "company": "Samsung", "domain": "samsung.com",
        "hint": "A blue oval with letters inside",
        "options": ["Samsung", "LG", "Sony", "Huawei"],
        "fun_fact": "Samsung means three stars in Korean — chosen to symbolise something big and eternal!",
        "image": "samsung",
    },
    {
        "id": 94, "category": "tech",
        "company": "LinkedIn", "domain": "linkedin.com",
        "hint": "A blue square with 'in' letters",
        "options": ["LinkedIn", "Indeed", "Glassdoor", "ZipRecruiter"],
        "fun_fact": "LinkedIn was founded in a living room in 2002 and now has over 900 million members!",
        "image": "linkedin",
    },
    {
        "id": 95, "category": "tech",
        "company": "Cloudflare", "domain": "cloudflare.com",
        "hint": "An orange cloud with a shield-like shape",
        "options": ["Cloudflare", "AWS", "Azure", "DigitalOcean"],
        "fun_fact": "Cloudflare protects about 20% of all websites on the internet from cyber attacks!",
        "image": "cloudflare",
    },
    {
        "id": 96, "category": "tech",
        "company": "WordPress", "domain": "wordpress.org",
        "hint": "A W inside a circle in blue",
        "options": ["WordPress", "Wix", "Squarespace", "Weebly"],
        "fun_fact": "WordPress powers over 40% of all websites on the internet!",
        "image": "wordpress",
    },

    # ========== FOOD & DRINKS (97-118) ==========
    {
        "id": 97, "category": "food",
        "company": "Coca-Cola", "domain": "coca-cola.com",
        "hint": "A flowing red and white script with a wave ribbon",
        "options": ["Coca-Cola", "Pepsi", "Dr Pepper", "RC Cola"],
        "fun_fact": "Coca-Cola's recipe is one of the most guarded trade secrets — it's kept in a vault in Atlanta!",
        "image": "cocacola",
    },
    {
        "id": 98, "category": "food",
        "company": "Chipotle", "domain": "chipotle.com",
        "hint": "A red pepper shape on a dark background",
        "options": ["Chipotle", "Taco Bell", "Qdoba", "Moe's"],
        "fun_fact": "Chipotle is named after a smoked jalapeño pepper — a chipotle!",
        "image": "chipotle",
    },
    {
        "id": 99, "category": "food",
        "company": "Pizza Hut", "domain": "pizzahut.com",
        "hint": "A red roof hat shape above text",
        "options": ["Pizza Hut", "Domino's", "Papa John's", "Little Caesars"],
        "fun_fact": "Pizza Hut's logo features the red roof that was based on the original restaurant building shape!",
        "image": "pizzahut",
    },
    {
        "id": 100, "category": "food",
        "company": "Popeyes", "domain": "popeyes.com",
        "hint": "An orange and red icon of a face with a hat",
        "options": ["Popeyes", "KFC", "Church's", "Raising Cane's"],
        "fun_fact": "Popeyes is named after the detective Popeye Doyle from The French Connection not the cartoon sailor!",
        "image": "popeyes",
    },
    {
        "id": 101, "category": "food",
        "company": "Krispy Kreme", "domain": "krispykreme.com",
        "hint": "Green and red text with a bowtie shape",
        "options": ["Krispy Kreme", "Dunkin'", "Tim Hortons", "Cinnabon"],
        "fun_fact": "Krispy Kreme's original recipe came from a French chef in New Orleans in the 1930s!",
        "image": "krispykreme",
    },
    {
        "id": 102, "category": "food",
        "company": "Baskin Robbins", "domain": "baskinrobbins.com",
        "hint": "Pink and blue with a hidden 31 in the letters",
        "options": ["Baskin Robbins", "Dairy Queen", "Cold Stone", "Häagen-Dazs"],
        "fun_fact": "The 31 hidden in the Baskin Robbins logo represents a different flavour for every day of the month!",
        "image": "baskinrobbins",
    },
    {
        "id": 103, "category": "food",
        "company": "DoorDash", "domain": "doordash.com",
        "hint": "A red D with a motion trail",
        "options": ["DoorDash", "UberEats", "Grubhub", "Postmates"],
        "fun_fact": "DoorDash was started by four Stanford students who wanted to help a macaroon shop with deliveries!",
        "image": "doordash",
    },
    {
        "id": 104, "category": "food",
        "company": "Grubhub", "domain": "grubhub.com",
        "hint": "An orange fork and plate icon",
        "options": ["Grubhub", "DoorDash", "Seamless", "Postmates"],
        "fun_fact": "Grubhub processes over 800000 orders per day across the United States!",
        "image": "grubhub",
    },
    {
        "id": 105, "category": "food",
        "company": "UberEats", "domain": "ubereats.com",
        "hint": "A green plate and utensil icon",
        "options": ["UberEats", "DoorDash", "Grubhub", "Deliveroo"],
        "fun_fact": "UberEats started as a small food delivery experiment inside Uber's office!",
        "image": "ubereats",
    },
    {
        "id": 106, "category": "food",
        "company": "Nespresso", "domain": "nespresso.com",
        "hint": "An elegant N with a coffee cup shape",
        "options": ["Nespresso", "Keurig", "Nescafé", "Lavazza"],
        "fun_fact": "George Clooney has been the face of Nespresso since 2006!",
        "image": "nespresso",
    },
    {
        "id": 107, "category": "food",
        "company": "Tim Hortons", "domain": "timhortons.com",
        "hint": "A red maple-leaf-inspired logo",
        "options": ["Tim Hortons", "Dunkin'", "Starbucks", "Costa"],
        "fun_fact": "Tim Hortons is named after a Canadian hockey player who co-founded the chain in 1964!",
        "image": "timhortons",
    },
    {
        "id": 108, "category": "food",
        "company": "Gatorade", "domain": "gatorade.com",
        "hint": "A lightning bolt G shape in orange",
        "options": ["Gatorade", "Powerade", "BodyArmor", "Prime"],
        "fun_fact": "Gatorade was invented at the University of Florida for their football team the Gators!",
        "image": "gatorade",
    },
    {
        "id": 109, "category": "food",
        "company": "Nestlé", "domain": "nestle.com",
        "hint": "A bird's nest with a mother bird feeding baby birds",
        "options": ["Nestlé", "Unilever", "Kraft", "Mondelez"],
        "fun_fact": "Nestlé's bird nest logo represents care and nourishment — it means 'little nest' in German!",
        "image": "nestle",
    },
    {
        "id": 110, "category": "food",
        "company": "Mountain Dew", "domain": "mountaindew.com",
        "hint": "A jagged green mountain shape with red accents",
        "options": ["Mountain Dew", "Sprite", "7-Up", "Sierra Mist"],
        "fun_fact": "Mountain Dew was originally created as a mixer for whiskey in Tennessee in the 1940s!",
        "image": "mountaindew",
    },
    {
        "id": 111, "category": "food",
        "company": "Sprite", "domain": "sprite.com",
        "hint": "A green and yellow lemon-lime burst",
        "options": ["Sprite", "7-Up", "Sierra Mist", "Mountain Dew"],
        "fun_fact": "Sprite was created by Coca-Cola in 1961 to compete with 7-Up!",
        "image": "sprite",
    },
    {
        "id": 112, "category": "food",
        "company": "Fanta", "domain": "fanta.com",
        "hint": "An orange and blue swirl with a leaf",
        "options": ["Fanta", "Sunkist", "Crush", "Mirinda"],
        "fun_fact": "Fanta was invented in Germany during World War II when Coca-Cola ingredients were hard to get!",
        "image": "fanta",
    },
    {
        "id": 113, "category": "food",
        "company": "Dairy Queen", "domain": "dairyqueen.com",
        "hint": "Red lips/smile shape with a curl on top",
        "options": ["Dairy Queen", "Baskin Robbins", "Cold Stone", "Culver's"],
        "fun_fact": "Dairy Queen's famous Blizzard is always served upside down to prove how thick it is!",
        "image": "dairyqueen",
    },
    {
        "id": 114, "category": "food",
        "company": "Panera", "domain": "panerabread.com",
        "hint": "A green circle with a woman holding bread",
        "options": ["Panera", "Au Bon Pain", "Corner Bakery", "Atlanta Bread"],
        "fun_fact": "Panera means 'bread basket' in Latin and Spanish!",
        "image": "panera",
    },
    {
        "id": 115, "category": "food",
        "company": "Sonic", "domain": "sonicdrivein.com",
        "hint": "A bold red and yellow retro drive-in style icon",
        "options": ["Sonic", "Shake Shack", "Five Guys", "In-N-Out"],
        "fun_fact": "Sonic is one of the last remaining drive-in restaurants — you eat in your car!",
        "image": "sonic",
    },
    {
        "id": 116, "category": "food",
        "company": "Five Guys", "domain": "fiveguys.com",
        "hint": "Red and white checkered pattern",
        "options": ["Five Guys", "In-N-Out", "Shake Shack", "Whataburger"],
        "fun_fact": "Five Guys is named after the five sons of the founders Jerry and Janie Murrell!",
        "image": "fiveguys",
    },
    {
        "id": 117, "category": "food",
        "company": "Heineken", "domain": "heineken.com",
        "hint": "A green star with a red star inside",
        "options": ["Heineken", "Budweiser", "Corona", "Guinness"],
        "fun_fact": "Heineken's red star has been part of the logo since the 1930s!",
        "image": "heineken",
    },
    {
        "id": 118, "category": "food",
        "company": "Budweiser", "domain": "budweiser.com",
        "hint": "A red bowtie ribbon shape",
        "options": ["Budweiser", "Heineken", "Miller", "Coors"],
        "fun_fact": "Budweiser is named after Budweis a city in the Czech Republic famous for brewing!",
        "image": "budweiser",
    },

    # ========== SPORTS & OUTDOORS (119-137) ==========
    {
        "id": 119, "category": "sports",
        "company": "Reebok", "domain": "reebok.com",
        "hint": "A red delta/triangle shape",
        "options": ["Reebok", "Nike", "Adidas", "New Balance"],
        "fun_fact": "Reebok is named after the rhebok a type of African antelope!",
        "image": "reebok",
    },
    {
        "id": 120, "category": "sports",
        "company": "New Balance", "domain": "newbalance.com",
        "hint": "A stylised NB letters forming a shape",
        "options": ["New Balance", "Nike", "ASICS", "Brooks"],
        "fun_fact": "New Balance was originally called New Balance Arch Support Company and made shoe insoles!",
        "image": "newbalance",
    },
    {
        "id": 121, "category": "sports",
        "company": "ASICS", "domain": "asics.com",
        "hint": "Curved crossing lines forming a dynamic shape",
        "options": ["ASICS", "Mizuno", "Brooks", "Saucony"],
        "fun_fact": "ASICS stands for Anima Sana In Corpore Sano — a healthy soul in a healthy body!",
        "image": "asics",
    },
    {
        "id": 122, "category": "sports",
        "company": "Fila", "domain": "fila.com",
        "hint": "A bold red F shape",
        "options": ["Fila", "Champion", "Ellesse", "Kappa"],
        "fun_fact": "Fila was founded in Italy in 1911 as an underwear company before making sportswear!",
        "image": "fila",
    },
    {
        "id": 123, "category": "sports",
        "company": "Jordan", "domain": "jordan.com",
        "hint": "A silhouette of a basketball player jumping with legs spread",
        "options": ["Jordan", "Nike", "Adidas", "Puma"],
        "fun_fact": "The Jumpman logo is based on a photo of Michael Jordan doing a ballet move not a basketball dunk!",
        "image": "jordan",
    },
    {
        "id": 124, "category": "sports",
        "company": "Oakley", "domain": "oakley.com",
        "hint": "An O shape with a squared cutout",
        "options": ["Oakley", "Ray-Ban", "Costa", "Maui Jim"],
        "fun_fact": "Oakley started in a garage making motorcycle grips before becoming a sunglasses giant!",
        "image": "oakley",
    },
    {
        "id": 125, "category": "sports",
        "company": "Columbia", "domain": "columbia.com",
        "hint": "A geometric gem shape in blue",
        "options": ["Columbia", "Patagonia", "North Face", "REI"],
        "fun_fact": "Columbia Sportswear was started by a family who fled Nazi Germany and settled in Portland Oregon!",
        "image": "columbia",
    },
    {
        "id": 126, "category": "sports",
        "company": "Patagonia", "domain": "patagonia.com",
        "hint": "A mountain ridge silhouette against a coloured sky",
        "options": ["Patagonia", "North Face", "REI", "Columbia"],
        "fun_fact": "Patagonia donates 1% of all sales to environmental organisations!",
        "image": "patagonia",
    },
    {
        "id": 127, "category": "sports",
        "company": "UFC", "domain": "ufc.com",
        "hint": "An octagon shape with letters inside",
        "options": ["UFC", "Bellator", "ONE", "PFL"],
        "fun_fact": "UFC's famous octagon ring shape was designed to be different from boxing's square ring!",
        "image": "ufc",
    },
    {
        "id": 128, "category": "sports",
        "company": "Formula 1", "domain": "formula1.com",
        "hint": "A red number 1 shape with speed lines",
        "options": ["Formula 1", "NASCAR", "IndyCar", "MotoGP"],
        "fun_fact": "Formula 1 cars can go from 0 to 100 mph and back to 0 in under 5 seconds!",
        "image": "formula1",
    },
    {
        "id": 129, "category": "sports",
        "company": "Premier League", "domain": "premierleague.com",
        "hint": "A lion head looking to the side with a crown",
        "options": ["Premier League", "La Liga", "Bundesliga", "Serie A"],
        "fun_fact": "The Premier League lion has been the logo since 1992 when the league was formed!",
        "image": "premierleague",
    },
    {
        "id": 130, "category": "sports",
        "company": "NHL", "domain": "nhl.com",
        "hint": "A shield shape with letters",
        "options": ["NHL", "NBA", "NFL", "MLS"],
        "fun_fact": "The NHL is the oldest of the four major North American professional sports leagues!",
        "image": "nhl",
    },
    {
        "id": 131, "category": "sports",
        "company": "MLB", "domain": "mlb.com",
        "hint": "A silhouette of a baseball batter in red white and blue",
        "options": ["MLB", "NFL", "NBA", "NHL"],
        "fun_fact": "The MLB logo batter's identity is officially a mystery — it's not based on any specific player!",
        "image": "mlb",
    },
    {
        "id": 132, "category": "sports",
        "company": "Speedo", "domain": "speedo.com",
        "hint": "A boomerang-like arrow shape",
        "options": ["Speedo", "Arena", "TYR", "Nike Swim"],
        "fun_fact": "Speedo invented the first non-wool swimsuit in 1928 and has been innovating ever since!",
        "image": "speedo",
    },
    {
        "id": 133, "category": "sports",
        "company": "Wilson", "domain": "wilson.com",
        "hint": "A W shape in red",
        "options": ["Wilson", "Spalding", "Rawlings", "Titleist"],
        "fun_fact": "The volleyball in the movie Cast Away was a Wilson ball named Wilson by Tom Hanks' character!",
        "image": "wilson",
    },
    {
        "id": 134, "category": "sports",
        "company": "Champion", "domain": "champion.com",
        "hint": "A C shape in red or blue",
        "options": ["Champion", "Nike", "Adidas", "Russell"],
        "fun_fact": "Champion invented the hoodie in the 1930s to keep workers warm in upstate New York!",
        "image": "champion",
    },
    {
        "id": 135, "category": "sports",
        "company": "Kappa", "domain": "kappa.com",
        "hint": "Two people sitting back to back silhouette",
        "options": ["Kappa", "Fila", "Ellesse", "Diadora"],
        "fun_fact": "Kappa's famous logo of two people back to back was originally an accident from a photo shoot!",
        "image": "kappa",
    },
    {
        "id": 136, "category": "sports",
        "company": "Arc'teryx", "domain": "arcteryx.com",
        "hint": "A fossil bird skeleton (Archaeopteryx)",
        "options": ["Arc'teryx", "Patagonia", "Mammut", "Salomon"],
        "fun_fact": "Arc'teryx is named after Archaeopteryx the first known bird that lived 150 million years ago!",
        "image": "arcteryx",
    },
    {
        "id": 137, "category": "sports",
        "company": "MLS", "domain": "mlssoccer.com",
        "hint": "A shield with a soccer ball and three stars",
        "options": ["MLS", "Premier League", "La Liga", "Bundesliga"],
        "fun_fact": "MLS was created in 1993 as part of the deal for the USA to host the 1994 World Cup!",
        "image": "mls",
    },

    # ========== CARS & TRANSPORT (138-159) ==========
    {
        "id": 138, "category": "cars",
        "company": "Hyundai", "domain": "hyundai.com",
        "hint": "A slanted H inside an oval",
        "options": ["Hyundai", "Honda", "Kia", "Mazda"],
        "fun_fact": "Hyundai means 'modernity' in Korean and their logo H also represents two people shaking hands!",
        "image": "hyundai",
    },
    {
        "id": 139, "category": "cars",
        "company": "Kia", "domain": "kia.com",
        "hint": "Stylised angular letters forming a connected shape",
        "options": ["Kia", "Hyundai", "Nissan", "Suzuki"],
        "fun_fact": "Kia means 'rising from Asia' and is South Korea's oldest car manufacturer!",
        "image": "kia",
    },
    {
        "id": 140, "category": "cars",
        "company": "Nissan", "domain": "nissan.com",
        "hint": "A circle with a horizontal bar through it",
        "options": ["Nissan", "Toyota", "Honda", "Mazda"],
        "fun_fact": "Nissan's name combines 'ni' for Japan and 'san' for production — Japanese production!",
        "image": "nissan",
    },
    {
        "id": 141, "category": "cars",
        "company": "Mazda", "domain": "mazda.com",
        "hint": "A winged M or V shape inside an oval",
        "options": ["Mazda", "Mitsubishi", "Nissan", "Suzuki"],
        "fun_fact": "Mazda is named after Ahura Mazda the god of wisdom in Zoroastrianism!",
        "image": "mazda",
    },
    {
        "id": 142, "category": "cars",
        "company": "Honda", "domain": "honda.com",
        "hint": "A bold H shape wider at the top",
        "options": ["Honda", "Hyundai", "Nissan", "Toyota"],
        "fun_fact": "Honda's H logo is wider at the top than bottom symbolising reaching for the sky!",
        "image": "honda",
    },
    {
        "id": 143, "category": "cars",
        "company": "Volvo", "domain": "volvocars.com",
        "hint": "A circle with an arrow pointing to the upper right",
        "options": ["Volvo", "Saab", "Volkswagen", "Peugeot"],
        "fun_fact": "Volvo's circle and arrow logo is actually the ancient chemical symbol for iron!",
        "image": "volvo",
    },
    {
        "id": 144, "category": "cars",
        "company": "Land Rover", "domain": "landrover.com",
        "hint": "An oval shape with text in green",
        "options": ["Land Rover", "Jeep", "Toyota", "Ford"],
        "fun_fact": "The first Land Rover was inspired by a Jeep and built on a farm in Wales in 1947!",
        "image": "landrover",
    },
    {
        "id": 145, "category": "cars",
        "company": "Bentley", "domain": "bentley.com",
        "hint": "A pair of wings spreading from a B letter",
        "options": ["Bentley", "Rolls-Royce", "Aston Martin", "Jaguar"],
        "fun_fact": "Every Bentley takes over 100 hours just to hand-stitch the leather interior!",
        "image": "bentley",
    },
    {
        "id": 146, "category": "cars",
        "company": "Rolls-Royce", "domain": "rolls-royce.com",
        "hint": "Two overlapping R letters",
        "options": ["Rolls-Royce", "Bentley", "Maybach", "Aston Martin"],
        "fun_fact": "The Spirit of Ecstasy hood ornament on every Rolls-Royce takes a full day to polish!",
        "image": "rollsroyce",
    },
    {
        "id": 147, "category": "cars",
        "company": "Aston Martin", "domain": "astonmartin.com",
        "hint": "Wings spreading from a centre with text",
        "options": ["Aston Martin", "Jaguar", "Bentley", "McLaren"],
        "fun_fact": "Aston Martin is James Bond's favourite car — it has appeared in over 10 Bond films!",
        "image": "astonmartin",
    },
    {
        "id": 148, "category": "cars",
        "company": "McLaren", "domain": "mclaren.com",
        "hint": "A red swoosh speedmark shape",
        "options": ["McLaren", "Ferrari", "Lamborghini", "Porsche"],
        "fun_fact": "McLaren started as a Formula 1 racing team before making road cars!",
        "image": "mclaren",
    },
    {
        "id": 149, "category": "cars",
        "company": "Bugatti", "domain": "bugatti.com",
        "hint": "An oval with EB initials surrounded by dots",
        "options": ["Bugatti", "Lamborghini", "Ferrari", "Koenigsegg"],
        "fun_fact": "Bugatti's Chiron can go over 300 mph making it one of the fastest cars ever made!",
        "image": "bugatti",
    },
    {
        "id": 150, "category": "cars",
        "company": "Maserati", "domain": "maserati.com",
        "hint": "A trident (three-pronged fork) in blue",
        "options": ["Maserati", "Alfa Romeo", "Ferrari", "Lamborghini"],
        "fun_fact": "Maserati's trident logo comes from the statue of Neptune in Bologna Italy!",
        "image": "maserati",
    },
    {
        "id": 151, "category": "cars",
        "company": "Alfa Romeo", "domain": "alfaromeo.com",
        "hint": "A circle with a cross and a serpent eating a person",
        "options": ["Alfa Romeo", "Fiat", "Maserati", "Lancia"],
        "fun_fact": "Alfa Romeo's serpent eating a man comes from the coat of arms of Milan Italy!",
        "image": "alfaromeo",
    },
    {
        "id": 152, "category": "cars",
        "company": "Fiat", "domain": "fiat.com",
        "hint": "Red letters in a circular badge",
        "options": ["Fiat", "Alfa Romeo", "Lancia", "Peugeot"],
        "fun_fact": "FIAT stands for Fabbrica Italiana Automobili Torino — Italian Automobile Factory of Turin!",
        "image": "fiat",
    },
    {
        "id": 153, "category": "cars",
        "company": "Jeep", "domain": "jeep.com",
        "hint": "Seven vertical slots forming a grille shape",
        "options": ["Jeep", "Land Rover", "Toyota", "Ford"],
        "fun_fact": "The Jeep seven-slot grille has been an icon since World War II military vehicles!",
        "image": "jeep",
    },
    {
        "id": 154, "category": "cars",
        "company": "Dodge", "domain": "dodge.com",
        "hint": "A ram head with curled horns",
        "options": ["Dodge", "Chevrolet", "Ford", "GMC"],
        "fun_fact": "Dodge's ram logo represents power and determination — the bighorn sheep!",
        "image": "dodge",
    },
    {
        "id": 155, "category": "cars",
        "company": "Cadillac", "domain": "cadillac.com",
        "hint": "A colourful crest shield shape",
        "options": ["Cadillac", "Lincoln", "Buick", "Chrysler"],
        "fun_fact": "Cadillac is named after the French explorer who founded the city of Detroit!",
        "image": "cadillac",
    },
    {
        "id": 156, "category": "cars",
        "company": "Lexus", "domain": "lexus.com",
        "hint": "A stylised L inside an oval",
        "options": ["Lexus", "Infiniti", "Acura", "Genesis"],
        "fun_fact": "Lexus was created by Toyota as their luxury brand — the first Lexus took 10 years to develop!",
        "image": "lexus",
    },
    {
        "id": 157, "category": "cars",
        "company": "Rivian", "domain": "rivian.com",
        "hint": "A compass-like geometric shape",
        "options": ["Rivian", "Tesla", "Lucid", "Polestar"],
        "fun_fact": "Rivian's name was inspired by the Indian River in Florida near the founder's hometown!",
        "image": "rivian",
    },
    {
        "id": 158, "category": "cars",
        "company": "Polestar", "domain": "polestar.com",
        "hint": "A four-pointed star shape",
        "options": ["Polestar", "Tesla", "Volvo", "Rivian"],
        "fun_fact": "Polestar started as Volvo's racing division before becoming an electric car brand!",
        "image": "polestar",
    },
    {
        "id": 159, "category": "cars",
        "company": "Lucid Motors", "domain": "lucidmotors.com",
        "hint": "A ring or circle shape",
        "options": ["Lucid Motors", "Tesla", "Rivian", "Polestar"],
        "fun_fact": "Lucid's Air sedan has the longest range of any electric car at over 500 miles!",
        "image": "lucid",
    },

    # ========== ENTERTAINMENT & MEDIA (160-183) ==========
    {
        "id": 160, "category": "entertainment",
        "company": "Hulu", "domain": "hulu.com",
        "hint": "A green lowercase text on dark background",
        "options": ["Hulu", "Netflix", "Peacock", "Paramount+"],
        "fun_fact": "Hulu means 'gourd' in Mandarin Chinese — it's also a word for 'holder of precious things'!",
        "image": "hulu",
    },
    {
        "id": 161, "category": "entertainment",
        "company": "HBO", "domain": "hbo.com",
        "hint": "Bold white letters on black",
        "options": ["HBO", "Showtime", "Starz", "AMC"],
        "fun_fact": "HBO stands for Home Box Office and was the first TV network to broadcast via satellite!",
        "image": "hbo",
    },
    {
        "id": 162, "category": "entertainment",
        "company": "Paramount", "domain": "paramount.com",
        "hint": "A mountain peak with stars above it",
        "options": ["Paramount", "Universal", "Warner Bros.", "Columbia"],
        "fun_fact": "Paramount's mountain logo originally had 24 stars representing the studio's 24 contracted actors!",
        "image": "paramount",
    },
    {
        "id": 163, "category": "entertainment",
        "company": "Sony", "domain": "sony.com",
        "hint": "Bold black letters in a clean font",
        "options": ["Sony", "Samsung", "LG", "Panasonic"],
        "fun_fact": "Sony's name comes from the Latin word 'sonus' meaning sound!",
        "image": "sony",
    },
    {
        "id": 164, "category": "entertainment",
        "company": "Sega", "domain": "sega.com",
        "hint": "Blue text with a white arch on top",
        "options": ["Sega", "Nintendo", "Atari", "SNK"],
        "fun_fact": "SEGA stands for Service Games — they originally made coin-operated machines for US military bases!",
        "image": "sega",
    },
    {
        "id": 165, "category": "entertainment",
        "company": "Atari", "domain": "atari.com",
        "hint": "A futuristic A shape like two vertical lines with an arch",
        "options": ["Atari", "Sega", "Commodore", "Coleco"],
        "fun_fact": "Atari's logo represents Mount Fuji and was inspired by the game of Go!",
        "image": "atari",
    },
    {
        "id": 166, "category": "entertainment",
        "company": "EA", "domain": "ea.com",
        "hint": "A circle with letters inside",
        "options": ["EA", "Ubisoft", "Activision", "Take-Two"],
        "fun_fact": "EA Sports is famous for its tagline 'It's in the game' which has been used since 1993!",
        "image": "ea",
    },
    {
        "id": 167, "category": "entertainment",
        "company": "Ubisoft", "domain": "ubisoft.com",
        "hint": "A swirl or spiral shape",
        "options": ["Ubisoft", "EA", "Activision", "Epic"],
        "fun_fact": "Ubisoft is a French company that makes Assassin's Creed and Just Dance!",
        "image": "ubisoft",
    },
    {
        "id": 168, "category": "entertainment",
        "company": "Riot Games", "domain": "riotgames.com",
        "hint": "A red fist or raised hand shape",
        "options": ["Riot Games", "Epic Games", "Valve", "Blizzard"],
        "fun_fact": "Riot Games was founded by two college roommates who just wanted to make a game they would enjoy!",
        "image": "riotgames",
    },
    {
        "id": 169, "category": "entertainment",
        "company": "Rockstar Games", "domain": "rockstargames.com",
        "hint": "A yellow R with a star cut out",
        "options": ["Rockstar Games", "Valve", "EA", "Ubisoft"],
        "fun_fact": "Rockstar's Grand Theft Auto V has sold over 200 million copies making it one of the best-selling games ever!",
        "image": "rockstargames",
    },
    {
        "id": 170, "category": "entertainment",
        "company": "Crunchyroll", "domain": "crunchyroll.com",
        "hint": "An orange manga-style eye or swirl",
        "options": ["Crunchyroll", "Funimation", "Netflix", "Hulu"],
        "fun_fact": "Crunchyroll started as a website for fan-subtitled anime before becoming a legal streaming service!",
        "image": "crunchyroll",
    },
    {
        "id": 171, "category": "entertainment",
        "company": "Apple Music", "domain": "music.apple.com",
        "hint": "A musical note on a red gradient background",
        "options": ["Apple Music", "Spotify", "Amazon Music", "Tidal"],
        "fun_fact": "Apple Music launched in 2015 and reached 100 million subscribers by 2022!",
        "image": "applemusic",
    },
    {
        "id": 172, "category": "entertainment",
        "company": "Amazon Music", "domain": "music.amazon.com",
        "hint": "A blue play button with a smile",
        "options": ["Amazon Music", "Apple Music", "Spotify", "Deezer"],
        "fun_fact": "Amazon Music was one of the first online music stores launching in 2007!",
        "image": "amazonmusic",
    },
    {
        "id": 173, "category": "entertainment",
        "company": "SoundCloud", "domain": "soundcloud.com",
        "hint": "An orange cloud shape with sound lines",
        "options": ["SoundCloud", "Bandcamp", "Audiomack", "Mixcloud"],
        "fun_fact": "SoundCloud was created in Berlin Germany and helped launch the careers of many famous artists!",
        "image": "soundcloud",
    },
    {
        "id": 174, "category": "entertainment",
        "company": "Deezer", "domain": "deezer.com",
        "hint": "A sound wave equalizer in purple",
        "options": ["Deezer", "Spotify", "Tidal", "Pandora"],
        "fun_fact": "Deezer is a French music streaming service with over 90 million tracks!",
        "image": "deezer",
    },
    {
        "id": 175, "category": "entertainment",
        "company": "Activision", "domain": "activision.com",
        "hint": "A stylised A with a line through it",
        "options": ["Activision", "EA", "Ubisoft", "THQ"],
        "fun_fact": "Activision was the world's first independent video game developer founded in 1979!",
        "image": "activision",
    },
    {
        "id": 176, "category": "entertainment",
        "company": "Warner Bros.", "domain": "warnerbros.com",
        "hint": "A shield shape with WB letters",
        "options": ["Warner Bros.", "Universal", "Paramount", "Columbia"],
        "fun_fact": "The Warner Bros shield logo has been used since the 1920s making it nearly 100 years old!",
        "image": "warnerbros",
    },
    {
        "id": 177, "category": "entertainment",
        "company": "Marvel", "domain": "marvel.com",
        "hint": "Bold red letters on white",
        "options": ["Marvel", "DC Comics", "Dark Horse", "Image"],
        "fun_fact": "Marvel Comics nearly went bankrupt in the 1990s before the MCU saved them!",
        "image": "marvel",
    },
    {
        "id": 178, "category": "entertainment",
        "company": "Cartoon Network", "domain": "cartoonnetwork.com",
        "hint": "Black and white checkered CN letters",
        "options": ["Cartoon Network", "Nickelodeon", "Disney Channel", "PBS Kids"],
        "fun_fact": "Cartoon Network launched in 1992 and its first show was a Bugs Bunny cartoon!",
        "image": "cartoonnetwork",
    },
    {
        "id": 179, "category": "entertainment",
        "company": "Nickelodeon", "domain": "nickelodeon.com",
        "hint": "An orange splat shape",
        "options": ["Nickelodeon", "Cartoon Network", "Disney Channel", "PBS Kids"],
        "fun_fact": "Nickelodeon's orange splat logo was inspired by the network's love of slime!",
        "image": "nickelodeon",
    },
    {
        "id": 180, "category": "entertainment",
        "company": "Valve", "domain": "valvesoftware.com",
        "hint": "A bald head with a valve/handle on the back",
        "options": ["Valve", "Epic Games", "Bethesda", "id Software"],
        "fun_fact": "Valve created both Steam and iconic games like Half-Life Portal and Counter-Strike!",
        "image": "valve",
    },
    {
        "id": 181, "category": "entertainment",
        "company": "Mojang", "domain": "mojang.com",
        "hint": "A red blocky face or head shape",
        "options": ["Mojang", "Valve", "Epic", "Bethesda"],
        "fun_fact": "Mojang is the Swedish studio that created Minecraft — mojang means 'gadget' in Swedish!",
        "image": "mojang",
    },
    {
        "id": 182, "category": "entertainment",
        "company": "Amazon Prime Video", "domain": "primevideo.com",
        "hint": "A blue play button with a smile arrow",
        "options": ["Amazon Prime Video", "Netflix", "Hulu", "Disney+"],
        "fun_fact": "Amazon Prime Video is available in over 240 countries making it one of the most global streaming services!",
        "image": "primevideo",
    },
    {
        "id": 183, "category": "entertainment",
        "company": "DC Comics", "domain": "dc.com",
        "hint": "Letters inside a circle",
        "options": ["DC Comics", "Marvel", "Image", "Dark Horse"],
        "fun_fact": "DC originally stood for Detective Comics — so saying DC Comics technically means Detective Comics Comics!",
        "image": "dc",
    },

    # ========== FASHION & LIFESTYLE (184-205) ==========
    {
        "id": 184, "category": "fashion",
        "company": "Vans", "domain": "vans.com",
        "hint": "A bold V shape with a stripe through it",
        "options": ["Vans", "Converse", "DC Shoes", "Etnies"],
        "fun_fact": "Vans waffle-pattern sole was created using an actual waffle iron pressed into rubber!",
        "image": "vans",
    },
    {
        "id": 185, "category": "fashion",
        "company": "Gucci", "domain": "gucci.com",
        "hint": "Two interlocking G letters mirrored",
        "options": ["Gucci", "Prada", "Fendi", "Louis Vuitton"],
        "fun_fact": "Gucci's double G logo represents the initials of founder Guccio Gucci!",
        "image": "gucci",
    },
    {
        "id": 186, "category": "fashion",
        "company": "Louis Vuitton", "domain": "louisvuitton.com",
        "hint": "Interlocking L and V letters",
        "options": ["Louis Vuitton", "Gucci", "Hermès", "Chanel"],
        "fun_fact": "Louis Vuitton started as a trunk maker for French royalty in 1854!",
        "image": "louisvuitton",
    },
    {
        "id": 187, "category": "fashion",
        "company": "Chanel", "domain": "chanel.com",
        "hint": "Two interlocking C letters facing opposite directions",
        "options": ["Chanel", "Dior", "Gucci", "Prada"],
        "fun_fact": "Coco Chanel created the little black dress and Chanel No. 5 the world's most famous perfume!",
        "image": "chanel",
    },
    {
        "id": 188, "category": "fashion",
        "company": "Burberry", "domain": "burberry.com",
        "hint": "An equestrian knight on horseback carrying a flag",
        "options": ["Burberry", "Barbour", "Ralph Lauren", "Tommy Hilfiger"],
        "fun_fact": "Burberry's famous plaid pattern was originally used as a trench coat lining for British soldiers!",
        "image": "burberry",
    },
    {
        "id": 189, "category": "fashion",
        "company": "Zara", "domain": "zara.com",
        "hint": "Bold overlapping letters in black",
        "options": ["Zara", "H&M", "Uniqlo", "Primark"],
        "fun_fact": "Zara can design and get a new garment on shelves in just two weeks!",
        "image": "zara",
    },
    {
        "id": 190, "category": "fashion",
        "company": "H&M", "domain": "hm.com",
        "hint": "Red bold letters",
        "options": ["H&M", "Zara", "Uniqlo", "Forever 21"],
        "fun_fact": "H&M stands for Hennes & Mauritz — the company started in Sweden in 1947 selling only women's clothes!",
        "image": "hm",
    },
    {
        "id": 191, "category": "fashion",
        "company": "Uniqlo", "domain": "uniqlo.com",
        "hint": "Red square with white Japanese-style letters",
        "options": ["Uniqlo", "Muji", "GU", "H&M"],
        "fun_fact": "Uniqlo started as a men's clothing store in Japan called Unique Clothing Warehouse!",
        "image": "uniqlo",
    },
    {
        "id": 192, "category": "fashion",
        "company": "Lululemon", "domain": "lululemon.com",
        "hint": "A stylised omega or A shape in red",
        "options": ["Lululemon", "Athleta", "Alo Yoga", "Fabletics"],
        "fun_fact": "Lululemon's founder chose the name because he thought it would be funny to hear Japanese people say it!",
        "image": "lululemon",
    },
    {
        "id": 193, "category": "fashion",
        "company": "Supreme", "domain": "supremenewyork.com",
        "hint": "White text in a red box",
        "options": ["Supreme", "BAPE", "Stüssy", "Palace"],
        "fun_fact": "Supreme started as a small skateboard shop in New York in 1994 and became a billion-dollar brand!",
        "image": "supreme",
    },
    {
        "id": 194, "category": "fashion",
        "company": "Timberland", "domain": "timberland.com",
        "hint": "A tree silhouette in a rounded shape",
        "options": ["Timberland", "Caterpillar", "Dr. Martens", "Red Wing"],
        "fun_fact": "Timberland's iconic yellow boot was originally designed for hard-working New England labourers!",
        "image": "timberland",
    },
    {
        "id": 195, "category": "fashion",
        "company": "Dr. Martens", "domain": "drmartens.com",
        "hint": "A heel loop tab shape in yellow stitching",
        "options": ["Dr. Martens", "Timberland", "Caterpillar", "Blundstone"],
        "fun_fact": "Dr. Martens boots were invented by a German doctor to help his injured foot heal after a skiing accident!",
        "image": "drmartens",
    },
    {
        "id": 196, "category": "fashion",
        "company": "Birkenstock", "domain": "birkenstock.com",
        "hint": "A blue footbed outline shape",
        "options": ["Birkenstock", "Crocs", "Teva", "Keen"],
        "fun_fact": "Birkenstock has been making shoes since 1774 — that's over 250 years of sandal-making!",
        "image": "birkenstock",
    },
    {
        "id": 197, "category": "fashion",
        "company": "Rolex", "domain": "rolex.com",
        "hint": "A golden crown with five points",
        "options": ["Rolex", "Omega", "Tag Heuer", "Cartier"],
        "fun_fact": "Rolex's crown logo represents the brand's status as the king of watches!",
        "image": "rolex",
    },
    {
        "id": 198, "category": "fashion",
        "company": "Costco", "domain": "costco.com",
        "hint": "Red and blue text on white",
        "options": ["Costco", "Sam's Club", "BJ's", "Aldi"],
        "fun_fact": "Costco's food court hot dog and soda combo has cost $1.50 since 1985 and the CEO refuses to raise it!",
        "image": "costco",
    },
    {
        "id": 199, "category": "fashion",
        "company": "Walmart", "domain": "walmart.com",
        "hint": "A yellow spark or sunburst shape",
        "options": ["Walmart", "Target", "Costco", "Kroger"],
        "fun_fact": "Walmart is the world's largest company by revenue and the largest private employer!",
        "image": "walmart",
    },
    {
        "id": 200, "category": "fashion",
        "company": "Dior", "domain": "dior.com",
        "hint": "Elegant serif letters in grey",
        "options": ["Dior", "Chanel", "Givenchy", "YSL"],
        "fun_fact": "Christian Dior revolutionised fashion in 1947 with his New Look collection of full skirts and fitted waists!",
        "image": "dior",
    },
    {
        "id": 201, "category": "fashion",
        "company": "Prada", "domain": "prada.com",
        "hint": "An inverted triangle with text inside",
        "options": ["Prada", "Gucci", "Versace", "Fendi"],
        "fun_fact": "Prada's logo is an inverted triangle originally used as a tag on their luxury leather trunks!",
        "image": "prada",
    },
    {
        "id": 202, "category": "fashion",
        "company": "Gap", "domain": "gap.com",
        "hint": "A dark blue square with white letters",
        "options": ["Gap", "Old Navy", "Banana Republic", "J.Crew"],
        "fun_fact": "Gap got its name from 'the generation gap' between children and adults in the 1960s!",
        "image": "gap",
    },
    {
        "id": 203, "category": "fashion",
        "company": "Swatch", "domain": "swatch.com",
        "hint": "A Swiss cross with colourful accents",
        "options": ["Swatch", "Casio", "Timex", "Seiko"],
        "fun_fact": "Swatch was created to save the Swiss watch industry from cheap Japanese digital watches!",
        "image": "swatch",
    },
    {
        "id": 204, "category": "fashion",
        "company": "Casio", "domain": "casio.com",
        "hint": "Bold angular letters in blue",
        "options": ["Casio", "Seiko", "Citizen", "Timex"],
        "fun_fact": "Casio's G-Shock watch was designed to survive a 10-metre drop and is used by military worldwide!",
        "image": "casio",
    },
    {
        "id": 205, "category": "fashion",
        "company": "Omega", "domain": "omega.com",
        "hint": "The Greek letter omega symbol Ω in gold",
        "options": ["Omega", "Rolex", "Tag Heuer", "Breitling"],
        "fun_fact": "Omega has been the official timekeeper of the Olympics since 1932!",
        "image": "omega",
    },
]


def generate_quiz(num_questions: int = 10, category: str | None = None) -> list:
    """Generate a logo identification quiz with shuffled options."""
    if category and category in CATEGORIES:
        pool = [q for q in QUESTION_BANK if q["category"] == category]
    else:
        pool = list(QUESTION_BANK)

    if len(pool) < num_questions:
        num_questions = len(pool)

    selected = random.sample(pool, num_questions)

    for q in selected:
        company = q["company"]
        options = list(q["options"])
        random.shuffle(options)
        q["_shuffled_options"] = options
        q["_answer_idx"] = options.index(company)
        q["_logo_url"] = get_logo_url(q["domain"])
        q["_image"] = q.get("image")

    random.shuffle(selected)
    return selected


def get_category_counts() -> dict:
    """Return {category_id: count} for questions in each category."""
    counts = {cat_id: 0 for cat_id in CATEGORIES}
    for q in QUESTION_BANK:
        counts[q["category"]] += 1
    return counts
