"""
World Map Explorer - Geography Quiz for Arjun

A fun world geography question bank with map coordinates.
Designed for an 11-year-old to build excitement and confidence while exploring
continents, capitals, landmarks, nature, flags, and world culture.
"""

import random

# ISO 3166-1 alpha-2 codes for flag images (flagcdn.com)
COUNTRY_FLAG_CODES = {
    "Canada": "ca", "Japan": "jp", "United States": "us", "Australia": "au",
    "India": "in", "France": "fr", "Switzerland": "ch", "China": "cn",
    "Brazil": "br", "Mexico": "mx", "Turkey": "tr", "United Kingdom": "gb",
    "Bangladesh": "bd", "Indonesia": "id", "Germany": "de", "Italy": "it",
    "Vietnam": "vn", "New Zealand": "nz", "South Korea": "kr", "Poland": "pl",
    "South Africa": "za", "Argentina": "ar", "Spain": "es", "Russia": "ru",
    "Egypt": "eg", "Peru": "pe", "Ireland": "ie", "Belgium": "be",
    "Sweden": "se", "Norway": "no", "Denmark": "dk", "Finland": "fi",
    "Greece": "gr", "Thailand": "th", "Pakistan": "pk", "Nigeria": "ng",
    "Colombia": "co", "Chile": "cl", "Austria": "at", "Nepal": "np",
    "Iran": "ir", "Saudi Arabia": "sa", "Malaysia": "my", "Singapore": "sg",
    "Philippines": "ph", "Taiwan": "tw", "Mongolia": "mn", "North Korea": "kp",
    "Liberia": "lr", "Cambodia": "kh", "Portugal": "pt", "Panama": "pa",
    "Lebanon": "lb", "Jamaica": "jm", "Ecuador": "ec", "Kenya": "ke",
    "Tanzania": "tz", "Israel": "il", "Wales": "gb-wls",
}


def get_flag_url(country: str) -> str | None:
    """Return the flagcdn.com URL for a country, or None if unknown."""
    code = COUNTRY_FLAG_CODES.get(country)
    if code:
        return f"https://flagcdn.com/w320/{code}.png"
    return None


CATEGORIES = {
    "continents": {"name": "Continents & Oceans", "emoji": "🌍", "color": "#3b82f6"},
    "capitals": {"name": "Countries & Capitals", "emoji": "🏛️", "color": "#10b981"},
    "landmarks": {"name": "Famous Landmarks", "emoji": "🗽", "color": "#f59e0b"},
    "nature": {"name": "Rivers, Mountains & Wonders", "emoji": "🏔️", "color": "#8b5cf6"},
    "flags": {"name": "Flags & Symbols", "emoji": "🏳️", "color": "#ef4444"},
    "culture": {"name": "World Culture", "emoji": "🎭", "color": "#ec4899"},
}

QUESTION_BANK = [
    # ========== CONTINENTS & OCEANS (~20 questions) ==========
    {
        "id": 1,
        "category": "continents",
        "question": "Which continent do penguins live on in the wild?",
        "options": ["Africa", "Europe", "Antarctica", "Asia"],
        "answer": 2,
        "explanation": "Fun fact: Antarctica is home to millions of penguins! They love the cold and spend most of their time in the water.",
        "lat": -75.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 2,
        "category": "continents",
        "question": "Which continent is India in?",
        "options": ["Europe", "Africa", "Asia", "Australia"],
        "answer": 2,
        "explanation": "Did you know? Asia is the biggest continent and India is one of its largest countries!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 3,
        "category": "continents",
        "question": "The United States is on which continent?",
        "options": ["South America", "Europe", "North America", "Asia"],
        "answer": 2,
        "explanation": "North America includes the USA, Canada, and Mexico—plus lots of other countries!",
        "lat": 38.9072,
        "lon": -77.0369,
        "country": "United States",
    },
    {
        "id": 4,
        "category": "continents",
        "question": "Which continent is known for safaris and lions?",
        "options": ["Asia", "Australia", "Africa", "Europe"],
        "answer": 2,
        "explanation": "Africa is amazing! It's where you'll find lions, elephants, giraffes, and zebras in the wild!",
        "lat": -1.2921,
        "lon": 36.8219,
        "country": "",
    },
    {
        "id": 5,
        "category": "continents",
        "question": "Which is the biggest ocean?",
        "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
        "answer": 3,
        "explanation": "Wow! The Pacific Ocean is so huge it covers more area than ALL the land on Earth combined!",
        "lat": 0.0,
        "lon": -150.0,
        "country": "",
    },
    {
        "id": 6,
        "category": "continents",
        "question": "Which continent is France in?",
        "options": ["Asia", "Africa", "Europe", "South America"],
        "answer": 2,
        "explanation": "France is in Europe—the same continent as the UK, Germany, Italy, and Spain!",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
    },
    {
        "id": 7,
        "category": "continents",
        "question": "Which continent is also a country?",
        "options": ["Europe", "Australia", "Antarctica", "South America"],
        "answer": 1,
        "explanation": "Australia is super special—it's the only place that's BOTH a continent AND a whole country!",
        "lat": -33.8688,
        "lon": 151.2093,
        "country": "Australia",
    },
    {
        "id": 8,
        "category": "continents",
        "question": "Which continent has the Amazon rainforest?",
        "options": ["Africa", "Asia", "South America", "Australia"],
        "answer": 2,
        "explanation": "The Amazon is incredible—it produces about 20% of the oxygen we breathe! It's like Earth's giant lung!",
        "lat": -3.4653,
        "lon": -58.3800,
        "country": "Brazil",
    },
    {
        "id": 9,
        "category": "continents",
        "question": "Which continent has the most people?",
        "options": ["Africa", "Europe", "Asia", "North America"],
        "answer": 2,
        "explanation": "Asia has over 4.5 billion people—that's more than half of everyone on Earth!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "",
    },
    {
        "id": 10,
        "category": "continents",
        "question": "Which ocean surrounds the North Pole?",
        "options": ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"],
        "answer": 3,
        "explanation": "The Arctic Ocean is where polar bears live! It's the coldest and smallest of the five oceans.",
        "lat": 90.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 11,
        "category": "continents",
        "question": "Which continent has the Sahara Desert?",
        "options": ["Asia", "Australia", "Africa", "South America"],
        "answer": 2,
        "explanation": "The Sahara is the world's biggest hot desert—it's almost as big as the entire United States!",
        "lat": 23.4162,
        "lon": 25.6628,
        "country": "",
    },
    {
        "id": 12,
        "category": "continents",
        "question": "Which continent is Japan in?",
        "options": ["Europe", "Africa", "Asia", "Australia"],
        "answer": 2,
        "explanation": "Japan is an island country in Asia—famous for anime, sushi, and cherry blossoms!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 13,
        "category": "continents",
        "question": "Which continent is the coldest?",
        "options": ["Europe", "North America", "Antarctica", "Asia"],
        "answer": 2,
        "explanation": "Antarctica is FREEZING! Temperatures can drop below -100°F. Brrr!",
        "lat": -75.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 14,
        "category": "continents",
        "question": "Which ocean lies between Africa and Australia?",
        "options": ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"],
        "answer": 2,
        "explanation": "The Indian Ocean is the third-largest ocean—and it's named after India!",
        "lat": -20.0,
        "lon": 80.0,
        "country": "",
    },
    {
        "id": 15,
        "category": "continents",
        "question": "Which continent is Brazil in?",
        "options": ["Africa", "Asia", "Europe", "South America"],
        "answer": 3,
        "explanation": "Brazil is the biggest country in South America—home to the Amazon and Carnival!",
        "lat": -22.9068,
        "lon": -43.1729,
        "country": "Brazil",
    },
    {
        "id": 16,
        "category": "continents",
        "question": "Which ocean separates Europe from North America?",
        "options": ["Pacific Ocean", "Indian Ocean", "Atlantic Ocean", "Arctic Ocean"],
        "answer": 2,
        "explanation": "The Atlantic Ocean is huge! Early explorers like Columbus crossed it to reach the Americas.",
        "lat": 45.0,
        "lon": -30.0,
        "country": "",
    },
    {
        "id": 17,
        "category": "continents",
        "question": "Which continent has no permanent human population?",
        "options": ["Australia", "Antarctica", "Africa", "South America"],
        "answer": 1,
        "explanation": "Only scientists and researchers visit Antarctica—no one lives there permanently. Just penguins!",
        "lat": -75.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 18,
        "category": "continents",
        "question": "Which continent is China in?",
        "options": ["Europe", "Africa", "Asia", "Australia"],
        "answer": 2,
        "explanation": "China is in Asia—it has the most people of any country and the famous Great Wall!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 19,
        "category": "continents",
        "question": "Which is the largest continent by area?",
        "options": ["Africa", "Europe", "North America", "Asia"],
        "answer": 3,
        "explanation": "Asia is massive! It covers about 30% of all the land on Earth.",
        "lat": 34.0479,
        "lon": 100.6197,
        "country": "",
    },
    {
        "id": 20,
        "category": "continents",
        "question": "Which continent is Egypt in?",
        "options": ["Asia", "Europe", "Africa", "South America"],
        "answer": 2,
        "explanation": "Egypt is in Africa—home to the ancient Pyramids and the mighty Nile River!",
        "lat": 30.0444,
        "lon": 31.2357,
        "country": "Egypt",
    },
    # ========== CAPITALS (~35 questions) ==========
    {
        "id": 21,
        "category": "capitals",
        "question": "What is the capital of the United States?",
        "options": ["New York", "Los Angeles", "Washington, D.C.", "Chicago"],
        "answer": 2,
        "explanation": "Washington, D.C. was built specially to be the capital—and it's not part of any state!",
        "lat": 38.9072,
        "lon": -77.0369,
        "country": "United States",
    },
    {
        "id": 22,
        "category": "capitals",
        "question": "What is the capital of France?",
        "options": ["Lyon", "Nice", "Paris", "Marseille"],
        "answer": 2,
        "explanation": "Paris is called the City of Light—and it's home to the amazing Eiffel Tower!",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
    },
    {
        "id": 23,
        "category": "capitals",
        "question": "What is the capital of India?",
        "options": ["Mumbai", "Bangalore", "New Delhi", "Kolkata"],
        "answer": 2,
        "explanation": "New Delhi is where India's government works—and it has beautiful monuments!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 24,
        "category": "capitals",
        "question": "What is the capital of Japan?",
        "options": ["Osaka", "Kyoto", "Tokyo", "Hiroshima"],
        "answer": 2,
        "explanation": "Tokyo is one of the biggest cities in the world—over 37 million people live in the area!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 25,
        "category": "capitals",
        "question": "What is the capital of the United Kingdom?",
        "options": ["Manchester", "London", "Edinburgh", "Birmingham"],
        "answer": 1,
        "explanation": "London has Big Ben, the Tower of London, and has been a major city for over 2,000 years!",
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
    },
    {
        "id": 26,
        "category": "capitals",
        "question": "What is the capital of China?",
        "options": ["Shanghai", "Hong Kong", "Beijing", "Guangzhou"],
        "answer": 2,
        "explanation": "Beijing is where you'll find the Forbidden City and the Great Wall nearby!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 27,
        "category": "capitals",
        "question": "What is the capital of Australia?",
        "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"],
        "answer": 2,
        "explanation": "Canberra was chosen as the capital because Sydney and Melbourne couldn't agree—so they picked a city between them!",
        "lat": -35.2809,
        "lon": 149.1300,
        "country": "Australia",
    },
    {
        "id": 28,
        "category": "capitals",
        "question": "What is the capital of Egypt?",
        "options": ["Alexandria", "Cairo", "Luxor", "Aswan"],
        "answer": 1,
        "explanation": "Cairo is right near the Pyramids of Giza—you can see them from the city!",
        "lat": 30.0444,
        "lon": 31.2357,
        "country": "Egypt",
    },
    {
        "id": 29,
        "category": "capitals",
        "question": "What is the capital of Canada?",
        "options": ["Toronto", "Vancouver", "Ottawa", "Montreal"],
        "answer": 2,
        "explanation": "Ottawa was picked as the capital because it's right between English-speaking and French-speaking parts of Canada!",
        "lat": 45.4215,
        "lon": -75.6972,
        "country": "Canada",
    },
    {
        "id": 30,
        "category": "capitals",
        "question": "What is the capital of Mexico?",
        "options": ["Cancún", "Guadalajara", "Mexico City", "Tijuana"],
        "answer": 2,
        "explanation": "Mexico City is one of the oldest cities in the Americas—and one of the biggest in the world!",
        "lat": 19.4326,
        "lon": -99.1332,
        "country": "Mexico",
    },
    {
        "id": 31,
        "category": "capitals",
        "question": "What is the capital of Brazil?",
        "options": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
        "answer": 2,
        "explanation": "Fun fact: Brasília was built in 1960 and the city is shaped like an airplane from above!",
        "lat": -15.7975,
        "lon": -47.8919,
        "country": "Brazil",
    },
    {
        "id": 32,
        "category": "capitals",
        "question": "What is the capital of Italy?",
        "options": ["Milan", "Venice", "Rome", "Florence"],
        "answer": 2,
        "explanation": "Rome is called the Eternal City—it was the center of the mighty Roman Empire!",
        "lat": 41.9028,
        "lon": 12.4964,
        "country": "Italy",
    },
    {
        "id": 33,
        "category": "capitals",
        "question": "What is the capital of Russia?",
        "options": ["Saint Petersburg", "Moscow", "Kazan", "Sochi"],
        "answer": 1,
        "explanation": "Moscow has the famous Red Square and the colorful St. Basil's Cathedral!",
        "lat": 55.7558,
        "lon": 37.6173,
        "country": "Russia",
    },
    {
        "id": 34,
        "category": "capitals",
        "question": "What is the capital of Germany?",
        "options": ["Munich", "Berlin", "Hamburg", "Frankfurt"],
        "answer": 1,
        "explanation": "Berlin has amazing museums, the Brandenburg Gate, and a rich history!",
        "lat": 52.5200,
        "lon": 13.4050,
        "country": "Germany",
    },
    {
        "id": 35,
        "category": "capitals",
        "question": "What is the capital of Spain?",
        "options": ["Barcelona", "Seville", "Madrid", "Valencia"],
        "answer": 2,
        "explanation": "Madrid is in the center of Spain—famous for art museums and delicious food!",
        "lat": 40.4168,
        "lon": -3.7038,
        "country": "Spain",
    },
    {
        "id": 36,
        "category": "capitals",
        "question": "What is the capital of South Korea?",
        "options": ["Busan", "Seoul", "Incheon", "Daegu"],
        "answer": 1,
        "explanation": "Seoul is super high-tech—they have some of the fastest internet in the world!",
        "lat": 37.5665,
        "lon": 126.9780,
        "country": "South Korea",
    },
    {
        "id": 37,
        "category": "capitals",
        "question": "What is the capital of Argentina?",
        "options": ["Córdoba", "Rosario", "Buenos Aires", "Mendoza"],
        "answer": 2,
        "explanation": "Buenos Aires means 'good airs' in Spanish—and it's the birthplace of the tango dance!",
        "lat": -34.6037,
        "lon": -58.3816,
        "country": "Argentina",
    },
    {
        "id": 38,
        "category": "capitals",
        "question": "What is the capital of Greece?",
        "options": ["Thessaloniki", "Athens", "Santorini", "Crete"],
        "answer": 1,
        "explanation": "Athens is one of the oldest cities in the world—over 3,400 years old! The Olympics started there!",
        "lat": 37.9838,
        "lon": 23.7275,
        "country": "Greece",
    },
    {
        "id": 39,
        "category": "capitals",
        "question": "What is the capital of Thailand?",
        "options": ["Chiang Mai", "Phuket", "Bangkok", "Pattaya"],
        "answer": 2,
        "explanation": "Bangkok has the longest city name in the world—over 160 letters! Try saying it!",
        "lat": 13.7563,
        "lon": 100.5018,
        "country": "Thailand",
    },
    {
        "id": 40,
        "category": "capitals",
        "question": "What is the capital of Indonesia?",
        "options": ["Bali", "Jakarta", "Surabaya", "Sumatra"],
        "answer": 1,
        "explanation": "Jakarta is on the island of Java—Indonesia has over 17,000 islands!",
        "lat": -6.2088,
        "lon": 106.8456,
        "country": "Indonesia",
    },
    {
        "id": 41,
        "category": "capitals",
        "question": "What is the capital of the Philippines?",
        "options": ["Cebu", "Manila", "Davao", "Boracay"],
        "answer": 1,
        "explanation": "Manila is one of the most crowded cities in the world—lots of people, lots of energy!",
        "lat": 14.5995,
        "lon": 120.9842,
        "country": "Philippines",
    },
    {
        "id": 42,
        "category": "capitals",
        "question": "What is the capital of Malaysia?",
        "options": ["Penang", "Kuala Lumpur", "Singapore", "Borneo"],
        "answer": 1,
        "explanation": "Kuala Lumpur has the famous Petronas Twin Towers—they were once the tallest buildings in the world!",
        "lat": 3.1390,
        "lon": 101.6869,
        "country": "Malaysia",
    },
    {
        "id": 43,
        "category": "capitals",
        "question": "What is the capital of Kenya?",
        "options": ["Mombasa", "Nairobi", "Kisumu", "Zanzibar"],
        "answer": 1,
        "explanation": "Cool fact: Nairobi is the only capital city with a national park inside its borders!",
        "lat": -1.2921,
        "lon": 36.8219,
        "country": "Kenya",
    },
    {
        "id": 44,
        "category": "capitals",
        "question": "Paris is the capital of which country?",
        "options": ["Italy", "France", "Germany", "Spain"],
        "answer": 1,
        "explanation": "Paris is called the City of Light — it has the Eiffel Tower, amazing bakeries, and beautiful art museums!",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
    },
    {
        "id": 45,
        "category": "capitals",
        "question": "Tokyo is the capital of which country?",
        "options": ["China", "Japan", "South Korea", "Thailand"],
        "answer": 1,
        "explanation": "Tokyo is one of the biggest cities in the world — it has incredible technology, anime studios, and amazing food!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 46,
        "category": "capitals",
        "question": "London is the capital of which country?",
        "options": ["France", "Germany", "United Kingdom", "Ireland"],
        "answer": 2,
        "explanation": "London is home to Big Ben, Buckingham Palace, and the Queen's Guard with their tall fuzzy hats!",
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
    },
    {
        "id": 47,
        "category": "capitals",
        "question": "Berlin is the capital of which country?",
        "options": ["Austria", "Switzerland", "Germany", "Poland"],
        "answer": 2,
        "explanation": "Berlin is famous for its history and the Brandenburg Gate — and Germans love their pretzels!",
        "lat": 52.5200,
        "lon": 13.4050,
        "country": "Germany",
    },
    {
        "id": 48,
        "category": "capitals",
        "question": "Rome is the capital of which country?",
        "options": ["Spain", "Greece", "Italy", "France"],
        "answer": 2,
        "explanation": "Rome is called the Eternal City — the ancient Romans built roads, bridges, and the Colosseum there!",
        "lat": 41.9028,
        "lon": 12.4964,
        "country": "Italy",
    },
    {
        "id": 49,
        "category": "capitals",
        "question": "Cairo is the capital of which country?",
        "options": ["Egypt", "Morocco", "Sudan", "Libya"],
        "answer": 0,
        "explanation": "Cairo is right next to the Great Pyramids! You can see them from many spots in the city!",
        "lat": 30.0444,
        "lon": 31.2357,
        "country": "Egypt",
    },
    {
        "id": 50,
        "category": "capitals",
        "question": "Moscow is the capital of which country?",
        "options": ["Ukraine", "Poland", "Russia", "Germany"],
        "answer": 2,
        "explanation": "Moscow has the famous Red Square and the colorful St. Basil's Cathedral with its onion-shaped domes!",
        "lat": 55.7558,
        "lon": 37.6173,
        "country": "Russia",
    },
    {
        "id": 51,
        "category": "capitals",
        "question": "Beijing is the capital of which country?",
        "options": ["Japan", "China", "South Korea", "India"],
        "answer": 1,
        "explanation": "Beijing has the Forbidden City — for 500 years only the emperor was allowed inside!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 52,
        "category": "capitals",
        "question": "Which famous city is the capital of Thailand?",
        "options": ["Bangkok", "Tokyo", "Manila", "Jakarta"],
        "answer": 0,
        "explanation": "Bangkok's full official name is the longest city name in the world — over 160 letters long!",
        "lat": 13.7563,
        "lon": 100.5018,
        "country": "Thailand",
    },
    {
        "id": 53,
        "category": "capitals",
        "question": "Athens is the capital of which country?",
        "options": ["Italy", "Turkey", "Greece", "Spain"],
        "answer": 2,
        "explanation": "Athens is one of the world's oldest cities — the ancient Greeks invented the Olympic Games there!",
        "lat": 37.9838,
        "lon": 23.7275,
        "country": "Greece",
    },
    {
        "id": 54,
        "category": "capitals",
        "question": "New Delhi is the capital of which country?",
        "options": ["Pakistan", "India", "Bangladesh", "Sri Lanka"],
        "answer": 1,
        "explanation": "India is the country with the most people in the world — and New Delhi is a huge, bustling capital!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 55,
        "category": "capitals",
        "question": "Washington, D.C. is the capital of which country?",
        "options": ["Canada", "United States", "Mexico", "Brazil"],
        "answer": 1,
        "explanation": "Washington, D.C. has the White House, the Capitol, and tons of free museums you can visit!",
        "lat": 38.9072,
        "lon": -77.0369,
        "country": "United States",
    },
    # ========== LANDMARKS (~30 questions) ==========
    {
        "id": 56,
        "category": "landmarks",
        "question": "In which country would you find the Eiffel Tower?",
        "options": ["Germany", "Belgium", "France", "Spain"],
        "answer": 2,
        "explanation": "Did you know? The Eiffel Tower was built for the 1889 World's Fair and was supposed to be temporary!",
        "lat": 48.8584,
        "lon": 2.2945,
        "country": "France",
    },
    {
        "id": 57,
        "category": "landmarks",
        "question": "The Great Pyramids are in which country?",
        "options": ["Libya", "Sudan", "Egypt", "Jordan"],
        "answer": 2,
        "explanation": "The Great Pyramid is the last of the Seven Wonders of the Ancient World still standing! Amazing!",
        "lat": 29.9792,
        "lon": 31.1342,
        "country": "Egypt",
    },
    {
        "id": 58,
        "category": "landmarks",
        "question": "Where is the Statue of Liberty?",
        "options": ["France", "United Kingdom", "United States", "Canada"],
        "answer": 2,
        "explanation": "Fun fact: France gave the Statue of Liberty to the USA as a gift of friendship in 1886!",
        "lat": 40.6892,
        "lon": -74.0445,
        "country": "United States",
    },
    {
        "id": 59,
        "category": "landmarks",
        "question": "The Great Wall of China is in which country?",
        "options": ["Japan", "Korea", "China", "Mongolia"],
        "answer": 2,
        "explanation": "The Great Wall stretches over 13,000 miles—longer than the distance from New York to Tokyo!",
        "lat": 40.4319,
        "lon": 116.5704,
        "country": "China",
    },
    {
        "id": 60,
        "category": "landmarks",
        "question": "The Taj Mahal is in which country?",
        "options": ["Pakistan", "Bangladesh", "India", "Nepal"],
        "answer": 2,
        "explanation": "An emperor built the Taj Mahal as a tomb for his favorite wife—it took 22 years and 20,000 workers!",
        "lat": 27.1751,
        "lon": 78.0421,
        "country": "India",
    },
    {
        "id": 61,
        "category": "landmarks",
        "question": "Big Ben is in which city?",
        "options": ["Paris", "Dublin", "London", "Edinburgh"],
        "answer": 2,
        "explanation": "Big Ben is actually the name of the BELL inside the clock tower—not the tower itself!",
        "lat": 51.5007,
        "lon": -0.1246,
        "country": "United Kingdom",
    },
    {
        "id": 62,
        "category": "landmarks",
        "question": "The Colosseum, where gladiators fought, is in which city?",
        "options": ["Athens", "Rome", "Florence", "Venice"],
        "answer": 1,
        "explanation": "The Colosseum could hold 50,000 people! It's almost 2,000 years old.",
        "lat": 41.8902,
        "lon": 12.4922,
        "country": "Italy",
    },
    {
        "id": 63,
        "category": "landmarks",
        "question": "Christ the Redeemer statue overlooks which city?",
        "options": ["São Paulo", "Buenos Aires", "Rio de Janeiro", "Santiago"],
        "answer": 2,
        "explanation": "The statue's arms stretch 92 feet wide—it stands on a mountain overlooking Rio!",
        "lat": -22.9519,
        "lon": -43.2105,
        "country": "Brazil",
    },
    {
        "id": 64,
        "category": "landmarks",
        "question": "The Sydney Opera House is in which country?",
        "options": ["New Zealand", "Australia", "Indonesia", "South Africa"],
        "answer": 1,
        "explanation": "The roof looks like giant sails—it's one of the most photographed buildings in the world!",
        "lat": -33.8568,
        "lon": 151.2153,
        "country": "Australia",
    },
    {
        "id": 65,
        "category": "landmarks",
        "question": "The Leaning Tower of Pisa is in which country?",
        "options": ["France", "Spain", "Italy", "Greece"],
        "answer": 2,
        "explanation": "The tower leans because it was built on soft ground—people take funny photos 'holding it up'!",
        "lat": 43.7230,
        "lon": 10.3966,
        "country": "Italy",
    },
    {
        "id": 66,
        "category": "landmarks",
        "question": "The Golden Gate Bridge is in which US city?",
        "options": ["Los Angeles", "Seattle", "San Francisco", "San Diego"],
        "answer": 2,
        "explanation": "Fun fact: The bridge is actually orange-red, not gold! The color helps it show up in the fog.",
        "lat": 37.8199,
        "lon": -122.4783,
        "country": "United States",
    },
    {
        "id": 67,
        "category": "landmarks",
        "question": "The Empire State Building is in which city?",
        "options": ["Chicago", "Los Angeles", "New York", "Boston"],
        "answer": 2,
        "explanation": "It was the world's tallest building for 40 years and has 102 floors!",
        "lat": 40.7484,
        "lon": -73.9857,
        "country": "United States",
    },
    {
        "id": 68,
        "category": "landmarks",
        "question": "The Hollywood Sign is in which US city?",
        "options": ["San Diego", "Las Vegas", "Los Angeles", "San Francisco"],
        "answer": 2,
        "explanation": "Each letter is 45 feet tall! It was first put up in 1923 to advertise a housing development.",
        "lat": 34.1341,
        "lon": -118.3215,
        "country": "United States",
    },
    {
        "id": 69,
        "category": "landmarks",
        "question": "The Tokyo Tower is in which country?",
        "options": ["China", "South Korea", "Japan", "Taiwan"],
        "answer": 2,
        "explanation": "Tokyo Tower is painted orange and white—it's a famous symbol of Japan's capital!",
        "lat": 35.6586,
        "lon": 139.7454,
        "country": "Japan",
    },
    {
        "id": 70,
        "category": "landmarks",
        "question": "Stonehenge, the mysterious stone circle, is in which country?",
        "options": ["Ireland", "Scotland", "England", "Wales"],
        "answer": 2,
        "explanation": "No one knows exactly why Stonehenge was built—it's over 5,000 years old! Spooky!",
        "lat": 51.1789,
        "lon": -1.8262,
        "country": "United Kingdom",
    },
    {
        "id": 71,
        "category": "landmarks",
        "question": "The Tower of London, where the Crown Jewels are kept, is in which country?",
        "options": ["France", "Scotland", "England", "Ireland"],
        "answer": 2,
        "explanation": "Ravens have lived at the Tower for centuries—legend says if they leave, the kingdom will fall!",
        "lat": 51.5081,
        "lon": -0.0759,
        "country": "United Kingdom",
    },
    {
        "id": 72,
        "category": "landmarks",
        "question": "The Forbidden City is in which city?",
        "options": ["Shanghai", "Xi'an", "Beijing", "Hong Kong"],
        "answer": 2,
        "explanation": "For 500 years, only the emperor and his family could enter—ordinary people were forbidden!",
        "lat": 39.9163,
        "lon": 116.3972,
        "country": "China",
    },
    {
        "id": 73,
        "category": "landmarks",
        "question": "The Burj Khalifa, the world's tallest building, is in which city?",
        "options": ["Riyadh", "Abu Dhabi", "Dubai", "Doha"],
        "answer": 2,
        "explanation": "The Burj Khalifa is over 2,700 feet tall—that's more than half a mile high! Whoa!",
        "lat": 25.1972,
        "lon": 55.2744,
        "country": "United Arab Emirates",
    },
    {
        "id": 74,
        "category": "landmarks",
        "question": "The CN Tower is a famous landmark in which city?",
        "options": ["Montreal", "Vancouver", "Toronto", "Calgary"],
        "answer": 2,
        "explanation": "It was the world's tallest free-standing structure for 32 years!",
        "lat": 43.6426,
        "lon": -79.3871,
        "country": "Canada",
    },
    {
        "id": 75,
        "category": "landmarks",
        "question": "Mount Rushmore with the presidents' faces is in which country?",
        "options": ["Canada", "Mexico", "United States", "Brazil"],
        "answer": 2,
        "explanation": "The faces of Washington, Jefferson, Roosevelt, and Lincoln are carved 60 feet tall into the mountain!",
        "lat": 43.8791,
        "lon": -103.4591,
        "country": "United States",
    },
    {
        "id": 76,
        "category": "landmarks",
        "question": "The Acropolis with the Parthenon is in which city?",
        "options": ["Rome", "Istanbul", "Athens", "Cairo"],
        "answer": 2,
        "explanation": "The Parthenon was built 2,500 years ago for the goddess Athena!",
        "lat": 37.9715,
        "lon": 23.7267,
        "country": "Greece",
    },
    {
        "id": 77,
        "category": "landmarks",
        "question": "Machu Picchu, the lost Inca city, is in which country?",
        "options": ["Mexico", "Colombia", "Peru", "Bolivia"],
        "answer": 2,
        "explanation": "Machu Picchu was hidden in the mountains until 1911—no one knew it existed!",
        "lat": -13.1631,
        "lon": -72.5450,
        "country": "Peru",
    },
    {
        "id": 78,
        "category": "landmarks",
        "question": "The Kremlin fortress is in which city?",
        "options": ["Saint Petersburg", "Kiev", "Moscow", "Warsaw"],
        "answer": 2,
        "explanation": "The Kremlin means 'fortress' in Russian—it's been the center of power for centuries!",
        "lat": 55.7520,
        "lon": 37.6175,
        "country": "Russia",
    },
    {
        "id": 79,
        "category": "landmarks",
        "question": "In which country is Disneyland Paris?",
        "options": ["United Kingdom", "Belgium", "France", "Germany"],
        "answer": 2,
        "explanation": "Disneyland Paris is the most visited theme park in Europe—it opened in 1992!",
        "lat": 48.8722,
        "lon": 2.7758,
        "country": "France",
    },
    {
        "id": 80,
        "category": "landmarks",
        "question": "The Petronas Twin Towers are in which city?",
        "options": ["Singapore", "Bangkok", "Kuala Lumpur", "Jakarta"],
        "answer": 2,
        "explanation": "These twin towers were once the tallest buildings in the world!",
        "lat": 3.1579,
        "lon": 101.7116,
        "country": "Malaysia",
    },
    {
        "id": 81,
        "category": "landmarks",
        "question": "The White House is in which city?",
        "options": ["New York", "Philadelphia", "Washington, D.C.", "Boston"],
        "answer": 2,
        "explanation": "The President of the United States lives and works in the White House!",
        "lat": 38.8977,
        "lon": -77.0365,
        "country": "United States",
    },
    {
        "id": 82,
        "category": "landmarks",
        "question": "The Great Sphinx is in which country?",
        "options": ["Libya", "Sudan", "Egypt", "Jordan"],
        "answer": 2,
        "explanation": "The Sphinx has a lion's body and a human head—it's been guarding the Pyramids for 4,500 years!",
        "lat": 29.9753,
        "lon": 31.1376,
        "country": "Egypt",
    },
    {
        "id": 83,
        "category": "landmarks",
        "question": "The Brandenburg Gate is in which city?",
        "options": ["Munich", "Vienna", "Berlin", "Prague"],
        "answer": 2,
        "explanation": "This famous gate became a symbol of peace when the Berlin Wall fell in 1989!",
        "lat": 52.5163,
        "lon": 13.3777,
        "country": "Germany",
    },
    {
        "id": 84,
        "category": "landmarks",
        "question": "The Space Needle is in which US city?",
        "options": ["Portland", "Seattle", "San Francisco", "Denver"],
        "answer": 1,
        "explanation": "It was built for the 1962 World's Fair and has a rotating restaurant at the top!",
        "lat": 47.6205,
        "lon": -122.3493,
        "country": "United States",
    },
    {
        "id": 85,
        "category": "landmarks",
        "question": "The Niagara Falls are on the border of which two countries?",
        "options": ["USA & Mexico", "USA & Canada", "USA & Cuba", "Canada & Greenland"],
        "answer": 1,
        "explanation": "Over 3,000 tons of water flow over Niagara Falls every second! That's a LOT of water!",
        "lat": 43.0962,
        "lon": -79.0377,
        "country": "Canada",
    },
    # ========== NATURE (~25 questions) ==========
    {
        "id": 86,
        "category": "nature",
        "question": "What is the tallest mountain in the world?",
        "options": ["Kilimanjaro", "K2", "Mount Everest", "Denali"],
        "answer": 2,
        "explanation": "Mount Everest is 29,032 feet tall—about 5.5 miles high! People climb it from Nepal.",
        "lat": 27.9881,
        "lon": 86.9250,
        "country": "Nepal",
    },
    {
        "id": 87,
        "category": "nature",
        "question": "Which is the biggest ocean?",
        "options": ["Atlantic", "Indian", "Arctic", "Pacific"],
        "answer": 3,
        "explanation": "The Pacific is SO big it covers more area than all the land on Earth combined!",
        "lat": 0.0,
        "lon": -150.0,
        "country": "",
    },
    {
        "id": 88,
        "category": "nature",
        "question": "What is the longest river in the world?",
        "options": ["Amazon", "Mississippi", "Nile", "Yangtze"],
        "answer": 2,
        "explanation": "The Nile flows over 4,100 miles—it's been supporting life in Egypt for 5,000 years!",
        "lat": 30.0444,
        "lon": 31.2357,
        "country": "Egypt",
    },
    {
        "id": 89,
        "category": "nature",
        "question": "Where do most polar bears live — North Pole or South Pole?",
        "options": ["South Pole", "North Pole", "Both", "Neither"],
        "answer": 1,
        "explanation": "Polar bears live at the North Pole (Arctic)! Penguins live at the South Pole (Antarctica).",
        "lat": 90.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 90,
        "category": "nature",
        "question": "Italy is shaped like which item of clothing?",
        "options": ["A hat", "A glove", "A boot", "A sock"],
        "answer": 2,
        "explanation": "Italy looks like a boot kicking a ball! The 'ball' is the island of Sicily.",
        "lat": 41.9028,
        "lon": 12.4964,
        "country": "Italy",
    },
    {
        "id": 91,
        "category": "nature",
        "question": "What is the largest hot desert in the world?",
        "options": ["Gobi Desert", "Sahara Desert", "Arabian Desert", "Kalahari Desert"],
        "answer": 1,
        "explanation": "The Sahara is almost as big as the United States! It can get as hot as 136°F!",
        "lat": 23.4162,
        "lon": 25.6628,
        "country": "",
    },
    {
        "id": 92,
        "category": "nature",
        "question": "Where is the Great Barrier Reef located?",
        "options": ["Caribbean", "Indian Ocean", "Australia", "Mediterranean"],
        "answer": 2,
        "explanation": "It's the world's largest coral reef and can even be seen from space! So cool!",
        "lat": -18.2871,
        "lon": 147.6992,
        "country": "Australia",
    },
    {
        "id": 93,
        "category": "nature",
        "question": "Which river carries the most water in the world?",
        "options": ["Nile", "Mississippi", "Amazon", "Yangtze"],
        "answer": 2,
        "explanation": "The Amazon carries about 20% of ALL the river water that flows into the oceans!",
        "lat": -3.4653,
        "lon": -58.3800,
        "country": "Brazil",
    },
    {
        "id": 94,
        "category": "nature",
        "question": "Mount Kilimanjaro, Africa's tallest mountain, is in which country?",
        "options": ["Kenya", "Ethiopia", "Tanzania", "Uganda"],
        "answer": 2,
        "explanation": "Kilimanjaro has snow on top even though it's near the equator—how cool is that?",
        "lat": -3.0758,
        "lon": 37.3533,
        "country": "Tanzania",
    },
    {
        "id": 95,
        "category": "nature",
        "question": "The Grand Canyon was carved by which river?",
        "options": ["Rio Grande", "Colorado River", "Mississippi River", "Columbia River"],
        "answer": 1,
        "explanation": "The Colorado River has been carving the Grand Canyon for millions of years!",
        "lat": 36.0544,
        "lon": -112.1401,
        "country": "United States",
    },
    {
        "id": 96,
        "category": "nature",
        "question": "The Amazon rainforest is primarily in which country?",
        "options": ["Colombia", "Peru", "Brazil", "Venezuela"],
        "answer": 2,
        "explanation": "Brazil has about 60% of the Amazon—it's often called the 'lungs of the Earth'!",
        "lat": -3.4653,
        "lon": -58.3800,
        "country": "Brazil",
    },
    {
        "id": 97,
        "category": "nature",
        "question": "Mount Fuji is the highest peak in which country?",
        "options": ["China", "South Korea", "Japan", "Taiwan"],
        "answer": 2,
        "explanation": "Mount Fuji is a volcano that's considered sacred in Japan—it's super symmetrical and beautiful!",
        "lat": 35.3606,
        "lon": 138.7274,
        "country": "Japan",
    },
    {
        "id": 98,
        "category": "nature",
        "question": "Which ocean is the deepest?",
        "options": ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
        "answer": 2,
        "explanation": "The Pacific has the Mariana Trench—over 36,000 feet deep! Deeper than Mount Everest is tall!",
        "lat": 0.0,
        "lon": -160.0,
        "country": "",
    },
    {
        "id": 99,
        "category": "nature",
        "question": "On which continent would you find the most penguins?",
        "options": ["North America", "Europe", "Antarctica", "Asia"],
        "answer": 2,
        "explanation": "Millions of penguins live in Antarctica! They love the icy cold weather and swim in freezing water.",
        "lat": -75.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 100,
        "category": "nature",
        "question": "What is the biggest rainforest in the world?",
        "options": ["Congo Rainforest", "Amazon Rainforest", "Daintree Rainforest", "Borneo Rainforest"],
        "answer": 1,
        "explanation": "The Amazon Rainforest is so big it covers parts of 9 countries! It makes about 20% of Earth's oxygen!",
        "lat": -3.4653,
        "lon": -58.3800,
        "country": "Brazil",
    },
    {
        "id": 101,
        "category": "nature",
        "question": "Which river flows through Paris?",
        "options": ["Thames", "Rhine", "Seine", "Danube"],
        "answer": 2,
        "explanation": "The Seine River divides Paris into the Left Bank and Right Bank!",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
    },
    {
        "id": 102,
        "category": "nature",
        "question": "Which river flows through London?",
        "options": ["Seine", "Rhine", "Thames", "Danube"],
        "answer": 2,
        "explanation": "The Thames has over 200 bridges and has been London's main waterway for 2,000 years!",
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
    },
    {
        "id": 103,
        "category": "nature",
        "question": "What is the tallest waterfall in the world?",
        "options": ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"],
        "answer": 2,
        "explanation": "Angel Falls in Venezuela drops 3,212 feet—that's 15 times taller than Niagara!",
        "lat": 5.9702,
        "lon": -62.5362,
        "country": "Venezuela",
    },
    {
        "id": 104,
        "category": "nature",
        "question": "The Himalayas, home to Mount Everest, are in which continent?",
        "options": ["Europe", "Africa", "Asia", "South America"],
        "answer": 2,
        "explanation": "The Himalayas contain 9 of the 10 tallest mountains in the world!",
        "lat": 27.9881,
        "lon": 86.9250,
        "country": "Nepal",
    },
    {
        "id": 105,
        "category": "nature",
        "question": "Which is the smallest ocean?",
        "options": ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
        "answer": 3,
        "explanation": "The Arctic Ocean is the smallest and coldest—it's where polar bears live!",
        "lat": 90.0,
        "lon": 0.0,
        "country": "",
    },
    {
        "id": 106,
        "category": "nature",
        "question": "What is the biggest animal on Earth?",
        "options": ["African Elephant", "Giraffe", "Blue Whale", "Great White Shark"],
        "answer": 2,
        "explanation": "The Blue Whale can be 100 feet long — that's as long as three school buses! They live in the ocean.",
        "lat": 0.0,
        "lon": -150.0,
        "country": "",
    },
    {
        "id": 107,
        "category": "nature",
        "question": "The Niagara Falls are on the border of the USA and which other country?",
        "options": ["Mexico", "Canada", "Brazil", "Cuba"],
        "answer": 1,
        "explanation": "Over 3,000 tons of water flow over Niagara Falls every second — that's a LOT of water!",
        "lat": 43.0962,
        "lon": -79.0377,
        "country": "Canada",
    },
    {
        "id": 108,
        "category": "nature",
        "question": "Which country is shaped like a long, thin strip?",
        "options": ["Brazil", "Argentina", "Chile", "Peru"],
        "answer": 2,
        "explanation": "Chile is over 2,600 miles long but only 110 miles wide on average—like a long noodle!",
        "lat": -33.4489,
        "lon": -70.6693,
        "country": "Chile",
    },
    {
        "id": 109,
        "category": "nature",
        "question": "Which country has the most volcanoes?",
        "options": ["Japan", "Indonesia", "Italy", "United States"],
        "answer": 1,
        "explanation": "Indonesia has over 130 active volcanoes—it's part of the 'Ring of Fire'!",
        "lat": -6.2088,
        "lon": 106.8456,
        "country": "Indonesia",
    },
    {
        "id": 110,
        "category": "nature",
        "question": "Which ocean is between North America and Europe?",
        "options": ["Pacific Ocean", "Indian Ocean", "Arctic Ocean", "Atlantic Ocean"],
        "answer": 3,
        "explanation": "The Atlantic has been an important route for explorers and trade for centuries!",
        "lat": 50.0,
        "lon": -25.0,
        "country": "",
    },
    # ========== FLAGS (~20 questions) ==========
    {
        "id": 111,
        "category": "flags",
        "question": "Which country's flag has a big red maple leaf?",
        "options": ["United States", "Canada", "Australia", "New Zealand"],
        "answer": 1,
        "explanation": "The maple leaf has been a Canadian symbol since the 1700s—Canada has lots of maple trees!",
        "lat": 45.4215,
        "lon": -75.6972,
        "country": "Canada",
    },
    {
        "id": 112,
        "category": "flags",
        "question": "Which country's flag has a red circle on a white background, like the sun?",
        "options": ["China", "South Korea", "Japan", "Vietnam"],
        "answer": 2,
        "explanation": "Japan is called the Land of the Rising Sun—the red circle represents the sun!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 113,
        "category": "flags",
        "question": "The flag with stars and stripes belongs to which country?",
        "options": ["United Kingdom", "United States", "Malaysia", "Liberia"],
        "answer": 1,
        "explanation": "The 50 stars = 50 states, and the 13 stripes = the original 13 colonies!",
        "lat": 38.9072,
        "lon": -77.0369,
        "country": "United States",
    },
    {
        "id": 114,
        "category": "flags",
        "question": "Which country's flag has a Union Jack in the corner?",
        "options": ["Ireland", "Australia", "India", "South Africa"],
        "answer": 1,
        "explanation": "Australia has the Union Jack because it was once part of the British Empire!",
        "lat": -35.2809,
        "lon": 149.1300,
        "country": "Australia",
    },
    {
        "id": 115,
        "category": "flags",
        "question": "Which country's flag has horizontal stripes of orange, white, and green?",
        "options": ["Nigeria", "India", "Ireland", "Italy"],
        "answer": 1,
        "explanation": "India's flag has a blue wheel (Ashoka Chakra) in the center with 24 spokes!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 116,
        "category": "flags",
        "question": "Which country's flag has blue, white, and red vertical stripes?",
        "options": ["Italy", "France", "Belgium", "Ireland"],
        "answer": 1,
        "explanation": "France's flag is called the Tricolore—it's one of the most famous flags in the world!",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
    },
    {
        "id": 117,
        "category": "flags",
        "question": "Which country's flag is red and white with a maple leaf?",
        "options": ["Canada", "Peru", "Austria", "Poland"],
        "answer": 0,
        "explanation": "Canada's flag was adopted in 1965—the maple leaf is simple and easy to recognize!",
        "lat": 45.4215,
        "lon": -75.6972,
        "country": "Canada",
    },
    {
        "id": 118,
        "category": "flags",
        "question": "Which country's flag has a white cross on a red background?",
        "options": ["Austria", "Denmark", "Switzerland", "Sweden"],
        "answer": 2,
        "explanation": "Switzerland's flag is actually square—not rectangle like most flags!",
        "lat": 46.9480,
        "lon": 7.4474,
        "country": "Switzerland",
    },
    {
        "id": 119,
        "category": "flags",
        "question": "Which country's flag has five stars in a pattern?",
        "options": ["United States", "China", "Brazil", "Australia"],
        "answer": 1,
        "explanation": "China's flag has one large star and four smaller ones on a red background!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 120,
        "category": "flags",
        "question": "Which country's flag has green, yellow, and blue with a circle?",
        "options": ["Brazil", "Argentina", "Colombia", "Chile"],
        "answer": 0,
        "explanation": "Brazil's flag shows the night sky over Rio as it appeared when Brazil became a republic!",
        "lat": -15.7975,
        "lon": -47.8919,
        "country": "Brazil",
    },
    {
        "id": 121,
        "category": "flags",
        "question": "Which country's flag has an eagle?",
        "options": ["Mexico", "United States", "Germany", "Poland"],
        "answer": 0,
        "explanation": "Mexico's flag shows an eagle eating a snake on a cactus—from an ancient Aztec legend!",
        "lat": 19.4326,
        "lon": -99.1332,
        "country": "Mexico",
    },
    {
        "id": 122,
        "category": "flags",
        "question": "Which country's flag has a crescent and star?",
        "options": ["India", "Turkey", "Egypt", "Iran"],
        "answer": 1,
        "explanation": "Turkey's flag has a white crescent and star on red—it's easy to spot!",
        "lat": 39.9334,
        "lon": 32.8597,
        "country": "Turkey",
    },
    {
        "id": 123,
        "category": "flags",
        "question": "Which country's flag has a Southern Cross constellation?",
        "options": ["Brazil", "Australia", "South Africa", "New Zealand"],
        "answer": 1,
        "explanation": "Australia's flag has the Southern Cross—a constellation you can see from the Southern Hemisphere!",
        "lat": -33.8688,
        "lon": 151.2093,
        "country": "Australia",
    },
    {
        "id": 124,
        "category": "flags",
        "question": "Which country's flag has a red circle (sun) on white?",
        "options": ["China", "South Korea", "Japan", "Taiwan"],
        "answer": 2,
        "explanation": "Japan's flag is simple and beautiful—the sun is a big part of Japanese culture!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 125,
        "category": "flags",
        "question": "Which country's flag has three horizontal stripes of black, red, and gold?",
        "options": ["Belgium", "Germany", "Italy", "Ireland"],
        "answer": 1,
        "explanation": "Germany's flag has been used since the 1800s—black, red, and gold!",
        "lat": 52.5200,
        "lon": 13.4050,
        "country": "Germany",
    },
    {
        "id": 126,
        "category": "flags",
        "question": "Which country's flag has green, white, and red vertical stripes?",
        "options": ["France", "Italy", "Ireland", "Belgium"],
        "answer": 1,
        "explanation": "Italy's flag is green, white, and red—the colors of the Italian flag!",
        "lat": 41.9028,
        "lon": 12.4964,
        "country": "Italy",
    },
    {
        "id": 127,
        "category": "flags",
        "question": "Which country's flag has a red background with a yellow star?",
        "options": ["China", "Vietnam", "North Korea", "Mongolia"],
        "answer": 1,
        "explanation": "Vietnam's flag has one yellow star on red—simple and bold!",
        "lat": 21.0285,
        "lon": 105.8542,
        "country": "Vietnam",
    },
    {
        "id": 128,
        "category": "flags",
        "question": "Which country's flag has the Union Jack (crosses of St. George, St. Andrew, St. Patrick)?",
        "options": ["Ireland", "Australia", "United Kingdom", "United States"],
        "answer": 2,
        "explanation": "The Union Jack combines the flags of England, Scotland, and Ireland!",
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
    },
    {
        "id": 129,
        "category": "flags",
        "question": "Which country's flag has a green background with a red circle?",
        "options": ["Bangladesh", "Japan", "Pakistan", "India"],
        "answer": 0,
        "explanation": "Bangladesh's flag has a red circle on green—the circle represents the sun rising over the land!",
        "lat": 23.8103,
        "lon": 90.4125,
        "country": "Bangladesh",
    },
    {
        "id": 130,
        "category": "flags",
        "question": "Which country's flag has red on top and white on bottom?",
        "options": ["Poland", "Indonesia", "Canada", "China"],
        "answer": 1,
        "explanation": "Indonesia's flag is simple—red on top, white on bottom. (Poland has it the other way around!)",
        "lat": -6.2088,
        "lon": 106.8456,
        "country": "Indonesia",
    },
    # ========== CULTURE (~25 questions) ==========
    {
        "id": 131,
        "category": "culture",
        "question": "Which country invented pizza?",
        "options": ["France", "Greece", "Italy", "Spain"],
        "answer": 2,
        "explanation": "Pizza was invented in Naples, Italy! The Margherita pizza was even named after a queen!",
        "lat": 41.9028,
        "lon": 12.4964,
        "country": "Italy",
    },
    {
        "id": 132,
        "category": "culture",
        "question": "Where do giant pandas live in the wild?",
        "options": ["Japan", "India", "China", "Thailand"],
        "answer": 2,
        "explanation": "Giant pandas only live in the wild in China! They love bamboo—they eat it all day!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 133,
        "category": "culture",
        "question": "Which country is famous for chocolate and cheese?",
        "options": ["Austria", "Belgium", "Switzerland", "Germany"],
        "answer": 2,
        "explanation": "Switzerland makes some of the world's yummiest chocolate and finest cheese!",
        "lat": 46.9480,
        "lon": 7.4474,
        "country": "Switzerland",
    },
    {
        "id": 134,
        "category": "culture",
        "question": "In which country was soccer (football) first played with official rules?",
        "options": ["Brazil", "Spain", "England", "Italy"],
        "answer": 2,
        "explanation": "England created the first official soccer rules in 1863—now it's the world's most popular sport!",
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
    },
    {
        "id": 135,
        "category": "culture",
        "question": "Tacos and burritos are traditional food from which country?",
        "options": ["Spain", "Brazil", "Mexico", "Argentina"],
        "answer": 2,
        "explanation": "Mexico gave the world tacos, burritos, guacamole, and so much delicious food!",
        "lat": 19.4326,
        "lon": -99.1332,
        "country": "Mexico",
    },
    {
        "id": 136,
        "category": "culture",
        "question": "Which country is famous for anime and manga?",
        "options": ["China", "South Korea", "Japan", "Taiwan"],
        "answer": 2,
        "explanation": "Japan is the home of anime and manga—from Pokémon to Studio Ghibli!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 137,
        "category": "culture",
        "question": "Where would you find kangaroos hopping around?",
        "options": ["New Zealand", "Australia", "South Africa", "Indonesia"],
        "answer": 1,
        "explanation": "Australia has unique wildlife—kangaroos, koalas, and wombats live nowhere else!",
        "lat": -33.8688,
        "lon": 151.2093,
        "country": "Australia",
    },
    {
        "id": 138,
        "category": "culture",
        "question": "Sushi is a traditional dish from which country?",
        "options": ["China", "Korea", "Japan", "Thailand"],
        "answer": 2,
        "explanation": "Sushi originated in Japan over 1,000 years ago—it's now popular all over the world!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 139,
        "category": "culture",
        "question": "Which country is famous for the festival of Carnival?",
        "options": ["Argentina", "Portugal", "Brazil", "Spain"],
        "answer": 2,
        "explanation": "Rio's Carnival is the biggest party in the world—millions dance in the streets!",
        "lat": -22.9068,
        "lon": -43.1729,
        "country": "Brazil",
    },
    {
        "id": 140,
        "category": "culture",
        "question": "Which country celebrates Diwali as a major festival?",
        "options": ["Thailand", "Indonesia", "India", "Sri Lanka"],
        "answer": 2,
        "explanation": "Diwali is the Festival of Lights—people light lamps to celebrate light over darkness!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 141,
        "category": "culture",
        "question": "Which country celebrates the Day of the Dead (Día de los Muertos)?",
        "options": ["Spain", "Brazil", "Mexico", "Argentina"],
        "answer": 2,
        "explanation": "This colorful festival honors loved ones with altars, marigolds, and sugar skulls!",
        "lat": 19.4326,
        "lon": -99.1332,
        "country": "Mexico",
    },
    {
        "id": 142,
        "category": "culture",
        "question": "Which country is the birthplace of the Olympic Games?",
        "options": ["Rome", "Egypt", "Greece", "Turkey"],
        "answer": 2,
        "explanation": "The ancient Olympics started in Olympia, Greece, over 2,700 years ago!",
        "lat": 37.9838,
        "lon": 23.7275,
        "country": "Greece",
    },
    {
        "id": 143,
        "category": "culture",
        "question": "Which country is famous for kangaroos and koalas?",
        "options": ["New Zealand", "Australia", "South Africa", "Indonesia"],
        "answer": 1,
        "explanation": "Over 80% of Australia's animals are found nowhere else on Earth!",
        "lat": -33.8688,
        "lon": 151.2093,
        "country": "Australia",
    },
    {
        "id": 144,
        "category": "culture",
        "question": "Which country is the home of reggae music?",
        "options": ["Cuba", "Trinidad", "Jamaica", "Bahamas"],
        "answer": 2,
        "explanation": "Bob Marley made reggae famous worldwide—it started in Jamaica in the 1960s!",
        "lat": 18.1096,
        "lon": -77.2975,
        "country": "Jamaica",
    },
    {
        "id": 145,
        "category": "culture",
        "question": "Which country is famous for bagpipes?",
        "options": ["Ireland", "Wales", "Scotland", "England"],
        "answer": 2,
        "explanation": "Scotland's bagpipes are iconic—they were originally used to rally troops in battle!",
        "lat": 55.9533,
        "lon": -3.1883,
        "country": "United Kingdom",
    },
    {
        "id": 146,
        "category": "culture",
        "question": "Which country invented the tango dance?",
        "options": ["Spain", "Brazil", "Argentina", "Chile"],
        "answer": 2,
        "explanation": "The tango was born in the streets of Buenos Aires in the late 1800s!",
        "lat": -34.6037,
        "lon": -58.3816,
        "country": "Argentina",
    },
    {
        "id": 147,
        "category": "culture",
        "question": "Which country is famous for tulips and windmills?",
        "options": ["Belgium", "Germany", "Netherlands", "Denmark"],
        "answer": 2,
        "explanation": "The Netherlands exports billions of tulips each year and has over 1,000 windmills!",
        "lat": 52.3676,
        "lon": 4.9041,
        "country": "Netherlands",
    },
    {
        "id": 148,
        "category": "culture",
        "question": "Which country is the origin of the kimono?",
        "options": ["China", "Korea", "Japan", "Vietnam"],
        "answer": 2,
        "explanation": "The kimono has been worn in Japan for over 1,000 years—it means 'thing to wear'!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 149,
        "category": "culture",
        "question": "Which country is famous for the haka dance?",
        "options": ["Australia", "Fiji", "New Zealand", "Samoa"],
        "answer": 2,
        "explanation": "The All Blacks rugby team performs the haka before every match—it's a traditional Māori war dance!",
        "lat": -41.2866,
        "lon": 174.7756,
        "country": "New Zealand",
    },
    {
        "id": 150,
        "category": "culture",
        "question": "Which country invented ice cream?",
        "options": ["France", "Italy", "China", "United States"],
        "answer": 2,
        "explanation": "Fun fact: Ice cream was first made in China over 4,000 years ago! Marco Polo brought the idea to Europe.",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 151,
        "category": "culture",
        "question": "In which country is the famous FAO Schwarz toy store (with the giant floor piano)?",
        "options": ["Japan", "United States", "Germany", "United Kingdom"],
        "answer": 1,
        "explanation": "FAO Schwarz is in New York City! You might have seen the giant floor piano in the movie Big!",
        "lat": 40.7580,
        "lon": -73.9855,
        "country": "United States",
    },
    {
        "id": 152,
        "category": "culture",
        "question": "Which country is famous for martial arts like karate and judo?",
        "options": ["China", "South Korea", "Japan", "Thailand"],
        "answer": 2,
        "explanation": "Japan gave the world karate, judo, and aikido—martial arts that focus on discipline!",
        "lat": 35.6762,
        "lon": 139.6503,
        "country": "Japan",
    },
    {
        "id": 153,
        "category": "culture",
        "question": "Which country celebrates Oktoberfest?",
        "options": ["Austria", "Switzerland", "Germany", "Netherlands"],
        "answer": 2,
        "explanation": "Oktoberfest in Munich is the world's largest beer festival—and it actually starts in September!",
        "lat": 48.1351,
        "lon": 11.5820,
        "country": "Germany",
    },
    {
        "id": 154,
        "category": "culture",
        "question": "Which country is famous for paella and flamenco dancing?",
        "options": ["Mexico", "Portugal", "Spain", "France"],
        "answer": 2,
        "explanation": "Spain has amazing food like paella (a rice dish) and flamenco is a passionate dance with guitars and clapping!",
        "lat": 40.4168,
        "lon": -3.7038,
        "country": "Spain",
    },
    {
        "id": 155,
        "category": "culture",
        "question": "Which country is famous for the Great Wall?",
        "options": ["Japan", "Korea", "China", "Mongolia"],
        "answer": 2,
        "explanation": "The Great Wall of China is one of the most amazing things humans have ever built!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    # ========== ADDITIONAL CONTINENTS & OCEANS ==========
    {
        "id": 156,
        "category": "continents",
        "question": "Which continent is Mexico in?",
        "options": ["South America", "North America", "Europe", "Asia"],
        "answer": 1,
        "explanation": "Mexico is in North America, right below the United States!",
        "lat": 19.4326,
        "lon": -99.1332,
        "country": "Mexico",
    },
    {
        "id": 157,
        "category": "continents",
        "question": "Which continent has the most countries?",
        "options": ["Asia", "Africa", "Europe", "South America"],
        "answer": 1,
        "explanation": "Africa has 54 countries — more than any other continent!",
        "lat": 1.0,
        "lon": 20.0,
        "country": "",
    },
    {
        "id": 158,
        "category": "continents",
        "question": "Which continent is New Zealand in?",
        "options": ["Asia", "Australia", "Africa", "Europe"],
        "answer": 1,
        "explanation": "New Zealand is near Australia in the region called Oceania — it's famous for stunning mountains!",
        "lat": -41.2866,
        "lon": 174.7756,
        "country": "New Zealand",
    },
    {
        "id": 159,
        "category": "continents",
        "question": "Which continent is Argentina in?",
        "options": ["North America", "Europe", "South America", "Africa"],
        "answer": 2,
        "explanation": "Argentina is in South America — it's famous for soccer, steak, and the tango!",
        "lat": -34.6037,
        "lon": -58.3816,
        "country": "Argentina",
    },
    {
        "id": 160,
        "category": "continents",
        "question": "The Mediterranean Sea is between which two continents?",
        "options": ["Asia & Australia", "Europe & Africa", "North & South America", "Asia & Africa"],
        "answer": 1,
        "explanation": "The Mediterranean sits between Europe and Africa — ancient Romans called it 'our sea'!",
        "lat": 35.0,
        "lon": 18.0,
        "country": "",
    },
    {
        "id": 161,
        "category": "continents",
        "question": "Which continent is Turkey mostly in?",
        "options": ["Europe", "Africa", "Asia", "South America"],
        "answer": 2,
        "explanation": "Turkey is unique — a small part is in Europe but most of it is in Asia!",
        "lat": 39.9334,
        "lon": 32.8597,
        "country": "Turkey",
    },
    {
        "id": 162,
        "category": "continents",
        "question": "Which ocean borders the west coast of the United States?",
        "options": ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"],
        "answer": 1,
        "explanation": "California, Oregon, and Washington all have beaches on the Pacific Ocean!",
        "lat": 37.7749,
        "lon": -122.4194,
        "country": "United States",
    },
    # ========== ADDITIONAL CAPITALS ==========
    {
        "id": 163,
        "category": "capitals",
        "question": "What is the capital of Turkey?",
        "options": ["Istanbul", "Ankara", "Izmir", "Antalya"],
        "answer": 1,
        "explanation": "Many people think Istanbul is the capital, but it's actually Ankara — Istanbul is the biggest city though!",
        "lat": 39.9334,
        "lon": 32.8597,
        "country": "Turkey",
    },
    {
        "id": 164,
        "category": "capitals",
        "question": "What is the capital of New Zealand?",
        "options": ["Auckland", "Christchurch", "Wellington", "Queenstown"],
        "answer": 2,
        "explanation": "Wellington is the world's southernmost national capital — it's known for being super windy!",
        "lat": -41.2866,
        "lon": 174.7756,
        "country": "New Zealand",
    },
    {
        "id": 165,
        "category": "capitals",
        "question": "What is the capital of Vietnam?",
        "options": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"],
        "answer": 1,
        "explanation": "Hanoi is over 1,000 years old and is famous for street food and beautiful lakes!",
        "lat": 21.0285,
        "lon": 105.8542,
        "country": "Vietnam",
    },
    {
        "id": 166,
        "category": "capitals",
        "question": "What is the capital of Peru?",
        "options": ["Cusco", "Lima", "Arequipa", "Machu Picchu"],
        "answer": 1,
        "explanation": "Lima is on the coast and is famous for amazing food — Peruvian cuisine is world-class!",
        "lat": -12.0464,
        "lon": -77.0428,
        "country": "Peru",
    },
    {
        "id": 167,
        "category": "capitals",
        "question": "What is the capital of Ireland?",
        "options": ["Cork", "Galway", "Dublin", "Belfast"],
        "answer": 2,
        "explanation": "Dublin is over 1,000 years old — it was founded by Vikings!",
        "lat": 53.3498,
        "lon": -6.2603,
        "country": "Ireland",
    },
    {
        "id": 168,
        "category": "capitals",
        "question": "What is the capital of Nigeria?",
        "options": ["Lagos", "Abuja", "Kano", "Ibadan"],
        "answer": 1,
        "explanation": "Lagos is the biggest city in Nigeria, but Abuja has been the capital since 1991!",
        "lat": 9.0579,
        "lon": 7.4951,
        "country": "Nigeria",
    },
    {
        "id": 169,
        "category": "capitals",
        "question": "What is the capital of Sweden?",
        "options": ["Gothenburg", "Stockholm", "Malmö", "Uppsala"],
        "answer": 1,
        "explanation": "Stockholm is built on 14 islands connected by bridges — it's called the Venice of the North!",
        "lat": 59.3293,
        "lon": 18.0686,
        "country": "Sweden",
    },
    {
        "id": 170,
        "category": "capitals",
        "question": "What is the capital of Colombia?",
        "options": ["Medellín", "Bogotá", "Cali", "Cartagena"],
        "answer": 1,
        "explanation": "Bogotá is high up in the mountains at 8,600 feet — you need to catch your breath there!",
        "lat": 4.7110,
        "lon": -74.0721,
        "country": "Colombia",
    },
    {
        "id": 171,
        "category": "capitals",
        "question": "What is the capital of Norway?",
        "options": ["Bergen", "Oslo", "Stavanger", "Tromsø"],
        "answer": 1,
        "explanation": "Oslo is a beautiful city surrounded by forests and the Oslo Fjord!",
        "lat": 59.9139,
        "lon": 10.7522,
        "country": "Norway",
    },
    {
        "id": 172,
        "category": "capitals",
        "question": "What is the capital of Pakistan?",
        "options": ["Karachi", "Lahore", "Islamabad", "Peshawar"],
        "answer": 2,
        "explanation": "Islamabad is a planned modern city — it was built in the 1960s to be the new capital!",
        "lat": 33.6844,
        "lon": 73.0479,
        "country": "Pakistan",
    },
    {
        "id": 173,
        "category": "capitals",
        "question": "What is the capital of South Africa?",
        "options": ["Johannesburg", "Cape Town", "Pretoria", "Durban"],
        "answer": 2,
        "explanation": "South Africa actually has three capitals! Pretoria is the administrative capital.",
        "lat": -25.7479,
        "lon": 28.2293,
        "country": "South Africa",
    },
    # ========== ADDITIONAL LANDMARKS ==========
    {
        "id": 174,
        "category": "landmarks",
        "question": "The Sagrada Familia church is in which city?",
        "options": ["Madrid", "Lisbon", "Barcelona", "Rome"],
        "answer": 2,
        "explanation": "It was designed by Gaudí and started in 1882 — it's STILL being built over 140 years later!",
        "lat": 41.4036,
        "lon": 2.1744,
        "country": "Spain",
    },
    {
        "id": 175,
        "category": "landmarks",
        "question": "The Angkor Wat temple complex is in which country?",
        "options": ["Thailand", "Vietnam", "Cambodia", "Indonesia"],
        "answer": 2,
        "explanation": "Angkor Wat is the largest religious monument in the world — it's on Cambodia's flag!",
        "lat": 13.4125,
        "lon": 103.8670,
        "country": "Cambodia",
    },
    {
        "id": 176,
        "category": "landmarks",
        "question": "The Louvre Museum is in which city?",
        "options": ["London", "Paris", "Berlin", "Madrid"],
        "answer": 1,
        "explanation": "The Louvre is the world's most visited museum — it has the famous Mona Lisa painting!",
        "lat": 48.8606,
        "lon": 2.3376,
        "country": "France",
    },
    {
        "id": 177,
        "category": "landmarks",
        "question": "The Panama Canal connects which two oceans?",
        "options": ["Atlantic & Indian", "Pacific & Indian", "Atlantic & Pacific", "Arctic & Atlantic"],
        "answer": 2,
        "explanation": "The Panama Canal saves ships a 12,000-mile trip around South America!",
        "lat": 9.0801,
        "lon": -79.6805,
        "country": "Panama",
    },
    {
        "id": 178,
        "category": "landmarks",
        "question": "The Little Mermaid statue is a famous landmark in which city?",
        "options": ["Oslo", "Stockholm", "Copenhagen", "Helsinki"],
        "answer": 2,
        "explanation": "The statue is based on Hans Christian Andersen's fairy tale — Denmark is the land of fairy tales!",
        "lat": 55.6929,
        "lon": 12.5996,
        "country": "Denmark",
    },
    {
        "id": 179,
        "category": "landmarks",
        "question": "The Terracotta Army was discovered in which country?",
        "options": ["Japan", "India", "China", "Vietnam"],
        "answer": 2,
        "explanation": "Over 8,000 life-size clay soldiers were buried with China's first emperor over 2,200 years ago!",
        "lat": 34.3847,
        "lon": 109.2785,
        "country": "China",
    },
    {
        "id": 180,
        "category": "landmarks",
        "question": "The Gateway of India is in which city?",
        "options": ["New Delhi", "Mumbai", "Kolkata", "Chennai"],
        "answer": 1,
        "explanation": "The Gateway of India was built in 1924 and overlooks the Arabian Sea in Mumbai!",
        "lat": 18.9220,
        "lon": 72.8347,
        "country": "India",
    },
    {
        "id": 181,
        "category": "landmarks",
        "question": "The Statue of Christ the King overlooks which city?",
        "options": ["Madrid", "Lisbon", "Rio de Janeiro", "Buenos Aires"],
        "answer": 1,
        "explanation": "Lisbon's Christ the King was inspired by the Christ the Redeemer statue in Rio de Janeiro!",
        "lat": 38.6790,
        "lon": -9.1714,
        "country": "Portugal",
    },
    {
        "id": 182,
        "category": "landmarks",
        "question": "The Colosseum could hold about how many spectators?",
        "options": ["10,000", "25,000", "50,000", "100,000"],
        "answer": 2,
        "explanation": "50,000 Romans would watch gladiator fights and wild animal shows — it even had a retractable roof!",
        "lat": 41.8902,
        "lon": 12.4922,
        "country": "Italy",
    },
    {
        "id": 183,
        "category": "landmarks",
        "question": "The Hagia Sophia is a famous landmark in which city?",
        "options": ["Athens", "Istanbul", "Cairo", "Baghdad"],
        "answer": 1,
        "explanation": "The Hagia Sophia was built in 537 AD — it was a church, then a mosque, then a museum, and now a mosque again!",
        "lat": 41.0086,
        "lon": 28.9802,
        "country": "Turkey",
    },
    # ========== ADDITIONAL NATURE ==========
    {
        "id": 184,
        "category": "nature",
        "question": "The Ganges River flows through which country?",
        "options": ["China", "Pakistan", "India", "Thailand"],
        "answer": 2,
        "explanation": "The Ganges is sacred to Hindus — over 400 million people depend on it for water!",
        "lat": 25.3176,
        "lon": 82.9739,
        "country": "India",
    },
    {
        "id": 185,
        "category": "nature",
        "question": "Which country has the most islands in the world?",
        "options": ["Philippines", "Indonesia", "Sweden", "Japan"],
        "answer": 2,
        "explanation": "Sweden has over 267,000 islands! Most are tiny and uninhabited.",
        "lat": 59.3293,
        "lon": 18.0686,
        "country": "Sweden",
    },
    {
        "id": 186,
        "category": "nature",
        "question": "The Dead Sea, one of the saltiest lakes, borders which two countries?",
        "options": ["Egypt & Libya", "Israel & Jordan", "Turkey & Greece", "Iran & Iraq"],
        "answer": 1,
        "explanation": "The Dead Sea is so salty you float without even trying — nothing can live in it!",
        "lat": 31.5,
        "lon": 35.5,
        "country": "Israel",
    },
    {
        "id": 187,
        "category": "nature",
        "question": "The Yangtze is the longest river in which continent?",
        "options": ["Europe", "Africa", "Asia", "South America"],
        "answer": 2,
        "explanation": "The Yangtze flows 3,900 miles through China — it's the third-longest river in the world!",
        "lat": 30.5728,
        "lon": 114.3162,
        "country": "China",
    },
    {
        "id": 188,
        "category": "nature",
        "question": "Which country is home to the most species of animals?",
        "options": ["India", "Australia", "Brazil", "China"],
        "answer": 2,
        "explanation": "Brazil has more species than any other country — the Amazon rainforest is full of amazing creatures!",
        "lat": -3.4653,
        "lon": -58.3800,
        "country": "Brazil",
    },
    {
        "id": 189,
        "category": "nature",
        "question": "Victoria Falls is on the border of which two African countries?",
        "options": ["Kenya & Tanzania", "Zambia & Zimbabwe", "South Africa & Mozambique", "Uganda & Congo"],
        "answer": 1,
        "explanation": "Victoria Falls is called 'The Smoke That Thunders' — you can hear it from 25 miles away!",
        "lat": -17.9243,
        "lon": 25.8572,
        "country": "",
    },
    {
        "id": 190,
        "category": "nature",
        "question": "Which mountain range runs along the west coast of South America?",
        "options": ["Himalayas", "Alps", "Andes", "Rocky Mountains"],
        "answer": 2,
        "explanation": "The Andes are the longest mountain range in the world — over 4,300 miles long!",
        "lat": -13.1631,
        "lon": -72.5450,
        "country": "Peru",
    },
    {
        "id": 191,
        "category": "nature",
        "question": "Which sea is the largest enclosed body of water?",
        "options": ["Black Sea", "Caspian Sea", "Red Sea", "Mediterranean Sea"],
        "answer": 1,
        "explanation": "The Caspian Sea is actually a lake — it's called a sea because of its size and saltiness!",
        "lat": 41.0,
        "lon": 51.0,
        "country": "",
    },
    {
        "id": 192,
        "category": "nature",
        "question": "The Alps mountain range is mostly in which continent?",
        "options": ["Asia", "Africa", "Europe", "North America"],
        "answer": 2,
        "explanation": "The Alps stretch across 8 European countries including Switzerland, France, Austria, and Italy!",
        "lat": 46.8182,
        "lon": 8.2275,
        "country": "Switzerland",
    },
    {
        "id": 193,
        "category": "nature",
        "question": "Which is the longest river in the United States?",
        "options": ["Colorado River", "Ohio River", "Missouri River", "Mississippi River"],
        "answer": 2,
        "explanation": "The Missouri River is 2,341 miles long — slightly longer than the Mississippi!",
        "lat": 38.8,
        "lon": -90.2,
        "country": "United States",
    },
    {
        "id": 194,
        "category": "nature",
        "question": "The Galápagos Islands, famous for unique wildlife, belong to which country?",
        "options": ["Brazil", "Ecuador", "Colombia", "Peru"],
        "answer": 1,
        "explanation": "Charles Darwin visited the Galápagos in 1835 and developed his theory of evolution there!",
        "lat": -0.9538,
        "lon": -90.9656,
        "country": "Ecuador",
    },
    # ========== ADDITIONAL FLAGS ==========
    {
        "id": 195,
        "category": "flags",
        "question": "Which country's flag has a dragon on it?",
        "options": ["China", "Japan", "Wales", "Mongolia"],
        "answer": 2,
        "explanation": "Wales has a red dragon on its flag — the dragon is a symbol of power and bravery!",
        "lat": 51.4816,
        "lon": -3.1791,
        "country": "United Kingdom",
    },
    {
        "id": 196,
        "category": "flags",
        "question": "Which country's flag has a leaf and a cedar tree?",
        "options": ["Lebanon", "Iran", "Iraq", "Syria"],
        "answer": 0,
        "explanation": "Lebanon's flag has a cedar tree in the center — cedars of Lebanon have been famous for thousands of years!",
        "lat": 33.8938,
        "lon": 35.5018,
        "country": "Lebanon",
    },
    {
        "id": 197,
        "category": "flags",
        "question": "Which country's flag has a blue cross on a white background?",
        "options": ["Sweden", "Finland", "Norway", "Denmark"],
        "answer": 1,
        "explanation": "Finland's flag represents the blue sky and white snow of their beautiful country!",
        "lat": 60.1699,
        "lon": 24.9384,
        "country": "Finland",
    },
    {
        "id": 198,
        "category": "flags",
        "question": "Which is the only country with a non-rectangular flag?",
        "options": ["Bhutan", "Nepal", "Sri Lanka", "Myanmar"],
        "answer": 1,
        "explanation": "Nepal's flag is two stacked triangles — it's the only national flag that isn't rectangular!",
        "lat": 27.7172,
        "lon": 85.3240,
        "country": "Nepal",
    },
    {
        "id": 199,
        "category": "flags",
        "question": "Which country's flag has green and white with a crescent and star?",
        "options": ["Turkey", "Pakistan", "Iran", "Saudi Arabia"],
        "answer": 1,
        "explanation": "Pakistan's flag has a white stripe for minorities and green for the Muslim majority!",
        "lat": 33.6844,
        "lon": 73.0479,
        "country": "Pakistan",
    },
    {
        "id": 200,
        "category": "flags",
        "question": "Which country's flag has a yellow cross on a blue background?",
        "options": ["Finland", "Norway", "Sweden", "Denmark"],
        "answer": 2,
        "explanation": "Sweden's blue and yellow flag has been used since the 1500s!",
        "lat": 59.3293,
        "lon": 18.0686,
        "country": "Sweden",
    },
    {
        "id": 201,
        "category": "flags",
        "question": "Which country's flag has red with a white cross that extends to the edges?",
        "options": ["Switzerland", "Denmark", "England", "Austria"],
        "answer": 1,
        "explanation": "Denmark's flag is the oldest continuously used national flag — over 800 years old!",
        "lat": 55.6761,
        "lon": 12.5683,
        "country": "Denmark",
    },
    {
        "id": 202,
        "category": "flags",
        "question": "Which country's flag has a yin-yang symbol?",
        "options": ["Japan", "China", "South Korea", "Taiwan"],
        "answer": 2,
        "explanation": "South Korea's flag has a red and blue yin-yang circle representing balance and harmony!",
        "lat": 37.5665,
        "lon": 126.9780,
        "country": "South Korea",
    },
    # ========== ADDITIONAL CULTURE ==========
    {
        "id": 203,
        "category": "culture",
        "question": "Which country is famous for the Sphinx and pyramids?",
        "options": ["Iraq", "Jordan", "Egypt", "Turkey"],
        "answer": 2,
        "explanation": "Ancient Egypt was one of the greatest civilizations — they built the pyramids 4,500 years ago!",
        "lat": 29.9792,
        "lon": 31.1342,
        "country": "Egypt",
    },
    {
        "id": 204,
        "category": "culture",
        "question": "Which country invented the sport of cricket?",
        "options": ["Australia", "India", "England", "South Africa"],
        "answer": 2,
        "explanation": "Cricket was invented in England in the 1500s — now it's hugely popular in India, Australia, and many countries!",
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
    },
    {
        "id": 205,
        "category": "culture",
        "question": "Pad Thai is a famous dish from which country?",
        "options": ["China", "Vietnam", "Thailand", "Indonesia"],
        "answer": 2,
        "explanation": "Pad Thai is a stir-fried noodle dish and one of Thailand's most popular street foods!",
        "lat": 13.7563,
        "lon": 100.5018,
        "country": "Thailand",
    },
    {
        "id": 206,
        "category": "culture",
        "question": "Which country is famous for the Maasai warriors?",
        "options": ["South Africa", "Nigeria", "Kenya", "Egypt"],
        "answer": 2,
        "explanation": "The Maasai are known for their tall jumping dance and their bright red clothing!",
        "lat": -1.2921,
        "lon": 36.8219,
        "country": "Kenya",
    },
    {
        "id": 207,
        "category": "culture",
        "question": "Which country is famous for K-pop music?",
        "options": ["Japan", "China", "South Korea", "Taiwan"],
        "answer": 2,
        "explanation": "K-pop bands like BTS and BLACKPINK are from South Korea and have fans all over the world!",
        "lat": 37.5665,
        "lon": 126.9780,
        "country": "South Korea",
    },
    {
        "id": 208,
        "category": "culture",
        "question": "Croissants are a famous pastry from which country?",
        "options": ["Italy", "France", "Belgium", "Switzerland"],
        "answer": 1,
        "explanation": "The flaky, buttery croissant is a breakfast staple in France — best with jam and coffee!",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
    },
    {
        "id": 209,
        "category": "culture",
        "question": "Which country celebrates Chinese New Year with dragon dances?",
        "options": ["Japan", "China", "Thailand", "India"],
        "answer": 1,
        "explanation": "Chinese New Year is the biggest holiday in China — over a billion people celebrate with fireworks and red lanterns!",
        "lat": 39.9042,
        "lon": 116.4074,
        "country": "China",
    },
    {
        "id": 210,
        "category": "culture",
        "question": "Which country is the world's largest producer of coffee?",
        "options": ["Colombia", "Ethiopia", "Brazil", "Vietnam"],
        "answer": 2,
        "explanation": "Brazil produces about one-third of all the world's coffee — that's a LOT of coffee beans!",
        "lat": -15.7975,
        "lon": -47.8919,
        "country": "Brazil",
    },
    {
        "id": 211,
        "category": "culture",
        "question": "Which country is famous for the Northern Lights (Aurora Borealis)?",
        "options": ["Spain", "Norway", "Italy", "France"],
        "answer": 1,
        "explanation": "Norway's far north is one of the best places to see the magical dancing lights in the sky!",
        "lat": 69.6496,
        "lon": 18.9560,
        "country": "Norway",
    },
    {
        "id": 212,
        "category": "culture",
        "question": "Which country is famous for maple syrup?",
        "options": ["United States", "Sweden", "Canada", "Finland"],
        "answer": 2,
        "explanation": "Canada produces about 71% of the world's maple syrup — Quebec alone makes most of it!",
        "lat": 45.4215,
        "lon": -75.6972,
        "country": "Canada",
    },
    {
        "id": 213,
        "category": "culture",
        "question": "Which country is the birthplace of basketball?",
        "options": ["United States", "United Kingdom", "Canada", "France"],
        "answer": 0,
        "explanation": "Basketball was invented in 1891 by James Naismith in Springfield, Massachusetts!",
        "lat": 42.1015,
        "lon": -72.5898,
        "country": "United States",
    },
    {
        "id": 214,
        "category": "culture",
        "question": "Samosas are a popular snack from which country?",
        "options": ["China", "Thailand", "India", "Japan"],
        "answer": 2,
        "explanation": "Samosas are crispy fried pastries filled with spiced potatoes and peas — delicious!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 215,
        "category": "culture",
        "question": "Which country is famous for creating LEGO toys?",
        "options": ["Sweden", "Germany", "Denmark", "Netherlands"],
        "answer": 2,
        "explanation": "LEGO was invented in Denmark in 1932 — the name comes from Danish words meaning 'play well'!",
        "lat": 55.6761,
        "lon": 12.5683,
        "country": "Denmark",
    },
    {
        "id": 216,
        "category": "culture",
        "question": "Which country celebrates Thanksgiving with turkey dinner?",
        "options": ["Canada", "United States", "United Kingdom", "Australia"],
        "answer": 1,
        "explanation": "Americans celebrate Thanksgiving on the fourth Thursday of November with family and lots of food!",
        "lat": 38.9072,
        "lon": -77.0369,
        "country": "United States",
    },
    {
        "id": 217,
        "category": "culture",
        "question": "Which country is famous for the festival of Holi?",
        "options": ["Thailand", "Japan", "India", "Nepal"],
        "answer": 2,
        "explanation": "Holi is the Festival of Colors — people throw colorful powder and water at each other to celebrate spring!",
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
    },
    {
        "id": 218,
        "category": "culture",
        "question": "Which country is famous for making watches?",
        "options": ["Germany", "Japan", "Switzerland", "Italy"],
        "answer": 2,
        "explanation": "Swiss watches like Rolex and Swatch are known worldwide for their precision and quality!",
        "lat": 46.9480,
        "lon": 7.4474,
        "country": "Switzerland",
    },
]


def generate_quiz(num_questions=10, category=None):
    """
    Generate a quiz with the specified number of questions.
    If category is None, picks questions ensuring variety across categories.
    If category is specified, picks from that category only.
    Returns shuffled questions as list of dicts.
    """
    if category is not None:
        if category not in CATEGORIES:
            raise ValueError(f"Unknown category: {category}")
        pool = [q for q in QUESTION_BANK if q["category"] == category]
    else:
        pool = list(QUESTION_BANK)

    if len(pool) < num_questions:
        num_questions = len(pool)

    selected = random.sample(pool, num_questions)
    random.shuffle(selected)
    return selected


def get_category_counts():
    """Return a dict of {category_id: count} for questions in each category."""
    counts = {cat_id: 0 for cat_id in CATEGORIES}
    for q in QUESTION_BANK:
        counts[q["category"]] += 1
    return counts
