"""
Science Corner — Grade 6 science quiz bank for Arjun.

Covers Inspire Science curriculum:
1. Life Science (cells, body systems, organisation)
2. Reproduction & Inheritance (heredity, genetics, variation)
3. Ecosystems & Energy Flow (food chains, matter cycling, human impact)
4. Matter & Physical Science (atoms, states of matter, forces, energy)
"""

import random

CATEGORIES = {
    "life_science": {
        "name": "Life Science",
        "emoji": "🧬",
        "color": "#10b981",
        "description": "Cells, body systems & how living things work",
    },
    "reproduction": {
        "name": "Reproduction & Inheritance",
        "emoji": "🧪",
        "color": "#8b5cf6",
        "description": "How traits are passed on to the next generation",
    },
    "ecosystems": {
        "name": "Ecosystems & Energy",
        "emoji": "🌿",
        "color": "#f59e0b",
        "description": "Food chains, energy flow & the environment",
    },
    "physical_science": {
        "name": "Matter & Physical Science",
        "emoji": "⚛️",
        "color": "#3b82f6",
        "description": "Atoms, molecules, forces & energy",
    },
}

QUESTION_BANK = [
    # ========== LIFE SCIENCE (~50 questions) ==========
    {
        "id": 1, "category": "life_science",
        "question": "What is the basic unit of life?",
        "options": ["Atom", "Cell", "Tissue", "Organ"],
        "answer": 1,
        "explanation": "Every living thing is made up of cells — they're the smallest unit that can carry out all life functions!",
    },
    {
        "id": 2, "category": "life_science",
        "question": "Which organelle is called the 'powerhouse of the cell'?",
        "options": ["Nucleus", "Ribosome", "Mitochondria", "Cell membrane"],
        "answer": 2,
        "explanation": "Mitochondria convert food into energy (ATP) that the cell can use — like tiny batteries!",
    },
    {
        "id": 3, "category": "life_science",
        "question": "What does the nucleus of a cell do?",
        "options": ["Makes energy", "Controls the cell", "Digests food", "Stores water"],
        "answer": 1,
        "explanation": "The nucleus contains DNA and acts as the cell's 'brain' — it controls everything the cell does!",
    },
    {
        "id": 4, "category": "life_science",
        "question": "Which of these is NOT a characteristic of living things?",
        "options": ["Growth", "Reproduction", "Magnetism", "Response to stimuli"],
        "answer": 2,
        "explanation": "Living things grow, reproduce, respond to their environment, and use energy — but magnetism isn't a life trait!",
    },
    {
        "id": 5, "category": "life_science",
        "question": "What is the correct order from smallest to largest?",
        "options": ["Organ → Tissue → Cell → System", "Cell → Tissue → Organ → System", "Tissue → Cell → System → Organ", "System → Organ → Tissue → Cell"],
        "answer": 1,
        "explanation": "Cells combine to form tissues, tissues form organs, and organs work together in organ systems!",
    },
    {
        "id": 6, "category": "life_science",
        "question": "What is the main function of the cell membrane?",
        "options": ["Makes proteins", "Produces energy", "Controls what enters and exits the cell", "Stores DNA"],
        "answer": 2,
        "explanation": "The cell membrane is like a gatekeeper — it decides what goes in and out of the cell!",
    },
    {
        "id": 7, "category": "life_science",
        "question": "Which body system is responsible for breaking down food?",
        "options": ["Respiratory system", "Digestive system", "Nervous system", "Skeletal system"],
        "answer": 1,
        "explanation": "The digestive system breaks food into nutrients your body can use — from mouth to stomach to intestines!",
    },
    {
        "id": 8, "category": "life_science",
        "question": "What do plant cells have that animal cells do NOT?",
        "options": ["Cell membrane", "Nucleus", "Cell wall", "Mitochondria"],
        "answer": 2,
        "explanation": "Plant cells have a rigid cell wall made of cellulose that gives them their boxy shape!",
    },
    {
        "id": 9, "category": "life_science",
        "question": "Which organ system pumps blood through your body?",
        "options": ["Nervous system", "Respiratory system", "Circulatory system", "Muscular system"],
        "answer": 2,
        "explanation": "The circulatory system — your heart, blood vessels, and blood — delivers oxygen and nutrients everywhere!",
    },
    {
        "id": 10, "category": "life_science",
        "question": "What gas do we breathe in that our cells need?",
        "options": ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
        "answer": 2,
        "explanation": "Our lungs take in oxygen, which our blood carries to every cell for making energy!",
    },
    {
        "id": 11, "category": "life_science",
        "question": "Which body system protects organs and supports the body?",
        "options": ["Muscular system", "Skeletal system", "Digestive system", "Endocrine system"],
        "answer": 1,
        "explanation": "Your skeleton has 206 bones that protect your organs and help you stand and move!",
    },
    {
        "id": 12, "category": "life_science",
        "question": "What is a group of similar cells working together called?",
        "options": ["Organ", "Tissue", "System", "Organism"],
        "answer": 1,
        "explanation": "Tissues are groups of similar cells that work together — like muscle tissue or nerve tissue!",
    },
    {
        "id": 13, "category": "life_science",
        "question": "Which organelle contains the cell's genetic material (DNA)?",
        "options": ["Ribosome", "Mitochondria", "Nucleus", "Vacuole"],
        "answer": 2,
        "explanation": "The nucleus holds DNA — the instructions for building and running the entire organism!",
    },
    {
        "id": 14, "category": "life_science",
        "question": "What is the function of the respiratory system?",
        "options": ["Digest food", "Exchange gases", "Pump blood", "Send signals"],
        "answer": 1,
        "explanation": "The respiratory system brings oxygen in and pushes carbon dioxide out through breathing!",
    },
    {
        "id": 15, "category": "life_science",
        "question": "Which part of a plant cell captures sunlight for photosynthesis?",
        "options": ["Nucleus", "Mitochondria", "Chloroplast", "Cell wall"],
        "answer": 2,
        "explanation": "Chloroplasts contain chlorophyll (the green pigment) and convert sunlight into food for the plant!",
    },
    {
        "id": 16, "category": "life_science",
        "question": "What does the nervous system do?",
        "options": ["Breaks down food", "Carries oxygen", "Sends messages through the body", "Makes hormones"],
        "answer": 2,
        "explanation": "The nervous system uses your brain, spinal cord, and nerves to send signals at incredible speed!",
    },
    {
        "id": 17, "category": "life_science",
        "question": "What is the largest organ in the human body?",
        "options": ["Heart", "Liver", "Brain", "Skin"],
        "answer": 3,
        "explanation": "Your skin covers about 20 square feet and protects everything inside — it's truly an organ!",
    },
    {
        "id": 18, "category": "life_science",
        "question": "Which blood cells fight infections in your body?",
        "options": ["Red blood cells", "Platelets", "White blood cells", "Plasma"],
        "answer": 2,
        "explanation": "White blood cells are like soldiers — they attack bacteria, viruses, and other invaders!",
    },
    {
        "id": 19, "category": "life_science",
        "question": "Where does digestion begin?",
        "options": ["Stomach", "Small intestine", "Mouth", "Large intestine"],
        "answer": 2,
        "explanation": "Digestion starts in the mouth — your teeth break food apart and saliva starts breaking it down chemically!",
    },
    {
        "id": 20, "category": "life_science",
        "question": "What do ribosomes do in a cell?",
        "options": ["Store water", "Make proteins", "Produce energy", "Control the cell"],
        "answer": 1,
        "explanation": "Ribosomes are tiny protein factories — they read instructions from DNA and build the proteins your body needs!",
    },
    {
        "id": 21, "category": "life_science",
        "question": "Which organ filters waste from the blood?",
        "options": ["Heart", "Lungs", "Kidneys", "Stomach"],
        "answer": 2,
        "explanation": "Your kidneys filter about 50 gallons of blood every day and remove waste as urine!",
    },
    {
        "id": 22, "category": "life_science",
        "question": "What carries oxygen in the blood?",
        "options": ["White blood cells", "Platelets", "Red blood cells", "Plasma"],
        "answer": 2,
        "explanation": "Red blood cells contain hemoglobin, which grabs oxygen in the lungs and delivers it everywhere!",
    },
    {
        "id": 23, "category": "life_science",
        "question": "What is the function of the vacuole in a cell?",
        "options": ["Makes energy", "Stores water and nutrients", "Controls the cell", "Makes proteins"],
        "answer": 1,
        "explanation": "Vacuoles are storage bubbles — plant cells have one big vacuole that helps keep the plant firm!",
    },
    {
        "id": 24, "category": "life_science",
        "question": "Which system works with the skeletal system to help you move?",
        "options": ["Digestive system", "Muscular system", "Respiratory system", "Nervous system"],
        "answer": 1,
        "explanation": "Muscles pull on bones to create movement — they work as a team with your skeleton!",
    },
    {
        "id": 25, "category": "life_science",
        "question": "What waste gas do cells produce that we breathe out?",
        "options": ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"],
        "answer": 2,
        "explanation": "When cells use oxygen to make energy, carbon dioxide is produced as waste — we exhale it!",
    },
    {
        "id": 26, "category": "life_science",
        "question": "What is the main function of the small intestine?",
        "options": ["Store food", "Absorb nutrients", "Chew food", "Pump blood"],
        "answer": 1,
        "explanation": "The small intestine is about 20 feet long and absorbs most of the nutrients from your food!",
    },
    {
        "id": 27, "category": "life_science",
        "question": "Which type of organism is made of only one cell?",
        "options": ["Multicellular", "Unicellular", "Colonial", "Complex"],
        "answer": 1,
        "explanation": "Unicellular organisms like bacteria and amoeba are just one cell that does everything!",
    },
    {
        "id": 28, "category": "life_science",
        "question": "What is homeostasis?",
        "options": ["Cell division", "Maintaining a stable internal environment", "Growing taller", "Eating food"],
        "answer": 1,
        "explanation": "Homeostasis means keeping things balanced — like your body staying at 98.6°F even when it's cold outside!",
    },
    {
        "id": 29, "category": "life_science",
        "question": "Which organ is the control center of the nervous system?",
        "options": ["Heart", "Spinal cord", "Brain", "Stomach"],
        "answer": 2,
        "explanation": "Your brain processes billions of signals and controls everything — thoughts, movements, and senses!",
    },
    {
        "id": 30, "category": "life_science",
        "question": "What are the tiny blood vessels where oxygen is exchanged called?",
        "options": ["Arteries", "Veins", "Capillaries", "Valves"],
        "answer": 2,
        "explanation": "Capillaries are so tiny that blood cells pass through in single file — that's where gas exchange happens!",
    },
    # ========== REPRODUCTION & INHERITANCE (~35 questions) ==========
    {
        "id": 31, "category": "reproduction",
        "question": "What is the molecule that carries genetic information?",
        "options": ["RNA", "DNA", "Protein", "Lipid"],
        "answer": 1,
        "explanation": "DNA stands for deoxyribonucleic acid — it's like a long instruction manual for building you!",
    },
    {
        "id": 32, "category": "reproduction",
        "question": "What are genes?",
        "options": ["Tiny organisms", "Sections of DNA that code for traits", "Types of cells", "Parts of the brain"],
        "answer": 1,
        "explanation": "Genes are segments of DNA that determine specific traits, like eye color or hair type!",
    },
    {
        "id": 33, "category": "reproduction",
        "question": "In sexual reproduction, how many parents are needed?",
        "options": ["One", "Two", "Three", "None"],
        "answer": 1,
        "explanation": "Sexual reproduction needs two parents — the offspring gets DNA from both mom and dad!",
    },
    {
        "id": 34, "category": "reproduction",
        "question": "In asexual reproduction, how many parents are needed?",
        "options": ["One", "Two", "Three", "Four"],
        "answer": 0,
        "explanation": "Asexual reproduction needs just one parent — the offspring is a genetic copy (clone) of the parent!",
    },
    {
        "id": 35, "category": "reproduction",
        "question": "What is an inherited trait?",
        "options": ["Something you learn at school", "A trait passed from parents through DNA", "A skill you practice", "A disease you catch"],
        "answer": 1,
        "explanation": "Inherited traits come from your parents' DNA — like eye color, hair color, and dimples!",
    },
    {
        "id": 36, "category": "reproduction",
        "question": "Which of these is an example of asexual reproduction?",
        "options": ["A dog having puppies", "A starfish regrowing an arm", "A bird laying eggs", "A flower being pollinated"],
        "answer": 1,
        "explanation": "Some starfish can regrow into a whole new animal from just one arm — that's asexual reproduction!",
    },
    {
        "id": 37, "category": "reproduction",
        "question": "What shape is a DNA molecule?",
        "options": ["Straight line", "Circle", "Double helix (twisted ladder)", "Triangle"],
        "answer": 2,
        "explanation": "DNA looks like a twisted ladder — scientists call this shape a double helix!",
    },
    {
        "id": 38, "category": "reproduction",
        "question": "What is a dominant trait?",
        "options": ["A trait that always skips a generation", "A trait that shows up even with one copy of the gene", "A trait that's always bad", "A trait only males have"],
        "answer": 1,
        "explanation": "A dominant trait only needs one copy to show up — like brown eyes being dominant over blue!",
    },
    {
        "id": 39, "category": "reproduction",
        "question": "What is a recessive trait?",
        "options": ["A trait that shows up only with two copies of the gene", "The strongest trait", "A trait that can't be inherited", "A learned behavior"],
        "answer": 0,
        "explanation": "You need two copies of a recessive gene for it to show — like needing two 'blue eye' genes for blue eyes!",
    },
    {
        "id": 40, "category": "reproduction",
        "question": "Why do siblings look different from each other?",
        "options": ["They eat different food", "They get different combinations of genes from parents", "They live in different rooms", "They go to different schools"],
        "answer": 1,
        "explanation": "Each child gets a random mix of mom's and dad's genes — so every combination is unique!",
    },
    {
        "id": 41, "category": "reproduction",
        "question": "What is variation in a population?",
        "options": ["Everyone looking the same", "Differences in traits among individuals", "Animals moving to new places", "Plants growing in soil"],
        "answer": 1,
        "explanation": "Variation means individuals in a species look or behave differently — no two are exactly alike!",
    },
    {
        "id": 42, "category": "reproduction",
        "question": "Which scientist is known as the father of genetics?",
        "options": ["Charles Darwin", "Gregor Mendel", "Isaac Newton", "Albert Einstein"],
        "answer": 1,
        "explanation": "Gregor Mendel studied pea plants in the 1860s and discovered how traits are passed down!",
    },
    {
        "id": 43, "category": "reproduction",
        "question": "What are chromosomes?",
        "options": ["Types of cells", "Structures made of DNA that carry genes", "Parts of the heart", "Types of tissues"],
        "answer": 1,
        "explanation": "Chromosomes are tightly packed bundles of DNA — humans have 46 of them (23 pairs)!",
    },
    {
        "id": 44, "category": "reproduction",
        "question": "How many chromosomes do human body cells normally have?",
        "options": ["23", "46", "12", "100"],
        "answer": 1,
        "explanation": "Human cells have 46 chromosomes — 23 from mom and 23 from dad, making 23 pairs!",
    },
    {
        "id": 45, "category": "reproduction",
        "question": "Which of these is an acquired trait (NOT inherited)?",
        "options": ["Eye color", "Natural hair color", "Speaking a language", "Blood type"],
        "answer": 2,
        "explanation": "Languages are learned — you're not born speaking English or Spanish, you learn them!",
    },
    {
        "id": 46, "category": "reproduction",
        "question": "What is an offspring?",
        "options": ["A parent organism", "A new organism produced by reproduction", "A type of cell", "A body system"],
        "answer": 1,
        "explanation": "Offspring are the 'children' of organisms — whether they're baby animals, seedlings, or bacteria!",
    },
    {
        "id": 47, "category": "reproduction",
        "question": "What do we call an organism that is an exact genetic copy of its parent?",
        "options": ["Hybrid", "Clone", "Mutant", "Twin"],
        "answer": 1,
        "explanation": "A clone has identical DNA to its parent — this happens naturally in asexual reproduction!",
    },
    {
        "id": 48, "category": "reproduction",
        "question": "Which of these organisms reproduces by budding?",
        "options": ["Dog", "Yeast", "Eagle", "Shark"],
        "answer": 1,
        "explanation": "Yeast grows a small bud on its body that breaks off to become a new organism!",
    },
    {
        "id": 49, "category": "reproduction",
        "question": "Why is genetic variation important for a species?",
        "options": ["It makes them all look the same", "It helps species survive changing environments", "It makes reproduction faster", "It reduces the population"],
        "answer": 1,
        "explanation": "Variation means some individuals may survive changes (disease, climate) that others can't!",
    },
    {
        "id": 50, "category": "reproduction",
        "question": "What is pollination in plants?",
        "options": ["When roots absorb water", "When pollen moves from one flower to another", "When leaves fall off", "When seeds sprout"],
        "answer": 1,
        "explanation": "Pollination is how flowering plants reproduce — bees, wind, and butterflies help carry pollen!",
    },
    {
        "id": 51, "category": "reproduction",
        "question": "Which of these is an inherited trait in humans?",
        "options": ["Riding a bicycle", "Eye color", "Haircut style", "Favorite food"],
        "answer": 1,
        "explanation": "Eye color is determined by genes from your parents — you can't choose or change it naturally!",
    },
    {
        "id": 52, "category": "reproduction",
        "question": "What does 'heredity' mean?",
        "options": ["Learning new skills", "Passing of traits from parents to offspring", "Growing taller", "Eating healthy food"],
        "answer": 1,
        "explanation": "Heredity is the process by which traits are transmitted from one generation to the next through genes!",
    },
    {
        "id": 53, "category": "reproduction",
        "question": "What happens during cell division?",
        "options": ["A cell shrinks", "A cell splits into two new cells", "A cell changes color", "A cell stops working"],
        "answer": 1,
        "explanation": "Cell division creates two new cells from one — it's how organisms grow and repair themselves!",
    },
    {
        "id": 54, "category": "reproduction",
        "question": "Which type of reproduction leads to more genetic diversity?",
        "options": ["Asexual reproduction", "Sexual reproduction", "Both equally", "Neither"],
        "answer": 1,
        "explanation": "Sexual reproduction mixes DNA from two parents, creating unique offspring with more variety!",
    },
    {
        "id": 55, "category": "reproduction",
        "question": "What is a mutation?",
        "options": ["A normal gene", "A change in the DNA sequence", "A type of cell", "A vitamin"],
        "answer": 1,
        "explanation": "Mutations are random changes in DNA — most are harmless, but some can cause new traits!",
    },
    # ========== ECOSYSTEMS & ENERGY FLOW (~45 questions) ==========
    {
        "id": 56, "category": "ecosystems",
        "question": "What is an ecosystem?",
        "options": ["Just the animals in an area", "A community of living things and their nonliving environment", "Only the plants in a forest", "A type of weather"],
        "answer": 1,
        "explanation": "An ecosystem includes ALL living things (animals, plants, microbes) plus nonliving things (water, soil, sunlight)!",
    },
    {
        "id": 57, "category": "ecosystems",
        "question": "What is a food chain?",
        "options": ["A restaurant menu", "The path of energy from one organism to another", "A type of plant", "A chain made of food"],
        "answer": 1,
        "explanation": "A food chain shows who eats whom — like: grass → grasshopper → frog → snake → hawk!",
    },
    {
        "id": 58, "category": "ecosystems",
        "question": "What is a producer in an ecosystem?",
        "options": ["An animal that hunts", "An organism that makes its own food", "A decomposer", "A parasite"],
        "answer": 1,
        "explanation": "Producers (like plants) make their own food using sunlight — they're the foundation of food chains!",
    },
    {
        "id": 59, "category": "ecosystems",
        "question": "What is a consumer?",
        "options": ["An organism that makes its own food", "An organism that eats other organisms", "A type of rock", "A nonliving thing"],
        "answer": 1,
        "explanation": "Consumers eat other organisms for energy — herbivores eat plants, carnivores eat animals!",
    },
    {
        "id": 60, "category": "ecosystems",
        "question": "What is a decomposer?",
        "options": ["An animal that hunts prey", "An organism that breaks down dead material", "A type of plant", "A rock formation"],
        "answer": 1,
        "explanation": "Decomposers like fungi and bacteria break down dead organisms, recycling nutrients back into the soil!",
    },
    {
        "id": 61, "category": "ecosystems",
        "question": "What do plants use from the sun to make food?",
        "options": ["Heat", "Light energy", "Wind", "Gravity"],
        "answer": 1,
        "explanation": "Plants use light energy from the sun in photosynthesis to make glucose (sugar) — their food!",
    },
    {
        "id": 62, "category": "ecosystems",
        "question": "What is a food web?",
        "options": ["A single food chain", "Multiple interconnected food chains", "A spider's web", "A fishing net"],
        "answer": 1,
        "explanation": "A food web shows how many food chains overlap — most organisms eat more than one thing!",
    },
    {
        "id": 63, "category": "ecosystems",
        "question": "What is the original source of energy for most ecosystems?",
        "options": ["Water", "Soil", "The Sun", "Wind"],
        "answer": 2,
        "explanation": "Almost all life on Earth depends on the Sun — plants capture sunlight, and animals eat plants!",
    },
    {
        "id": 64, "category": "ecosystems",
        "question": "What is an herbivore?",
        "options": ["An animal that eats only meat", "An animal that eats only plants", "An animal that eats both", "A type of plant"],
        "answer": 1,
        "explanation": "Herbivores like rabbits, deer, and cows eat plants — they're primary consumers in food chains!",
    },
    {
        "id": 65, "category": "ecosystems",
        "question": "What is a carnivore?",
        "options": ["An animal that eats only plants", "An animal that eats only meat", "A decomposer", "A producer"],
        "answer": 1,
        "explanation": "Carnivores like lions, eagles, and sharks eat other animals for energy!",
    },
    {
        "id": 66, "category": "ecosystems",
        "question": "What is an omnivore?",
        "options": ["Eats only plants", "Eats only meat", "Eats both plants and animals", "Eats nothing"],
        "answer": 2,
        "explanation": "Omnivores like bears, humans, and pigs eat both plants and animals — they have flexible diets!",
    },
    {
        "id": 67, "category": "ecosystems",
        "question": "What happens to energy as it moves up a food chain?",
        "options": ["It increases", "It stays the same", "Most of it is lost as heat", "It turns into water"],
        "answer": 2,
        "explanation": "About 90% of energy is lost as heat at each level — that's why there are fewer top predators!",
    },
    {
        "id": 68, "category": "ecosystems",
        "question": "What is the water cycle?",
        "options": ["Water flowing in rivers", "The continuous movement of water through the environment", "Rain falling", "Water in a glass"],
        "answer": 1,
        "explanation": "The water cycle moves water through evaporation, condensation, precipitation, and collection — over and over!",
    },
    {
        "id": 69, "category": "ecosystems",
        "question": "What is the carbon cycle?",
        "options": ["Carbon staying in one place", "The movement of carbon through living things and the environment", "Carbon in pencils", "Carbon dioxide only"],
        "answer": 1,
        "explanation": "Carbon moves from the air into plants, then to animals, then back to the air when things decompose or burn!",
    },
    {
        "id": 70, "category": "ecosystems",
        "question": "What is photosynthesis?",
        "options": ["Animals eating food", "Plants converting sunlight into food", "Rocks breaking apart", "Water evaporating"],
        "answer": 1,
        "explanation": "In photosynthesis, plants use sunlight + water + CO₂ to make glucose and release oxygen!",
    },
    {
        "id": 71, "category": "ecosystems",
        "question": "How does deforestation affect ecosystems?",
        "options": ["It helps animals", "It destroys habitats and reduces biodiversity", "It has no effect", "It creates more forests"],
        "answer": 1,
        "explanation": "Cutting down forests destroys homes for animals, reduces oxygen production, and increases erosion!",
    },
    {
        "id": 72, "category": "ecosystems",
        "question": "What is biodiversity?",
        "options": ["Having one type of animal", "The variety of life in an ecosystem", "A type of ecosystem", "A chemical process"],
        "answer": 1,
        "explanation": "Biodiversity means having many different species — ecosystems with high biodiversity are healthier!",
    },
    {
        "id": 73, "category": "ecosystems",
        "question": "What is an apex predator?",
        "options": ["An animal at the bottom of the food chain", "A top predator with no natural enemies", "A type of plant", "A decomposer"],
        "answer": 1,
        "explanation": "Apex predators like lions, sharks, and eagles are at the top — nothing regularly hunts them!",
    },
    {
        "id": 74, "category": "ecosystems",
        "question": "What are biotic factors in an ecosystem?",
        "options": ["Nonliving things like water and rocks", "Living things like plants and animals", "Only the weather", "Only the soil"],
        "answer": 1,
        "explanation": "Biotic means 'living' — all organisms in an ecosystem are biotic factors!",
    },
    {
        "id": 75, "category": "ecosystems",
        "question": "What are abiotic factors in an ecosystem?",
        "options": ["Living organisms", "Nonliving things like water, temperature, and sunlight", "Only animals", "Only plants"],
        "answer": 1,
        "explanation": "Abiotic means 'nonliving' — things like sunlight, water, temperature, and soil are abiotic factors!",
    },
    {
        "id": 76, "category": "ecosystems",
        "question": "What is a habitat?",
        "options": ["A food chain", "The place where an organism lives", "A type of animal", "An extinct species"],
        "answer": 1,
        "explanation": "A habitat provides everything an organism needs — food, water, shelter, and space!",
    },
    {
        "id": 77, "category": "ecosystems",
        "question": "What is an invasive species?",
        "options": ["A native species", "A species introduced to a new environment where it causes harm", "An endangered species", "A decomposer"],
        "answer": 1,
        "explanation": "Invasive species have no natural predators in their new home, so they can take over and harm native species!",
    },
    {
        "id": 78, "category": "ecosystems",
        "question": "What is the role of nitrogen in the nitrogen cycle?",
        "options": ["It's only in the air", "It cycles through air, soil, and living things as a nutrient", "It stays in water only", "It only exists in space"],
        "answer": 1,
        "explanation": "Nitrogen is essential for making proteins — bacteria in soil convert it into forms plants can use!",
    },
    {
        "id": 79, "category": "ecosystems",
        "question": "What is a primary consumer?",
        "options": ["A top predator", "An herbivore that eats producers", "A decomposer", "A producer"],
        "answer": 1,
        "explanation": "Primary consumers eat producers (plants) directly — rabbits, deer, and caterpillars are examples!",
    },
    {
        "id": 80, "category": "ecosystems",
        "question": "What would happen if all decomposers disappeared?",
        "options": ["Nothing", "Dead material would pile up and nutrients wouldn't recycle", "More plants would grow", "Animals would be healthier"],
        "answer": 1,
        "explanation": "Without decomposers, dead organisms would pile up and the soil would run out of nutrients for plants!",
    },
    {
        "id": 81, "category": "ecosystems",
        "question": "What is an energy pyramid?",
        "options": ["A pyramid in Egypt", "A diagram showing energy decreasing at each level of a food chain", "A type of solar panel", "A mountain shape"],
        "answer": 1,
        "explanation": "Energy pyramids show that producers have the most energy, and each level above has less!",
    },
    {
        "id": 82, "category": "ecosystems",
        "question": "How do humans impact ecosystems negatively?",
        "options": ["By planting trees", "By pollution, deforestation, and overuse of resources", "By recycling", "By studying nature"],
        "answer": 1,
        "explanation": "Pollution, cutting forests, and overusing resources all damage ecosystems and reduce biodiversity!",
    },
    {
        "id": 83, "category": "ecosystems",
        "question": "What is symbiosis?",
        "options": ["Organisms competing", "A close relationship between two different species", "Animals fighting", "Plants dying"],
        "answer": 1,
        "explanation": "Symbiosis is when two species live closely together — like clownfish living in sea anemones!",
    },
    {
        "id": 84, "category": "ecosystems",
        "question": "What is mutualism?",
        "options": ["One organism benefits, the other is harmed", "Both organisms benefit from the relationship", "One benefits, the other is unaffected", "Both are harmed"],
        "answer": 1,
        "explanation": "In mutualism, both species win — like bees getting nectar while pollinating flowers!",
    },
    {
        "id": 85, "category": "ecosystems",
        "question": "What is the greenhouse effect?",
        "options": ["Growing plants in a greenhouse", "Gases in the atmosphere trapping heat from the Sun", "The Sun getting hotter", "Ice melting"],
        "answer": 1,
        "explanation": "Greenhouse gases like CO₂ trap heat in our atmosphere — some is natural, but too much causes global warming!",
    },
    {
        "id": 86, "category": "ecosystems",
        "question": "Which of these is a renewable resource?",
        "options": ["Coal", "Natural gas", "Solar energy", "Oil"],
        "answer": 2,
        "explanation": "Solar energy comes from the Sun and won't run out — unlike fossil fuels which take millions of years to form!",
    },
    {
        "id": 87, "category": "ecosystems",
        "question": "What is a trophic level?",
        "options": ["A type of weather", "A feeding level in a food chain", "A tropical island", "A type of soil"],
        "answer": 1,
        "explanation": "Trophic levels show who eats whom: Level 1 = producers, Level 2 = herbivores, Level 3 = carnivores!",
    },
    {
        "id": 88, "category": "ecosystems",
        "question": "What is ecological succession?",
        "options": ["Animals going extinct", "The gradual change of an ecosystem over time", "A sudden earthquake", "Water pollution"],
        "answer": 1,
        "explanation": "After a forest fire, grasses grow first, then shrubs, then small trees, then a full forest — that's succession!",
    },
    # ========== MATTER & PHYSICAL SCIENCE (~45 questions) ==========
    {
        "id": 89, "category": "physical_science",
        "question": "What is the smallest unit of an element?",
        "options": ["Molecule", "Atom", "Cell", "Tissue"],
        "answer": 1,
        "explanation": "Atoms are the building blocks of all matter — everything around you is made of atoms!",
    },
    {
        "id": 90, "category": "physical_science",
        "question": "What are the three common states of matter?",
        "options": ["Hot, warm, cold", "Solid, liquid, gas", "Big, medium, small", "Fast, slow, still"],
        "answer": 1,
        "explanation": "Water shows all three: ice (solid), water (liquid), and steam (gas)!",
    },
    {
        "id": 91, "category": "physical_science",
        "question": "What is a molecule?",
        "options": ["A single atom", "Two or more atoms bonded together", "A type of cell", "A form of energy"],
        "answer": 1,
        "explanation": "A water molecule (H₂O) is made of 2 hydrogen atoms bonded to 1 oxygen atom!",
    },
    {
        "id": 92, "category": "physical_science",
        "question": "What are the three parts of an atom?",
        "options": ["Head, body, tail", "Protons, neutrons, electrons", "Solid, liquid, gas", "Red, blue, green"],
        "answer": 1,
        "explanation": "Protons (+) and neutrons (no charge) are in the center, and electrons (-) orbit around them!",
    },
    {
        "id": 93, "category": "physical_science",
        "question": "Which subatomic particle has a positive charge?",
        "options": ["Electron", "Neutron", "Proton", "Photon"],
        "answer": 2,
        "explanation": "Protons have a positive charge and are found in the nucleus of the atom!",
    },
    {
        "id": 94, "category": "physical_science",
        "question": "Which subatomic particle has a negative charge?",
        "options": ["Proton", "Neutron", "Electron", "Nucleus"],
        "answer": 2,
        "explanation": "Electrons are tiny particles with a negative charge that zoom around the nucleus!",
    },
    {
        "id": 95, "category": "physical_science",
        "question": "What is a physical change?",
        "options": ["A change that creates a new substance", "A change in appearance without creating a new substance", "Only melting", "Only freezing"],
        "answer": 1,
        "explanation": "Cutting paper, melting ice, and dissolving sugar are physical changes — no new substance is made!",
    },
    {
        "id": 96, "category": "physical_science",
        "question": "What is a chemical change?",
        "options": ["Changing shape", "A change that produces a new substance", "Mixing water and oil", "Cutting wood"],
        "answer": 1,
        "explanation": "Burning wood, rusting iron, and cooking an egg are chemical changes — new substances form!",
    },
    {
        "id": 97, "category": "physical_science",
        "question": "What happens to molecules when matter is heated?",
        "options": ["They slow down", "They move faster and spread apart", "They disappear", "They get heavier"],
        "answer": 1,
        "explanation": "Heat gives molecules more energy, so they vibrate and move faster — that's why solids melt into liquids!",
    },
    {
        "id": 98, "category": "physical_science",
        "question": "What is the Periodic Table?",
        "options": ["A timetable", "A chart organizing all known elements", "A multiplication table", "A recipe book"],
        "answer": 1,
        "explanation": "The Periodic Table organizes 118 elements by their properties — it's like the alphabet of chemistry!",
    },
    {
        "id": 99, "category": "physical_science",
        "question": "What is an element?",
        "options": ["A mixture of substances", "A pure substance made of only one type of atom", "A compound", "A solution"],
        "answer": 1,
        "explanation": "Gold, oxygen, and carbon are elements — each made of only one kind of atom!",
    },
    {
        "id": 100, "category": "physical_science",
        "question": "What is a compound?",
        "options": ["A single element", "A substance made of two or more different elements chemically bonded", "A mixture", "A type of atom"],
        "answer": 1,
        "explanation": "Water (H₂O) is a compound — hydrogen and oxygen atoms bonded together make something completely new!",
    },
    {
        "id": 101, "category": "physical_science",
        "question": "What is the chemical formula for water?",
        "options": ["CO₂", "H₂O", "NaCl", "O₂"],
        "answer": 1,
        "explanation": "H₂O means two hydrogen atoms and one oxygen atom — that's water!",
    },
    {
        "id": 102, "category": "physical_science",
        "question": "What is gravity?",
        "options": ["A type of light", "A force that pulls objects toward each other", "A type of sound", "A chemical reaction"],
        "answer": 1,
        "explanation": "Gravity keeps you on the ground and the Moon orbiting Earth — it pulls everything with mass together!",
    },
    {
        "id": 103, "category": "physical_science",
        "question": "What is mass?",
        "options": ["How tall something is", "The amount of matter in an object", "How fast something moves", "A type of energy"],
        "answer": 1,
        "explanation": "Mass is the amount of 'stuff' in an object — it stays the same even on the Moon!",
    },
    {
        "id": 104, "category": "physical_science",
        "question": "What is the difference between mass and weight?",
        "options": ["They are the same thing", "Mass is the amount of matter; weight is the force of gravity on that matter", "Weight is always more", "Mass changes with location"],
        "answer": 1,
        "explanation": "Your mass stays the same everywhere, but you'd weigh less on the Moon because gravity is weaker there!",
    },
    {
        "id": 105, "category": "physical_science",
        "question": "What is friction?",
        "options": ["A type of energy", "A force that resists motion between surfaces", "A form of light", "A chemical bond"],
        "answer": 1,
        "explanation": "Friction slows things down — it's why you can walk without slipping and why brakes stop a car!",
    },
    {
        "id": 106, "category": "physical_science",
        "question": "What is kinetic energy?",
        "options": ["Stored energy", "The energy of motion", "Heat energy only", "Sound energy only"],
        "answer": 1,
        "explanation": "Anything that's moving has kinetic energy — a rolling ball, a running person, a flying bird!",
    },
    {
        "id": 107, "category": "physical_science",
        "question": "What is potential energy?",
        "options": ["Energy of motion", "Stored energy that could be released", "Sound energy", "Only electrical energy"],
        "answer": 1,
        "explanation": "A ball at the top of a hill has potential energy — when it rolls down, that energy becomes kinetic!",
    },
    {
        "id": 108, "category": "physical_science",
        "question": "How does heat transfer by conduction?",
        "options": ["Through empty space", "By direct contact between objects", "By moving fluids", "By sound waves"],
        "answer": 1,
        "explanation": "Conduction is heat moving through touch — like a metal spoon getting hot in a pot of soup!",
    },
    {
        "id": 109, "category": "physical_science",
        "question": "How does heat transfer by convection?",
        "options": ["Through direct contact", "Through the movement of fluids (liquids or gases)", "Through empty space", "Through solids only"],
        "answer": 1,
        "explanation": "Convection happens when warm fluids rise and cool fluids sink — like hot air rising from a heater!",
    },
    {
        "id": 110, "category": "physical_science",
        "question": "How does heat transfer by radiation?",
        "options": ["Through direct contact", "Through moving fluids", "Through electromagnetic waves (no medium needed)", "Through sound"],
        "answer": 2,
        "explanation": "Radiation is how the Sun's heat reaches Earth — it travels through empty space as waves!",
    },
    {
        "id": 111, "category": "physical_science",
        "question": "What is Newton's First Law of Motion?",
        "options": ["Force equals mass times acceleration", "For every action there's an equal reaction", "An object at rest stays at rest unless acted on by a force", "Energy cannot be created or destroyed"],
        "answer": 2,
        "explanation": "This is also called the law of inertia — objects keep doing what they're doing unless a force changes that!",
    },
    {
        "id": 112, "category": "physical_science",
        "question": "What is density?",
        "options": ["How heavy something is", "Mass divided by volume", "How big something is", "How fast something moves"],
        "answer": 1,
        "explanation": "Density = mass ÷ volume — it's why a small rock sinks but a big piece of wood floats!",
    },
    {
        "id": 113, "category": "physical_science",
        "question": "What is the chemical formula for carbon dioxide?",
        "options": ["H₂O", "NaCl", "CO₂", "O₂"],
        "answer": 2,
        "explanation": "CO₂ has one carbon atom and two oxygen atoms — it's what you breathe out and plants breathe in!",
    },
    {
        "id": 114, "category": "physical_science",
        "question": "Which state of matter has a definite shape and volume?",
        "options": ["Liquid", "Gas", "Solid", "Plasma"],
        "answer": 2,
        "explanation": "Solids have tightly packed molecules that hold their shape — like a rock or a book!",
    },
    {
        "id": 115, "category": "physical_science",
        "question": "Which state of matter has a definite volume but no definite shape?",
        "options": ["Solid", "Liquid", "Gas", "Plasma"],
        "answer": 1,
        "explanation": "Liquids take the shape of their container but keep the same volume — pour water into any glass!",
    },
    {
        "id": 116, "category": "physical_science",
        "question": "Which state of matter has no definite shape or volume?",
        "options": ["Solid", "Liquid", "Gas", "None of these"],
        "answer": 2,
        "explanation": "Gas molecules spread out to fill any container — that's why air fills an entire room!",
    },
    {
        "id": 117, "category": "physical_science",
        "question": "What is a mixture?",
        "options": ["A pure substance", "Two or more substances combined but not chemically bonded", "A single element", "A compound"],
        "answer": 1,
        "explanation": "Trail mix, salt water, and air are all mixtures — the parts aren't chemically joined and can be separated!",
    },
    {
        "id": 118, "category": "physical_science",
        "question": "What is the law of conservation of energy?",
        "options": ["Energy can be created", "Energy can be destroyed", "Energy cannot be created or destroyed, only transformed", "Energy always increases"],
        "answer": 2,
        "explanation": "Energy just changes form — like electrical energy becoming light and heat in a light bulb!",
    },
    {
        "id": 119, "category": "physical_science",
        "question": "What is speed?",
        "options": ["Mass times volume", "Distance divided by time", "Force times area", "Weight divided by mass"],
        "answer": 1,
        "explanation": "Speed = distance ÷ time — if you run 100 meters in 20 seconds, your speed is 5 m/s!",
    },
    {
        "id": 120, "category": "physical_science",
        "question": "What is a solution?",
        "options": ["A solid only", "A well-mixed mixture where one substance dissolves in another", "A pure element", "A chemical reaction"],
        "answer": 1,
        "explanation": "Sugar dissolved in water is a solution — the sugar particles are so small you can't see them!",
    },
    {
        "id": 121, "category": "physical_science",
        "question": "Which of these is a sign of a chemical change?",
        "options": ["Changing shape", "Changing size", "Producing gas bubbles or a color change", "Melting"],
        "answer": 2,
        "explanation": "Bubbles, color changes, heat/light production, and new smells are all signs of chemical reactions!",
    },
    {
        "id": 122, "category": "physical_science",
        "question": "What is an insulator?",
        "options": ["A material that conducts heat well", "A material that resists the flow of heat or electricity", "A type of metal", "A magnet"],
        "answer": 1,
        "explanation": "Insulators like rubber, wood, and plastic don't let heat or electricity pass through easily!",
    },
    {
        "id": 123, "category": "physical_science",
        "question": "What is a conductor?",
        "options": ["A material that blocks heat", "A material that allows heat or electricity to flow through easily", "A type of plastic", "An insulator"],
        "answer": 1,
        "explanation": "Metals like copper and aluminum are great conductors — that's why wires are made of metal!",
    },
    {
        "id": 124, "category": "physical_science",
        "question": "What is acceleration?",
        "options": ["Constant speed", "A change in speed or direction over time", "Distance traveled", "Standing still"],
        "answer": 1,
        "explanation": "Acceleration means speeding up, slowing down, or changing direction — it's any change in velocity!",
    },
    {
        "id": 125, "category": "physical_science",
        "question": "What is the law of conservation of mass?",
        "options": ["Mass can be created", "Mass can be destroyed", "In a chemical reaction, mass is neither created nor destroyed", "Mass always increases"],
        "answer": 2,
        "explanation": "The total mass before and after a chemical reaction is always the same — atoms just rearrange!",
    },
    {
        "id": 126, "category": "physical_science",
        "question": "What is evaporation?",
        "options": ["Gas turning to liquid", "Liquid turning to gas", "Solid turning to liquid", "Gas turning to solid"],
        "answer": 1,
        "explanation": "When water evaporates, liquid molecules gain enough energy to escape into the air as gas!",
    },
    {
        "id": 127, "category": "physical_science",
        "question": "What is condensation?",
        "options": ["Liquid turning to gas", "Gas turning to liquid", "Solid turning to gas", "Liquid turning to solid"],
        "answer": 1,
        "explanation": "When water vapor cools, it condenses into liquid droplets — that's how clouds form!",
    },
    {
        "id": 128, "category": "physical_science",
        "question": "What is the pH scale used to measure?",
        "options": ["Temperature", "How acidic or basic a substance is", "Weight", "Speed"],
        "answer": 1,
        "explanation": "The pH scale goes from 0 (very acidic) to 14 (very basic), with 7 being neutral (like pure water)!",
    },
    {
        "id": 129, "category": "physical_science",
        "question": "What is thermal energy?",
        "options": ["Light energy", "Sound energy", "The total kinetic energy of particles in a substance", "Nuclear energy"],
        "answer": 2,
        "explanation": "Thermal energy is the total energy of all the moving particles — the faster they move, the more thermal energy!",
    },
    {
        "id": 130, "category": "physical_science",
        "question": "What is Newton's Third Law of Motion?",
        "options": ["Objects at rest stay at rest", "F = ma", "For every action there is an equal and opposite reaction", "Energy is conserved"],
        "answer": 2,
        "explanation": "When you push a wall, the wall pushes back on you with equal force — action and reaction!",
    },
]


def generate_quiz(num_questions: int = 10, category: str | None = None) -> list:
    """Generate a science quiz with variety across categories."""
    if category and category in CATEGORIES:
        pool = [q for q in QUESTION_BANK if q["category"] == category]
    else:
        pool = list(QUESTION_BANK)

    if len(pool) < num_questions:
        num_questions = len(pool)

    selected = random.sample(pool, num_questions)

    for q in selected:
        correct_text = q["options"][q["answer"]]
        indices = list(range(len(q["options"])))
        random.shuffle(indices)
        q["options"] = [q["options"][j] for j in indices]
        q["answer"] = q["options"].index(correct_text)

    random.shuffle(selected)
    return selected


def get_category_counts() -> dict:
    """Return {category_id: count} for questions in each category."""
    counts = {cat_id: 0 for cat_id in CATEGORIES}
    for q in QUESTION_BANK:
        counts[q["category"]] += 1
    return counts
