"""
State-level map data for Sangeetha's GK app.

Uses REAL geographic data:
  - State map images are generated from actual GeoJSON boundaries (matplotlib).
  - Location positions use real latitude/longitude coordinates.
  - Bounding-box data converts lat/lon to image (x%, y%) at render time.
"""

import base64
import json
import os

_STATE_MAPS_DIR = os.path.join(os.path.dirname(__file__), "state_maps")
_BOUNDS_PATH = os.path.join(os.path.dirname(__file__), "state_bounds.json")
_STATE_B64_CACHE: dict[str, str] = {}
_BOUNDS: dict[str, dict] = {}


def _load_bounds():
    """Load state bounding boxes from JSON (generated by generate_state_maps_geo.py)."""
    global _BOUNDS
    if _BOUNDS:
        return
    if os.path.exists(_BOUNDS_PATH):
        with open(_BOUNDS_PATH) as f:
            _BOUNDS = json.load(f)


def _get_state_b64(state_key: str) -> str | None:
    """Load a state map as a base64 data URI (cached)."""
    if state_key in _STATE_B64_CACHE:
        return _STATE_B64_CACHE[state_key]
    path = os.path.join(_STATE_MAPS_DIR, f"{state_key}.png")
    if not os.path.exists(path):
        return None
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode()
    uri = f"data:image/png;base64,{encoded}"
    _STATE_B64_CACHE[state_key] = uri
    return uri


# ── Map display names of states / UTs to file-system keys ──
STATE_KEY_MAP: dict[str, str] = {
    # ── 28 States ──
    "Andhra Pradesh":       "andhra_pradesh",
    "Arunachal Pradesh":    "arunachal_pradesh",
    "Assam":                "assam",
    "Bihar":                "bihar",
    "Chhattisgarh":         "chhattisgarh",
    "Goa":                  "goa",
    "Gujarat":              "gujarat",
    "Haryana":              "haryana",
    "Himachal Pradesh":     "himachal_pradesh",
    "Jharkhand":            "jharkhand",
    "Karnataka":            "karnataka",
    "Kerala":               "kerala",
    "Madhya Pradesh":       "madhya_pradesh",
    "Maharashtra":          "maharashtra",
    "Manipur":              "manipur",
    "Meghalaya":            "meghalaya",
    "Mizoram":              "mizoram",
    "Nagaland":             "nagaland",
    "Odisha":               "odisha",
    "Punjab":               "punjab",
    "Rajasthan":            "rajasthan",
    "Sikkim":               "sikkim",
    "Tamil Nadu":           "tamil_nadu",
    "Telangana":            "telangana",
    "Tripura":              "tripura",
    "Uttar Pradesh":        "uttar_pradesh",
    "Uttarakhand":          "uttarakhand",
    "West Bengal":          "west_bengal",

    # ── 8 Union Territories ──
    "Andaman and Nicobar Islands": "andaman_nicobar",
    "Andaman and Nicobar":  "andaman_nicobar",
    "Chandigarh":           "chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu": "dadra_daman_diu",
    "Daman and Diu":        "dadra_daman_diu",
    "Dadra and Nagar Haveli": "dadra_daman_diu",
    "Delhi":                "delhi",
    "NCT of Delhi":         "delhi",
    "New Delhi":            "delhi",
    "Jammu and Kashmir":    "jammu_and_kashmir",
    "Ladakh":               "ladakh",
    "Lakshadweep":          "lakshadweep",
    "Puducherry":           "puducherry",
    "Pondicherry":          "puducherry",
}


# ══════════════════════════════════════════════════════════════════
# REAL LAT/LON COORDINATES for cities, rivers, landmarks, etc.
# Format: (latitude, longitude)
# These are actual geographic coordinates.
# ══════════════════════════════════════════════════════════════════

STATE_LOCATIONS: dict[str, dict[str, tuple[float, float]]] = {

    # ── KARNATAKA ──
    "karnataka": {
        "Bengaluru":        (12.97, 77.59),
        "Bangalore":        (12.97, 77.59),
        "Mysuru":           (12.30, 76.65),
        "Mysore":           (12.30, 76.65),
        "Mangaluru":        (12.87, 74.88),
        "Mangalore":        (12.87, 74.88),
        "Hubli":            (15.36, 75.12),
        "Dharwad":          (15.46, 75.01),
        "Belgaum":          (15.85, 74.50),
        "Belagavi":         (15.85, 74.50),
        "Hampi":            (15.33, 76.46),
        "Badami":           (15.92, 75.68),
        "Gulbarga":         (17.33, 76.83),
        "Kalaburagi":       (17.33, 76.83),
        "Raichur":          (16.20, 77.36),
        "Shimoga":          (13.93, 75.57),
        "Shivamogga":       (13.93, 75.57),
        "Hassan":           (13.00, 76.10),
        "Chitradurga":      (14.23, 76.40),
        "Udupi":            (13.34, 74.75),
        "Bidar":            (17.91, 77.52),
        "Kaveri":           (12.42, 76.70),
        "Cauvery":          (12.42, 76.70),
        "Tungabhadra":      (15.35, 76.46),
        "Krishna":          (16.70, 76.20),
        "Sharavathi":       (14.10, 74.80),
        "Nethravathi":      (12.80, 75.00),
        "Kabini":           (11.95, 76.30),
        "Hemavathi":        (13.10, 76.05),
        "Arkavathi":        (12.90, 77.50),
        "Coorg":            (12.34, 75.80),
        "Kodagu":           (12.34, 75.80),
        "Mysore Palace":    (12.30, 76.65),
        "Gol Gumbaz":       (16.83, 75.74),
    },

    # ── TAMIL NADU ──
    "tamil_nadu": {
        "Chennai":          (13.08, 80.27),
        "Madurai":          (9.92, 78.12),
        "Coimbatore":       (11.00, 76.96),
        "Trichy":           (10.79, 78.69),
        "Tiruchirappalli":  (10.79, 78.69),
        "Salem":            (11.66, 78.15),
        "Tirunelveli":      (8.73, 77.69),
        "Thanjavur":        (10.79, 79.14),
        "Tanjore":          (10.79, 79.14),
        "Kanchipuram":      (12.83, 79.70),
        "Mahabalipuram":    (12.62, 80.19),
        "Rameswaram":       (9.29, 79.31),
        "Ooty":             (11.41, 76.69),
        "Kodaikanal":       (10.23, 77.49),
        "Vellore":          (12.92, 79.13),
        "Erode":            (11.34, 77.73),
        "Kaveri":           (11.00, 78.00),
        "Cauvery":          (11.00, 78.00),
        "Vaigai":           (9.90, 78.10),
        "Tamiraparani":     (8.75, 77.70),
        "Bhavani":          (11.45, 77.68),
        "Amaravathi":       (11.00, 78.20),
        "Moyar":            (11.55, 76.55),
        "Brihadeeswarar Temple": (10.78, 79.13),
        "Meenakshi Temple": (9.92, 78.12),
        "Meenakshi Amman Temple": (9.92, 78.12),
        "Nilgiri":          (11.40, 76.70),
    },

    # ── KERALA ──
    "kerala": {
        "Thiruvananthapuram": (8.52, 76.94),
        "Kochi":            (9.93, 76.27),
        "Cochin":           (9.93, 76.27),
        "Kozhikode":        (11.25, 75.77),
        "Calicut":          (11.25, 75.77),
        "Thrissur":         (10.53, 76.21),
        "Alappuzha":        (9.49, 76.34),
        "Alleppey":         (9.49, 76.34),
        "Kollam":           (8.89, 76.60),
        "Kannur":           (11.87, 75.37),
        "Palakkad":         (10.78, 76.65),
        "Munnar":           (10.09, 77.06),
        "Wayanad":          (11.69, 76.13),
        "Kottayam":         (9.59, 76.52),
        "Idukki":           (9.85, 76.97),
        "Periyar":          (9.47, 77.17),
        "Pamba":            (9.40, 76.70),
        "Bharathappuzha":   (10.78, 75.95),
        "Chaliyar":         (11.17, 75.90),
        "Nila":             (10.78, 75.95),
    },

    # ── ANDHRA PRADESH ──
    "andhra_pradesh": {
        "Amaravati":        (16.51, 80.52),
        "Visakhapatnam":    (17.69, 83.22),
        "Vizag":            (17.69, 83.22),
        "Vijayawada":       (16.51, 80.65),
        "Tirupati":         (13.63, 79.42),
        "Guntur":           (16.30, 80.44),
        "Nellore":          (14.45, 79.99),
        "Kurnool":          (15.83, 78.04),
        "Rajahmundry":      (17.00, 81.80),
        "Kakinada":         (16.94, 82.24),
        "Anantapur":        (14.68, 77.60),
        "Srisailam":        (15.85, 78.87),
        "Krishna":          (16.50, 80.60),
        "Godavari":         (17.00, 81.80),
        "Pennar":           (14.60, 79.80),
        "Chitravathi":      (14.50, 77.60),
        "Tungabhadra":      (15.90, 78.10),
    },

    # ── TELANGANA ──
    "telangana": {
        "Hyderabad":        (17.38, 78.49),
        "Warangal":         (18.00, 79.59),
        "Nizamabad":        (18.67, 78.09),
        "Karimnagar":       (18.44, 79.13),
        "Khammam":          (17.25, 80.15),
        "Nalgonda":         (17.06, 79.27),
        "Medak":            (18.04, 78.26),
        "Adilabad":         (19.67, 78.53),
        "Mahbubnagar":      (16.74, 78.00),
        "Charminar":        (17.36, 78.47),
        "Golconda Fort":    (17.38, 78.40),
        "Godavari":         (18.80, 79.50),
        "Krishna":          (16.80, 78.50),
    },

    # ── MAHARASHTRA ──
    "maharashtra": {
        "Mumbai":           (19.08, 72.88),
        "Pune":             (18.52, 73.86),
        "Nagpur":           (21.15, 79.09),
        "Nashik":           (20.00, 73.79),
        "Aurangabad":       (19.88, 75.34),
        "Solapur":          (17.66, 75.91),
        "Kolhapur":         (16.70, 74.24),
        "Thane":            (19.22, 72.98),
        "Amravati":         (20.93, 77.78),
        "Latur":            (18.40, 76.57),
        "Sangli":           (16.86, 74.56),
        "Ajanta":           (20.55, 75.70),
        "Ellora":           (20.02, 75.18),
        "Gateway of India": (18.92, 72.83),
        "Shirdi":           (19.77, 74.48),
        "Lonavala":         (18.75, 73.41),
        "Mahabaleshwar":    (17.92, 73.66),
        "Ratnagiri":        (16.99, 73.31),
        "Godavari":         (19.80, 75.50),
        "Krishna":          (16.80, 74.40),
        "Tapi":             (21.10, 75.50),
    },

    # ── RAJASTHAN ──
    "rajasthan": {
        "Jaipur":           (26.91, 75.79),
        "Jodhpur":          (26.29, 73.02),
        "Udaipur":          (24.59, 73.68),
        "Jaisalmer":        (26.91, 70.92),
        "Bikaner":          (28.02, 73.31),
        "Ajmer":            (26.45, 74.64),
        "Pushkar":          (26.49, 74.55),
        "Kota":             (25.18, 75.86),
        "Bharatpur":        (27.22, 77.50),
        "Mount Abu":        (24.59, 72.71),
        "Chittorgarh":      (24.88, 74.63),
        "Amber Fort":       (26.99, 75.85),
        "Hawa Mahal":       (26.92, 75.83),
        "Mehrangarh Fort":  (26.30, 73.02),
        "Ranthambore":      (26.02, 76.45),
        "Chambal":          (25.50, 76.50),
        "Aravalli":         (25.00, 73.50),
    },

    # ── GUJARAT ──
    "gujarat": {
        "Ahmedabad":        (23.02, 72.57),
        "Surat":            (21.17, 72.83),
        "Vadodara":         (22.31, 73.19),
        "Rajkot":           (22.30, 70.80),
        "Bhavnagar":        (21.76, 72.15),
        "Jamnagar":         (22.47, 70.07),
        "Junagadh":         (21.52, 70.46),
        "Gandhinagar":      (23.22, 72.64),
        "Kutch":            (23.73, 69.86),
        "Rann of Kutch":    (23.80, 70.10),
        "Gir":              (21.12, 70.79),
        "Dwarka":           (22.24, 68.97),
        "Somnath":          (20.89, 70.40),
        "Dandi":            (20.92, 72.83),
        "Sabarmati Ashram": (23.06, 72.58),
        "Sabarmati":        (23.06, 72.58),
        "Narmada":          (21.80, 73.00),
    },

    # ── UTTAR PRADESH ──
    "uttar_pradesh": {
        "Lucknow":          (26.85, 80.95),
        "Agra":             (27.18, 78.02),
        "Varanasi":         (25.32, 83.01),
        "Kanpur":           (26.45, 80.35),
        "Prayagraj":        (25.43, 81.85),
        "Allahabad":        (25.43, 81.85),
        "Noida":            (28.57, 77.32),
        "Meerut":           (28.98, 77.71),
        "Mathura":          (27.49, 77.67),
        "Ayodhya":          (26.80, 82.20),
        "Aligarh":          (27.88, 78.08),
        "Jhansi":           (25.45, 78.57),
        "Taj Mahal":        (27.17, 78.04),
        "Fatehpur Sikri":   (27.09, 77.66),
        "Red Fort":         (28.66, 77.24),
        "Sarnath":          (25.38, 83.02),
        "Ganga":            (26.00, 81.00),
        "Yamuna":           (27.50, 77.70),
    },

    # ── MADHYA PRADESH ──
    "madhya_pradesh": {
        "Bhopal":           (23.26, 77.41),
        "Indore":           (22.72, 75.86),
        "Jabalpur":         (23.18, 79.95),
        "Gwalior":          (26.22, 78.18),
        "Ujjain":           (23.18, 75.77),
        "Rewa":             (24.53, 81.30),
        "Sagar":            (23.84, 78.74),
        "Sanchi":           (23.48, 77.74),
        "Khajuraho":        (24.85, 79.92),
        "Pachmarhi":        (22.47, 78.43),
        "Orchha":           (25.35, 78.64),
        "Mandu":            (22.33, 75.39),
        "Narmada":          (22.60, 77.00),
        "Chambal":          (26.00, 78.00),
        "Sanchi Stupa":     (23.48, 77.74),
        "Buland Darwaza":   (27.09, 77.66),
    },

    # ── WEST BENGAL ──
    "west_bengal": {
        "Kolkata":          (22.57, 88.36),
        "Darjeeling":       (27.05, 88.26),
        "Siliguri":         (26.72, 88.40),
        "Howrah":           (22.59, 88.26),
        "Asansol":          (23.68, 86.94),
        "Durgapur":         (23.55, 87.32),
        "Murshidabad":      (24.18, 88.27),
        "Santiniketan":     (23.68, 87.69),
        "Sundarbans":       (21.95, 88.90),
        "Digha":            (21.63, 87.55),
        "Victoria Memorial": (22.54, 88.34),
        "Hooghly":          (22.90, 88.40),
        "Ganga":            (23.00, 88.20),
    },

    # ── ODISHA ──
    "odisha": {
        "Bhubaneswar":      (20.30, 85.82),
        "Puri":             (19.80, 85.83),
        "Cuttack":          (20.46, 85.88),
        "Rourkela":         (22.26, 84.85),
        "Sambalpur":        (21.47, 83.97),
        "Berhampur":        (19.31, 84.79),
        "Konark":           (19.88, 86.09),
        "Chilika":          (19.72, 85.32),
        "Simlipal":         (21.83, 86.37),
        "Mahanadi":         (20.50, 84.50),
        "Konark Sun Temple": (19.88, 86.09),
    },

    # ── BIHAR ──
    "bihar": {
        "Patna":            (25.61, 85.14),
        "Gaya":             (24.80, 84.99),
        "Nalanda":          (25.13, 85.44),
        "Bodh Gaya":        (24.70, 84.99),
        "Rajgir":           (25.03, 85.42),
        "Vaishali":         (25.99, 85.13),
        "Muzaffarpur":      (26.12, 85.39),
        "Bhagalpur":        (25.24, 86.97),
        "Darbhanga":        (26.17, 85.90),
        "Ganga":            (25.60, 85.10),
    },

    # ── PUNJAB ──
    "punjab": {
        "Chandigarh":       (30.73, 76.78),
        "Amritsar":         (31.63, 74.87),
        "Ludhiana":         (30.90, 75.86),
        "Jalandhar":        (31.33, 75.58),
        "Patiala":          (30.34, 76.39),
        "Bathinda":         (30.21, 74.95),
        "Pathankot":        (32.27, 75.65),
        "Golden Temple":    (31.62, 74.88),
        "Jallianwala Bagh": (31.62, 74.88),
        "Sutlej":           (30.90, 75.90),
    },

    # ── GOA ──
    "goa": {
        "Panaji":           (15.50, 73.83),
        "Margao":           (15.28, 73.96),
        "Vasco da Gama":    (15.40, 73.81),
        "Mapusa":           (15.59, 73.81),
        "Old Goa":          (15.50, 73.91),
        "Calangute":        (15.55, 73.76),
        "Anjuna":           (15.58, 73.74),
        "Mandovi":          (15.50, 73.85),
    },

    # ── JHARKHAND ──
    "jharkhand": {
        "Ranchi":           (23.34, 85.31),
        "Jamshedpur":       (22.80, 86.18),
        "Dhanbad":          (23.80, 86.44),
        "Bokaro":           (23.67, 86.15),
        "Deoghar":          (24.48, 86.69),
        "Hazaribagh":       (23.99, 85.36),
    },

    # ── CHHATTISGARH ──
    "chhattisgarh": {
        "Raipur":           (21.25, 81.63),
        "Bilaspur":         (22.08, 82.15),
        "Durg":             (21.19, 81.28),
        "Korba":            (22.35, 82.68),
        "Jagdalpur":        (19.08, 82.02),
        "Rajnandgaon":      (21.10, 81.03),
        "Mahanadi":         (21.50, 82.00),
    },

    # ── UTTARAKHAND ──
    "uttarakhand": {
        "Dehradun":         (30.32, 78.03),
        "Haridwar":         (29.95, 78.16),
        "Rishikesh":        (30.09, 78.27),
        "Nainital":         (29.38, 79.45),
        "Mussoorie":        (30.45, 78.07),
        "Almora":           (29.60, 79.66),
        "Badrinath":        (30.74, 79.49),
        "Kedarnath":        (30.73, 79.07),
        "Valley of Flowers": (30.73, 79.60),
        "Jim Corbett":      (29.53, 78.77),
        "Ganga":            (30.10, 78.30),
    },

    # ── HIMACHAL PRADESH ──
    "himachal_pradesh": {
        "Shimla":           (31.10, 77.17),
        "Manali":           (32.24, 77.19),
        "Dharamshala":      (32.22, 76.32),
        "Kullu":            (31.96, 77.11),
        "Dalhousie":        (32.54, 75.97),
        "Kasauli":          (30.90, 76.96),
        "Spiti":            (32.50, 78.00),
        "Kinnaur":          (31.58, 78.17),
        "Mandi":            (31.71, 76.93),
    },

    # ── JAMMU AND KASHMIR ──
    "jammu_and_kashmir": {
        "Srinagar":         (34.08, 74.80),
        "Jammu":            (32.73, 74.87),
        "Gulmarg":          (34.05, 74.38),
        "Pahalgam":         (34.02, 75.32),
        "Sonamarg":         (34.30, 75.30),
        "Dal Lake":         (34.10, 74.85),
        "Vaishno Devi":     (33.03, 74.95),
    },

    # ── ASSAM ──
    "assam": {
        "Guwahati":         (26.14, 91.74),
        "Dispur":           (26.14, 91.79),
        "Jorhat":           (26.75, 94.21),
        "Dibrugarh":        (27.47, 94.91),
        "Silchar":          (24.83, 92.80),
        "Tezpur":           (26.63, 92.80),
        "Nagaon":           (26.35, 92.68),
        "Kaziranga":        (26.58, 93.17),
        "Majuli":           (26.95, 94.17),
        "Brahmaputra":      (26.50, 93.00),
    },

    # ── HARYANA ──
    "haryana": {
        "Chandigarh":       (30.73, 76.78),
        "Gurugram":         (28.46, 77.03),
        "Gurgaon":          (28.46, 77.03),
        "Faridabad":        (28.41, 77.31),
        "Ambala":           (30.38, 76.78),
        "Panipat":          (29.39, 76.97),
        "Karnal":           (29.69, 76.99),
        "Hisar":            (29.15, 75.72),
        "Rohtak":           (28.89, 76.57),
        "Kurukshetra":      (29.97, 76.84),
        "Yamuna":           (28.80, 77.20),
    },

    # ══════════════════════════════════════════════
    # NORTHEAST STATES
    # ══════════════════════════════════════════════

    "arunachal_pradesh": {
        "Itanagar":         (27.10, 93.62),
        "Tawang":           (27.59, 91.87),
        "Ziro":             (27.63, 93.83),
        "Pasighat":         (28.07, 95.33),
        "Along":            (28.17, 94.80),
        "Bomdila":          (27.26, 92.42),
        "Namdapha":         (27.49, 96.39),
        "Sela Pass":        (27.50, 92.10),
        "Brahmaputra":      (27.50, 94.00),
    },

    "manipur": {
        "Imphal":           (24.82, 93.95),
        "Churachandpur":    (24.33, 93.68),
        "Thoubal":          (24.63, 94.00),
        "Bishnupur":        (24.63, 93.78),
        "Ukhrul":           (25.12, 94.37),
        "Loktak Lake":      (24.55, 93.80),
        "Kangla Fort":      (24.80, 93.95),
    },

    "meghalaya": {
        "Shillong":         (25.57, 91.88),
        "Tura":             (25.51, 90.22),
        "Cherrapunji":      (25.30, 91.70),
        "Sohra":            (25.30, 91.70),
        "Mawsynram":        (25.30, 91.58),
        "Jowai":            (25.45, 92.20),
        "Dawki":            (25.19, 92.01),
        "Nongpoh":          (25.90, 91.87),
        "Living Root Bridges": (25.30, 91.70),
    },

    "mizoram": {
        "Aizawl":           (23.73, 92.72),
        "Lunglei":          (22.88, 92.75),
        "Champhai":         (23.47, 93.33),
        "Serchhip":         (23.30, 92.85),
        "Kolasib":          (24.22, 92.68),
        "Saiha":            (22.49, 92.98),
        "Blue Mountain":    (23.20, 92.90),
    },

    "nagaland": {
        "Kohima":           (25.67, 94.12),
        "Dimapur":          (25.90, 93.73),
        "Mokokchung":       (26.32, 94.52),
        "Tuensang":         (26.27, 94.83),
        "Mon":              (26.72, 95.00),
        "Wokha":            (26.10, 94.27),
        "Zunheboto":        (25.97, 94.52),
        "Hornbill Festival": (25.67, 94.12),
    },

    "sikkim": {
        "Gangtok":          (27.33, 88.61),
        "Namchi":           (27.17, 88.35),
        "Pelling":          (27.30, 88.23),
        "Ravangla":         (27.31, 88.36),
        "Lachung":          (27.70, 88.74),
        "Yuksom":           (27.37, 88.22),
        "Kanchenjunga":     (27.70, 88.15),
        "Tsomgo Lake":      (27.37, 88.77),
        "Nathula Pass":     (27.39, 88.83),
    },

    "tripura": {
        "Agartala":         (23.83, 91.28),
        "Udaipur":          (23.53, 91.48),
        "Dharmanagar":      (24.38, 92.17),
        "Kailashahar":      (24.33, 92.00),
        "Ambassa":          (23.92, 91.85),
        "Neermahal":        (23.50, 91.40),
        "Unakoti":          (24.32, 92.08),
    },

    # ══════════════════════════════════════════════
    # UNION TERRITORIES
    # ══════════════════════════════════════════════

    "andaman_nicobar": {
        "Port Blair":       (11.67, 92.73),
        "Havelock Island":  (12.02, 92.98),
        "Neil Island":      (11.83, 93.04),
        "Cellular Jail":    (11.69, 92.75),
        "Ross Island":      (11.68, 92.77),
        "Baratang":         (12.07, 92.76),
        "Diglipur":         (13.26, 93.00),
        "Car Nicobar":      (9.15, 92.77),
        "Great Nicobar":    (7.00, 93.88),
        "Indira Point":     (6.75, 93.84),
    },

    "chandigarh": {
        "Chandigarh":       (30.73, 76.78),
        "Rock Garden":      (30.75, 76.81),
        "Sukhna Lake":      (30.74, 76.82),
        "Capitol Complex":  (30.76, 76.80),
        "Rose Garden":      (30.73, 76.78),
        "Sector 17":        (30.74, 76.78),
    },

    "dadra_daman_diu": {
        "Daman":            (20.42, 72.84),
        "Diu":              (20.71, 70.98),
        "Silvassa":         (20.27, 73.00),
        "Dadra":            (20.33, 73.07),
        "Nagar Haveli":     (20.27, 73.00),
    },

    "delhi": {
        "New Delhi":        (28.61, 77.21),
        "Delhi":            (28.65, 77.23),
        "Old Delhi":        (28.66, 77.23),
        "Red Fort":         (28.66, 77.24),
        "India Gate":       (28.61, 77.23),
        "Qutub Minar":      (28.52, 77.19),
        "Lotus Temple":     (28.55, 77.26),
        "Humayun's Tomb":   (28.59, 77.25),
        "Chandni Chowk":    (28.66, 77.23),
        "Connaught Place":  (28.63, 77.22),
        "Rashtrapati Bhavan": (28.62, 77.20),
        "Parliament House": (28.62, 77.21),
        "Jantar Mantar":    (28.63, 77.22),
        "Yamuna":           (28.63, 77.24),
    },

    "ladakh": {
        "Leh":              (34.16, 77.58),
        "Kargil":           (34.55, 76.13),
        "Pangong Lake":     (33.76, 78.65),
        "Nubra Valley":     (34.68, 77.57),
        "Zanskar":          (33.50, 76.85),
        "Khardung La":      (34.28, 77.60),
        "Tso Moriri":       (32.90, 78.32),
        "Magnetic Hill":    (34.17, 77.53),
        "Shanti Stupa":     (34.16, 77.58),
        "Indus":            (34.20, 77.60),
    },

    "lakshadweep": {
        "Kavaratti":        (10.57, 72.64),
        "Agatti":           (10.87, 72.20),
        "Minicoy":          (8.29, 73.05),
        "Bangaram":         (10.94, 72.29),
        "Andrott":          (10.82, 73.67),
        "Kalpeni":          (10.08, 73.64),
        "Kadmat":           (11.23, 72.78),
    },

    "puducherry": {
        "Puducherry":       (11.93, 79.83),
        "Pondicherry":      (11.93, 79.83),
        "Karaikal":         (10.92, 79.84),
        "Mahe":             (11.70, 75.53),
        "Yanam":            (16.73, 82.22),
        "Auroville":        (12.01, 79.81),
        "Promenade Beach":  (11.93, 79.84),
        "French Quarter":   (11.93, 79.83),
    },
}


# ══════════════════════════════════════════════
# COORDINATE CONVERSION — lat/lon → image (x%, y%)
# ══════════════════════════════════════════════

def _latlon_to_pct(lat: float, lon: float, bounds: dict, pad_frac: float = 0.08) -> tuple[float, float]:
    """Convert real lat/lon to (x%, y%) on the state map image.

    The map image was generated with padding around the bounding box.
    x% is horizontal (left=0, right=100), y% is vertical (top=0, bottom=100).
    Note: latitude is inverted (higher lat = higher on map = lower y%).
    """
    min_lon = bounds["min_lon"]
    max_lon = bounds["max_lon"]
    min_lat = bounds["min_lat"]
    max_lat = bounds["max_lat"]

    lon_range = max_lon - min_lon or 0.01
    lat_range = max_lat - min_lat or 0.01

    # Add the same padding fraction used during image generation
    pad_lon = lon_range * pad_frac
    pad_lat = lat_range * pad_frac

    eff_min_lon = min_lon - pad_lon
    eff_max_lon = max_lon + pad_lon
    eff_min_lat = min_lat - pad_lat
    eff_max_lat = max_lat + pad_lat

    eff_lon_range = eff_max_lon - eff_min_lon
    eff_lat_range = eff_max_lat - eff_min_lat

    x_pct = ((lon - eff_min_lon) / eff_lon_range) * 100
    y_pct = ((eff_max_lat - lat) / eff_lat_range) * 100  # inverted: top=max_lat

    # Clamp to [2, 98] to keep markers inside the image
    x_pct = max(2, min(98, x_pct))
    y_pct = max(2, min(98, y_pct))

    return (round(x_pct, 1), round(y_pct, 1))


# ══════════════════════════════════════════════
# REVERSE LOOKUP: location → state
# ══════════════════════════════════════════════

_LOCATION_TO_STATE: dict[str, str] = {}


def _build_location_to_state():
    """Populate the reverse lookup from STATE_LOCATIONS (run once)."""
    if _LOCATION_TO_STATE:
        return
    key_to_display: dict[str, str] = {}
    for display, key in STATE_KEY_MAP.items():
        if key not in key_to_display:
            key_to_display[key] = display
    for state_key, locs in STATE_LOCATIONS.items():
        display = key_to_display.get(state_key, state_key)
        for loc_name in locs:
            lower = loc_name.lower()
            if lower not in _LOCATION_TO_STATE:
                _LOCATION_TO_STATE[lower] = display


def infer_state(question_dict: dict) -> str:
    """Try to figure out the state from a question dict.

    Checks (in order):
      1. Explicit "state" field in the JSON
      2. The "location" field IS itself a state/UT name
      3. Scan question text and explanation for state/UT names (longest first)
      4. Reverse lookup: location is a city/landmark → map to its state
      5. Last resort: scan answer options for state names
    Returns the state display name or empty string.
    """
    # 1. Explicit field
    state = question_dict.get("state", "").strip()
    if state and get_state_key(state):
        return state

    loc = question_dict.get("location", "").strip()

    # 2. Location IS a state/UT name itself
    if loc and get_state_key(loc):
        return loc

    # 3. Scan question text + explanation for state/UT names
    all_names = sorted(STATE_KEY_MAP.keys(), key=len, reverse=True)
    primary_text = " ".join([
        question_dict.get("question", ""),
        question_dict.get("explanation", ""),
    ]).lower()

    for name in all_names:
        if name.lower() in primary_text:
            return name

    _build_location_to_state()

    # 4. Reverse city→state lookup
    if loc:
        found = _LOCATION_TO_STATE.get(loc.lower())
        if found:
            return found

    # 5. Last resort: check answer options
    options_text = " ".join(question_dict.get("options", [])).lower()
    for name in all_names:
        if name.lower() in options_text:
            return name

    return ""


# ══════════════════════════════════════════════
# PUBLIC API
# ══════════════════════════════════════════════

def get_state_key(state_name: str) -> str | None:
    """Convert a state display name to its file-system key."""
    if not state_name:
        return None
    if state_name in STATE_KEY_MAP:
        return STATE_KEY_MAP[state_name]
    lower = state_name.lower().strip()
    for display, key in STATE_KEY_MAP.items():
        if display.lower() == lower:
            return key
    for display, key in STATE_KEY_MAP.items():
        if lower in display.lower() or display.lower() in lower:
            return key
    return None


def get_state_location_coords(
    state_key: str, location_name: str
) -> tuple[float, float] | None:
    """Look up image-percentage coordinates for a location within a state map.

    Returns (x%, y%) on the state map image, or (50, 50) as fallback.
    """
    _load_bounds()

    if not state_key or not location_name:
        return None

    bounds = _BOUNDS.get(state_key)
    if not bounds:
        return (50, 50)

    locs = STATE_LOCATIONS.get(state_key, {})

    # Find the lat/lon for this location
    latlon = None

    if location_name in locs:
        latlon = locs[location_name]
    else:
        lower = location_name.lower().strip()
        for key, coords in locs.items():
            if key.lower() == lower:
                latlon = coords
                break
        if not latlon:
            for key, coords in locs.items():
                if lower in key.lower() or key.lower() in lower:
                    latlon = coords
                    break

    if latlon:
        return _latlon_to_pct(latlon[0], latlon[1], bounds)

    return (50, 50)


def render_state_map_with_marker(
    state_name: str, location_name: str, label: str = ""
) -> str | None:
    """Return HTML for a state map with a pulsing marker at the given location.

    Returns None if the state map image doesn't exist.
    """
    state_key = get_state_key(state_name)
    if not state_key:
        return None

    state_b64 = _get_state_b64(state_key)
    if not state_b64:
        return None

    coords = get_state_location_coords(state_key, location_name)
    if not coords:
        coords = (50, 50)

    x, y = coords
    display_label = label or location_name
    display_state = state_name

    return f"""
    <div style="position:relative;display:inline-block;width:100%;max-width:380px;
                margin:0.5rem auto;border-radius:20px;overflow:hidden;
                box-shadow:0 4px 20px rgba(0,0,0,0.12);background:white;">
        <img src="{state_b64}" style="width:100%;display:block;border-radius:20px;" />
        <!-- State name header -->
        <div style="position:absolute;top:6px;left:50%;transform:translateX(-50%);z-index:12;
                    background:rgba(240,147,251,0.9);color:white;padding:4px 14px;border-radius:12px;
                    font-size:0.75rem;font-weight:700;white-space:nowrap;
                    box-shadow:0 2px 8px rgba(0,0,0,0.15);">
            🗺️ {display_state}
        </div>
        <!-- Pulsing marker -->
        <div style="position:absolute;left:{x}%;top:{y}%;transform:translate(-50%,-50%);z-index:10;">
            <div style="
                width:18px;height:18px;
                background:#ef4444;
                border:3px solid white;
                border-radius:50%;
                box-shadow:0 0 0 3px #ef4444, 0 2px 8px rgba(0,0,0,0.3);
                animation: state-pulse 1.5s ease-in-out infinite;
            "></div>
        </div>
        <!-- Location label -->
        <div style="position:absolute;left:{x}%;top:{min(y + 5, 92)}%;transform:translateX(-50%);z-index:10;
                    background:rgba(0,0,0,0.8);color:white;padding:3px 10px;border-radius:8px;
                    font-size:0.65rem;font-weight:600;white-space:nowrap;
                    box-shadow:0 2px 6px rgba(0,0,0,0.2);">
            📍 {display_label}
        </div>
    </div>
    <style>
        @keyframes state-pulse {{
            0%   {{ box-shadow: 0 0 0 3px #ef4444, 0 0 0 6px rgba(239,68,68,0.4); }}
            50%  {{ box-shadow: 0 0 0 5px #ef4444, 0 0 0 14px rgba(239,68,68,0.15); }}
            100% {{ box-shadow: 0 0 0 3px #ef4444, 0 0 0 6px rgba(239,68,68,0.4); }}
        }}
    </style>
    """
