"""
State-level map data for Rakesh's US-focused GK app.

Uses REAL geographic data:
  - State map images are generated from actual GeoJSON boundaries (matplotlib).
  - Location positions use real latitude/longitude coordinates.
  - Bounding-box data converts lat/lon to image (x%, y%) at render time.
"""

import base64
import json
import os

_US_STATE_MAPS_DIR = os.path.join(os.path.dirname(__file__), "us_state_maps")
_US_BOUNDS_PATH = os.path.join(os.path.dirname(__file__), "us_state_bounds.json")
_STATE_B64_CACHE: dict[str, str] = {}
_BOUNDS: dict[str, dict] = {}


def _load_bounds():
    """Load state bounding boxes from JSON (generated by generate_state_maps_geo.py)."""
    global _BOUNDS
    if _BOUNDS:
        return
    if os.path.exists(_US_BOUNDS_PATH):
        with open(_US_BOUNDS_PATH) as f:
            _BOUNDS = json.load(f)


def _get_state_b64(state_key: str) -> str | None:
    """Load a state map as a base64 data URI (cached)."""
    if state_key in _STATE_B64_CACHE:
        return _STATE_B64_CACHE[state_key]
    path = os.path.join(_US_STATE_MAPS_DIR, f"{state_key}.png")
    if not os.path.exists(path):
        return None
    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode()
    uri = f"data:image/png;base64,{encoded}"
    _STATE_B64_CACHE[state_key] = uri
    return uri


# ── Map display names of states / territories to file-system keys ──
STATE_KEY_MAP: dict[str, str] = {
    # ── 50 States ──
    "Alabama": "alabama",
    "Alaska": "alaska",
    "Arizona": "arizona",
    "Arkansas": "arkansas",
    "California": "california",
    "Colorado": "colorado",
    "Connecticut": "connecticut",
    "Delaware": "delaware",
    "Florida": "florida",
    "Georgia": "georgia",
    "Hawaii": "hawaii",
    "Idaho": "idaho",
    "Illinois": "illinois",
    "Indiana": "indiana",
    "Iowa": "iowa",
    "Kansas": "kansas",
    "Kentucky": "kentucky",
    "Louisiana": "louisiana",
    "Maine": "maine",
    "Maryland": "maryland",
    "Massachusetts": "massachusetts",
    "Michigan": "michigan",
    "Minnesota": "minnesota",
    "Mississippi": "mississippi",
    "Missouri": "missouri",
    "Montana": "montana",
    "Nebraska": "nebraska",
    "Nevada": "nevada",
    "New Hampshire": "new_hampshire",
    "New Jersey": "new_jersey",
    "New Mexico": "new_mexico",
    "New York": "new_york",
    "North Carolina": "north_carolina",
    "North Dakota": "north_dakota",
    "Ohio": "ohio",
    "Oklahoma": "oklahoma",
    "Oregon": "oregon",
    "Pennsylvania": "pennsylvania",
    "Rhode Island": "rhode_island",
    "South Carolina": "south_carolina",
    "South Dakota": "south_dakota",
    "Tennessee": "tennessee",
    "Texas": "texas",
    "Utah": "utah",
    "Vermont": "vermont",
    "Virginia": "virginia",
    "Washington": "washington",
    "West Virginia": "west_virginia",
    "Wisconsin": "wisconsin",
    "Wyoming": "wyoming",

    # ── District of Columbia ──
    "District of Columbia": "district_of_columbia",
    "DC": "district_of_columbia",
    "D.C.": "district_of_columbia",
    "Washington D.C.": "district_of_columbia",
    "Washington DC": "district_of_columbia",

    # ── Territories ──
    "Puerto Rico": "puerto_rico",
}


# ══════════════════════════════════════════════════════════════════
# REAL LAT/LON COORDINATES for cities, rivers, landmarks, etc.
# Format: (latitude, longitude)
# These are actual geographic coordinates.
# ══════════════════════════════════════════════════════════════════

STATE_LOCATIONS: dict[str, dict[str, tuple[float, float]]] = {
    "alabama": {
        "Montgomery": (32.38, -86.30),
        "Birmingham": (33.52, -86.80),
        "Huntsville": (34.73, -86.59),
        "Mobile": (30.69, -88.04),
    },
    "alaska": {
        "Juneau": (58.30, -134.42),
        "Anchorage": (61.22, -149.90),
        "Fairbanks": (64.84, -147.72),
        "Denali": (63.07, -151.01),
    },
    "arizona": {
        "Phoenix": (33.45, -112.07),
        "Tucson": (32.22, -110.93),
        "Grand Canyon": (36.10, -112.11),
        "Sedona": (34.87, -111.76),
        "Flagstaff": (35.20, -111.65),
    },
    "arkansas": {
        "Little Rock": (34.75, -92.29),
        "Fort Smith": (35.39, -94.40),
        "Hot Springs": (34.50, -93.05),
    },
    "california": {
        "Sacramento": (38.58, -121.49),
        "Los Angeles": (34.05, -118.24),
        "San Francisco": (37.77, -122.42),
        "San Diego": (32.72, -117.16),
        "Yosemite": (37.87, -119.54),
        "Hollywood": (34.09, -118.33),
        "Silicon Valley": (37.39, -122.03),
    },
    "colorado": {
        "Denver": (39.74, -104.99),
        "Colorado Springs": (38.83, -104.82),
        "Boulder": (40.01, -105.27),
        "Aspen": (39.19, -106.82),
        "Rocky Mountain NP": (40.34, -105.68),
    },
    "connecticut": {
        "Hartford": (41.76, -72.68),
        "New Haven": (41.31, -72.92),
        "Yale University": (41.31, -72.93),
    },
    "delaware": {
        "Dover": (39.16, -75.52),
        "Wilmington": (39.74, -75.55),
    },
    "district_of_columbia": {
        "Washington D.C.": (38.91, -77.04),
        "White House": (38.90, -77.04),
        "Capitol": (38.89, -77.01),
        "Lincoln Memorial": (38.89, -77.05),
        "Smithsonian": (38.89, -77.03),
    },
    "florida": {
        "Tallahassee": (30.44, -84.28),
        "Miami": (25.76, -80.19),
        "Orlando": (28.54, -81.38),
        "Tampa": (27.95, -82.46),
        "Jacksonville": (30.33, -81.66),
        "Kennedy Space Center": (28.57, -80.65),
        "Everglades": (25.29, -80.90),
        "Key West": (24.56, -81.78),
    },
    "georgia": {
        "Atlanta": (33.75, -84.39),
        "Savannah": (32.08, -81.09),
        "Augusta": (33.47, -81.97),
    },
    "hawaii": {
        "Honolulu": (21.31, -157.86),
        "Maui": (20.80, -156.32),
        "Pearl Harbor": (21.36, -157.95),
    },
    "idaho": {
        "Boise": (43.62, -116.21),
        "Sun Valley": (43.70, -114.35),
        "Craters of the Moon": (43.42, -113.52),
    },
    "illinois": {
        "Springfield": (39.80, -89.65),
        "Chicago": (41.88, -87.63),
        "Peoria": (40.69, -89.59),
    },
    "indiana": {
        "Indianapolis": (39.77, -86.16),
        "Fort Wayne": (41.08, -85.14),
        "Gary": (41.59, -87.35),
    },
    "iowa": {
        "Des Moines": (41.59, -93.62),
        "Cedar Rapids": (41.98, -91.67),
        "Iowa City": (41.66, -91.53),
    },
    "kansas": {
        "Topeka": (39.05, -95.68),
        "Wichita": (37.69, -97.34),
        "Kansas City": (39.11, -94.63),
        "Dodge City": (37.75, -100.02),
    },
    "kentucky": {
        "Frankfort": (38.20, -84.87),
        "Louisville": (38.25, -85.76),
        "Lexington": (38.04, -84.50),
        "Mammoth Cave": (37.19, -86.10),
    },
    "louisiana": {
        "Baton Rouge": (30.45, -91.19),
        "New Orleans": (29.95, -90.07),
        "Shreveport": (32.53, -93.75),
    },
    "maine": {
        "Augusta": (44.31, -69.78),
        "Portland": (43.66, -70.26),
        "Acadia": (44.34, -68.21),
        "Bar Harbor": (44.39, -68.20),
    },
    "maryland": {
        "Annapolis": (38.97, -76.49),
        "Baltimore": (39.29, -76.61),
        "Chesapeake Bay": (38.50, -76.30),
    },
    "massachusetts": {
        "Boston": (42.36, -71.06),
        "Cambridge": (42.37, -71.11),
        "Plymouth": (41.96, -70.67),
        "Cape Cod": (41.67, -70.30),
        "Harvard": (42.37, -71.12),
        "MIT": (42.36, -71.09),
    },
    "michigan": {
        "Lansing": (42.73, -84.56),
        "Detroit": (42.33, -83.05),
        "Ann Arbor": (42.28, -83.74),
        "Mackinac Island": (45.85, -84.62),
    },
    "minnesota": {
        "St. Paul": (44.94, -93.09),
        "Minneapolis": (44.98, -93.27),
        "Duluth": (46.79, -92.10),
    },
    "mississippi": {
        "Jackson": (32.30, -90.18),
        "Biloxi": (30.40, -88.89),
        "Vicksburg": (32.35, -90.88),
    },
    "missouri": {
        "Jefferson City": (38.58, -92.17),
        "St. Louis": (38.63, -90.20),
        "Kansas City": (39.10, -94.58),
        "Gateway Arch": (38.63, -90.19),
        "Branson": (36.64, -93.22),
    },
    "montana": {
        "Helena": (46.59, -112.04),
        "Billings": (45.78, -108.50),
        "Glacier NP": (48.70, -113.80),
        "Yellowstone": (44.43, -110.59),
    },
    "nebraska": {
        "Lincoln": (40.81, -96.70),
        "Omaha": (41.26, -95.94),
    },
    "nevada": {
        "Carson City": (39.16, -119.77),
        "Las Vegas": (36.17, -115.14),
        "Reno": (39.53, -119.81),
        "Area 51": (37.24, -115.81),
        "Hoover Dam": (36.02, -114.74),
    },
    "new_hampshire": {
        "Concord": (43.21, -71.54),
        "Manchester": (42.99, -71.46),
        "White Mountains": (44.27, -71.30),
    },
    "new_jersey": {
        "Trenton": (40.22, -74.76),
        "Newark": (40.74, -74.17),
        "Atlantic City": (39.36, -74.42),
        "Princeton": (40.35, -74.66),
    },
    "new_mexico": {
        "Santa Fe": (35.69, -105.94),
        "Albuquerque": (35.08, -106.65),
        "Roswell": (33.39, -104.52),
        "Carlsbad Caverns": (32.17, -104.44),
    },
    "new_york": {
        "Albany": (42.65, -73.76),
        "New York City": (40.71, -74.01),
        "Buffalo": (42.89, -78.88),
        "Niagara Falls": (43.08, -79.07),
        "Statue of Liberty": (40.69, -74.04),
        "Times Square": (40.76, -73.99),
    },
    "north_carolina": {
        "Raleigh": (35.78, -78.64),
        "Charlotte": (35.23, -80.84),
        "Asheville": (35.60, -82.55),
        "Outer Banks": (35.56, -75.46),
    },
    "north_dakota": {
        "Bismarck": (46.81, -100.78),
        "Fargo": (46.88, -96.79),
        "Theodore Roosevelt NP": (46.97, -103.45),
    },
    "ohio": {
        "Columbus": (39.96, -82.99),
        "Cleveland": (41.50, -81.69),
        "Cincinnati": (39.10, -84.51),
        "Rock & Roll Hall": (41.51, -81.70),
    },
    "oklahoma": {
        "Oklahoma City": (35.47, -97.52),
        "Tulsa": (36.15, -95.99),
    },
    "oregon": {
        "Salem": (44.94, -123.03),
        "Portland": (45.52, -122.68),
        "Crater Lake": (42.87, -122.17),
        "Eugene": (44.05, -123.09),
    },
    "pennsylvania": {
        "Harrisburg": (40.27, -76.88),
        "Philadelphia": (39.95, -75.17),
        "Pittsburgh": (40.44, -80.00),
        "Gettysburg": (39.83, -77.23),
        "Independence Hall": (39.95, -75.15),
    },
    "rhode_island": {
        "Providence": (41.82, -71.41),
        "Newport": (41.49, -71.31),
    },
    "south_carolina": {
        "Columbia": (34.00, -81.03),
        "Charleston": (32.78, -79.93),
        "Myrtle Beach": (33.69, -78.89),
    },
    "south_dakota": {
        "Pierre": (44.37, -100.35),
        "Rapid City": (44.08, -103.23),
        "Mount Rushmore": (43.88, -103.46),
        "Badlands": (43.75, -102.50),
    },
    "tennessee": {
        "Nashville": (36.16, -86.78),
        "Memphis": (35.15, -90.05),
        "Knoxville": (35.96, -83.92),
        "Great Smoky Mtns": (35.61, -83.53),
        "Graceland": (35.05, -90.02),
    },
    "texas": {
        "Austin": (30.27, -97.74),
        "Houston": (29.76, -95.37),
        "Dallas": (32.78, -96.80),
        "San Antonio": (29.42, -98.49),
        "El Paso": (31.76, -106.44),
        "The Alamo": (29.43, -98.49),
        "Big Bend": (29.25, -103.25),
    },
    "utah": {
        "Salt Lake City": (40.76, -111.89),
        "Moab": (38.57, -109.55),
        "Zion": (37.30, -113.05),
        "Arches": (38.73, -109.59),
        "Bryce Canyon": (37.63, -112.17),
    },
    "vermont": {
        "Montpelier": (44.26, -72.58),
        "Burlington": (44.48, -73.21),
        "Stowe": (44.47, -72.69),
    },
    "virginia": {
        "Richmond": (37.54, -77.44),
        "Virginia Beach": (36.85, -75.98),
        "Arlington": (38.88, -77.10),
        "Mount Vernon": (38.71, -77.09),
        "Charlottesville": (38.03, -78.48),
        "Jamestown": (37.21, -76.78),
    },
    "washington": {
        "Olympia": (47.04, -122.90),
        "Seattle": (47.61, -122.33),
        "Spokane": (47.66, -117.43),
        "Mount Rainier": (46.85, -121.76),
        "Space Needle": (47.62, -122.35),
    },
    "west_virginia": {
        "Charleston": (38.35, -81.63),
        "Morgantown": (39.63, -79.96),
        "New River Gorge": (38.07, -81.08),
    },
    "wisconsin": {
        "Madison": (43.07, -89.40),
        "Milwaukee": (43.04, -87.91),
        "Green Bay": (44.51, -88.02),
    },
    "wyoming": {
        "Cheyenne": (41.14, -104.82),
        "Yellowstone": (44.43, -110.59),
        "Grand Teton": (43.74, -110.80),
        "Jackson Hole": (43.48, -110.76),
    },
    "puerto_rico": {
        "San Juan": (18.47, -66.11),
        "Ponce": (18.01, -66.61),
        "El Yunque": (18.29, -65.79),
    },
}


# ══════════════════════════════════════════════
# COORDINATE CONVERSION — lat/lon → image (x%, y%)
# ══════════════════════════════════════════════

def _latlon_to_pct(lat: float, lon: float, bounds: dict, pad_frac: float = 0.08) -> tuple[float, float]:
    """Convert real lat/lon to (x%, y%) on the state map image.

    The map image was generated with padding around the bounding box.
    x% is horizontal (left=0, right=100), y% is vertical (top=0, bottom=100).
    Note: latitude is inverted (higher lat = higher on map = lower y%).
    """
    min_lon = bounds["min_lon"]
    max_lon = bounds["max_lon"]
    min_lat = bounds["min_lat"]
    max_lat = bounds["max_lat"]

    lon_range = max_lon - min_lon or 0.01
    lat_range = max_lat - min_lat or 0.01

    # Add the same padding fraction used during image generation
    pad_lon = lon_range * pad_frac
    pad_lat = lat_range * pad_frac

    eff_min_lon = min_lon - pad_lon
    eff_max_lon = max_lon + pad_lon
    eff_min_lat = min_lat - pad_lat
    eff_max_lat = max_lat + pad_lat

    eff_lon_range = eff_max_lon - eff_min_lon
    eff_lat_range = eff_max_lat - eff_min_lat

    x_pct = ((lon - eff_min_lon) / eff_lon_range) * 100
    y_pct = ((eff_max_lat - lat) / eff_lat_range) * 100  # inverted: top=max_lat

    # Clamp to [2, 98] to keep markers inside the image
    x_pct = max(2, min(98, x_pct))
    y_pct = max(2, min(98, y_pct))

    return (round(x_pct, 1), round(y_pct, 1))


# ══════════════════════════════════════════════
# REVERSE LOOKUP: location → state
# ══════════════════════════════════════════════

_LOCATION_TO_STATE: dict[str, str] = {}


def _build_location_to_state():
    """Populate the reverse lookup from STATE_LOCATIONS (run once)."""
    if _LOCATION_TO_STATE:
        return
    key_to_display: dict[str, str] = {}
    for display, key in STATE_KEY_MAP.items():
        if key not in key_to_display:
            key_to_display[key] = display
    for state_key, locs in STATE_LOCATIONS.items():
        display = key_to_display.get(state_key, state_key)
        for loc_name in locs:
            lower = loc_name.lower()
            if lower not in _LOCATION_TO_STATE:
                _LOCATION_TO_STATE[lower] = display


def infer_state(question_dict: dict) -> str:
    """Try to figure out the state from a question dict.

    Checks (in order):
      1. Explicit "state" field in the JSON
      2. The "location" field IS itself a state/territory name
      3. Scan question text and explanation for state/territory names (longest first)
      4. Reverse lookup: location is a city/landmark → map to its state
      5. Last resort: scan answer options for state names
    Returns the state display name or empty string.
    """
    # 1. Explicit field
    state = question_dict.get("state", "").strip()
    if state and get_state_key(state):
        return state

    loc = question_dict.get("location", "").strip()

    # 2. Location IS a state/territory name itself
    if loc and get_state_key(loc):
        return loc

    # 3. Scan question text + explanation for state/territory names
    all_names = sorted(STATE_KEY_MAP.keys(), key=len, reverse=True)
    primary_text = " ".join([
        question_dict.get("question", ""),
        question_dict.get("explanation", ""),
    ]).lower()

    for name in all_names:
        if name.lower() in primary_text:
            return name

    _build_location_to_state()

    # 4. Reverse city→state lookup
    if loc:
        found = _LOCATION_TO_STATE.get(loc.lower())
        if found:
            return found

    # 5. Last resort: check answer options
    options_text = " ".join(question_dict.get("options", [])).lower()
    for name in all_names:
        if name.lower() in options_text:
            return name

    return ""


# ══════════════════════════════════════════════
# PUBLIC API
# ══════════════════════════════════════════════

def get_state_key(state_name: str) -> str | None:
    """Convert a state display name to its file-system key."""
    if not state_name:
        return None
    if state_name in STATE_KEY_MAP:
        return STATE_KEY_MAP[state_name]
    lower = state_name.lower().strip()
    for display, key in STATE_KEY_MAP.items():
        if display.lower() == lower:
            return key
    for display, key in STATE_KEY_MAP.items():
        if lower in display.lower() or display.lower() in lower:
            return key
    return None


def get_state_location_coords(
    state_key: str, location_name: str
) -> tuple[float, float] | None:
    """Look up image-percentage coordinates for a location within a state map.

    Returns (x%, y%) on the state map image, or (50, 50) as fallback.
    """
    _load_bounds()

    if not state_key or not location_name:
        return None

    bounds = _BOUNDS.get(state_key)
    if not bounds:
        return (50, 50)

    locs = STATE_LOCATIONS.get(state_key, {})

    # Find the lat/lon for this location
    latlon = None

    if location_name in locs:
        latlon = locs[location_name]
    else:
        lower = location_name.lower().strip()
        for key, coords in locs.items():
            if key.lower() == lower:
                latlon = coords
                break
        if not latlon:
            for key, coords in locs.items():
                if lower in key.lower() or key.lower() in lower:
                    latlon = coords
                    break

    if latlon:
        return _latlon_to_pct(latlon[0], latlon[1], bounds)

    return (50, 50)


def render_state_map_with_marker(
    state_name: str, location_name: str, label: str = ""
) -> str | None:
    """Return HTML for a state map with a pulsing marker at the given location.

    Returns None if the state map image doesn't exist.
    US-themed styling: blue header badge (#3b82f6).
    """
    state_key = get_state_key(state_name)
    if not state_key:
        return None

    state_b64 = _get_state_b64(state_key)
    if not state_b64:
        return None

    coords = get_state_location_coords(state_key, location_name)
    if not coords:
        coords = (50, 50)

    x, y = coords
    display_label = label or location_name
    display_state = state_name

    return f"""
    <div style="position:relative;display:inline-block;width:100%;max-width:380px;
                margin:0.5rem auto;border-radius:20px;overflow:hidden;
                box-shadow:0 4px 20px rgba(0,0,0,0.12);background:white;">
        <img src="{state_b64}" style="width:100%;display:block;border-radius:20px;" />
        <!-- State name header (US blue theme) -->
        <div style="position:absolute;top:6px;left:50%;transform:translateX(-50%);z-index:12;
                    background:rgba(59,130,246,0.9);color:white;padding:4px 14px;border-radius:12px;
                    font-size:0.75rem;font-weight:700;white-space:nowrap;
                    box-shadow:0 2px 8px rgba(0,0,0,0.15);">
            🗺️ {display_state}
        </div>
        <!-- Pulsing marker -->
        <div style="position:absolute;left:{x}%;top:{y}%;transform:translate(-50%,-50%);z-index:10;">
            <div style="
                width:18px;height:18px;
                background:#ef4444;
                border:3px solid white;
                border-radius:50%;
                box-shadow:0 0 0 3px #ef4444, 0 2px 8px rgba(0,0,0,0.3);
                animation: us-state-pulse 1.5s ease-in-out infinite;
            "></div>
        </div>
        <!-- Location label -->
        <div style="position:absolute;left:{x}%;top:{min(y + 5, 92)}%;transform:translateX(-50%);z-index:10;
                    background:rgba(0,0,0,0.8);color:white;padding:3px 10px;border-radius:8px;
                    font-size:0.65rem;font-weight:600;white-space:nowrap;
                    box-shadow:0 2px 6px rgba(0,0,0,0.2);">
            📍 {display_label}
        </div>
    </div>
    <style>
        @keyframes us-state-pulse {{
            0%   {{ box-shadow: 0 0 0 3px #ef4444, 0 0 0 6px rgba(239,68,68,0.4); }}
            50%  {{ box-shadow: 0 0 0 5px #ef4444, 0 0 0 14px rgba(239,68,68,0.15); }}
            100% {{ box-shadow: 0 0 0 3px #ef4444, 0 0 0 6px rgba(239,68,68,0.4); }}
        }}
    </style>
    """
