"""UNIT_DATA entries for Harshit Biology Units 2–4 (Stage 2 & 3 seed source)."""

from __future__ import annotations

UNITS_234_DATA: dict[int, dict] = {
    2: {
        "meta": {
            "unit_id": 2,
            "chapter": 6,
            "pdf": "jesc106.pdf",
            "title": "Control and Coordination",
        },
        "activities": [
            {
                "id": "6.1",
                "title": "Taste with blocked nose",
                "summary": "Block nose while eating sugar — taste is reduced, showing smell contributes to flavour perception.",
                "concept_ids": ["u2_d2_c03", "u2_d2_c04", "u2_d2_c05"],
                "stage2_day": 17,
            },
            {
                "id": "6.2",
                "title": "Phototropism in bean seedlings",
                "summary": "Bean seeds in flask bend toward light; turning flask shows new growth follows light direction.",
                "concept_ids": ["u2_d8_c02", "u2_d8_c03", "u2_d7_c06"],
                "stage2_day": 18,
            },
            {
                "id": "6.3",
                "title": "Identify endocrine glands",
                "summary": "Locate pituitary, thyroid, adrenal, pancreas, and gonads on Fig 6.7 diagrams.",
                "concept_ids": ["u2_d9_c05", "u2_d10_c05", "u2_d10_c10"],
                "stage2_day": 19,
            },
            {
                "id": "6.4",
                "title": "Complete hormone Table 6.1",
                "summary": "Match hormones to endocrine glands and functions — growth hormone, thyroxin, insulin, etc.",
                "concept_ids": ["u2_d10_c05", "u2_d10_c06", "u2_d10_c10"],
                "stage2_day": 20,
            },
        ],
        "exercise_mcqs": [
            {
                "num": 1,
                "question": "Which of the following is a plant hormone?",
                "options": ["Insulin", "Thyroxin", "Oestrogen", "Cytokinin"],
                "answer": 3,
                "explanation": "Cytokinin promotes cell division in plants. Insulin, thyroxin, and oestrogen are animal hormones.",
                "misconception": "plant_animal_hormone_swap",
                "source": "NCERT Ch 6 Exercises Q1",
            },
            {
                "num": 2,
                "question": "The gap between two neurons is called a",
                "options": ["dendrite", "synapse", "axon", "impulse"],
                "answer": 1,
                "explanation": "The synapse is the junction between two neurons where chemical neurotransmitters cross the gap.",
                "misconception": "synapse_axon_confusion",
                "source": "NCERT Ch 6 Exercises Q2",
            },
            {
                "num": 3,
                "question": "The brain is responsible for",
                "options": [
                    "thinking",
                    "regulating the heart beat",
                    "balancing the body",
                    "all of the above",
                ],
                "answer": 3,
                "explanation": "Fore-brain handles thinking; medulla regulates heartbeat; cerebellum maintains balance — all are brain functions.",
                "misconception": "cerebellum_cerebrum_swap",
                "source": "NCERT Ch 6 Exercises Q3",
            },
        ],
        "intext_samples": [
            {
                "ref": "Section 6.1 — reflex action",
                "question": "What is the difference between a reflex action and walking?",
                "options": [
                    "Reflex is voluntary; walking is involuntary",
                    "Reflex is automatic without thinking; walking is a voluntary action",
                    "Both are controlled only by the spinal cord",
                    "Walking is faster than a reflex action",
                ],
                "answer": 1,
                "explanation": "Reflex actions are sudden and automatic; walking involves conscious decision by the brain.",
                "misconception": "reflex_brain_confusion",
                "source": "NCERT Ch 6 Intext",
            },
            {
                "ref": "Section 6.1 — synapse",
                "question": "What happens at the synapse between two neurons?",
                "options": [
                    "Electrical impulse jumps directly across the gap",
                    "Chemicals cross the gap and trigger impulse in the next neuron",
                    "The axon splits into two dendrites",
                    "The impulse is stored permanently in the gap",
                ],
                "answer": 1,
                "explanation": "At the synapse, electrical impulse triggers release of chemicals that diffuse across and start an impulse in the next neuron.",
                "misconception": "synapse_axon_confusion",
                "source": "NCERT Ch 6 Intext",
            },
            {
                "ref": "Section 6.1 — cerebellum",
                "question": "Which part of the brain maintains posture and equilibrium of the body?",
                "options": ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"],
                "answer": 1,
                "explanation": "The cerebellum in the hind-brain controls posture, balance, and precision of voluntary actions.",
                "misconception": "cerebellum_cerebrum_swap",
                "source": "NCERT Ch 6 Intext",
            },
            {
                "ref": "Section 6.2 — plant hormones",
                "question": "Give an example of a plant hormone that promotes growth.",
                "options": ["Insulin", "Auxin", "Adrenaline", "Thyroxin"],
                "answer": 1,
                "explanation": "Auxin promotes cell elongation and is involved in phototropism. Insulin and adrenaline are animal hormones.",
                "misconception": "plant_animal_hormone_swap",
                "source": "NCERT Ch 6 Intext",
            },
            {
                "ref": "Section 6.3 — adrenaline",
                "question": "How does our body respond when adrenaline is secreted into the blood?",
                "options": [
                    "Heart rate slows and digestion speeds up",
                    "Heart beats faster, breathing increases, blood diverted to muscles",
                    "Blood sugar drops immediately",
                    "All voluntary muscles relax completely",
                ],
                "answer": 1,
                "explanation": "Adrenaline prepares for fight-or-flight: faster heartbeat, increased breathing, blood to skeletal muscles.",
                "misconception": "nervous_hormonal_speed_swap",
                "source": "NCERT Ch 6 Intext",
            },
            {
                "ref": "Section 6.3 — iodised salt",
                "question": "Why is the use of iodised salt advisable?",
                "options": [
                    "Iodine makes food taste better",
                    "Iodine is needed for thyroxin synthesis; deficiency causes goitre",
                    "Iodine kills bacteria in food",
                    "Iodine increases height in adults",
                ],
                "answer": 1,
                "explanation": "Thyroid gland needs iodine to make thyroxin; iodine deficiency leads to goitre (swollen neck).",
                "misconception": "plant_animal_hormone_swap",
                "source": "NCERT Ch 6 Intext",
            },
        ],
        "exercise_meta": {
            "active": True,
            "stage": 3,
            "range": "Exercises Q4–Q12",
            "note": "Exam-style written questions. Chapter 6 has 3 MCQs (Stage 2) and 9 long-form exercises here.",
            "chapter": "NCERT Class 10 Science Ch 6",
            "pdf": "jesc106.pdf",
        },
        "exercises": [
            {
                "id": "u2_ex_q04",
                "num": 4,
                "type": "explain",
                "marks": 3,
                "question": "What is the function of receptors in our body? Think of situations where receptors do not work properly. What problems are likely to arise?",
                "hints": [
                    "Receptors detect stimuli at dendritic tips in sense organs.",
                    "Examples: gustatory (taste), olfactory (smell), photoreceptors (light).",
                    "If receptors fail: blindness, deafness, loss of taste.",
                ],
                "model_answer": "**Function:** Receptors are specialised tips of nerve cells in sense organs that **detect environmental stimuli** and trigger nerve impulses.\n\n**Examples:** Gustatory receptors (taste), olfactory receptors (smell), receptors in eye and ear.\n\n**If receptors fail:** Cannot detect changes — **blindness** (no light detection), **deafness** (no sound), **loss of taste/smell** — so the body cannot respond appropriately.",
                "marking_points": [
                    "States receptors detect stimuli",
                    "Gives examples of receptors or sense organs",
                    "Explains consequences of receptor failure",
                ],
                "common_mistakes": [
                    "Confusing receptors with effectors (muscles/glands)",
                    "Not giving examples of receptor failure",
                ],
                "concept_ids": ["u2_d2_c01", "u2_d2_c02", "u2_d1_c07"],
                "misconception": "reflex_brain_confusion",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q4",
            },
            {
                "id": "u2_ex_q05",
                "num": 5,
                "type": "diagram_explain",
                "marks": 5,
                "question": "Draw the structure of a neuron and explain its function.",
                "hints": [
                    "Label dendrites, cell body, axon, axon terminals.",
                    "Dendrites receive; axon transmits impulse.",
                    "Synapse at end connects to next neuron or effector.",
                ],
                "model_answer": "**Structure:** Dendrites (receive signals) → cell body (contains nucleus) → axon (long fibre) → axon terminals (synapse with next cell).\n\n**Function:** Neuron **acquires information** at dendrites, creates **electrical impulse** that travels along axon, and passes signal via **synapse** to next neuron, muscle, or gland.",
                "marking_points": [
                    "Correct diagram with dendrites, cell body, axon labelled",
                    "Explains reception at dendrites",
                    "Explains transmission along axon and synapse",
                ],
                "common_mistakes": [
                    "Labelling synapse as part of the neuron itself",
                    "Reversing direction of impulse",
                ],
                "concept_ids": ["u2_d2_c06", "u2_d2_c07", "u2_d3_c01"],
                "misconception": "synapse_axon_confusion",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q5",
            },
            {
                "id": "u2_ex_q06",
                "num": 6,
                "type": "explain",
                "marks": 3,
                "question": "How does phototropism occur in plants?",
                "hints": [
                    "Auxin synthesised at shoot tip.",
                    "Light from one side → auxin diffuses to shady side.",
                    "Shady side cells elongate more → shoot bends toward light.",
                ],
                "model_answer": "When light comes from one direction, **auxin** (plant hormone) at the shoot tip **diffuses to the shady side**. Higher auxin concentration on the shady side causes those cells to **grow longer**, making the shoot **bend toward light** — this is positive phototropism.",
                "marking_points": [
                    "Mentions auxin at shoot tip",
                    "Uneven auxin distribution toward shady side",
                    "Differential cell elongation causes bending",
                ],
                "common_mistakes": [
                    "Saying plants move like animals using muscles",
                    "Omitting role of auxin",
                ],
                "concept_ids": ["u2_d8_c02", "u2_d8_c01", "u2_d7_c06"],
                "misconception": "plant_animal_hormone_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q6",
            },
            {
                "id": "u2_ex_q07",
                "num": 7,
                "type": "explain",
                "marks": 3,
                "question": "Which signals will get disrupted in case of a spinal cord injury?",
                "hints": [
                    "Spinal cord connects brain to rest of body.",
                    "Carries sensory signals up and motor signals down.",
                    "Reflex arcs also processed in spinal cord.",
                ],
                "model_answer": "Spinal cord injury disrupts **communication between brain and body parts below the injury**. **Sensory signals** from body to brain and **motor signals** from brain to muscles are blocked. **Reflex actions** below the injury site may also be lost.",
                "marking_points": [
                    "Brain-body communication disrupted",
                    "Sensory and/or motor signals affected",
                    "Mentions loss of sensation or paralysis below injury",
                ],
                "common_mistakes": [
                    "Saying only reflexes are affected",
                    "Confusing spinal cord with vertebral column only",
                ],
                "concept_ids": ["u2_d6_c07", "u2_d4_c04", "u2_d5_c01"],
                "misconception": "reflex_brain_confusion",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q7",
            },
            {
                "id": "u2_ex_q08",
                "num": 8,
                "type": "explain",
                "marks": 3,
                "question": "How does chemical coordination occur in plants?",
                "hints": [
                    "Plants use hormones (phytohormones).",
                    "Synthesised in one part, diffuse to action site.",
                    "Examples: auxin, gibberellin, cytokinin, abscisic acid.",
                ],
                "model_answer": "Plants use **plant hormones** (e.g. auxin, gibberellin, cytokinin) that are **produced in one part** and **diffuse** to cells where they act. They regulate **growth, cell division, and responses** to light, gravity, and water — without a nervous system.",
                "marking_points": [
                    "Plant hormones as chemical messengers",
                    "Produced at one site, act elsewhere",
                    "Names at least one hormone with function",
                ],
                "common_mistakes": [
                    "Describing animal endocrine system instead",
                    "Saying plants have nerves",
                ],
                "concept_ids": ["u2_d8_c01", "u2_d8_c02", "u2_d8_c05"],
                "misconception": "plant_animal_hormone_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q8",
            },
            {
                "id": "u2_ex_q09",
                "num": 9,
                "type": "explain",
                "marks": 3,
                "question": "What is the need for a system of control and coordination in an organism?",
                "hints": [
                    "Organisms face changing environments.",
                    "Must detect stimuli and respond appropriately.",
                    "Multicellular bodies need communication between parts.",
                ],
                "model_answer": "Organisms constantly face **changes in their environment**. They must **detect stimuli** and produce **appropriate, timely responses** for survival. In multicellular organisms, different parts must **work together** — control and coordination systems (nervous and hormonal) ensure the correct response reaches the right body part.",
                "marking_points": [
                    "Detect stimuli and respond appropriately",
                    "Survival depends on correct responses",
                    "Multicellular organisms need communication systems",
                ],
                "common_mistakes": [
                    "Only mentioning movement without detection",
                    "Ignoring multicellular coordination need",
                ],
                "concept_ids": ["u2_d1_c02", "u2_d1_c03", "u2_d11_c03"],
                "misconception": "nervous_hormonal_speed_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q9",
            },
            {
                "id": "u2_ex_q10",
                "num": 10,
                "type": "compare",
                "marks": 4,
                "question": "How are involuntary actions and reflex actions different from each other?",
                "hints": [
                    "Reflex: sudden, specific stimulus, via reflex arc.",
                    "Involuntary: continuous, no specific trigger (heartbeat).",
                    "Both lack conscious control.",
                ],
                "model_answer": "**Reflex actions:** sudden, in response to a **specific stimulus**, via **reflex arc** in spinal cord (e.g. hand withdrawal from flame).\n\n**Involuntary actions:** **no specific stimulus** needed, controlled by mid-brain/hind-brain, run continuously (e.g. heartbeat, digestion, salivation).\n\nBoth lack conscious control, but reflex needs a trigger; involuntary does not.",
                "marking_points": [
                    "Reflex is stimulus-triggered and rapid",
                    "Involuntary runs without specific stimulus",
                    "One example of each",
                ],
                "common_mistakes": [
                    "Saying all involuntary actions are reflexes",
                    "Claiming reflex actions involve conscious thought",
                ],
                "concept_ids": ["u2_d4_c08", "u2_d5_c10", "u2_d5_c09"],
                "misconception": "reflex_brain_confusion",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q10",
            },
            {
                "id": "u2_ex_q11",
                "num": 11,
                "type": "compare",
                "marks": 4,
                "question": "Compare and contrast nervous and hormonal mechanisms for control and coordination in animals.",
                "hints": [
                    "Nervous: electrical impulses, fast, through nerves.",
                    "Hormonal: chemicals in blood, slow, widespread.",
                    "Give at least three differences.",
                ],
                "model_answer": "| Feature | Nervous | Hormonal |\n|---|---|---|\n| Signal | Electrical impulse | Chemical hormone |\n| Speed | Very fast (ms) | Slower (minutes) |\n| Pathway | Nerve fibres | Bloodstream |\n| Duration | Short-lived | Longer lasting |\n| Reach | Connected cells only | All cells with receptors |",
                "marking_points": [
                    "At least three valid differences",
                    "Correct transmission medium for each",
                    "Examples (reflex vs growth/adrenaline)",
                ],
                "common_mistakes": [
                    "Saying hormones use nerves to travel",
                    "Swapping speed characteristics",
                ],
                "concept_ids": ["u2_d10_c08", "u2_d11_c02", "u2_d3_c06"],
                "misconception": "nervous_hormonal_speed_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q11",
            },
            {
                "id": "u2_ex_q12",
                "num": 12,
                "type": "compare",
                "marks": 4,
                "question": "What is the difference between the manner in which movement takes place in a sensitive plant and the movement in our legs?",
                "hints": [
                    "Mimosa: turgor change, fast, no growth, no muscles.",
                    "Legs: muscle contraction, nervous control, voluntary.",
                    "Compare mechanism, speed, and tissues involved.",
                ],
                "model_answer": "**Sensitive plant (Mimosa):** movement by **change in water content** (turgor) in cells — **no muscles, no nerves**, very **fast**, **no growth** involved.\n\n**Leg movement:** **muscle contraction** controlled by **nervous system** — can be **voluntary** (walking) or involuntary; uses specialised muscle proteins.",
                "marking_points": [
                    "Mimosa: turgor-based, no muscle/nervous tissue",
                    "Legs: muscle contraction with nervous control",
                    "Compares speed or voluntary nature",
                ],
                "common_mistakes": [
                    "Saying Mimosa uses auxin for folding",
                    "Claiming plants have muscle tissue",
                ],
                "concept_ids": ["u2_d7_c03", "u2_d7_c04", "u2_d6_c04"],
                "misconception": "plant_animal_hormone_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 6 Exercises Q12",
            },
        ],
    },
    3: {
        "meta": {
            "unit_id": 3,
            "chapter": 7,
            "pdf": "jesc107.pdf",
            "title": "How do Organisms Reproduce?",
        },
        "activities": [
            {
                "id": "7.1",
                "title": "Yeast budding in sugar solution",
                "summary": "Yeast in glucose solution produces buds visible under microscope — asexual reproduction by budding.",
                "concept_ids": ["u3_d4_c04", "u3_d3_c05", "u3_d3_c02"],
                "stage2_day": 17,
            },
            {
                "id": "7.2",
                "title": "Bread mould on wet bread",
                "summary": "Wet bread grows mould (hyphae and spores) — compare yeast budding vs mould spore formation.",
                "concept_ids": ["u3_d4_c06", "u3_d5_c03", "u3_d4_c04"],
                "stage2_day": 17,
            },
            {
                "id": "7.3",
                "title": "Binary fission in Amoeba",
                "summary": "Observe permanent slides of Amoeba and binary fission — unicellular asexual reproduction.",
                "concept_ids": ["u3_d3_c02", "u3_d3_c03", "u3_d3_c01"],
                "stage2_day": 18,
            },
            {
                "id": "7.4",
                "title": "Fragmentation in Spirogyra",
                "summary": "Filamentous Spirogyra breaks into fragments that grow into new individuals.",
                "concept_ids": ["u3_d4_c01", "u3_d4_c02", "u3_d3_c01"],
                "stage2_day": 18,
            },
            {
                "id": "7.5",
                "title": "Spore formation in Rhizopus",
                "summary": "Observe bread mould spores in sporangia — asexual reproduction by spores.",
                "concept_ids": ["u3_d5_c01", "u3_d5_c02", "u3_d5_c03"],
                "stage2_day": 19,
            },
            {
                "id": "7.6",
                "title": "Vegetative propagation in Bryophyllum",
                "summary": "Bryophyllum plantlets on leaf margins grow into new plants — vegetative propagation.",
                "concept_ids": ["u3_d5_c04", "u3_d5_c05", "u3_d4_c03"],
                "stage2_day": 19,
            },
            {
                "id": "7.7",
                "title": "Germination of pollen on stigma",
                "summary": "Pollen grains germinate on stigma; pollen tubes grow toward ovules.",
                "concept_ids": ["u3_d7_c05", "u3_d7_c06", "u3_d8_c02"],
                "stage2_day": 20,
            },
        ],
        "exercise_mcqs": [
            {
                "num": 1,
                "question": "Asexual reproduction takes place through budding in",
                "options": ["Amoeba", "Yeast", "Plasmodium", "Leishmania"],
                "answer": 1,
                "explanation": "Yeast reproduces asexually by budding — a small outgrowth forms and separates. Amoeba uses binary fission.",
                "misconception": "binary_budding_swap",
                "source": "NCERT Ch 7 Exercises Q1",
            },
            {
                "num": 2,
                "question": "Which of the following is not a part of the female reproductive system in human beings?",
                "options": ["Ovary", "Uterus", "Vas deferens", "Fallopian tube"],
                "answer": 2,
                "explanation": "Vas deferens is part of the male reproductive system — it carries sperm. Ovary, uterus, and fallopian tube are female parts.",
                "misconception": "male_female_organ_swap",
                "source": "NCERT Ch 7 Exercises Q2",
            },
            {
                "num": 3,
                "question": "The anther contains",
                "options": ["sepal", "ovules", "carpel", "pollen grains"],
                "answer": 3,
                "explanation": "Anther is the part of stamen (male) that produces pollen grains containing male gametes.",
                "misconception": "pollination_fertilisation_swap",
                "source": "NCERT Ch 7 Exercises Q3",
            },
        ],
        "intext_samples": [
            {
                "ref": "Section 7.1 — DNA copying",
                "question": "What is the importance of DNA copying in reproduction?",
                "options": [
                    "DNA copying is not needed for reproduction",
                    "DNA copying ensures offspring receive complete genetic information for body design",
                    "DNA copying only happens in sexual reproduction",
                    "DNA copying prevents all variation",
                ],
                "answer": 1,
                "explanation": "DNA must be copied and passed to new cells so offspring inherit instructions for body design and survival.",
                "misconception": "dna_copying_confusion",
                "source": "NCERT Ch 7 Intext",
            },
            {
                "ref": "Section 7.1 — variation",
                "question": "Why is variation beneficial to the species but not necessarily for the individual?",
                "options": [
                    "Variation harms all organisms equally",
                    "Variation helps species survive environmental changes even if some individuals suffer",
                    "Variation only benefits the individual",
                    "Variation prevents reproduction",
                ],
                "answer": 1,
                "explanation": "Variations create diversity so some individuals may survive if conditions change — benefits species survival.",
                "misconception": "dna_copying_confusion",
                "source": "NCERT Ch 7 Intext",
            },
            {
                "ref": "Section 7.2 — fission",
                "question": "How does binary fission differ from multiple fission?",
                "options": [
                    "Binary fission produces many cells; multiple fission produces two",
                    "Binary fission splits into two; multiple fission produces many daughter cells at once",
                    "Both are sexual reproduction methods",
                    "Multiple fission occurs only in plants",
                ],
                "answer": 1,
                "explanation": "Binary fission: one cell → two (Amoeba). Multiple fission: one cell → many (Plasmodium).",
                "misconception": "binary_budding_swap",
                "source": "NCERT Ch 7 Intext",
            },
            {
                "ref": "Section 7.3 — pollination",
                "question": "How is the process of pollination different from fertilisation?",
                "options": [
                    "They are the same process",
                    "Pollination is transfer of pollen to stigma; fertilisation is fusion of gametes",
                    "Fertilisation happens before pollination always",
                    "Pollination occurs only in animals",
                ],
                "answer": 1,
                "explanation": "Pollination moves pollen to stigma; fertilisation fuses male and female gametes inside the ovule.",
                "misconception": "pollination_fertilisation_swap",
                "source": "NCERT Ch 7 Intext",
            },
            {
                "ref": "Section 7.3 — puberty",
                "question": "What are the changes seen in girls at the time of puberty?",
                "options": [
                    "No visible changes occur",
                    "Breast development, menstruation begins, wider hips",
                    "Only height increases with no other changes",
                    "Voice becomes deeper like boys",
                ],
                "answer": 1,
                "explanation": "Puberty in girls includes breast development, onset of menstrual cycle, and wider hips — driven by oestrogen.",
                "misconception": "male_female_organ_swap",
                "source": "NCERT Ch 7 Intext",
            },
            {
                "ref": "Section 7.2 — spores",
                "question": "How will an organism be benefited if it reproduces through spores?",
                "options": [
                    "Spores require two parents",
                    "Spores are lightweight, easily dispersed, and survive harsh conditions",
                    "Spores cannot survive without water",
                    "Spores always produce identical offspring with no variation",
                ],
                "answer": 1,
                "explanation": "Spores have thick walls, are light and easily spread by air/water, and survive unfavourable conditions.",
                "misconception": "asexual_sexual_swap",
                "source": "NCERT Ch 7 Intext",
            },
        ],
        "exercise_meta": {
            "active": True,
            "stage": 3,
            "range": "Exercises Q4–Q11",
            "note": "Exam-style written questions. Chapter 7 has 3 MCQs (Stage 2) and 8 long-form exercises here.",
            "chapter": "NCERT Class 10 Science Ch 7",
            "pdf": "jesc107.pdf",
        },
        "exercises": [
            {
                "id": "u3_ex_q04",
                "num": 4,
                "type": "explain",
                "marks": 3,
                "question": "What are the advantages of sexual reproduction over asexual reproduction?",
                "hints": [
                    "Sexual involves two parents and gamete fusion.",
                    "Creates more variation in offspring.",
                    "Variation helps species adapt to changing environments.",
                ],
                "model_answer": "Sexual reproduction creates **more variations** because offspring inherit traits from **two parents** with **new combinations** of genes. This **genetic diversity** helps the **species survive** changing environments — some variants may be better suited than others.",
                "marking_points": [
                    "Two parents / gamete fusion mentioned",
                    "More variation created",
                    "Variation benefits species survival/adaptation",
                ],
                "common_mistakes": [
                    "Saying sexual reproduction is always faster",
                    "Not linking variation to survival",
                ],
                "concept_ids": ["u3_d6_c02", "u3_d2_c02", "u3_d1_c04"],
                "misconception": "asexual_sexual_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q4",
            },
            {
                "id": "u3_ex_q05",
                "num": 5,
                "type": "explain",
                "marks": 3,
                "question": "What are the functions performed by the testis in human beings?",
                "hints": [
                    "Testis produces male gametes (sperm).",
                    "Also secretes testosterone at puberty.",
                    "Located in scrotum outside body for lower temperature.",
                ],
                "model_answer": "Testis performs two functions:\n\n1. **Produces sperm** (male gametes) by meiosis.\n2. **Secretes testosterone** — the male sex hormone that develops secondary sexual characters at puberty (deep voice, facial hair, etc.).",
                "marking_points": [
                    "Produces sperm/male gametes",
                    "Secretes testosterone",
                    "Optional: scrotum location for sperm production temperature",
                ],
                "common_mistakes": [
                    "Confusing testis with vas deferens function",
                    "Omitting hormone secretion role",
                ],
                "concept_ids": ["u3_d9_c01", "u3_d9_c03", "u3_d9_c04"],
                "misconception": "male_female_organ_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q5",
            },
            {
                "id": "u3_ex_q06",
                "num": 6,
                "type": "explain",
                "marks": 3,
                "question": "Why does menstruation occur?",
                "hints": [
                    "Uterus prepares lining each month for possible pregnancy.",
                    "If egg not fertilised, lining breaks down.",
                    "Menstrual blood is blood and uterine lining tissue.",
                ],
                "model_answer": "Each month the **uterus prepares its lining** (endometrium) to receive a fertilised egg. If **fertilisation does not occur**, the thickened lining is **not needed** and **breaks down** — this is shed as **menstrual blood** through the vagina (menstruation).",
                "marking_points": [
                    "Uterus lining prepared for pregnancy",
                    "No fertilisation → lining breaks down",
                    "Shed as menstrual flow",
                ],
                "common_mistakes": [
                    "Saying menstruation is excretion of eggs",
                    "Confusing menstruation with fertilisation",
                ],
                "concept_ids": ["u3_d10_c05", "u3_d10_c06", "u3_d10_c04"],
                "misconception": "male_female_organ_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q6",
            },
            {
                "id": "u3_ex_q07",
                "num": 7,
                "type": "diagram_explain",
                "marks": 5,
                "question": "Draw a labelled diagram of the longitudinal section of a flower.",
                "hints": [
                    "Show sepals, petals, stamen (anther + filament), pistil (stigma, style, ovary).",
                    "Label anther, pollen, ovary, ovule.",
                    "Longitudinal section shows internal structure.",
                ],
                "model_answer": "Diagram should show:\n\n**Stamen (male):** anther (pollen grains) + filament.\n**Pistil/carpel (female):** stigma → style → ovary (containing ovules).\n**Accessories:** sepals, petals.\n\nPollen from anther reaches stigma (pollination); male gamete fuses with egg in ovule (fertilisation).",
                "marking_points": [
                    "Stamen and pistil correctly drawn and labelled",
                    "Anther and ovary/ovule labelled",
                    "Sepals/petals shown",
                ],
                "common_mistakes": [
                    "Labelling ovules in anther",
                    "Confusing stamen with pistil",
                ],
                "concept_ids": ["u3_d7_c01", "u3_d7_c02", "u3_d7_c03"],
                "misconception": "pollination_fertilisation_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q7",
            },
            {
                "id": "u3_ex_q08",
                "num": 8,
                "type": "describe",
                "marks": 5,
                "question": "What are the different methods of contraception?",
                "hints": [
                    "Barrier methods: condom, diaphragm.",
                    "Chemical: oral pills (hormonal).",
                    "Surgical: vasectomy, tubectomy. IUD, etc.",
                ],
                "model_answer": "Methods of contraception:\n\n1. **Barrier:** condoms, diaphragms — prevent sperm reaching egg.\n2. **Hormonal:** oral pills — prevent ovulation.\n3. **Intrauterine devices (IUDs):** prevent implantation.\n4. **Surgical:** vasectomy (males), tubectomy (females) — block gamete passage.\n5. **Natural/withdrawal** (less reliable).",
                "marking_points": [
                    "At least three methods named",
                    "Brief mechanism for each",
                    "Barrier and hormonal methods included",
                ],
                "common_mistakes": [
                    "Confusing vasectomy with tubectomy",
                    "Saying contraception prevents all STDs (barrier helps but not all methods)",
                ],
                "concept_ids": ["u3_d12_c01", "u3_d12_c02", "u3_d12_c03"],
                "misconception": "male_female_organ_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q8",
            },
            {
                "id": "u3_ex_q09",
                "num": 9,
                "type": "compare",
                "marks": 4,
                "question": "How are the modes for reproduction different in unicellular and multicellular organisms?",
                "hints": [
                    "Unicellular: fission, budding, simple body design.",
                    "Multicellular: specialised reproductive organs, complex modes.",
                    "Cell-by-cell division impractical for complex bodies.",
                ],
                "model_answer": "**Unicellular:** simple modes — **binary fission**, **budding**, **multiple fission** — entire cell divides.\n\n**Multicellular:** need **specialised reproductive organs/tissues** because body has many cell types in fixed positions. Modes include **fragmentation, regeneration, spores, vegetative propagation**, and **sexual reproduction** with gametes.",
                "marking_points": [
                    "Unicellular modes named (fission/budding)",
                    "Multicellular needs specialised structures",
                    "Explains why simple division doesn't work for complex bodies",
                ],
                "common_mistakes": [
                    "Saying multicellular organisms only reproduce sexually",
                    "Omitting asexual modes in multicellular organisms",
                ],
                "concept_ids": ["u3_d3_c01", "u3_d4_c02", "u3_d6_c01"],
                "misconception": "asexual_sexual_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q9",
            },
            {
                "id": "u3_ex_q10",
                "num": 10,
                "type": "explain",
                "marks": 3,
                "question": "How does reproduction help in providing stability to populations of species?",
                "hints": [
                    "Reproduction maintains population numbers.",
                    "DNA copying preserves species characteristics.",
                    "Variation allows adaptation over generations.",
                ],
                "model_answer": "Reproduction **maintains population size** by replacing individuals that die. **DNA copying** ensures offspring inherit species characteristics, providing **stability** of basic body design. **Variation** from slight copying inaccuracies allows gradual adaptation without losing species identity.",
                "marking_points": [
                    "Maintains population numbers",
                    "Preserves species characteristics via DNA",
                    "Links to stability of species over time",
                ],
                "common_mistakes": [
                    "Confusing individual stability with population stability",
                    "Saying reproduction eliminates all variation",
                ],
                "concept_ids": ["u3_d1_c01", "u3_d2_c01", "u3_d1_c05"],
                "misconception": "dna_copying_confusion",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q10",
            },
            {
                "id": "u3_ex_q11",
                "num": 11,
                "type": "explain",
                "marks": 3,
                "question": "What could be the reasons for adopting contraceptive methods?",
                "hints": [
                    "Prevent unwanted pregnancies.",
                    "Population control / family planning.",
                    "Health of mother; spacing of children.",
                ],
                "model_answer": "Reasons for contraception:\n\n1. **Prevent unwanted pregnancy** and allow **family planning**.\n2. **Population control** — limit family size.\n3. **Protect mother's health** — avoid frequent pregnancies.\n4. **Economic/social reasons** — spacing children for better care and education.",
                "marking_points": [
                    "Prevent unwanted pregnancy",
                    "Family planning or population control",
                    "Health or economic reason",
                ],
                "common_mistakes": [
                    "Only mentioning one reason",
                    "Confusing contraception with STD prevention alone",
                ],
                "concept_ids": ["u3_d12_c04", "u3_d12_c05", "u3_d12_c01"],
                "misconception": "male_female_organ_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 7 Exercises Q11",
            },
        ],
    },
    4: {
        "meta": {
            "unit_id": 4,
            "chapter": 8,
            "pdf": "jesc108.pdf",
            "title": "Heredity",
        },
        "activities": [
            {
                "id": "8.1",
                "title": "Variation in asexual population",
                "summary": "Compare trait frequency in asexual population — trait present in 60% likely arose earlier than trait in 10%.",
                "concept_ids": ["u4_d2_c01", "u4_d2_c02", "u4_d1_c03"],
                "stage2_day": 17,
            },
            {
                "id": "8.2",
                "title": "Mendel's monohybrid cross",
                "summary": "Cross tall and short pea plants — F1 all tall, F2 shows 3:1 ratio proving dominant and recessive traits.",
                "concept_ids": ["u4_d4_c02", "u4_d5_c01", "u4_d5_c03"],
                "stage2_day": 18,
            },
        ],
        "exercise_mcqs": [
            {
                "num": 1,
                "question": "A Mendelian experiment consisted of breeding tall pea plants bearing violet flowers with short pea plants bearing white flowers. The progeny all bore violet flowers, but almost half of them were short. This suggests that the genetic make-up of the tall parent can be depicted as",
                "options": ["TTWW", "TTww", "TtWW", "TtWw"],
                "answer": 2,
                "explanation": "All flowers violet → at least one W allele from tall parent. Half progeny short → tall parent is Tt (heterozygous). Tall parent genotype: TtWW.",
                "misconception": "dominant_recessive_swap",
                "source": "NCERT Ch 8 Exercises Q1",
            },
        ],
        "intext_samples": [
            {
                "ref": "Section 8.1 — variation in asexual species",
                "question": "If a trait A exists in 10% of a population of an asexually reproducing species and a trait B exists in 60% of the same population, which trait is likely to have arisen earlier?",
                "options": [
                    "Trait A, because it is rarer",
                    "Trait B, because higher frequency suggests it arose earlier and spread",
                    "Both arose at the same time",
                    "Cannot be determined without DNA testing",
                ],
                "answer": 1,
                "explanation": "In asexual reproduction, fewer variations arise. A trait present in more individuals (60%) likely appeared earlier and has been copied more times.",
                "misconception": "variation_inheritance_swap",
                "source": "NCERT Ch 8 Intext",
            },
            {
                "ref": "Section 8.1 — variation and survival",
                "question": "How does the creation of variations in a species promote survival?",
                "options": [
                    "Variations make all individuals identical",
                    "Variations ensure some individuals may survive if environment changes",
                    "Variations prevent reproduction",
                    "Variations only harm the species",
                ],
                "answer": 1,
                "explanation": "Variation creates diversity so if conditions change, some variants may survive while others may not — species continues.",
                "misconception": "variation_inheritance_swap",
                "source": "NCERT Ch 8 Intext",
            },
            {
                "ref": "Section 8.2 — dominant and recessive",
                "question": "How do Mendel's experiments show that traits may be dominant or recessive?",
                "options": [
                    "F1 showed both traits equally",
                    "F1 showed only dominant trait; recessive reappeared in F2 in 3:1 ratio",
                    "Recessive trait always appears in F1",
                    "Dominant and recessive traits blend in F1",
                ],
                "answer": 1,
                "explanation": "Mendel crossed pure tall (TT) with pure short (tt) — F1 all tall (dominant). F2 had 3 tall : 1 short — recessive reappeared.",
                "misconception": "dominant_recessive_swap",
                "source": "NCERT Ch 8 Intext",
            },
            {
                "ref": "Section 8.2 — independent inheritance",
                "question": "How do Mendel's experiments show that traits are inherited independently?",
                "options": [
                    "All traits are always linked together",
                    "Dihybrid cross produced new combinations (tall-wrinkled, short-round) in 9:3:3:1 ratio",
                    "Only one trait can be inherited at a time",
                    "F1 always matches one parent exactly",
                ],
                "answer": 1,
                "explanation": "Dihybrid cross of seed shape and colour produced four phenotypes including new combinations — traits assort independently.",
                "misconception": "monohybrid_dihybrid_swap",
                "source": "NCERT Ch 8 Intext",
            },
            {
                "ref": "Section 8.2 — sex determination",
                "question": "How is the sex of the child determined in human beings?",
                "options": [
                    "Mother decides sex by producing X or Y eggs",
                    "Father determines sex — X sperm → girl (XX), Y sperm → boy (XY)",
                    "Sex is determined by diet during pregnancy",
                    "Both parents contribute Y chromosome equally",
                ],
                "answer": 1,
                "explanation": "Mother always gives X chromosome. Father gives X (girl) or Y (boy). Sex determined by father's sperm.",
                "misconception": "sex_determination_confusion",
                "source": "NCERT Ch 8 Intext",
            },
            {
                "ref": "Section 8.2 — blood groups",
                "question": "A man with blood group A marries a woman with blood group O and their daughter has blood group O. Can we determine which blood group is dominant?",
                "options": [
                    "Yes, O is definitely dominant",
                    "Yes, A is definitely dominant",
                    "No — father could be AO heterozygote, so data is insufficient",
                    "Yes, AB is dominant over both",
                ],
                "answer": 2,
                "explanation": "A can be AA or AO. If father is AO and mother OO, child can be O. Need more data to determine dominance.",
                "misconception": "dominant_recessive_swap",
                "source": "NCERT Ch 8 Intext",
            },
            {
                "ref": "Section 8.2 — genotype vs phenotype",
                "question": "A tall pea plant could have genotype TT or Tt. What term describes this visible tallness?",
                "options": ["Genotype", "Phenotype", "Variation", "Mutation"],
                "answer": 1,
                "explanation": "Phenotype is the observable trait (tall). Genotype is the genetic makeup (TT or Tt).",
                "misconception": "genotype_phenotype_swap",
                "source": "NCERT Ch 8 Intext",
            },
        ],
        "exercise_meta": {
            "active": True,
            "stage": 3,
            "range": "Exercises Q2–Q4",
            "note": "Exam-style written questions. Chapter 8 has 1 MCQ (Stage 2) and 3 long-form exercises here.",
            "chapter": "NCERT Class 10 Science Ch 8",
            "pdf": "jesc108.pdf",
        },
        "exercises": [
            {
                "id": "u4_ex_q02",
                "num": 2,
                "type": "explain",
                "marks": 3,
                "question": "A study found that children with light-coloured eyes are likely to have parents with light-coloured eyes. On this basis, can we say anything about whether the light eye colour trait is dominant or recessive? Why or why not?",
                "hints": [
                    "Like parents like children suggests inheritance.",
                    "But need F1/F2 cross data like Mendel.",
                    "Single family study is insufficient.",
                ],
                "model_answer": "**No**, we cannot definitively say whether light eye colour is dominant or recessive from this study alone.\n\nWhile children resembling parents suggests **inheritance**, determining dominance requires **controlled crosses** (like Mendel's F1 and F2 ratios). This observation could fit **either** dominant or recessive patterns depending on genotypes in the population.",
                "marking_points": [
                    "Answer: No, not enough evidence",
                    "Explains why (need controlled crosses / F2 ratios)",
                    "Mentions observation suggests heredity but not dominance",
                ],
                "common_mistakes": [
                    "Definitively stating light eyes are dominant",
                    "Not explaining what evidence would be needed",
                ],
                "concept_ids": ["u4_d5_c01", "u4_d5_c03", "u4_d7_c02"],
                "misconception": "dominant_recessive_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 8 Exercises Q2",
            },
            {
                "id": "u4_ex_q03",
                "num": 3,
                "type": "project",
                "marks": 5,
                "question": "Outline a project which aims to find the dominant coat colour in dogs.",
                "hints": [
                    "Observe coat colours in many dog families.",
                    "Record parent and puppy colours across generations.",
                    "Look for patterns like Mendel — which colour appears when two different colours mate.",
                ],
                "model_answer": "**Project outline:**\n\n1. **Survey** 30–50 dog families — record coat colours of **both parents and all puppies**.\n2. **Cross analysis:** When two different coloured parents produce puppies, note which colour appears in **all F1** puppies (dominant candidate).\n3. **F2 check:** If F1 dogs are bred, check if recessive colour **reappears** in F2.\n4. **Conclusion:** Colour always present in F1 is likely **dominant**; reappearing in F2 is **recessive**.",
                "marking_points": [
                    "Data collection method (families/generations)",
                    "Compare parent and offspring colours",
                    "Mendelian logic applied to determine dominant colour",
                ],
                "common_mistakes": [
                    "No systematic data collection plan",
                    "Concluding from single family only",
                ],
                "concept_ids": ["u4_d4_c02", "u4_d5_c01", "u4_d10_c02"],
                "misconception": "dominant_recessive_swap",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 8 Exercises Q3",
            },
            {
                "id": "u4_ex_q04",
                "num": 4,
                "type": "explain",
                "marks": 3,
                "question": "How is the equal genetic contribution of male and female parents ensured in the progeny?",
                "hints": [
                    "Humans have 23 pairs of chromosomes.",
                    "Gametes are haploid (23 chromosomes each).",
                    "Fertilisation restores diploid (46) with half from each parent.",
                ],
                "model_answer": "Each parent produces **gametes with half the normal chromosome number** (23 in humans) through **meiosis**. During **fertilisation**, the **male gamete (sperm)** fuses with the **female gamete (egg)** to form a zygote with the **full chromosome number (46)** — **equal contribution** of 23 from each parent.",
                "marking_points": [
                    "Gametes are haploid (half chromosomes)",
                    "Fertilisation combines two gametes",
                    "Equal 23 + 23 = 46 in zygote",
                ],
                "common_mistakes": [
                    "Saying parents contribute unequal DNA",
                    "Confusing mitosis with meiosis",
                ],
                "concept_ids": ["u4_d1_c04", "u4_d7_c04", "u4_d7_c05"],
                "misconception": "sex_determination_confusion",
                "guided_tool": None,
                "ncert_ref": "NCERT Ch 8 Exercises Q4",
            },
        ],
    },
}
