"""Full concept card content for Harshit Biology Unit 2 — Days 1–16 (Ch 6 Control and Coordination)."""

from __future__ import annotations


def _card(
    cid: str,
    name: str,
    simple: str,
    visual_type: str,
    visual_config: dict | None,
    why: str,
    example: str,
    remember: str,
    confusion: str = "",
    optional: str = "",
    glossary: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "name": name,
        "simple_answer": simple,
        "visual": {"type": visual_type, **(visual_config or {})},
        "why": why,
        "example": example,
        "remember": remember,
        "common_confusion": confusion,
        "optional_detail": optional,
        "glossary_terms": glossary or [],
    }


def _build_day(day: int, cards: list[tuple]) -> list[dict]:
    out = []
    for i, row in enumerate(cards, 1):
        name, simple, vtype, vcfg, why, ex, rem, *rest = row
        confusion = rest[0] if len(rest) > 0 else ""
        optional = rest[1] if len(rest) > 1 else ""
        gloss = rest[2] if len(rest) > 2 else []
        out.append(
            _card(
                f"u2_d{day}_c{i:02d}",
                name,
                simple,
                vtype,
                vcfg if isinstance(vcfg, dict) else {},
                why,
                ex,
                rem,
                confusion,
                optional,
                gloss if isinstance(gloss, list) else [],
            )
        )
    return out


DAY1 = _build_day(1, [
    ('What is control and coordination?', 'Control and coordination are processes that help an organism respond to changes in its internal and external environment in a proper and timely manner.', 'placeholder', {'label': 'Control and coordination overview'}, 'NCERT Ch 6 opens with how organisms respond to stimuli.', 'Pulling hand away from a hot object shows quick coordination.', 'All living organisms need to respond to survive.', 'Control is not the same as movement alone — plants also coordinate.', '', ['control', 'coordination']),
    ('Why organisms need coordination', 'Organisms must detect changes (stimuli) and produce appropriate responses so body parts work together efficiently.', 'placeholder', {'label': 'Stimulus → response'}, 'Links detection to survival.', 'A deer runs when it hears a predator — coordinated response.', 'Stimulus detected → message carried → response produced.', 'Every cell cannot sense every change — specialised systems help.', '', []),
    ('Stimulus and response', 'A stimulus is a detectable change in the environment; a response is the reaction of the organism to that stimulus.', 'placeholder', {'label': 'Stimulus → response pair'}, 'Foundation terms for Ch 6.', 'Bright light (stimulus) makes pupil constrict (response).', 'Define both terms clearly in exams.', 'Stimulus can be internal (hunger) or external (heat).', '', ['stimulus', 'response']),
    ('Types of coordination in animals', 'Animals coordinate through the nervous system (fast, electrical) and endocrine system (slower, chemical hormones).', 'placeholder', {'label': 'Nervous + endocrine coordination'}, 'Two-system overview.', 'Reflex is nervous; growth spurt at puberty is hormonal.', 'Nervous = fast; endocrine = widespread and sustained.', 'Do not say only nerves coordinate animals.', '', []),
    ('Nervous vs hormonal coordination', 'Nervous messages travel as electrical impulses along nerves; hormonal messages travel in blood as chemical messengers.', 'formula_panel', {'formula': 'Nerve: electrical impulse | Hormone: blood chemical', 'note': 'Speed and mode differ'}, 'Core comparison in Ch 6.', 'Adrenaline rush is fast (nerve + hormone); height growth is slow (hormone).', 'Nerves act in seconds; hormones may act over hours or years.', 'Both systems often work together — integration day later.', '', []),
    ('Receptors in animals', 'Receptors are specialised cells or organs that detect stimuli such as heat, light, sound, taste, and smell.', 'placeholder', {'label': 'Receptors detect stimuli'}, 'Input side of nervous system.', 'Photoreceptors in eye detect light; taste buds detect chemicals.', 'Receptors convert stimulus into nerve message.', 'Effectors produce response — do not confuse with receptors.', '', ['receptor']),
    ('Effectors in animals', 'Effectors are muscles or glands that produce the response after receiving a nerve signal or hormone.', 'placeholder', {'label': 'Effectors — muscles and glands'}, 'Output side of coordination.', 'Biceps contracts to lift arm; salivary gland secretes saliva.', 'Muscle contraction or gland secretion = response.', 'All responses involve effectors, not just muscles.', '', ['effector']),
    ('Coordination in plants — overview', 'Plants also respond to stimuli but lack a nervous system; they use hormones and growth-based movements.', 'placeholder', {'label': 'Plant coordination without nerves'}, 'Plant section preview.', 'Touch-me-not leaf folds on touch; roots grow toward water.', 'Plant responses are usually slower than animal reflexes.', 'Plants do coordinate — they just use different mechanisms.', '', []),
    ('Immediate vs growth responses in plants', 'Plants show immediate responses (e.g. leaf folding) and growth-dependent responses (tropisms over hours/days).', 'placeholder', {'label': 'Immediate vs growth responses'}, 'Two plant response types.', 'Mimosa pudica folds leaves in seconds; shoot bends toward light over days.', 'Immediate = turgor change; growth = differential cell elongation.', 'Tropisms are growth responses, not reflex arcs.', '', []),
    ('Chapter 6 roadmap', 'Ch 6 covers nervous system, reflex arc, brain, plant movements, hormones, and Activities 6.1–6.4.', 'placeholder', {'label': 'Ch 6 roadmap — 16 days'}, 'Orient learner to unit plan.', 'Activities include nerve tissue, reflex, and hormone demos.', 'Animals: nerves + hormones. Plants: hormones + tropisms.', '', '', []),
])

DAY2 = _build_day(2, [
    ('Nervous system — definition', 'The nervous system is the system of nerves, brain, and spinal cord that receives information, integrates it, and sends instructions for response.', 'placeholder', {'label': 'Nervous system defined'}, 'Main animal coordination system.', 'Brain decides to speak; nerves carry commands to speech muscles.', 'Central + peripheral nervous system work together.', 'Nervous system does not make hormones — endocrine system does.', '', ['nervous system']),
    ('Central nervous system (CNS)', 'CNS consists of the brain and spinal cord — the command and integration centre.', 'placeholder', {'label': 'CNS — brain and spinal cord'}, 'Protected inside skull and vertebral column.', 'Spinal cord relays messages between brain and body.', 'CNS processes information; PNS carries messages to/from CNS.', 'Peripheral nerves are not part of CNS.', '', ['CNS']),
    ('Peripheral nervous system (PNS)', 'PNS is all nerves outside the brain and spinal cord that connect the CNS to the rest of the body.', 'placeholder', {'label': 'PNS — nerves to body'}, 'Links CNS to receptors and effectors.', 'Sciatic nerve carries signals to leg muscles.', 'PNS includes cranial and spinal nerves.', 'PNS alone cannot think — integration is in CNS.', '', ['PNS']),
    ('Neuron — basic unit', 'The neuron (nerve cell) is the functional unit of the nervous system that transmits electrical impulses.', 'placeholder', {'label': 'Neuron — nerve cell'}, 'Leads to Day 3 detail.', 'One long nerve cell can run from spine to toe.', 'Neurons are specialised for rapid message transfer.', 'Nerve ≠ neuron — a nerve is a bundle of many neurons.', '', ['neuron']),
    ('Nerve vs neuron', 'A neuron is a single nerve cell; a nerve is a bundle of many nerve fibres (axons) wrapped together.', 'placeholder', {'label': 'Neuron vs nerve bundle'}, 'Common terminology fix.', 'Optic nerve contains thousands of neuron axons.', 'One neuron; many neurons form a nerve.', "Students often use 'nerve cell' and 'nerve' interchangeably — wrong.", '', []),
    ('Three types of neurons', 'Sensory neurons carry impulses from receptors to CNS; motor neurons from CNS to effectors; relay neurons connect within CNS.', 'placeholder', {'label': 'Sensory | relay | motor neurons'}, 'Classification for exams.', 'Touch receptor → sensory neuron → spinal cord → motor neuron → hand muscle.', 'Sensory in; motor out; relay inside CNS.', 'Interneurons = relay neurons in spinal cord and brain.', '', []),
    ('Electrical impulse in nerves', 'Information in neurons travels as an electrical impulse (nerve impulse) along the nerve fibre.', 'formula_panel', {'formula': 'Receptor → impulse → CNS → impulse → effector', 'note': 'Electrical signal path'}, 'Signal nature in nervous system.', 'Impulse jumps from node to node in myelinated axon.', 'Impulses are fast but need intact neuron pathway.', 'Impulse is not blood flow — it is electrical event in cell membrane.', '', ['nerve impulse']),
    ('Voluntary vs involuntary actions', 'Voluntary actions are under conscious control (writing); involuntary actions are automatic (heartbeat, digestion).', 'placeholder', {'label': 'Voluntary vs involuntary'}, 'Action classification.', 'Choosing to walk is voluntary; pupil size change is involuntary.', 'Brain can override some involuntary actions with practice.', 'Reflexes are involuntary but use nervous system.', '', []),
    ('Reflex action preview', 'A reflex is a rapid, involuntary response to a stimulus without conscious thought — handled often by spinal cord.', 'placeholder', {'label': 'Reflex — quick automatic response'}, 'Detailed on Day 5.', 'Knee-jerk when doctor taps patellar tendon.', 'Reflex protects body from harm quickly.', "Reflex is not 'no brain involved ever' — brain may perceive later.", '', ['reflex']),
    ('Nervous system summary', 'Nervous system: receptors → sensory nerves → CNS → motor nerves → effectors; fast electrical coordination.', 'placeholder', {'label': 'Nervous pathway summary'}, 'Day 2 consolidation.', 'Trace path for touching a hot pan.', 'Draw labelled flowchart for exams.', '', '', []),
])

DAY3 = _build_day(3, [
    ('Neuron structure overview', 'A typical neuron has cell body (cyton), dendrites (receive signals), and axon (conducts impulse away).', 'placeholder', {'label': 'Neuron — dendrite, cell body, axon'}, 'Core diagram labels.', 'Cell body in brain; axon may extend a metre.', 'Dendrites in; axon out.', 'Axon and dendrite roles must not be swapped.', '', ['neuron']),
    ('Dendrites function', 'Dendrites are branched extensions that receive impulses from other neurons or receptors and carry them toward cell body.', 'placeholder', {'label': 'Dendrites receive signals'}, 'Input branches of neuron.', 'Many dendrites increase connections with other neurons.', 'Short, branched, receive side.', 'Dendrites do not send impulse away from cell body.', '', ['dendrite']),
    ('Axon function', 'Axon is a long fibre that conducts nerve impulses away from cell body toward another neuron or effector.', 'placeholder', {'label': 'Axon conducts impulse out'}, 'Output fibre of neuron.', 'Motor neuron axon reaches muscle fibre.', 'One axon per neuron typically; can be very long.', 'Myelin on axon speeds impulse — not on dendrites usually.', '', ['axon']),
    ('Cell body (cyton)', 'Cell body contains nucleus and cytoplasm; it integrates incoming signals and maintains the neuron.', 'placeholder', {'label': 'Cell body with nucleus'}, 'Metabolic centre of neuron.', 'If cell body damaged, neuron may not survive.', 'Nucleus in cell body controls protein synthesis for repair.', 'Impulse is regenerated along axon, not in cell body alone.', '', []),
    ('Myelin sheath', 'Myelin is a fatty insulating layer on some axons that speeds up nerve impulse transmission.', 'placeholder', {'label': 'Myelin speeds impulse'}, 'Adaptation for fast conduction.', 'Impulse appears to jump between nodes of Ranvier.', 'More myelin = faster signal in long nerves.', 'Myelin damage (e.g. disease) slows or blocks impulses.', '', ['myelin sheath']),
    ('Synapse preview', 'Axon ends at synapse — junction with next neuron or effector where impulse crosses by chemicals.', 'placeholder', {'label': 'Synapse at axon end'}, 'Leads to Day 4.', 'Gap between two neurons is synaptic cleft.', 'Electrical signal becomes chemical then electrical again.', 'Synapse is not a physical fusion of cells.', '', ['synapse']),
    ('One-way transmission in neuron', 'Impulse travels one way: dendrite/cell body → axon → synapse. Prevents signal chaos.', 'formula_panel', {'formula': 'Dendrite → cell body → axon → synapse', 'note': 'One direction'}, 'Direction rule for diagrams.', 'Impulse does not reverse in same neuron during normal function.', 'Memorise direction for arrow labels.', 'Some axons carry signals toward CNS — still dendrite side receives.', '', []),
    ('Activity 6.1 — nerve tissue', 'Activity 6.1: observe permanent slide of nerve tissue — see bundles of nerve fibres and cell bodies.', 'placeholder', {'label': 'Activity 6.1 — nerve slide'}, 'NCERT microscopy activity.', 'Under microscope, neurons look like thread bundles with dots.', 'Identify axons as long fibres; cell bodies as swollen regions.', 'Nerve tissue slide shows many neurons together.', '', []),
    ('Motor neuron pathway', 'Motor neuron cell body in CNS; axon extends to muscle or gland effector.', 'placeholder', {'label': 'Motor neuron path'}, 'Exam favourite diagram.', 'Spinal motor neuron synapses on muscle fibre.', 'CNS location of cell body is key label.', 'Sensory neuron has receptor end, not muscle end.', '', []),
    ('Sensory neuron pathway', 'Sensory neuron dendrite/receptor end detects stimulus; axon carries impulse to CNS.', 'placeholder', {'label': 'Sensory neuron path'}, 'Pair with motor neuron.', 'Pain receptor in skin → sensory neuron → spinal cord.', 'Receptor at dendrite end near stimulus.', 'Sensory cell body may lie in ganglion outside CNS.', '', []),
])

DAY4 = _build_day(4, [
    ('Synapse — definition', 'A synapse is the junction between two neurons (or neuron and effector) where nerve impulse is transmitted across a gap.', 'placeholder', {'label': 'Synapse defined'}, 'Key Ch 6 structure.', 'Gap between two brain neurons is a synapse.', 'Impulse crosses gap chemically at synapse.', 'Synapse is not continuous cytoplasm between cells.', '', ['synapse']),
    ('Synaptic cleft', 'Synaptic cleft is the tiny gap between axon terminal of one neuron and dendrite of the next.', 'placeholder', {'label': 'Synaptic cleft gap'}, 'Physical gap in diagram.', 'Gap is about 20–40 nanometres — invisible without EM.', 'Impulse cannot jump electrically across cleft alone.', 'Cleft separates pre-synaptic and post-synaptic neurons.', '', []),
    ('Neurotransmitters', 'Neurotransmitters are chemical messengers released at synapse that diffuse across cleft and trigger impulse in next neuron.', 'placeholder', {'label': 'Neurotransmitters cross cleft'}, 'Chemical phase of synaptic transmission.', 'Acetylcholine at many synapses; many types exist.', 'Electrical → chemical → electrical again.', 'Neurotransmitters are not hormones — act locally at synapse.', '', ['neurotransmitter']),
    ('Synaptic transmission steps', 'Impulse reaches axon end → vesicles release neurotransmitter → crosses cleft → binds receptors on next neuron → new impulse starts.', 'formula_panel', {'formula': 'Impulse → chemical → impulse', 'note': 'Synaptic transmission'}, 'Sequence for written answers.', 'One-way crossing prevents backward random firing.', 'Know five-step outline for 3-mark questions.', 'Reuptake of neurotransmitter ends signal — detail optional.', '', []),
    ('Neuromuscular junction', 'Neuromuscular junction is synapse between motor neuron and muscle fibre where impulse triggers contraction.', 'placeholder', {'label': 'Neuron-muscle synapse'}, 'Synapse with effector.', 'Motor nerve ending on biceps triggers movement.', 'Same chemical mechanism as neuron-neuron synapse.', 'Muscle fibre is not a neuron — still has specialised junction.', '', []),
    ('Why synapses matter', 'Synapses allow integration, one-way flow, and adjustment of signals — brain processing depends on synaptic networks.', 'placeholder', {'label': 'Why synapses are important'}, 'Functional significance.', 'Learning may involve strengthening certain synapses.', 'Brain has trillions of synapses.', 'Without synapses, nerves would be simple wires — no processing.', '', []),
    ('Speed at synapse', 'Chemical crossing at synapse is slower than electrical flow along axon — but still very fast.', 'placeholder', {'label': 'Synapse adds slight delay'}, 'Timing concept.', 'Many synapses in path add small delays.', 'Overall reflex still feels instant.', 'Synaptic delay is milliseconds per synapse.', '', []),
    ('Excitatory vs inhibitory synapses', 'Some synapses excite next neuron (start impulse); others inhibit (reduce firing) — brain balances both.', 'placeholder', {'label': 'Excite or inhibit next neuron'}, 'Integration concept preview.', 'Too much inhibition → drowsiness; some drugs affect balance.', 'Not every synapse passes signal forward equally.', 'Class 10 needs concept, not detailed pharmacology.', '', []),
    ('Synapse diagram labels', 'Label: axon terminal, vesicles, synaptic cleft, receptors, dendrite of next neuron.', 'placeholder', {'label': 'Synapse diagram checklist'}, 'Exam diagram skill.', 'Draw two neurons with gap and arrows for neurotransmitter.', 'Practice NCERT-style synapse figure.', 'Pre-synaptic = sender; post-synaptic = receiver.', '', []),
    ('Synapse summary', 'Synapse converts electrical impulse to chemical neurotransmitter and back — enables controlled nervous communication.', 'placeholder', {'label': 'Synapse day summary'}, 'Day 4 consolidation.', 'Explain why impulse is not purely electrical end-to-end.', 'Synapse + neuron structure = core nervous system biology.', '', '', []),
])

DAY5 = _build_day(5, [
    ('Reflex action — definition', 'A reflex action is a sudden, involuntary motor response to a stimulus without conscious involvement of the brain.', 'placeholder', {'label': 'Reflex action defined'}, 'NCERT core concept.', 'Blinking when object approaches eye.', 'Fast, automatic, protective.', 'Brain may know after reflex already happened.', '', ['reflex action']),
    ('Reflex arc — definition', 'Reflex arc is the nerve pathway taken by impulse during a reflex: receptor → sensory → relay → motor → effector.', 'formula_panel', {'formula': 'Receptor → sensory → relay → motor → effector', 'note': 'Reflex arc path'}, 'Must-draw pathway.', 'Hand withdrawal from pin prick follows reflex arc.', 'Minimum five components in order.', 'Reflex arc may bypass brain for speed.', '', ['reflex arc']),
    ('Spinal cord in reflex', 'Many reflexes are processed in spinal cord — impulse reaches cord, relay neuron connects, motor response goes out before brain interprets.', 'placeholder', {'label': 'Spinal cord reflex centre'}, 'Why reflex is fast.', 'Knee jerk: stimulus at knee, integration in spinal cord.', 'Spinal reflex does not mean brain is inactive forever.', 'Brain receives message shortly after response.', '', []),
    ('Example — withdrawal reflex', 'Sharp object touches hand → pain receptor → sensory neuron → spinal cord → motor neuron → arm muscles contract — hand pulls away.', 'placeholder', {'label': 'Hand withdrawal reflex'}, 'Classic NCERT example.', 'Happens before you consciously feel full pain.', 'Protects body from continuing harm.', 'Both arms can reflex — path is specific to stimulus side.', '', []),
    ('Example — knee-jerk reflex', 'Tap on patellar tendon stretches muscle → stretch receptors → sensory to spinal cord → motor to thigh muscle → leg kicks.', 'placeholder', {'label': 'Knee-jerk (patellar) reflex'}, 'Doctor examination reflex.', 'Tests spinal cord and nerve integrity.', 'Involuntary — cannot stop mid-kick easily.', 'Different from voluntary kicking a ball.', '', []),
    ('Blink reflex', 'Object near eye → stimulus detected → rapid reflex closes eyelid to protect cornea.', 'placeholder', {'label': 'Blink reflex protects eye'}, 'Protective reflex example.', 'Wind or flying insect triggers blink.', 'Cornea protection is critical.', 'Some blinks are voluntary too — distinguish context.', '', []),
    ('Advantage of reflexes', 'Reflexes minimise delay and prevent injury by responding before slow conscious thought completes.', 'placeholder', {'label': 'Why reflexes are useful'}, 'Evolutionary advantage.', 'Touching hot stove — reflex saves skin.', 'Speed over conscious decision.', 'Not all situations need reflex — some need thinking.', '', []),
    ('Activity 6.2 — reflex testing', 'Activity 6.2: partner drops ruler; catch measures reaction time — voluntary vs reflex comparison.', 'placeholder', {'label': 'Activity 6.2 — reaction time'}, 'NCERT practical.', 'Shorter distance fallen = faster reaction.', 'Reflex arc is faster than voluntary catch in some tests.', 'Voluntary reaction involves brain processing — slower.', '', []),
    ('Reflex vs voluntary action', 'Reflex: no conscious thought, spinal cord often, very fast. Voluntary: brain decides, slower, learned skill possible.', 'placeholder', {'label': 'Reflex vs voluntary table'}, 'Comparison question.', 'Writing name = voluntary; sneeze reflex = involuntary.', 'Fill comparison table for exams.', 'Sneezing is reflex; holding breath is voluntary override.', '', []),
    ('Reflex arc diagram', 'Draw and label: receptor, sensory neuron, relay neuron in spinal cord (cross-section), motor neuron, effector muscle.', 'placeholder', {'label': 'Reflex arc diagram exam prep'}, 'High-yield diagram.', 'Show spinal cord in cross-section with nerve paths.', 'Practice until labels are automatic.', 'Arrow direction shows impulse flow only one way.', '', []),
])

DAY6 = _build_day(6, [
    ('Human brain — overview', 'Brain is the main coordinating centre of body enclosed in skull; integrates information and controls voluntary and involuntary actions.', 'placeholder', {'label': 'Brain — command centre'}, 'CNS supreme integrator.', 'Brain interprets vision, sound, memory, emotion.', 'Soft, highly protected organ.', 'Brain is part of CNS with spinal cord.', '', ['brain']),
    ('Forebrain — cerebrum', 'Cerebrum is largest part of forebrain; controls thinking, memory, reasoning, voluntary actions, and sensory interpretation.', 'placeholder', {'label': 'Cerebrum — thinking and senses'}, 'Higher functions.', 'Reading this card uses cerebrum.', 'Two hemispheres with many folds (gyri).', 'Cerebrum is not the whole brain — also midbrain, hindbrain.', '', ['cerebrum']),
    ('Forebrain — sensory areas', 'Different regions of cerebrum receive and interpret impulses from eyes, ears, nose, tongue, and skin.', 'placeholder', {'label': 'Sensory areas in cerebrum'}, 'Functional localisation.', 'Visual area at back; touch area in side regions.', 'Damage to area may impair specific sense interpretation.', 'Sensory organ vs sensory area in brain — different.', '', []),
    ('Forebrain — motor areas', 'Motor areas of cerebrum send impulses to voluntary muscles for coordinated movement.', 'placeholder', {'label': 'Motor areas send commands'}, 'Voluntary movement control.', 'Deciding to pick up pen activates motor area.', 'Opposite side often controls opposite body limb.', 'Reflex motor output can bypass cerebrum.', '', []),
    ('Midbrain', 'Midbrain connects forebrain and hindbrain; controls some reflexes connected with vision and hearing.', 'placeholder', {'label': 'Midbrain — vision/hearing reflexes'}, 'Middle section role.', 'Pupil reflex and some eye movement involve midbrain.', 'Smaller region between fore and hindbrain.', 'Not the main thinking centre.', '', ['midbrain']),
    ('Hindbrain — cerebellum', 'Cerebellum coordinates precision of voluntary movements, posture, and balance.', 'placeholder', {'label': 'Cerebellum — balance and precision'}, 'Motor fine-tuning.', 'Cyclist maintains balance using cerebellum.', 'Damage causes shaky, uncoordinated movement.', 'Cerebellum does not initiate movement — cerebrum does.', '', ['cerebellum']),
    ('Hindbrain — medulla', 'Medulla oblongata controls involuntary actions: breathing, heartbeat, blood pressure, swallowing, vomiting.', 'placeholder', {'label': 'Medulla — vital involuntary control'}, 'Life-sustaining centres.', 'Breathing continues during sleep thanks to medulla.', 'Never damage medulla — fatal functions.', 'Medulla is hindbrain, not midbrain.', '', ['medulla']),
    ('Hindbrain — pons', 'Pons connects different regions of brain and helps relay signals between cerebellum and other parts.', 'placeholder', {'label': 'Pons — relay in hindbrain'}, 'Bridge region.', 'Works with medulla for some respiratory rhythm.', 'Part of brainstem with medulla.', 'Less detail required than cerebrum/medulla.', '', []),
    ('Brain diagram practice', 'Label cerebrum, cerebellum, medulla, spinal cord on NCERT brain figure; state one function each.', 'placeholder', {'label': 'Brain diagram labels'}, 'Exam preparation.', 'Side view and top view both appear in textbooks.', 'Function match is common 5-mark question.', 'Spinal cord continues from medulla downward.', '', []),
    ('Brain structure summary', 'Forebrain: thinking and senses. Midbrain: some reflexes. Hindbrain: cerebellum (balance), medulla (vital functions).', 'placeholder', {'label': 'Brain regions summary'}, 'Day 6 consolidation.', 'Make flashcard: region → function.', 'Three main parts with sub-parts.', '', '', []),
])

DAY7 = _build_day(7, [
    ('Skull protects brain', 'Brain is protected by hard skull (cranium) that shields against mechanical injury.', 'placeholder', {'label': 'Skull — bony protection'}, 'First protection layer.', 'Helmet protects skull which protects brain.', 'Bone casing absorbs some impact.', 'Skull protects but concussion still possible.', '', []),
    ('Meninges', 'Brain and spinal cord are wrapped in three membranes called meninges that provide support and protection.', 'placeholder', {'label': 'Three meninges layers'}, 'Membrane protection.', 'Dura, arachnoid, pia — names optional at basic level.', 'Meninges hold CSF and blood vessels.', 'Meningitis is infection of meninges.', '', ['meninges']),
    ('Cerebrospinal fluid (CSF)', 'CSF fills space around brain and spinal cord; acts as shock absorber and supports brain weight.', 'placeholder', {'label': 'CSF shock absorption'}, 'Fluid cushion.', 'Brain floats in CSF inside skull.', 'Reduces impact damage from jolts.', 'CSF is not the same as blood.', '', []),
    ('Vertebral column protects spinal cord', 'Spinal cord runs through vertebral column (backbone) which protects it from injury.', 'placeholder', {'label': 'Vertebrae protect spinal cord'}, 'Spinal cord safety.', 'Spinal injury may cause paralysis if cord damaged.', 'Vertebrae are individual bones in column.', 'Spinal nerves exit between vertebrae.', '', []),
    ('Spinal cord — function', 'Spinal cord relays messages between brain and body and acts as reflex centre for many reflex actions.', 'placeholder', {'label': 'Spinal cord dual role'}, 'Link brain to periphery.', 'Reflex and conscious messages both use cord.', 'Damage disrupts both reflex and voluntary paths.', 'Spinal cord is not just a passive cable — integrates reflexes.', '', ['spinal cord']),
    ('Peripheral nerves from cord', 'Pairs of spinal nerves branch from spinal cord to trunk and limbs carrying sensory and motor fibres.', 'placeholder', {'label': 'Spinal nerves branch out'}, 'PNS connection point.', 'Arm sensation and movement use spinal nerves.', '31 pairs of spinal nerves in humans.', 'Cranial nerves come from brain, not cord.', '', []),
    ('Why brain protection matters', 'Brain tissue cannot regenerate easily; protection prevents permanent loss of coordination, memory, or vital control.', 'placeholder', {'label': 'Why protect CNS'}, 'Health relevance.', 'Wear helmet, avoid diving into shallow water.', 'Prevention better than cure for brain injury.', 'Spinal cord injury is often permanent.', '', []),
    ('Concussion awareness', 'Sudden blow to head can disturb brain function temporarily (concussion) — rest and medical check needed.', 'placeholder', {'label': 'Concussion — brain injury'}, 'Sports safety link.', 'Headache, dizziness after head hit — tell adult.', 'Protection reduces but does not eliminate risk.', 'Not a detailed medical topic — awareness only.', '', []),
    ('Activity 6.3 — brain model / discussion', 'Activity 6.3 explores brain structure and function — identify regions and relate to daily activities.', 'placeholder', {'label': 'Activity 6.3 — brain study'}, 'NCERT activity reference.', 'Discuss which part helps in sport vs study.', 'Relate structure to function in activity.', 'Use NCERT diagram while discussing.', '', []),
    ('CNS protection summary', 'Skull + meninges + CSF protect brain; vertebral column protects spinal cord — essential for safe nervous function.', 'placeholder', {'label': 'Brain protection summary'}, 'Day 7 consolidation.', 'List four protection features in order.', 'Protection theme pairs with brain structure day.', '', '', []),
])

DAY8 = _build_day(8, [
    ('Plants respond to stimuli', 'Plants respond to environmental stimuli such as light, gravity, water, touch, and chemicals — without nervous system.', 'placeholder', {'label': 'Plants detect and respond'}, 'Start plant coordination block.', 'Roots grow toward moist soil.', 'Responses use hormones and turgor changes.', 'Plant response ≠ no response — they are not inactive.', '', []),
    ('Mimosa pudica — touch response', 'Mimosa (touch-me-not) leaves fold and droop when touched — immediate response due to loss of turgor in pulvinus cells.', 'placeholder', {'label': 'Mimosa leaf folding'}, 'NCERT immediate response example.', 'Touch leaf → folds within seconds.', 'Turgor change, not growth, causes movement.', 'Different from tropism which is growth-based.', '', []),
    ('Turgor and plant movement', 'Turgor pressure in plant cells can change quickly, causing reversible movement in some plants.', 'placeholder', {'label': 'Turgor-driven movement'}, 'Mechanism for immediate response.', 'Wilting is loss of turgor; Mimosa pulvinus loses turgor on touch.', 'Water movement between cells changes shape.', 'Growth movements are slower and permanent in direction.', '', ['turgor']),
    ('Sensitive plant pulvinus', 'Pulvinus is swollen base of leaf stalk in Mimosa; cells lose turgor on stimulus spreading folding to whole leaf.', 'placeholder', {'label': 'Pulvinus at leaf base'}, 'Structure behind folding.', 'Stimulus spreads from touched leaflet to others.', 'Localized motor-like tissue in plant.', 'Not found in all plants.', '', []),
    ('Venus flytrap (optional example)', 'Some insectivorous plants snap shut quickly when trigger hairs touched — rapid turgor/movement response.', 'placeholder', {'label': 'Fast trap closure'}, 'Extension example beyond NCERT.', 'Shows plants can have very fast responses.', 'Still not a nervous system — localized mechanism.', 'Optional enrichment, not core exam.', '', []),
    ('Immediate vs tropism again', 'Immediate: reversible, seconds (Mimosa). Tropism: growth response over hours/days toward/away from stimulus.', 'placeholder', {'label': 'Immediate vs tropism contrast'}, 'Critical distinction.', 'Phototropism of shoot takes days to bend clearly.', 'Exam asks difference — know both.', 'Hormones mediate tropisms; turgor often mediates immediate.', '', []),
    ('No nervous system in plants', 'Plants lack neurons and brain; coordination is by hormones diffusing through tissues and local cell changes.', 'placeholder', {'label': 'Plants use hormones not nerves'}, 'Fundamental plant-animal difference.', 'Auxin redistribution bends shoot — no nerve needed.', 'Do not draw reflex arc for plants.', "Plant 'signals' are chemical and slow compared to nerves.", '', []),
    ('Environmental stimuli for plants', 'Light, gravity, water, touch, and day length all act as stimuli for plant responses and growth.', 'placeholder', {'label': 'Plant stimuli list'}, 'Stimulus breadth.', 'Seed germination responds to water and temperature.', 'Same stimulus word as in animals — different mechanism.', '', '', []),
    ('Adaptive value of plant responses', 'Plant responses improve photosynthesis, anchorage, and reproduction — tropisms and touch responses aid survival.', 'placeholder', {'label': 'Why plants respond'}, 'Functional reasoning.', 'Roots toward water prevent drought death.', 'Link response to survival advantage.', '', '', []),
    ('Immediate response summary', 'Mimosa folding is classic immediate plant response via turgor; plants coordinate without nerves using hormones and cell mechanics.', 'placeholder', {'label': 'Plant immediate response summary'}, 'Day 8 consolidation.', 'Contrast Mimosa with sunflower following sun (growth).', 'Two plant response types mastered.', '', '', []),
])

DAY9 = _build_day(9, [
    ('Plant hormones — definition', 'Plant hormones (phytohormones) are chemical compounds produced in plants that control growth and responses at low concentration.', 'placeholder', {'label': 'Phytohormones defined'}, 'Plant chemical coordination.', 'Auxin made in shoot tip controls bending.', 'Hormones move by diffusion or transport.', 'Plant hormones ≠ animal hormones but similar idea.', '', ['phytohormone']),
    ('Auxin', 'Auxin promotes cell elongation in shoots; uneven distribution causes bending toward or away from light.', 'placeholder', {'label': 'Auxin — growth hormone'}, 'Main NCERT plant hormone.', 'Shoot tip cut → plant stops growing upward properly.', 'Made mainly in apical meristem.', 'Auxin in roots inhibits elongation — opposite effect.', '', ['auxin']),
    ('Phototropism', 'Phototropism is growth movement of plant part toward (positive) or away from (negative) light.', 'placeholder', {'label': 'Phototropism — response to light'}, 'Classic tropism.', 'Shoot bends toward window light — positive phototropism.', 'Auxin accumulates on shaded side → more elongation → bend.', 'Roots show negative phototropism.', '', ['phototropism']),
    ('Geotropism (gravitropism)', 'Geotropism is growth response to gravity — roots grow down (positive), shoots grow up (negative).', 'placeholder', {'label': 'Geotropism — gravity response'}, 'Second major tropism.', 'Place seedling horizontally — root bends down, shoot up.', 'Gravity affects auxin distribution.', 'Also called gravitropism.', '', ['geotropism']),
    ('Hydrotropism', 'Hydrotropism is growth of roots toward water — may override geotropism slightly when water is sideways.', 'placeholder', {'label': 'Hydrotropism — toward water'}, 'NCERT root behaviour.', 'Roots bend toward wet soil in uneven moisture setup.', 'Important for drought survival.', 'Demonstrates roots sense moisture gradient.', '', ['hydrotropism']),
    ('Chemotropism', 'Chemotropism is growth toward a chemical — pollen tube grows toward ovule guided by chemical signals.', 'placeholder', {'label': 'Chemotropism — pollen tube'}, 'Reproduction link preview.', 'Pollen tube grows down style toward egg.', 'Chemical gradient directs growth.', 'Connects Ch 6 plant hormones to Ch 7.', '', []),
    ('Gibberellins', 'Gibberellins promote stem elongation, seed germination, and fruit growth.', 'placeholder', {'label': 'Gibberellins — stem growth'}, 'Additional phytohormone.', 'Gibberellin spray can increase grape bunch size.', 'Work with auxin in growth control.', 'Less detail than auxin in Class 10.', '', ['gibberellin']),
    ('Cytokinins', 'Cytokinins promote cell division and delay leaf ageing (senescence).', 'placeholder', {'label': 'Cytokinins — cell division'}, 'Growth coordination hormone.', 'Balance with auxin controls root vs shoot development.', 'Found in growing fruits and seeds.', 'Class 10 — name and general role enough.', '', ['cytokinin']),
    ('Abscisic acid (ABA)', 'Abscisic acid inhibits growth and promotes dormancy and stomatal closure in stress (e.g. drought).', 'placeholder', {'label': 'ABA — stress hormone'}, 'Growth inhibitor role.', 'Closing stomata reduces water loss in drought.', 'Opposite effect to gibberellins in germination.', 'Stress hormone concept for plants.', '', ['abscisic acid']),
    ('Tropisms summary', 'Tropisms are directed growth responses: phototropism (light), geotropism (gravity), hydrotropism (water) — controlled by hormones like auxin.', 'placeholder', {'label': 'Tropisms and hormones summary'}, 'Day 9 consolidation.', 'Draw auxin uneven distribution diagram for phototropism.', 'Positive = toward stimulus; negative = away.', '', '', []),
])

DAY10 = _build_day(10, [
    ('Endocrine system — definition', 'Endocrine system is a collection of ductless glands that secrete hormones directly into blood to regulate body functions.', 'placeholder', {'label': 'Endocrine system defined'}, 'Chemical coordination in animals.', 'Pituitary, thyroid, adrenal among key glands.', 'Hormones travel in blood to target organs.', 'Endocrine glands have no ducts — exocrine have ducts.', '', ['endocrine system']),
    ('Hormone — definition', 'A hormone is a chemical messenger produced by endocrine gland, carried by blood, acting on specific target cells.', 'placeholder', {'label': 'Hormone defined'}, 'Core term Ch 6.', 'Insulin from pancreas lowers blood sugar in liver and muscles.', 'Low concentration, high effect; specific target.', 'Hormones are not enzymes — different roles.', '', ['hormone']),
    ('Ductless glands', 'Endocrine glands release hormones directly into bloodstream; unlike salivary gland which uses duct.', 'placeholder', {'label': 'Ductless vs duct glands'}, 'Structural distinction.', 'Thyroid secretes thyroxine into blood.', 'No tube leading to target — blood carries hormone.', 'Salivary = exocrine with duct to mouth.', '', []),
    ('Target organs', 'Target organs or cells have specific receptors that respond to particular hormones.', 'placeholder', {'label': 'Hormone target specificity'}, "Why hormones don't affect all cells equally.", 'Adrenaline acts on heart and liver during stress.', 'One hormone, specific targets with receptors.', 'All cells are not targets for every hormone.', '', []),
    ('Pituitary gland', 'Pituitary is master endocrine gland at base of brain; secretes hormones controlling other glands and growth.', 'placeholder', {'label': 'Pituitary — master gland'}, 'Key gland list start.', 'Growth hormone from pituitary affects height.', 'Called master gland — controls thyroid, adrenals etc.', 'Tiny but controls many body functions.', '', ['pituitary gland']),
    ('Thyroid gland', 'Thyroid in neck secretes thyroxine regulating carbohydrate, protein, and fat metabolism and growth rate.', 'placeholder', {'label': 'Thyroid — thyroxine'}, 'Metabolism hormone.', 'Iodine needed for thyroxine — goitre if iodine deficient.', 'Over/under secretion affects body weight and energy.', 'Goitre = enlarged thyroid from iodine lack.', '', ['thyroid']),
    ('Adrenal glands', 'Adrenal glands atop kidneys secrete adrenaline (epinephrine) for fight-or-flight response.', 'placeholder', {'label': 'Adrenal — adrenaline'}, 'Emergency hormone.', 'Fear increases heart rate via adrenaline.', 'Prepares body for sudden action.', 'Adrenal cortex and medulla differ — Class 10 focuses on adrenaline.', '', ['adrenal gland']),
    ('Pancreas — dual role', 'Pancreas acts as endocrine gland (insulin, glucagon) and exocrine gland (digestive enzymes).', 'placeholder', {'label': 'Pancreas endocrine + exocrine'}, 'Unique dual gland.', 'Insulin controls blood glucose; pancreatic juice digests food.', 'Islets of Langerhans = endocrine part.', 'Diabetes linked to insulin problem.', '', ['pancreas']),
    ('Endocrine system summary table', 'Know gland → hormone → function: pituitary (GH), thyroid (thyroxine), adrenal (adrenaline), pancreas (insulin).', 'placeholder', {'label': 'Gland-hormone-function table'}, 'Exam table preparation.', 'Fill blank table from memory.', 'Iodised salt prevents thyroid problems.', '', '', []),
    ('Endocrine vs nervous', 'Endocrine: slow, long-lasting, blood transport. Nervous: fast, short-lived, nerve fibres.', 'formula_panel', {'formula': 'Endocrine: blood, slow | Nervous: impulse, fast', 'note': 'Compare coordination modes'}, 'Day 10 opening comparison.', 'Adrenaline is fast for hormone but still uses blood.', 'Both coordinate; often work together.', '', '', []),
])

DAY11 = _build_day(11, [
    ('Insulin — function', 'Insulin secreted by pancreas lowers blood glucose by promoting uptake and storage as glycogen in liver and muscles.', 'placeholder', {'label': 'Insulin lowers blood sugar'}, 'Critical hormone for exams.', 'After meal, insulin rises to store excess glucose.', 'Deficiency causes diabetes mellitus.', 'Insulin does not raise blood sugar — glucagon does.', '', ['insulin']),
    ('Glucagon — function', 'Glucagon from pancreas raises blood glucose by breaking down glycogen in liver when sugar level falls.', 'placeholder', {'label': 'Glucagon raises blood sugar'}, 'Pair with insulin.', 'Between meals glucagon maintains blood glucose.', 'Insulin and glucagon oppose each other.', 'Both from pancreas — balance blood sugar.', '', ['glucagon']),
    ('Feedback mechanism', 'Feedback control: if a level rises, hormone reduces it; if it falls, opposite hormone raises it — maintains balance (homeostasis).', 'formula_panel', {'formula': 'High glucose → insulin ↑ | Low glucose → glucagon ↑', 'note': 'Negative feedback'}, 'Homeostasis concept.', 'Thermostat analogy — sense change, reverse it.', 'Negative feedback stabilises internal conditions.', 'Positive feedback is rare (childbirth) — not core Class 10.', '', ['feedback mechanism']),
    ('Adrenaline — fight or flight', 'Adrenaline increases heart rate, breathing, blood flow to muscles, and glucose release for emergency response.', 'placeholder', {'label': 'Adrenaline emergency response'}, 'Stress hormone effects.', 'Exam fear: sweaty palms, fast heartbeat.', 'Body prepared for intense action quickly.', 'Adrenaline works with sympathetic nervous system.', '', ['adrenaline']),
    ('Growth hormone', 'Growth hormone from pituitary stimulates growth of bones and muscles; deficiency causes dwarfism, excess gigantism in youth.', 'placeholder', {'label': 'Growth hormone (GH)'}, 'Pituitary hormone effect.', 'Childhood height depends on adequate GH.', 'Secreted throughout life but peaks in growth years.', 'Dwarfism/gigantism are pituitary GH disorders.', '', ['growth hormone']),
    ('Thyroxine and iodine', 'Thyroxine requires iodine; deficiency causes goitre and can reduce metabolic rate and mental development in children.', 'placeholder', {'label': 'Iodine for thyroxine'}, 'Nutrition-endocrine link.', 'Iodised salt prevents goitre in population.', 'Hormone needs mineral for its synthesis.', 'Goitre is visible neck swelling — preventable.', '', []),
    ('Diabetes mellitus', 'Diabetes: blood glucose stays high — Type 1 (little insulin) or Type 2 (cells resist insulin); treated with diet, insulin injection, exercise.', 'placeholder', {'label': 'Diabetes — high blood sugar'}, 'Common disorder application.', 'Frequent urination and thirst are symptoms.', 'Insulin injection replaces missing hormone in Type 1.', 'Diabetes is not contagious.', '', ['diabetes']),
    ('Activity 6.4 — iodine and starch / hormone demos', 'Activity 6.4 and related demos show role of iodine and hormone effects — link to thyroid and plant growth experiments.', 'placeholder', {'label': 'Activity 6.4 — iodine/hormones'}, 'NCERT lab connection.', 'Compare plant growth with and without tip.', 'Activities support hormone concept.', 'Relate activity observations to auxin or iodine.', '', []),
    ('Sex hormones preview', 'Testosterone and estrogen control secondary sexual characters at puberty — detailed in reproductive health units.', 'placeholder', {'label': 'Sex hormones at puberty'}, 'Bridge to Ch 7/8.', 'Voice deepens in males due to testosterone.', 'Pituitary hormones trigger sex hormone release.', 'Full detail in adolescence/reproduction chapters.', '', []),
    ('Hormone summary', 'Hormones maintain homeostasis via feedback: insulin/glucagon (sugar), thyroxine (metabolism), adrenaline (stress), GH (growth).', 'placeholder', {'label': 'Hormones day summary'}, 'Day 11 consolidation.', 'Draw feedback loop for blood glucose.', 'Disorder name linked to gland/hormone.', '', '', []),
])

DAY12 = _build_day(12, [
    ('Integration of systems', 'Nervous and endocrine systems work together — nerves can trigger hormone release and hormones affect nerve activity.', 'placeholder', {'label': 'Nervous + endocrine integration'}, 'Day 12 theme.', 'Fear: brain senses → adrenal medulla stimulated → adrenaline released.', 'One stimulus, both systems respond.', 'Integration gives flexible, adaptive responses.', '', []),
    ('Adrenaline and nerves together', 'Sympathetic nervous system stimulates adrenal gland to release adrenaline during stress — dual coordination.', 'placeholder', {'label': 'Nerve triggers adrenaline'}, 'Classic integration example.', 'Stage fright: brain interprets → physical symptoms via adrenaline.', 'Fast nerve signal + sustained hormone effect.', 'Adrenaline is hormone, not neurotransmitter at synapse.', '', []),
    ('Reflex plus hormone', 'Some responses start as reflex then hormones prolong effect — e.g. injury pain reflex then adrenaline maintains alertness.', 'placeholder', {'label': 'Reflex then hormone'}, 'Layered response.', 'Hand pulls from flame (reflex) then shaking continues (adrenaline).', 'Short reflex + longer hormonal state.', '', '', []),
    ('Growth coordination', 'Growth hormone and thyroxine both affect body growth; pituitary and thyroid coordinated by feedback and hypothalamus.', 'placeholder', {'label': 'Hormones in growth'}, 'Long-term integration.', 'Child needs adequate nutrition + hormones for growth.', 'Multiple hormones affect same process.', 'Iodine deficiency affects brain development via thyroxine.', '', []),
    ('Plant-animal coordination contrast', 'Animals: nerves + endocrine glands. Plants: hormones only, growth and turgor responses, no reflex arc.', 'placeholder', {'label': 'Plant vs animal coordination'}, 'Whole chapter comparison.', "Same word 'hormone' — different systems in plant vs animal.", 'Table compare speed, mechanism, examples.', 'Do not attribute brain to plants.', '', []),
    ('Homeostasis', 'Homeostasis is maintaining stable internal conditions (temperature, glucose, water) despite external changes.', 'placeholder', {'label': 'Homeostasis defined'}, 'Unifying concept.', 'Sweating cools body; insulin lowers sugar — both homeostasis.', 'Nervous + endocrine + organs cooperate.', 'Failure of homeostasis → illness.', '', ['homeostasis']),
    ('Temperature regulation (brief)', 'Skin blood flow and sweating help maintain body temperature — nervous and hormonal inputs involved.', 'placeholder', {'label': 'Temperature homeostasis'}, 'Applied integration.', 'Shivering generates heat when cold.', 'Hypothalamus acts as thermostat — detail optional.', 'Not full physiology — overview only.', '', []),
    ('Coordination in daily life', 'Walking, speaking, fighting infection, digesting food, and puberty all need coordinated nervous and hormonal control.', 'placeholder', {'label': 'Coordination in daily activities'}, 'Relatable synthesis.', 'Running: brain, nerves, adrenaline, breathing, heart.', 'Every complex action uses both systems.', '', '', []),
    ('Common exam integration questions', 'Explain how body responds to danger using nervous system AND adrenaline; compare plant tropism with animal reflex.', 'placeholder', {'label': 'Integration exam questions'}, 'Practice prompts.', 'Write dual-system answer for full marks.', "Always give both systems when asked 'how body coordinates'.", '', '', []),
    ('Integration summary', 'Effective coordination = receptors + nerves + brain/spinal cord + hormones + effectors working as one integrated system.', 'placeholder', {'label': 'Integration day summary'}, 'Day 12 consolidation.', 'Draw concept map linking all Ch 6 parts.', 'Prepare for activities review next day.', '', '', []),
])

DAY13 = _build_day(13, [
    ('Activity 6.1 review — nerve tissue slide', 'Observe nerve tissue: identify long fibres (axons) and cell bodies; nerves are bundles of neurons.', 'placeholder', {'label': 'Activity 6.1 recap'}, 'Microscopy skill check.', 'Describe what you see in one paragraph.', 'Link slide to neuron structure day.', '', '', []),
    ('Activity 6.2 review — reflex and reaction', 'Compare reflex speed vs voluntary reaction using ruler drop test; reflex arc bypasses conscious brain path.', 'placeholder', {'label': 'Activity 6.2 recap'}, 'Data interpretation.', 'Record multiple trials; calculate average catch distance.', 'Reflex is faster when pathway is shorter.', '', '', []),
    ('Activity 6.3 review — brain regions', 'Identify cerebrum, cerebellum, medulla on diagram; assign one function to each region studied.', 'placeholder', {'label': 'Activity 6.3 recap'}, 'Brain lab/discussion.', 'Explain which part helps balance on one leg.', 'Medulla controls breathing — never voluntary stop permanently.', '', '', []),
    ('Activity 6.4 review — iodine and growth', 'Relate iodine importance to thyroxine; plant tip removal experiment shows auxin role in growth.', 'placeholder', {'label': 'Activity 6.4 recap'}, 'Chemistry-biology link.', 'Decolourised leaf with alcohol — safety in lab.', 'Iodine test and hormone growth demo combined in chapter activities.', '', '', []),
    ('Reflex arc written practice', 'Write full reflex arc for hand withdrawal with five labelled components in correct order.', 'placeholder', {'label': 'Reflex arc writing practice'}, 'Written exam drill.', 'Marking scheme: labels + sequence + spinal cord.', 'Sensory neuron afferent; motor efferent.', '', '', []),
    ('Gland and hormone matching', 'Practice matching: pituitary-GH, thyroid-thyroxine, adrenal-adrenaline, pancreas-insulin.', 'placeholder', {'label': 'Gland-hormone drill'}, 'Table recall.', 'Add function column without looking.', 'Iodine deficiency → thyroid → goitre chain.', '', '', []),
    ('Tropism experiment design', 'Describe experiment showing phototropism: germinating seed in box with side hole — shoot bends toward light.', 'placeholder', {'label': 'Phototropism experiment'}, 'NCERT-style design question.', 'Control: same setup in open light.', 'Independent variable: light direction.', '', '', []),
    ('Compare coordination modes', 'Fill table: nervous vs hormonal vs plant hormone — speed, pathway, example.', 'placeholder', {'label': 'Three-way comparison table'}, 'Synthesis exercise.', 'Reflex vs adrenaline vs phototropism as examples.', 'One row per coordination type.', '', '', []),
    ('NCERT intext questions Ch 6', 'Review NCERT intext questions on reflex, brain parts, auxin, and insulin.', 'placeholder', {'label': 'NCERT intext review'}, 'Textbook checkpoint.', 'Answer in notebook without notes first.', 'Intext Q often reappear in board exams.', '', '', []),
    ('Activities block summary', 'Activities 6.1–6.4 cover nerve observation, reflex timing, brain function, iodine/hormones — master observations and conclusions.', 'placeholder', {'label': 'Activities 6.1–6.4 summary'}, 'Day 13 consolidation.', "Write 'aim, procedure, observation, conclusion' for each.", 'Activities support diagram and long answers.', '', '', []),
])

DAY14 = _build_day(14, [
    ('Neuron diagram — exam standard', 'Draw neuron with dendrites, cell body, nucleus, axon, myelin sheath, axon terminals — label all.', 'placeholder', {'label': 'Neuron exam diagram'}, 'Diagram day focus.', 'Use pencil; arrows show impulse direction.', 'Cell body must show nucleus.', 'Do not confuse with nerve cross-section.', '', []),
    ('Synapse diagram — exam standard', 'Draw two neurons with synaptic cleft, vesicles, neurotransmitter dots, receptors on post-synaptic dendrite.', 'placeholder', {'label': 'Synapse exam diagram'}, 'High-frequency figure.', 'Label pre- and post-synaptic neurons.', 'Show chemical crossing with arrows.', '', '', []),
    ('Reflex arc diagram — exam standard', 'Full reflex arc with spinal cord cross-section, dorsal sensory root, ventral motor root, effector muscle.', 'placeholder', {'label': 'Reflex arc exam diagram'}, 'Most asked Ch 6 diagram.', 'Relay neuron inside grey matter of cord.', 'Receptor at skin clearly shown.', '', '', []),
    ('Brain diagram — exam standard', 'Side view: cerebrum (large), cerebellum (behind, lower), medulla (joins spinal cord), label functions.', 'placeholder', {'label': 'Brain exam diagram'}, 'Second most asked figure.', 'Spinal cord continues downward.', 'Cerebellum looks like smaller lobe at back.', '', '', []),
    ('Phototropism auxin diagram', 'Show shoot tip, light from one side, auxin more on shaded side, faster elongation, bend toward light.', 'placeholder', {'label': 'Phototropism auxin diagram'}, 'Plant diagram favourite.', 'Arrow for light direction required.', 'Explain in caption below figure.', '', '', []),
    ('Endocrine glands location map', 'Sketch body outline; mark pituitary, thyroid, adrenal, pancreas, testes/ovaries at correct positions.', 'placeholder', {'label': 'Gland location map'}, 'Anatomy recall.', 'Adrenal on top of kidney shape.', 'Pituitary at base of brain.', '', '', []),
    ('Diagram marking tips', 'Use clear labels with leader lines; title each diagram; scale not needed but proportions should be recognisable.', 'placeholder', {'label': 'Diagram scoring tips'}, 'Exam technique.', 'Neatness earns partial credit.', 'Practice timed 5-minute sketches.', '', '', []),
    ('Common diagram errors', 'Swapping dendrite/axon; missing relay neuron in reflex arc; labelling cerebellum as cerebrum.', 'placeholder', {'label': 'Avoid diagram mistakes'}, 'Error prevention.', 'Check list before submitting paper.', "Peer review each other's diagrams.", '', '', []),
    ('Label spelling list', 'Cerebellum, medulla, synapse, dendrite, axon, phototropism, insulin, adrenaline — spell correctly.', 'placeholder', {'label': 'Spelling checklist'}, 'Written exam hygiene.', 'Wrong spelling may lose mark in strict boards.', 'Write glossary on revision card.', '', '', []),
    ('Diagram day summary', 'Master five figures: neuron, synapse, reflex arc, brain, phototropism — draw daily until automatic.', 'placeholder', {'label': 'Diagram day summary'}, 'Day 14 consolidation.', 'Time yourself: five diagrams in 25 minutes.', 'Diagrams carry 3–5 marks each in boards.', '', '', []),
])

DAY15 = _build_day(15, [
    ('3-mark: Define reflex action', 'Reflex: sudden involuntary response to stimulus; example knee jerk or hand withdrawal; via reflex arc.', 'placeholder', {'label': '3-mark reflex definition'}, 'Short answer template.', 'Definition + example + pathway mention.', 'One paragraph, under 80 words.', '', '', []),
    ('3-mark: Plant vs animal coordination', 'Animals use nervous and endocrine systems; plants use hormones; plants show tropisms, animals show reflexes and voluntary actions.', 'placeholder', {'label': '3-mark plant vs animal'}, 'Comparison short answer.', 'Give one example each side.', 'Mention speed difference.', '', '', []),
    ('5-mark: Reflex arc explanation', 'Define reflex arc; draw diagram; explain stimulus to response; state role of spinal cord; give example.', 'placeholder', {'label': '5-mark reflex arc'}, 'Long answer structure.', 'Introduction → diagram → stepwise → conclusion.', 'Allocate 2 marks to diagram.', '', '', []),
    ('5-mark: Hormonal regulation of glucose', 'Explain insulin and glucagon; feedback mechanism; diagram optional; mention diabetes if insulin fails.', 'placeholder', {'label': '5-mark glucose regulation'}, 'Endocrine long answer.', 'Start with normal meal cycle.', 'Negative feedback keyword earns credit.', '', '', []),
    ('5-mark: Brain parts and functions', 'Describe forebrain, midbrain, hindbrain with cerebrum, cerebellum, medulla functions.', 'placeholder', {'label': '5-mark brain functions'}, 'Structure-function answer.', 'One function per region minimum.', 'Use subheadings in answer.', '', '', []),
    ('NCERT exercise Q — tropism', 'Explain phototropism and role of auxin with experiment outline — common textbook question.', 'placeholder', {'label': 'NCERT tropism long Q'}, 'Textbook aligned.', 'Refer to shoot tip hormone production.', 'Control experiment description adds marks.', '', '', []),
    ('Value-based / application question', 'Why iodised salt? Link iodine → thyroxine → metabolism → prevention of goitre and mental retardation.', 'placeholder', {'label': 'Application — iodised salt'}, 'Public health angle.', 'Government fortification programme.', 'Connect biology to daily nutrition.', '', '', []),
    ('Assertion-reason practice', "Practice AR questions: e.g. 'Assertion: Plants have no coordination. Reason: ...' — identify false assertion.", 'placeholder', {'label': 'Assertion-reason Ch 6'}, 'Objective-style written prep.', 'Plants do coordinate via hormones.', 'Read reason carefully — may be true alone.', '', '', []),
    ('Previous year themes', 'Recurring topics: reflex arc diagram, insulin function, difference nervous/hormonal, phototropism.', 'placeholder', {'label': 'Board exam themes Ch 6'}, 'Strategic revision.', 'Collect 5 past questions and answer timed.', 'Themes repeat across years.', '', '', []),
    ('Written prep summary', 'Prepare 3 short + 3 long answers covering reflex, brain, hormones, tropisms, integration.', 'placeholder', {'label': 'Written prep summary'}, 'Day 15 consolidation.', 'Self-mark using NCERT key points.', 'Full answers under exam time limit.', '', '', []),
])

DAY16 = _build_day(16, [
    ('Ch 6 key terms flashcard 1', 'Stimulus, response, receptor, effector, neuron, nerve impulse, synapse, neurotransmitter.', 'placeholder', {'label': 'Key terms set 1'}, 'Term drill.', 'Define each in one line.', 'Cover and recall daily.', '', '', []),
    ('Ch 6 key terms flashcard 2', 'Reflex arc, spinal cord, cerebrum, cerebellum, medulla, auxin, phototropism, geotropism.', 'placeholder', {'label': 'Key terms set 2'}, 'Term drill continued.', 'Match term to example.', 'Second set of eight terms.', '', '', []),
    ('Ch 6 key terms flashcard 3', 'Hormone, endocrine gland, insulin, glucagon, adrenaline, thyroxine, feedback, homeostasis.', 'placeholder', {'label': 'Key terms set 3'}, 'Endocrine term drill.', 'Gland-hormone-function triangle.', 'Third set completes chapter vocabulary.', '', '', []),
    ('Top five comparisons', 'Nervous vs hormonal; reflex vs voluntary; dendrite vs axon; immediate vs tropism plant response; insulin vs glucagon.', 'placeholder', {'label': 'Top five comparison pairs'}, 'Revision checklist.', 'One table per pair.', 'Comparison questions are predictable.', '', '', []),
    ('Must-draw diagrams list', 'Neuron, synapse, reflex arc, brain side view, phototropism — redraw from memory.', 'placeholder', {'label': 'Must-draw five diagrams'}, 'Final diagram check.', 'No notes — pure recall.', 'Done? Unit diagram ready.', '', '', []),
    ('Must-know activities', '6.1 nerve slide; 6.2 reflex; 6.3 brain; 6.4 iodine/growth — aim and conclusion each.', 'placeholder', {'label': 'Four activities recall'}, 'Activity summary.', 'One sentence conclusion per activity.', 'Activities link to long answers.', '', '', []),
    ('Common mistakes to avoid', "Saying plants don't respond; swapping xylem-style transport into nerves; calling insulin a digestive enzyme.", 'placeholder', {'label': 'Avoid common mistakes'}, 'Error correction.', 'Review wrong answers from practice.', 'Fix one misconception per revision pass.', '', '', []),
    ('15-minute mixed quiz prep', 'Mix MCQ themes: gland locations, reflex path order, tropism types, hormone functions.', 'placeholder', {'label': 'Mixed quiz prep'}, 'Pre-practice stage.', 'Use before Stage 2 MCQ days.', 'Timed 15 minutes.', '', '', []),
    ('NCERT chapter summary read', 'Re-read NCERT Ch 6 summary points; tick each concept card topic as covered.', 'placeholder', {'label': 'NCERT summary review'}, 'Textbook closure.', 'Summary at chapter end is exam blueprint.', 'Every summary point has a card.', '', '', []),
    ('Unit 2 complete', 'Unit 2 Control and Coordination complete — 160 concept cards; proceed to Practice when unlocked.', 'placeholder', {'label': 'Unit 2 complete — 160 cards'}, 'Completion card.', 'Next: reproduction and heredity units.', 'Concepts done → practice → NCERT MCQs.', '', '', []),
])


DAY_BUILDERS = {
    1: lambda: DAY1,
    2: lambda: DAY2,
    3: lambda: DAY3,
    4: lambda: DAY4,
    5: lambda: DAY5,
    6: lambda: DAY6,
    7: lambda: DAY7,
    8: lambda: DAY8,
    9: lambda: DAY9,
    10: lambda: DAY10,
    11: lambda: DAY11,
    12: lambda: DAY12,
    13: lambda: DAY13,
    14: lambda: DAY14,
    15: lambda: DAY15,
    16: lambda: DAY16
}

DAY_TITLES = {
    1: "Control and Coordination — Introduction",
    2: "Nervous System — Overview",
    3: "Neurons — Structure and Function",
    4: "Synapse — Nerve to Nerve Junction",
    5: "Reflex Arc and Reflex Actions",
    6: "Brain — Structure and Functions",
    7: "Brain Protection and Spinal Cord",
    8: "Plant Immediate Responses",
    9: "Plant Hormones and Tropisms",
    10: "Endocrine System — Overview",
    11: "Hormones, Feedback and Disorders",
    12: "Integration — Nervous and Endocrine Systems",
    13: "Activities 6.1–6.4 Review",
    14: "Exam Diagrams — Control and Coordination",
    15: "Written Questions — Control and Coordination",
    16: "Revision and Unit 2 Complete"
}
