"""Full concept card content for Harshit Chemistry Unit 3 — Days 1–16 (Ch 3 Metals and Non-metals)."""

from __future__ import annotations


def _card(
    cid: str,
    name: str,
    simple: str,
    visual_type: str,
    visual_config: dict | None,
    why: str,
    example: str,
    remember: str,
    confusion: str = "",
    optional: str = "",
    glossary: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "name": name,
        "simple_answer": simple,
        "visual": {"type": visual_type, **(visual_config or {})},
        "why": why,
        "example": example,
        "remember": remember,
        "common_confusion": confusion,
        "optional_detail": optional,
        "glossary_terms": glossary or [],
    }


def _build_day(day: int, cards: list[tuple]) -> list[dict]:
    out = []
    for i, row in enumerate(cards, 1):
        name, simple, vtype, vcfg, why, ex, rem, *rest = row
        confusion = rest[0] if len(rest) > 0 else ""
        optional = rest[1] if len(rest) > 1 else ""
        gloss = rest[2] if len(rest) > 2 else []
        out.append(
            _card(
                f"u3_d{day}_c{i:02d}",
                name,
                simple,
                vtype,
                vcfg if isinstance(vcfg, dict) else {},
                why,
                ex,
                rem,
                confusion,
                optional,
                gloss if isinstance(gloss, list) else [],
            )
        )
    return out


DAY1 = _build_day(1, [
    ("What are metals?", "Metals are elements that are generally lustrous, malleable, ductile, and good conductors of heat and electricity.", "placeholder", {"label": "Metals — lustrous, malleable, conductive"}, "Foundation of Ch 3 — metals introduced first.", "Iron, copper, aluminium, gold, and silver are familiar metals.", "Lustre + malleability + conductivity = metal clues.", "Not every metal shows all properties — mercury is liquid at room temperature.", "", ["metal"]),
    ("What are non-metals?", "Non-metals are elements that are generally dull, brittle, and poor conductors — with exceptions like graphite and iodine.", "placeholder", {"label": "Non-metals — dull, brittle, poor conductors"}, "Pair concept with metals.", "Carbon, sulphur, oxygen, and chlorine are non-metals.", "Dull + brittle + poor conductor = non-metal clues.", "Graphite conducts electricity — important exception.", "", ["non-metal"]),
    ("Elements classified as metals or non-metals", "About 80% of known elements are metals; rest are non-metals or metalloids on the zig-zag line of the periodic table.", "placeholder", {"label": "Periodic table — metals vs non-metals"}, "NCERT classification overview.", "Left and centre of periodic table = mostly metals.", "Metals dominate the periodic table.", "Metalloids (Si, Ge) show properties of both.", "", []),
    ("Physical vs chemical properties", "Physical properties (lustre, hardness) can be observed without changing substance; chemical properties (reactivity) need a reaction.", "placeholder", {"label": "Physical vs chemical properties"}, "Framework for Days 2–12.", "Shining copper is physical; copper turning green is chemical.", "Physical = no new substance; chemical = reaction.", "Both types matter in Ch 3 exams.", "", []),
    ("Activity 3.1 preview — appearance and hardness", "NCERT Activity 3.1: collect samples of metals and non-metals; observe lustre, hardness, and surface.", "placeholder", {"label": "Activity 3.1 — appearance and hardness"}, "First lab activity anchor.", "Compare iron nail, copper wire, sulphur lump, and carbon.", "Observe before you react — physical properties first.", "Handle samples safely — some are powders or brittle.", "", []),
    ("Common metal samples in Ch 3", "NCERT uses iron, copper, aluminium, magnesium, zinc, lead, and sodium/potassium for reactions.", "placeholder", {"label": "Ch 3 metal samples"}, "Know the substances used in activities.", "Magnesium ribbon burns with dazzling white flame.", "Memorise the common metal list for equations.", "Sodium and potassium stored under kerosene — very reactive.", "", []),
    ("Common non-metal samples in Ch 3", "NCERT uses sulphur, carbon (graphite/diamond), iodine, oxygen, and chlorine in examples.", "placeholder", {"label": "Ch 3 non-metal samples"}, "Know non-metal examples.", "Sulphur is yellow solid; iodine is grey-black solid.", "S, C, I, O, Cl appear throughout chapter.", "Iodine sublimes — solid to vapour directly.", "", []),
    ("Uses of metals in daily life", "Metals used in utensils, wires, construction, jewellery, and vehicles because of strength and conductivity.", "placeholder", {"label": "Metals in daily life"}, "Motivation for studying metals.", "Copper wires carry electricity; aluminium foils wrap food.", "Properties explain everyday uses.", "Alloys (steel, brass) often used instead of pure metals.", "", []),
    ("Uses of non-metals in daily life", "Non-metals essential for life — oxygen for breathing, nitrogen in fertilisers, carbon in all living matter.", "placeholder", {"label": "Non-metals in daily life"}, "Non-metals equally important.", "Graphite in pencil lead; sulphur in matches.", "Non-metals in air, food, and industry.", "Chlorine disinfects drinking water.", "", []),
    ("Chapter 3 roadmap", "Ch 3 covers physical properties, reactions with air/water/acids, reactivity series, ionic bonding, extraction, and corrosion.", "placeholder", {"label": "Ch 3 roadmap — 16 days"}, "Orient learner to unit plan.", "Activities 3.1–3.6 in lab sections.", "Properties → reactions → ions → extraction → corrosion.", "", "", []),
])

DAY2 = _build_day(2, [
    ("Metallic lustre", "Metals have a shining surface called metallic lustre when freshly cut or polished.", "placeholder", {"label": "Metallic lustre — shining surface"}, "Core Day 2 property.", "Freshly cut copper looks reddish-brown and shiny.", "Shiny surface = metallic lustre.", "Tarnished metals lose lustre due to surface oxide layer.", "", ["lustre"]),
    ("Why metals appear lustrous", "Metals reflect light strongly from their surface because of free electrons in the metal lattice.", "placeholder", {"label": "Free electrons reflect light"}, "Conceptual reason for lustre.", "Gold jewellery shines because of metallic bonding.", "Free electrons → light reflection → lustre.", "Non-metals generally do not reflect light this way.", "", []),
    ("Activity 3.1 — testing lustre", "NCERT Activity 3.1: observe iron, copper, aluminium, magnesium, and zinc for lustre; compare with sulphur and carbon.", "placeholder", {"label": "Activity 3.1 — lustre test"}, "Lab observation anchor.", "Iron nail shiny when new; sulphur dull yellow.", "Metals lustrous; non-metals dull.", "Clean surface with sandpaper before observing lustre.", "", []),
    ("Hardness of metals", "Most metals are hard — cannot be cut with a knife; exceptions: sodium and potassium are soft enough to cut.", "placeholder", {"label": "Metals generally hard"}, "Second Day 2 property.", "Iron and copper are hard; sodium cuts with knife.", "Hardness varies — alkali metals are soft.", "Hardness is not the same as strength.", "", ["hardness"]),
    ("Hardness of non-metals", "Non-metals are generally soft (sulphur, iodine) or very hard (diamond — allotrope of carbon).", "placeholder", {"label": "Non-metals — soft or very hard"}, "Contrast with metals.", "Diamond is hardest natural substance — carbon non-metal.", "Non-metal hardness varies widely.", "Diamond hardness is exception — most non-metals brittle.", "", []),
    ("Activity 3.1 — hardness comparison", "Try cutting samples with knife — sodium/potassium cut easily; iron, copper, and zinc do not.", "placeholder", {"label": "Activity 3.1 — hardness test"}, "Hands-on NCERT observation.", "Only alkali metals among samples cut with knife.", "Soft metals = Group 1 (Na, K).", "Never cut sodium without teacher supervision — reacts with moisture.", "", []),
    ("State of metals at room temperature", "Most metals are solid at room temperature; mercury (Hg) is the only liquid metal.", "formula_panel", {"formula": "Most metals: solid | Hg: liquid", "note": "State at room temperature"}, "Physical property for classification.", "Mercury used in thermometers (being phased out).", "Hg is liquid metal — unique exception.", "Gallium melts in hand — slightly above room temp.", "", []),
    ("State of non-metals at room temperature", "Non-metals exist as solids (S, C, I), liquids (bromine), or gases (O₂, N₂, Cl₂) at room temperature.", "formula_panel", {"formula": "Non-metals: solid, liquid (Br), or gas", "note": "More varied states than metals"}, "Broader state range for non-metals.", "Bromine is red-brown liquid non-metal.", "Non-metals show all three states.", "Bromine fumes are toxic — avoid inhalation.", "", []),
    ("Compare lustre — metal vs non-metal", "Metals: lustrous (shiny). Non-metals: generally non-lustrous (dull) — iodine has slight lustre.", "formula_panel", {"formula": "Metal: lustrous | Non-metal: dull", "note": "Iodine exception — lustrous"}, "Exam comparison table entry.", "Compare polished copper with sulphur lump.", "Lustre is quick visual test for classification.", "Iodine crystals show metallic lustre — rare for non-metals.", "", []),
    ("Exam — lustre and hardness", "Define lustre → give metal example → define hardness → compare Na (soft) with Fe (hard) → Activity 3.1 observations.", "placeholder", {"label": "Exam: lustre and hardness template"}, "Structured answer.", "Fresh iron shiny; sulphur dull and soft.", "Two properties + activity reference + examples.", "Always mention mercury as liquid metal if asked about state.", "", []),
])

DAY3 = _build_day(3, [
    ("Malleability definition", "Malleability is the property of metals to be beaten into thin sheets without breaking.", "placeholder", {"label": "Malleability — beaten into sheets"}, "Core Day 3 concept.", "Gold beaten into gold leaf for decoration.", "Hammer metal → thin sheet = malleable.", "Non-metals are not malleable — they crumble.", "", ["malleability"]),
    ("Activity 3.2 — malleability test", "NCERT Activity 3.2: beat iron, copper, aluminium, and zinc with hammer — form thin sheets.", "placeholder", {"label": "Activity 3.2 — malleability"}, "Lab activity anchor.", "Aluminium foil is malleable aluminium sheet.", "Metals form sheets; non-metals powder or break.", "Do not hammer sodium — dangerous reaction with moisture.", "", []),
    ("Gold and silver malleability", "Gold is most malleable — beaten into extremely thin sheets; silver also highly malleable.", "placeholder", {"label": "Gold — most malleable metal"}, "NCERT memorable example.", "Gold leaf on temple domes and picture frames.", "Au and Ag most malleable metals.", "Malleability explains use in jewellery and leaf.", "", []),
    ("Ductility definition", "Ductility is the property of metals to be drawn into thin wires without breaking.", "placeholder", {"label": "Ductility — drawn into wires"}, "Second Day 3 concept.", "Copper and aluminium wires in electrical cables.", "Pull metal → thin wire = ductile.", "Non-metals cannot be drawn into wires.", "", ["ductility"]),
    ("Activity 3.2 — ductility test", "NCERT Activity 3.2: try drawing copper and aluminium into wires — metals extend without snapping.", "placeholder", {"label": "Activity 3.2 — ductility"}, "Lab observation link.", "Copper wire in motor winding.", "Metals form wires; sulphur breaks if pulled.", "Gold wire used in micro-electronics — very ductile.", "", []),
    ("Copper and aluminium wires", "Copper is excellent electrical conductor — used in household wiring; aluminium in overhead power lines.", "placeholder", {"label": "Cu and Al wires — daily use"}, "Application of ductility + conductivity.", "Overhead cables on streets are aluminium.", "Ductility + conductivity → wire use.", "Al lighter than Cu — preferred for long spans.", "", []),
    ("Sonority definition", "Sonority is the property of metals to produce a ringing sound when struck hard.", "placeholder", {"label": "Sonority — ringing sound"}, "Third Day 3 concept.", "School bell and temple bell are metal — sonorous.", "Strike metal → ringing sound = sonorous.", "Non-metals do not ring — dull thud.", "", ["sonority"]),
    ("Activity 3.2 — sonority test", "NCERT Activity 3.2: strike iron, copper, and aluminium — hear ringing; strike sulphur or carbon — dull sound.", "placeholder", {"label": "Activity 3.2 — sonority test"}, "Lab observation anchor.", "Bell metal (bronze alloy) rings clearly.", "Metals ring; non-metals do not.", "Sonority explains use of metals in bells and gongs.", "", []),
    ("Malleability vs ductility", "Malleability = beaten into sheets (hammer). Ductility = drawn into wires (pulling). Both show metal plasticity.", "formula_panel", {"formula": "Malleability: sheets | Ductility: wires", "note": "Both are metal properties"}, "Exam distinction.", "Al foil = malleable; copper wire = ductile.", "Hammer vs pull — different tests.", "Gold is both most malleable and very ductile.", "", []),
    ("Exam — malleability, ductility, sonority", "Define all three → Activity 3.2 for each → examples: gold leaf (malleable), copper wire (ductile), bell (sonorous).", "placeholder", {"label": "Exam: malleability ductility sonority"}, "Three-part answer template.", "Non-metals fail all three tests — contrast.", "Definition + activity + example for each.", "Do not confuse malleability with ductility.", "", []),
])

DAY4 = _build_day(4, [
    ("Heat conductivity of metals", "Metals are good conductors of heat — heat passes quickly through metal.", "placeholder", {"label": "Metals conduct heat well"}, "Core Day 4 concept.", "Metal spoon in hot tea gets hot quickly.", "Heat flows fast through metals.", "Used in cooking pans and radiators.", "", []),
    ("Activity 3.3 — heat conductivity", "NCERT Activity 3.3: hold metal rod in flame — heat reaches far end quickly; compare with non-metal rod.", "placeholder", {"label": "Activity 3.3 — heat conduction"}, "Lab activity anchor.", "Iron rod end gets hot when one end is heated.", "Metal rod conducts heat along length.", "Use tongs — metal gets very hot.", "", []),
    ("Electrical conductivity of metals", "Metals are good conductors of electricity — allow electric current to pass through easily.", "placeholder", {"label": "Metals conduct electricity"}, "Second Day 4 concept.", "Copper wires in household electrical circuits.", "Free electrons carry current in metals.", "Basis for all electrical wiring.", "", []),
    ("Activity 3.3 — electrical conductivity", "NCERT Activity 3.3: connect iron, copper, and aluminium in circuit with bulb — bulb glows; try sulphur or carbon — no glow.", "placeholder", {"label": "Activity 3.3 — electrical test"}, "Lab circuit test.", "Bulb glows with metal in circuit.", "Metals complete circuit; most non-metals do not.", "Use low voltage battery for safety.", "", []),
    ("Why metals conduct electricity", "Metal atoms have loosely held valence electrons (free electrons) that move and carry electric charge.", "formula_panel", {"formula": "Free electrons → current flow", "note": "Metallic bonding explanation"}, "Mechanism for conductivity.", "Same free electrons explain heat conduction.", "Mobile electrons = good conductor.", "Insulators lack free electrons.", "", []),
    ("Uses of heat conductivity", "Metal cooking pans, radiators, and heat sinks use high thermal conductivity.", "placeholder", {"label": "Heat conductivity — daily uses"}, "Application card.", "Copper bottom pans heat food evenly.", "Good heat conductor → cooking utensils.", "Handles often plastic or wood — insulators.", "", []),
    ("Uses of electrical conductivity", "Copper and aluminium wires, electrical contacts, and circuit boards use metal conductors.", "placeholder", {"label": "Electrical conductivity — daily uses"}, "Application card.", "Every electrical appliance has metal wires.", "Conductors carry current in all circuits.", "Gold plating on connectors — resists corrosion.", "", []),
    ("Compare conductivity — metals vs non-metals", "Metals: good conductors of heat and electricity. Non-metals: generally poor conductors (insulators).", "formula_panel", {"formula": "Metal: good conductor | Non-metal: poor conductor", "note": "General rule with exceptions"}, "Key Ch 3 comparison.", "Iron conducts; sulphur does not.", "Conductivity distinguishes metals from non-metals.", "Graphite and iodine are exceptions — see Day 5.", "", []),
    ("Activity 3.3 summary", "Activity 3.3 confirms metals conduct heat and electricity; non-metals (except graphite) do not.", "placeholder", {"label": "Activity 3.3 — summary"}, "Synthesis of Day 4.", "Three tests: heat rod, electric circuit, compare.", "Both heat and electrical tests on same metals.", "Graphite exception tested separately in Activity 3.4.", "", []),
    ("Exam — conductivity of metals", "State metals are good conductors → explain free electrons → Activity 3.3 → uses (wires, pans) → contrast non-metals.", "placeholder", {"label": "Exam: metal conductivity template"}, "Structured answer.", "Cu wires + metal pan as two examples.", "Free electrons link heat and electrical conduction.", "Mention graphite exception briefly.", "", []),
])

DAY5 = _build_day(5, [
    ("Physical properties of non-metals — overview", "Non-metals are generally dull, brittle, non-sonorous, and poor conductors of heat and electricity.", "placeholder", {"label": "Non-metal physical properties"}, "Day 5 theme — contrast with metals.", "Sulphur is dull, brittle, and insulator.", "Opposite of typical metal properties.", "Exceptions exist — always note graphite and iodine.", "", []),
    ("Non-metals are dull (non-lustrous)", "Most non-metals have dull surfaces without metallic shine — sulphur is yellow but not lustrous.", "placeholder", {"label": "Non-metals — dull surface"}, "First non-metal property.", "Compare shiny copper with dull sulphur lump.", "No metallic lustre on most non-metals.", "Iodine crystals show slight lustre — exception.", "", []),
    ("Non-metals are brittle", "Non-metals break into pieces when hammered — not malleable or ductile.", "placeholder", {"label": "Non-metals — brittle"}, "Second non-metal property.", "Sulphur crumbles when hammered.", "Brittle = breaks, not bends.", "Diamond is hard but still brittle — shatters.", "", []),
    ("Activity 3.4 — non-metal properties", "NCERT Activity 3.4: test sulphur and carbon — dull, brittle, non-sonorous, do not conduct (except graphite).", "placeholder", {"label": "Activity 3.4 — non-metal tests"}, "Lab activity anchor.", "Sulphur powder after hammering.", "All four properties tested on non-metals.", "Graphite tested separately for conductivity.", "", []),
    ("Non-metals poor heat conductors", "Non-metals are bad conductors of heat — insulators; wood and plastic handles stay cool.", "placeholder", {"label": "Non-metals — poor heat conductors"}, "Thermal insulator property.", "Wooden spoon stays cool in hot soup.", "Heat does not pass easily through non-metals.", "Air (mixture) is also poor conductor — wool traps air.", "", []),
    ("Non-metals poor electrical conductors", "Most non-metals do not conduct electricity — used as insulators in cables and equipment.", "placeholder", {"label": "Non-metals — electrical insulators"}, "Electrical insulator property.", "Rubber and plastic coating on wires.", "No free electrons → no current flow.", "Insulators protect from electric shock.", "", []),
    ("Exception — graphite conducts electricity", "Graphite (allotrope of carbon) conducts electricity — used in pencil lead and electrodes.", "formula_panel", {"formula": "Graphite (C) — conducts electricity", "note": "Exception among non-metals"}, "Critical NCERT exception.", "Dry cell electrode contains graphite.", "Graphite is non-metal that conducts.", "Graphite conducts but sulphur and diamond do not.", "", []),
    ("Exception — iodine lustre", "Iodine is a non-metal with lustrous grey-black crystals — sublimes on heating.", "placeholder", {"label": "Iodine — lustrous non-metal"}, "Second NCERT exception.", "Iodine tincture used as antiseptic.", "Iodine has metallic appearance but is non-metal.", "Iodine sublimes — solid to vapour without melting.", "", []),
    ("Allotropes of carbon", "Carbon exists as diamond (hard, insulator) and graphite (soft, conductor) — same element, different properties.", "formula_panel", {"formula": "Diamond: hard, insulator | Graphite: soft, conductor", "note": "Allotropes of carbon"}, "Important NCERT comparison.", "Pencil lead is graphite; diamond in jewellery.", "Same element — different arrangement.", "Fullerene and graphene beyond Class 10 scope.", "", []),
    ("Exam — non-metal physical properties", "List dull, brittle, non-sonorous, poor conductor → Activity 3.4 → exceptions: graphite (conducts), iodine (lustrous).", "placeholder", {"label": "Exam: non-metal properties template"}, "Structured answer with exceptions.", "Always mention graphite and iodine exceptions.", "Four properties + two exceptions = full marks.", "Do not say all non-metals are gases — many are solids.", "", []),
])

DAY6 = _build_day(6, [
    ("Metals react with oxygen in air", "Most metals combine with oxygen when heated or burned to form metal oxides.", "formula_panel", {"formula": "Metal + O₂ → Metal oxide", "note": "General reaction with air"}, "Core Day 6 pattern.", "Magnesium burns with dazzling white flame.", "Burning metal → metal oxide.", "Some oxides protective; others flaky.", "", []),
    ("Activity 3.5 — burning magnesium", "NCERT Activity 3.5: burn magnesium ribbon in air — dazzling white flame; white ash MgO forms.", "formula_panel", {"formula": "2Mg + O₂ → 2MgO", "note": "Magnesium oxide — white ash"}, "Classic NCERT burning demo.", "Mg ribbon cleaned with sandpaper before burning.", "White ash = magnesium oxide.", "Never look directly at burning Mg — very bright.", "", []),
    ("Activity 3.5 — burning copper", "Heat copper wire in flame — black copper(II) oxide CuO forms on surface.", "formula_panel", {"formula": "2Cu + O₂ → 2CuO", "note": "Black copper oxide layer"}, "Second Activity 3.5 example.", "Copper vessel bottom turns black on heating.", "Black coating = CuO.", "Green patina on old copper is basic carbonate — not Day 6 focus.", "", []),
    ("Activity 3.5 — burning aluminium", "Aluminium forms white aluminium oxide Al₂O₃ layer — protects metal from further corrosion.", "formula_panel", {"formula": "4Al + 3O₂ → 2Al₂O₃", "note": "Protective oxide layer"}, "Protective oxide example.", "Aluminium utensils resist rust due to Al₂O₃ layer.", "Al₂O₃ layer prevents further reaction.", "Anodised aluminium has thicker oxide layer.", "", []),
    ("Iron burns in air", "Iron does not burn easily in air at room temperature but forms rust slowly; iron filings burn in flame.", "formula_panel", {"formula": "Iron + O₂ → Fe₂O₃ / Fe₃O₄", "note": "Rust and oxides"}, "Iron oxidation link to corrosion.", "Iron filings spark in Bunsen flame.", "Iron rusts slowly at room temperature.", "Rust is hydrated iron oxide — Day 15 detail.", "", []),
    ("Sodium and potassium in air", "Sodium and potassium react vigorously with oxygen at room temperature — stored under kerosene.", "formula_panel", {"formula": "4Na + O₂ → 2Na₂O", "note": "Stored under kerosene"}, "Highly reactive metals.", "Na cut surface tarnishes instantly in air.", "Never leave Na/K exposed to air.", "K reacts even faster than Na with oxygen.", "", []),
    ("Metal oxides are generally basic", "Metal oxides are basic in nature — turn red litmus blue; react with acids (links Ch 2).", "formula_panel", {"formula": "Metal oxide + Acid → Salt + Water", "note": "Basic oxide — Ch 2 link"}, "Cross-chapter link.", "MgO reacts with HCl — neutralisation type.", "Metal oxide = basic oxide.", "Amphoteric oxides (Al₂O₃, ZnO) are exceptions.", "", []),
    ("Non-metals burn in air", "Non-metals combine with oxygen to form non-metal oxides — often acidic or neutral.", "formula_panel", {"formula": "Non-metal + O₂ → Non-metal oxide", "note": "Often acidic oxide"}, "Contrast with metal oxides.", "S + O₂ → SO₂; C + O₂ → CO₂.", "Non-metal oxides often acidic.", "SO₂ and CO₂ dissolve in water forming acids.", "", []),
    ("Compare metal vs non-metal oxides", "Metal oxides: basic (MgO, CuO). Non-metal oxides: acidic (CO₂, SO₂).", "formula_panel", {"formula": "Metal oxide: basic | Non-metal oxide: acidic", "note": "Ch 2 and Ch 3 link"}, "Key exam comparison.", "MgO basic; CO₂ forms carbonic acid in water.", "Basic vs acidic oxides — opposite nature.", "CO and N₂O are neutral oxides — exceptions.", "", []),
    ("Exam — metals burned in air", "General equation → Mg, Cu, Al examples with balanced equations → Activity 3.5 → basic nature of metal oxides.", "placeholder", {"label": "Exam: metal + oxygen template"}, "Structured answer.", "2Mg + O₂ → 2MgO with white flame observation.", "Equation + observation + oxide nature.", "Balance all equations for full marks.", "", []),
])

DAY7 = _build_day(7, [
    ("Metals react with water — overview", "Some metals react with water to form metal hydroxide and hydrogen gas; reactivity varies greatly.", "formula_panel", {"formula": "Metal + Water → Metal hydroxide + H₂", "note": "General pattern (where reaction occurs)"}, "Day 7 core theme.", "Sodium reacts violently with cold water.", "Not all metals react with water.", "Product depends on metal reactivity.", "", []),
    ("Sodium with cold water", "Sodium reacts vigorously with cold water — moves on surface, melts, H₂ gas evolved, solution alkaline.", "formula_panel", {"formula": "2Na + 2H₂O → 2NaOH + H₂", "note": "Violent reaction — cold water"}, "Most dramatic NCERT example.", "Na piece fizzes and may catch fire.", "Na + cold water → NaOH + H₂.", "Never add large Na piece to water unsupervised.", "", []),
    ("Potassium with cold water", "Potassium reacts even more vigorously than sodium — catches fire with lilac flame.", "formula_panel", {"formula": "2K + 2H₂O → 2KOH + H₂", "note": "More violent than sodium"}, "More reactive alkali metal.", "K explodes on water surface.", "K faster than Na — lower in series but same group.", "Lilac flame colour characteristic of potassium.", "", []),
    ("Calcium with cold water", "Calcium reacts with cold water moderately — bubbles of H₂, milky Ca(OH)₂ solution.", "formula_panel", {"formula": "Ca + 2H₂O → Ca(OH)₂ + H₂", "note": "Limewater formed — milky"}, "Moderate reactivity example.", "Ca(OH)₂ is limewater — turns milky with CO₂.", "Ca less violent than Na/K.", "Milky suspension — Ca(OH)₂ slightly soluble.", "", []),
    ("Magnesium with hot water", "Magnesium reacts slowly with hot water or steam — Mg(OH)₂ and H₂ formed.", "formula_panel", {"formula": "Mg + 2H₂O → Mg(OH)₂ + H₂", "note": "Hot water or steam needed"}, "Less reactive than Ca.", "Mg ribbon in boiling water reacts slowly.", "Mg needs hot water — not cold.", "Mg(OH)₂ is milk of magnesia — antacid.", "", []),
    ("Iron with steam", "Iron reacts with steam at high temperature to form iron(II,III) oxide and hydrogen.", "formula_panel", {"formula": "3Fe + 4H₂O → Fe₃O₄ + 4H₂", "note": "Steam — not cold water"}, "NCERT steam reaction.", "Iron glows red hot in steam — H₂ collected.", "Fe does not react with cold water.", "Fe₃O₄ is magnetic iron oxide.", "", []),
    ("Less reactive metals and water", "Aluminium, zinc, and lead do not react with cold or hot water; aluminium reacts with steam.", "formula_panel", {"formula": "2Al + 3H₂O → Al₂O₃ + 3H₂", "note": "Steam only for Al"}, "Lower reactivity group.", "Al foil does not react with water at room temp.", "Reactivity decreases down practical list.", "Copper, silver, gold — no reaction with water.", "", []),
    ("Testing hydrogen from metal + water", "Bring burning splint to gas — hydrogen burns with pop sound.", "placeholder", {"label": "H₂ test — pop sound"}, "Same test as Ch 2 acid + metal.", "Pop sound confirms H₂ from Na + water.", "Pop test = hydrogen.", "Do not confuse with oxygen — relights splint.", "", []),
    ("Activity 3.6 — metals and water", "NCERT Activity 3.6: add Na, Ca, Mg, Fe, Cu to water — observe which react and how vigorously.", "placeholder", {"label": "Activity 3.6 — metal + water"}, "Lab activity anchor.", "Only Na, K, Ca react with cold water visibly.", "Compare vigour: K > Na > Ca > Mg (hot) > Fe (steam).", "Cu placed in water — no reaction.", "", []),
    ("Exam — metals and water", "General equation → Na, Ca, Mg, Fe examples with conditions (cold/hot/steam) → H₂ pop test → reactivity trend.", "placeholder", {"label": "Exam: metal + water template"}, "Structured answer.", "State water temperature needed for each metal.", "Conditions matter — cold vs hot vs steam.", "Cu, Ag, Au — no reaction with water.", "", []),
])

DAY8 = _build_day(8, [
    ("Metal + acid — general reaction", "Acid reacts with reactive metal to give salt and hydrogen gas.", "formula_panel", {"formula": "Metal + Acid → Salt + H₂ ↑", "note": "Same as Ch 2 pattern"}, "Day 8 core — links Ch 2.", "Zn + HCl → ZnCl₂ + H₂.", "Metal displaces H from acid.", "Only metals above H in reactivity series.", "", []),
    ("Zinc and dilute HCl", "Zn + 2HCl → ZnCl₂ + H₂ — bubbles of hydrogen, zinc dissolves.", "formula_panel", {"formula": "Zn + 2HCl → ZnCl₂ + H₂", "note": "Zinc chloride + hydrogen"}, "Classic NCERT example.", "Activity in Ch 2 and Ch 3 context.", "Zinc above hydrogen — reacts.", "Copper below hydrogen — no reaction with dilute HCl.", "", []),
    ("Iron and dilute H₂SO₄", "Fe + H₂SO₄ → FeSO₄ + H₂ — iron nails produce hydrogen slowly.", "formula_panel", {"formula": "Fe + H₂SO₄ → FeSO₄ + H₂", "note": "Ferrous sulphate + H₂"}, "Second metal-acid example.", "Pale green FeSO₄ solution forms.", "Iron reacts with dilute acids.", "Conc. HNO₃ may not give H₂ — oxidising acid.", "", []),
    ("Magnesium and dilute acid", "Mg + 2HCl → MgCl₂ + H₂ — vigorous reaction, hydrogen evolved rapidly.", "formula_panel", {"formula": "Mg + 2HCl → MgCl₂ + H₂", "note": "Vigorous — Mg highly reactive"}, "More reactive than Zn and Fe.", "Mg ribbon reacts faster than Zn.", "Same pattern: salt + H₂.", "Reaction exothermic — test tube warms.", "", []),
    ("Aluminium and dilute acid", "2Al + 6HCl → 2AlCl₃ + 3H₂ — aluminium reacts after oxide layer removed.", "formula_panel", {"formula": "2Al + 6HCl → 2AlCl₃ + 3H₂", "note": "Remove Al₂O₃ layer first"}, "Protective oxide must be removed.", "Sandpaper Al before acid test.", "Al₂O₃ layer initially prevents reaction.", "AlCl₃ dissolved in water — aluminium chloride.", "", []),
    ("Copper and dilute acid — no reaction", "Copper does not react with dilute HCl or H₂SO₄ — below hydrogen in reactivity series.", "formula_panel", {"formula": "Cu + HCl → No reaction", "note": "Cu below H in series"}, "Important negative example.", "Cu metal placed in HCl — no bubbles.", "Cu cannot displace H from dilute acid.", "Hot conc. HNO₃ reacts with Cu — different reaction.", "", []),
    ("Testing hydrogen gas", "Bring burning splint to mouth of tube — hydrogen burns with characteristic pop sound.", "placeholder", {"label": "H₂ test — pop sound"}, "Confirmatory test from Ch 2.", "Pop sound = H₂ confirmed.", "Same test for acid + metal and water + metal.", "Oxygen relights glowing splint — different test.", "", []),
    ("Salt name from acid", "HCl → chloride; H₂SO₄ → sulphate; HNO₃ → nitrate — acid determines salt anion.", "formula_panel", {"formula": "HCl → chloride | H₂SO₄ → sulphate", "note": "Acid anion names salt"}, "Naming products.", "Zn + HCl → zinc chloride.", "Anion from acid names the salt.", "Same naming as Ch 2.", "", []),
    ("Reactivity and acid reaction", "More reactive metals react faster and more vigorously with dilute acids.", "placeholder", {"label": "More reactive → faster reaction"}, "Trend within acid reactions.", "Mg reacts faster than Zn; Zn faster than Fe.", "Reactivity series predicts acid reaction.", "Ag and Au do not react with dilute acids.", "", []),
    ("Exam — metal + acid", "General equation → Zn/Fe/Mg examples → H₂ pop test → explain why Cu does not react → reactivity series link.", "placeholder", {"label": "Exam: metal + acid template"}, "Structured answer.", "Three-part: equation + salt name + H₂ test.", "Cu no reaction — below hydrogen — key point.", "Balance equations for full marks.", "", []),
])

DAY9 = _build_day(9, [
    ("Displacement reaction definition", "A more reactive metal displaces a less reactive metal from its salt solution.", "formula_panel", {"formula": "More reactive metal + Salt of less reactive metal → Displacement", "note": "Reactivity drives reaction"}, "Core Day 9 concept.", "Zinc displaces copper from CuSO₄ solution.", "Higher in series displaces lower.", "No reaction if metal is less reactive than salt metal.", "", ["displacement reaction"]),
    ("Zinc and copper sulphate", "Zn + CuSO₄ → ZnSO₄ + Cu — iron grey zinc displaces red-brown copper.", "formula_panel", {"formula": "Zn + CuSO₄ → ZnSO₄ + Cu", "note": "Blue solution fades; copper deposited"}, "Most important NCERT displacement example.", "Blue CuSO₄ solution becomes colourless ZnSO₄.", "Zn more reactive than Cu — displacement occurs.", "Copper deposits as red-brown solid on zinc.", "", []),
    ("Iron and copper sulphate", "Fe + CuSO₄ → FeSO₄ + Cu — iron displaces copper from blue solution.", "formula_panel", {"formula": "Fe + CuSO₄ → FeSO₄ + Cu", "note": "Iron displaces copper"}, "Second displacement example.", "Iron nail in CuSO₄ gets copper coating.", "Fe above Cu in reactivity series.", "Pale green FeSO₄ solution forms.", "", []),
    ("Copper and zinc sulphate — no reaction", "Copper cannot displace zinc from ZnSO₄ — Cu less reactive than Zn.", "formula_panel", {"formula": "Cu + ZnSO₄ → No reaction", "note": "Cu below Zn in series"}, "Important negative example.", "Cu metal in ZnSO₄ — no change.", "Less reactive cannot displace more reactive.", "Predicting no reaction is exam skill.", "", []),
    ("Silver and copper sulphate — no reaction", "Silver does not displace copper from CuSO₄ — Ag less reactive than Cu.", "formula_panel", {"formula": "Ag + CuSO₄ → No reaction", "note": "Ag below Cu in series"}, "Second negative example.", "Ag coin in CuSO₄ — no reaction.", "Ag near bottom of reactivity series.", "Gold also does not displace copper.", "", []),
    ("Observations in displacement", "Colour change in solution, metal deposit on strip, original metal dissolves or reacts.", "placeholder", {"label": "Displacement observations"}, "What to record in lab.", "Blue → colourless + red-brown Cu on Zn.", "Watch solution colour and metal coating.", "Write observations before equation in exam.", "", []),
    ("Activity 3.7 — displacement reactions", "NCERT Activity 3.7: place Zn, Fe, Cu, Ag in various salt solutions — observe displacement.", "placeholder", {"label": "Activity 3.7 — displacement"}, "Lab activity anchor.", "Test Zn in CuSO₄, Cu in ZnSO₄, Fe in CuSO₄.", "More reactive metal in less reactive salt.", "Systematic table of metal vs salt results.", "", []),
    ("Displacement and reactivity series", "Displacement reactions prove and use the reactivity series — higher displaces lower.", "formula_panel", {"formula": "If Metal A > Metal B → A displaces B from B's salt", "note": "Reactivity series rule"}, "Link to Day 10.", "Zn > Fe > Cu > Ag order confirmed by displacement.", "Series predicts displacement outcome.", "Single displacement — one metal swaps.", "", []),
    ("Double displacement vs single displacement", "Ch 3 displacement is single — one element replaces another. Ch 1 double displacement swaps ions.", "formula_panel", {"formula": "Single: Zn + CuSO₄ | Double: AB + CD → AD + CB", "note": "Different reaction types"}, "Avoid confusion with Ch 1.", "Zn + CuSO₄ is single displacement.", "One metal replaces another metal ion.", "Precipitation reactions are double displacement.", "", []),
    ("Exam — displacement reactions", "Define displacement → Zn + CuSO₄ equation and observations → explain why Cu + ZnSO₄ no reaction → Activity 3.7.", "placeholder", {"label": "Exam: displacement template"}, "Structured answer.", "Blue fades, red-brown Cu, Zn dissolves.", "Equation + observation + reactivity reason.", "Always state which metal is more reactive.", "", []),
])

DAY10 = _build_day(10, [
    ("Reactivity series definition", "Reactivity series arranges metals in order of decreasing reactivity — most reactive at top.", "formula_panel", {"formula": "K > Na > Ca > Mg > Al > Zn > Fe > Pb > Cu > Hg > Ag", "note": "NCERT reactivity series"}, "Central Day 10 concept.", "K and Na most reactive; Ag least reactive common metal.", "Top = most reactive; bottom = least.", "Hydrogen included as reference point.", "", ["reactivity series"]),
    ("Full NCERT reactivity series", "K, Na, Ca, Mg, Al, Zn, Fe, Pb, (H), Cu, Hg, Ag — memorise this order.", "formula_panel", {"formula": "K Na Ca Mg Al Zn Fe Pb Cu Hg Ag", "note": "Mnemonic: Please send charlie's monkeys and zebras..."}, "Must-memorise for exams.", "Mnemonic helps recall order.", "Hydrogen position between Pb and Cu.", "Au and Pt even less reactive than Ag.", "", []),
    ("Most reactive metals — K, Na, Ca", "Potassium, sodium, and calcium react vigorously with cold water and air.", "placeholder", {"label": "K, Na, Ca — most reactive"}, "Top of series behaviour.", "Na stored under kerosene.", "Top three react with cold water.", "Never handle Na/K without proper supervision.", "", []),
    ("Middle reactivity — Mg, Al, Zn, Fe", "Magnesium, aluminium, zinc, and iron react with acids; Al needs oxide removed; Fe rusts.", "placeholder", {"label": "Mg, Al, Zn, Fe — middle reactivity"}, "Middle of series behaviour.", "Zn and Fe common in displacement examples.", "React with dilute acids — above hydrogen.", "Al protected by Al₂O₃ layer.", "", []),
    ("Least reactive — Cu, Hg, Ag", "Copper, mercury, and silver do not react with dilute acids or cold water; found free in nature.", "placeholder", {"label": "Cu, Hg, Ag — least reactive"}, "Bottom of series behaviour.", "Silver and gold jewellery — unreacted metal.", "Low reactivity → occur native/free.", "Cu reacts slowly with moist air — green patina.", "", []),
    ("Hydrogen in reactivity series", "Hydrogen placed between lead and copper — metals above H displace H from dilute acids.", "formula_panel", {"formula": "Metal above H → reacts with dilute acid → H₂", "note": "H as reference in series"}, "Explains acid reactions.", "Zn above H — gives H₂ with HCl.", "Below H — no H₂ from dilute acid.", "H not a metal but used as benchmark.", "", []),
    ("Reactivity series predicts reactions", "Series predicts: water reactions, acid reactions, displacement, and extraction method.", "placeholder", {"label": "Series predicts all Ch 3 reactions"}, "Unifying exam concept.", "K reacts with cold water; Cu does not.", "One series — many predictions.", "Higher metal reduces lower metal oxide.", "", []),
    ("Relative reactivity comparisons", "Exam asks: 'Which is more reactive, Zn or Fe?' — Zn is higher in series.", "formula_panel", {"formula": "Zn > Fe > Cu", "note": "Common comparison triple"}, "Quick comparison skill.", "Zn displaces Fe? No — both react with acid but Zn displaces Cu.", "Higher in list = more reactive.", "Compare positions, not properties alone.", "", []),
    ("Reactivity and extraction link", "Highly reactive metals (Na, Ca, Al) extracted by electrolysis; less reactive by reduction with C.", "placeholder", {"label": "Reactivity → extraction method"}, "Preview Day 13–14.", "Al from bauxite by electrolysis.", "More reactive = harder to extract = electrolysis.", "Cu and Hg extracted by heating sulphide ore.", "", []),
    ("Exam — reactivity series", "Write full series → explain one reaction prediction (water/acid/displacement) → compare two metals → mnemonic.", "placeholder", {"label": "Exam: reactivity series template"}, "Structured answer.", "K Na Ca Mg Al Zn Fe Pb Cu Hg Ag — write completely.", "One application example mandatory.", "Include H position between Pb and Cu.", "", []),
])

DAY11 = _build_day(11, [
    ("How metals and non-metals react", "Metals and non-metals react by transfer of electrons — metal loses electrons, non-metal gains.", "formula_panel", {"formula": "Metal → loses e⁻ | Non-metal → gains e⁻", "note": "Electron transfer reaction"}, "Core Day 11 concept.", "Na gives electron to Cl forming NaCl.", "Electron transfer = ionic bond formation.", "Not sharing — transfer (ionic compounds).", "", ["ionic bond"]),
    ("Metal atoms lose electrons", "Metal atoms have 1–3 valence electrons — easily lost to form positive ions (cations).", "formula_panel", {"formula": "Na → Na⁺ + e⁻", "note": "Metal forms cation"}, "First half of electron transfer.", "Sodium loses 1 electron → Na⁺.", "Metal → positive ion (cation).", "More reactive metals lose electrons more easily.", "", []),
    ("Non-metal atoms gain electrons", "Non-metal atoms have 5–7 valence electrons — gain electrons to complete octet, form negative ions (anions).", "formula_panel", {"formula": "Cl + e⁻ → Cl⁻", "note": "Non-metal forms anion"}, "Second half of electron transfer.", "Chlorine gains 1 electron → Cl⁻.", "Non-metal → negative ion (anion).", "Gaining electrons completes outer shell.", "", []),
    ("Formation of sodium chloride NaCl", "Sodium donates 1 e⁻ to chlorine — Na⁺ and Cl⁻ attract electrostatically forming NaCl.", "formula_panel", {"formula": "Na + Cl → Na⁺Cl⁻ (NaCl)", "note": "Ionic compound — electron transfer"}, "Classic NCERT ionic example.", "Table salt — ionic crystal lattice.", "Na⁺ + Cl⁻ held by electrostatic force.", "NaCl solid — ions packed in crystal.", "", []),
    ("Formation of magnesium chloride MgCl₂", "Magnesium loses 2 electrons; two chlorine atoms each gain 1 — Mg²⁺ and 2Cl⁻ form MgCl₂.", "formula_panel", {"formula": "Mg + 2Cl → Mg²⁺(Cl⁻)₂", "note": "Mg loses 2 e⁻"}, "Divalent metal example.", "MgCl₂ used in tofu and road de-icing.", "Balance electrons: Mg gives 2, each Cl takes 1.", "Mg²⁺ needs two Cl⁻ for neutral compound.", "", []),
    ("Electron dot structure — NaCl", "Show Na with 1 dot (valence e⁻) transferring to Cl (7 dots → 8) — Na⁺ and Cl⁻ formed.", "placeholder", {"label": "Electron dot — NaCl formation"}, "NCERT diagram skill.", "Draw Na atom, Cl atom, then ions.", "Dot structure shows electron transfer.", "Cl⁻ has 8 outer electrons after gaining.", "", []),
    ("Ionic compounds definition", "Compounds formed by transfer of electrons between metal and non-metal — contain ions.", "formula_panel", {"formula": "Ionic compound = Cation + Anion", "note": "Held by electrostatic attraction"}, "Definition for exams.", "NaCl, MgO, CaCl₂ are ionic.", "Metal + non-metal → usually ionic.", "Not all metal-non-metal compounds ionic — SnCl₄ covalent (advanced).", "", ["ionic compound"]),
    ("Electrovalency", "Electrovalency is the number of electrons lost or gained — equals charge on ion.", "formula_panel", {"formula": "Na⁺: electrovalency 1 | Mg²⁺: electrovalency 2", "note": "Charge = valency in ionic compounds"}, "NCERT term.", "Cl⁻ has electrovalency 1.", "Electrovalency = electrons transferred.", "Same as valency for main group elements.", "", []),
    ("Compare metal vs non-metal electron behaviour", "Metals: lose e⁻, form cations, low ionisation energy. Non-metals: gain e⁻, form anions, high electron affinity.", "formula_panel", {"formula": "Metal: cation (+) | Non-metal: anion (−)", "note": "Opposite electron behaviour"}, "Exam comparison.", "Na loses; Cl gains — opposite tendencies.", "Opposite behaviour enables ionic bond.", "Metalloids can do both — borderline.", "", []),
    ("Exam — electron transfer and ions", "Explain electron transfer → NaCl formation with equations → dot structure → define ionic compound.", "placeholder", {"label": "Exam: ion formation template"}, "Structured answer.", "Na → Na⁺ + e⁻; Cl + e⁻ → Cl⁻; Na⁺ + Cl⁻ → NaCl.", "Draw dot structure for marks.", "State cation and anion clearly.", "", []),
])

DAY12 = _build_day(12, [
    ("Physical state of ionic compounds", "Ionic compounds are generally solid at room temperature — hard crystalline solids.", "placeholder", {"label": "Ionic compounds — solid crystals"}, "First property of ionic compounds.", "NaCl, MgO, CaCl₂ are white crystalline solids.", "Solid at room temperature.", "Crystal lattice of alternating ions.", "", []),
    ("High melting and boiling points", "Ionic compounds have high melting and boiling points — strong electrostatic forces between ions.", "placeholder", {"label": "Ionic — high mp and bp"}, "Second property.", "NaCl melts at 801°C — very high.", "Strong ionic bonds need much heat to break.", "High mp distinguishes ionic from covalent.", "", []),
    ("Solubility in water", "Most ionic compounds dissolve in water — water molecules surround ions (hydration).", "placeholder", {"label": "Ionic compounds soluble in water"}, "Third property.", "NaCl dissolves readily in water.", "Polar water dissolves ionic compounds.", "Some insoluble: AgCl, BaSO₄ — exceptions.", "", []),
    ("Electrical conductivity — solid vs molten", "Ionic compounds do NOT conduct electricity in solid state; DO conduct when molten or dissolved in water.", "formula_panel", {"formula": "Solid: no conduction | Molten/aqueous: conducts", "note": "Ions must be free to move"}, "Critical exam distinction.", "NaCl solid — bulb off; NaCl solution — bulb glows.", "Ions fixed in solid; mobile when molten/dissolved.", "Most common exam trap in Ch 3.", "", []),
    ("Why solid ionic compounds do not conduct", "In solid ionic crystal, ions are fixed in lattice positions — cannot move to carry charge.", "placeholder", {"label": "Solid — ions cannot move"}, "Mechanism explanation.", "NaCl crystal — Na⁺ and Cl⁻ locked in place.", "No mobile ions = no current.", "Metallic solids conduct — different mechanism.", "", []),
    ("Why molten ionic compounds conduct", "When melted, ionic lattice breaks — ions free to move toward electrodes carrying charge.", "placeholder", {"label": "Molten — ions move freely"}, "Mechanism for molten state.", "Electrolysis of molten NaCl gives Na and Cl₂.", "Molten = liquid ions = conductor.", "Basis for electrolytic extraction.", "", []),
    ("Why aqueous ionic solutions conduct", "Water dissolves ionic compound — ions surrounded by water molecules and free to move.", "placeholder", {"label": "Aqueous — dissolved ions conduct"}, "Mechanism for aqueous state.", "Salt water conducts — ions in solution.", "Dissolved ions carry current.", "Pure water alone conducts poorly.", "", []),
    ("Brittleness of ionic crystals", "Ionic crystals are brittle — shatter when struck because ion layers shift and repel.", "placeholder", {"label": "Ionic crystals — brittle"}, "Additional property.", "NaCl crystal shatters if hammered.", "Same charge ions align and repel — crack.", "Contrast with malleable metals.", "", []),
    ("Properties summary table", "Solid, high mp, soluble, conduct when molten/dissolved, brittle — five key ionic properties.", "formula_panel", {"formula": "Solid | High mp | Soluble | Conduct (molten/aq) | Brittle", "note": "Five ionic compound properties"}, "Exam revision card.", "Memorise all five for long answer.", "Conductivity condition is most tested.", "Graphite conducts in solid — not ionic.", "", []),
    ("Exam — properties of ionic compounds", "List five properties → explain conductivity solid vs molten vs aqueous → NaCl example for each.", "placeholder", {"label": "Exam: ionic properties template"}, "Structured answer.", "Solid NaCl insulator; NaCl(aq) conductor.", "Five properties with explanation.", "Conductivity trap — solid does NOT conduct.", "", []),
])

DAY13 = _build_day(13, [
    ("Occurrence of metals in nature", "Most metals found as compounds in earth's crust; only less reactive metals found free.", "placeholder", {"label": "Metals in crust — mostly compounds"}, "Day 13 introduction.", "Al and Fe abundant as oxides; Au, Ag rare as free metal.", "Reactive metals never found free.", "Abundance: Al > Fe > Ca in crust.", "", []),
    ("Minerals and ores", "Mineral is natural compound of metal; ore is mineral from which metal extracted profitably.", "formula_panel", {"formula": "Mineral → may be ore if economical", "note": "All ores are minerals; not all minerals are ores"}, "Key definitions.", "Bauxite is ore of aluminium.", "Ore = economically extractable mineral.", "Haematite is ore; other iron minerals may not be.", "", ["ore", "mineral"]),
    ("Gangue definition", "Gangue is unwanted earthy material (sand, rocky impurities) mixed with ore.", "placeholder", {"label": "Gangue — unwanted impurities"}, "Important extraction term.", "Sand and clay in iron ore.", "Remove gangue before extraction.", "Also called matrix or impurities.", "", ["gangue"]),
    ("Enrichment of ores", "Ores concentrated by removing gangue — methods: hydraulic washing, magnetic separation, froth flotation.", "placeholder", {"label": "Enrichment — remove gangue"}, "First step in extraction.", "Magnetic separation for magnetic ores like magnetite.", "Concentrate ore before chemical extraction.", "Froth flotation for sulphide ores.", "", []),
    ("Important ores — aluminium", "Bauxite (Al₂O₃·2H₂O) is main ore of aluminium — most abundant metal in crust.", "formula_panel", {"formula": "Bauxite: Al₂O₃·2H₂O", "note": "Ore of aluminium"}, "First ore to memorise.", "Aluminium from bauxite by electrolysis.", "Bauxite enriched then processed.", "Al most abundant metal — from bauxite.", "", []),
    ("Important ores — iron", "Haematite (Fe₂O₃) and magnetite (Fe₃O₄) are main ores of iron.", "formula_panel", {"formula": "Haematite: Fe₂O₃ | Magnetite: Fe₃O₄", "note": "Iron ores"}, "Second ore pair.", "Blast furnace uses haematite.", "Iron most used structural metal.", "Magnetite magnetic — separated magnetically.", "", []),
    ("Important ores — copper and zinc", "Copper from copper pyrites (CuFeS₂); zinc from zinc blende (ZnS).", "formula_panel", {"formula": "Copper pyrites: CuFeS₂ | Zinc blende: ZnS", "note": "Sulphide ores"}, "Third ore pair.", "Sulphide ores roasted before reduction.", "Cu and Zn from sulphide ores.", "Roasting converts sulphide to oxide.", "", []),
    ("Calcination definition", "Calcination heats ore in absence or limited air — carbonate/hydroxide ore decomposes to oxide.", "formula_panel", {"formula": "ZnCO₃ → ZnO + CO₂", "note": "Calcination — limited air"}, "Thermal treatment term.", "Carbonate ores calcined before reduction.", "Heat without sufficient oxygen.", "Opposite of roasting — no air.", "", ["calcination"]),
    ("Roasting definition", "Roasting heats sulphide ore in presence of air — sulphide converts to oxide.", "formula_panel", {"formula": "2ZnS + 3O₂ → 2ZnO + 2SO₂", "note": "Roasting — in air"}, "Second thermal treatment.", "Sulphide ores roasted to oxide.", "Air supplied — SO₂ produced.", "Roasting for sulphides; calcination for carbonates.", "", ["roasting"]),
    ("Exam — ores and enrichment", "Define ore and gangue → name three ores with formulae → enrichment methods → calcination vs roasting.", "placeholder", {"label": "Exam: ores and enrichment template"}, "Structured answer.", "Bauxite, haematite, zinc blende examples.", "Calcination vs roasting distinction key.", "Gangue removal before extraction.", "", []),
])

DAY14 = _build_day(14, [
    ("Extracting metals — overview", "Method of extraction depends on reactivity — highly reactive need electrolysis; moderate use C/CO reduction.", "placeholder", {"label": "Extraction depends on reactivity"}, "Day 14 theme.", "K, Na, Ca, Mg, Al — electrolysis.", "More reactive = electrolysis.", "Less reactive = reduction with carbon.", "", []),
    ("Reduction of metal oxides", "Metal oxide reduced to free metal by heating with carbon, carbon monoxide, or more reactive metal.", "formula_panel", {"formula": "Metal oxide + Reducing agent → Metal + Oxide of reducer", "note": "Reduction = loss of oxygen from metal compound"}, "Core extraction reaction.", "Fe₂O₃ + 3CO → 2Fe + 3CO₂ in blast furnace.", "Remove oxygen from ore = reduction.", "C and CO common reducing agents.", "", []),
    ("Iron extraction — blast furnace", "Haematite reduced by CO in blast furnace at high temperature — molten iron collected.", "formula_panel", {"formula": "Fe₂O₃ + 3CO → 2Fe + 3CO₂", "note": "Blast furnace — ~1500°C"}, "Major industrial process.", "Coke produces CO which reduces iron ore.", "Blast furnace: coke + limestone + ore.", "Limestone removes silica as slag.", "", []),
    ("Zinc extraction — reduction", "Zinc oxide from roasted zinc blende reduced by heating with carbon.", "formula_panel", {"formula": "ZnO + C → Zn + CO", "note": "Reduction with carbon"}, "Moderate reactivity extraction.", "Zn distils off and collected.", "ZnO reduced by C at high temperature.", "Zn boils below reduction temperature — distillation.", "", []),
    ("Copper extraction — sulphide route", "Copper sulphide ore roasted to oxide, then reduced; low reactivity allows heating alone.", "formula_panel", {"formula": "2Cu₂S + 3O₂ → 2Cu₂O + 2SO₂", "note": "Roast then reduce Cu₂O"}, "Less reactive metal extraction.", "Cu₂O + Cu₂S → 6Cu + SO₂ (self-reduction).", "Cu extracted by heating sulphide ore.", "Some Cu found native — low reactivity.", "", []),
    ("Mercury extraction", "Cinnabar (HgS) roasted to HgO, then HgO decomposes to Hg on heating.", "formula_panel", {"formula": "2HgO → 2Hg + O₂", "note": "Low reactivity — heat alone"}, "Simplest extraction example.", "Mercury liquid at room temperature.", "HgO unstable on heating — releases Hg.", "Hg toxic — historical thermometers.", "", []),
    ("Electrolysis for highly reactive metals", "Na, Ca, Mg, and Al extracted by electrolysis of molten chloride or oxide — too reactive for C reduction.", "formula_panel", {"formula": "Al₂O₃ (molten) → Al + O₂ (electrolysis)", "note": "Hall-Heroult process for Al"}, "Top of series extraction.", "Al from bauxite via electrolysis in cryolite.", "Electrolysis for K, Na, Ca, Mg, Al.", "Large electricity consumption — expensive.", "", []),
    ("Sodium extraction — electrolysis", "Molten NaCl electrolysed — sodium at cathode, chlorine at anode.", "formula_panel", {"formula": "2NaCl (l) → 2Na + Cl₂", "note": "Downs cell — electrolysis"}, "Electrolysis example for Na.", "Same brine electrolysis as chlor-alkali (Ch 2).", "Molten NaCl — not aqueous for Na metal.", "Na collects at cathode — very reactive.", "", []),
    ("Activity series and reducing agent strength", "More reactive metal can reduce less reactive metal oxide — thermite: Al reduces Fe₂O₃.", "formula_panel", {"formula": "Fe₂O₃ + 2Al → 2Fe + Al₂O₃", "note": "Thermite reaction — Al displaces Fe"}, "Displacement in extraction.", "Thermite weld railway tracks.", "Al more reactive than Fe — reduces Fe₂O₃.", "Very exothermic — molten iron produced.", "", []),
    ("Exam — extracting metals", "Link reactivity to method → blast furnace equation → electrolysis for Al/Na → calcination/roasting before reduction.", "placeholder", {"label": "Exam: metal extraction template"}, "Structured answer.", "Fe: blast furnace; Al: electrolysis.", "Three methods: electrolysis, C reduction, heating.", "Always name ore and write key equation.", "", []),
])

DAY15 = _build_day(15, [
    ("Electrolytic refining definition", "Electrolytic refining purifies impure metal using electrolysis — pure metal deposited at cathode.", "formula_panel", {"formula": "Impure metal anode → Pure metal cathode", "note": "Electrolytic refining"}, "Day 15 first topic.", "Pure Cu deposited from CuSO₄ solution.", "Anode dissolves; cathode gains pure metal.", "Used for Cu, Zn, Ag, Au refining.", "", []),
    ("Electrolytic refining of copper", "Impure Cu anode, pure Cu cathode, CuSO₄ electrolyte — pure Cu plates on cathode.", "formula_panel", {"formula": "Anode: impure Cu → Cathode: pure Cu", "note": "CuSO₄(aq) electrolyte"}, "NCERT refining example.", "Insoluble impurities fall as anode mud.", "Pure copper 99.9% by this method.", "Anode mud contains Ag and Au — valuable.", "", []),
    ("Anode mud", "Insoluble impurities (gold, silver) settle below anode during electrolytic refining — called anode mud.", "placeholder", {"label": "Anode mud — precious impurities"}, "By-product of refining.", "Gold and silver recovered from anode mud.", "Less reactive impurities do not dissolve.", "Anode mud economically valuable.", "", []),
    ("Corrosion definition", "Corrosion is gradual destruction of metals by chemical reaction with environment — moisture and air.", "placeholder", {"label": "Corrosion — metal deterioration"}, "Second Day 15 topic.", "Iron rusts; silver tarnishes; copper patina.", "Metal + environment → corroded product.", "Corrosion is electrochemical process.", "", ["corrosion"]),
    ("Rusting of iron", "Rusting is corrosion of iron — forms hydrated iron(III) oxide (rust) in presence of oxygen and water.", "formula_panel", {"formula": "4Fe + 3O₂ + 2xH₂O → 2Fe₂O₃·xH₂O", "note": "Rust — hydrated iron oxide"}, "Most important corrosion example.", "Brown flaky rust on iron gates and nails.", "Needs both O₂ and H₂O for rust.", "Rust is porous — corrosion continues underneath.", "", ["rust"]),
    ("Conditions for rusting", "Iron rusts when both oxygen and water present — dry air or pure water alone insufficient.", "formula_panel", {"formula": "Fe + O₂ + H₂O → Rust", "note": "Both O₂ and H₂O required"}, "Exam conditions question.", "Nail in dry air — no rust; in boiled water + oil — no rust.", "Both moisture AND air needed.", "Salt water accelerates rusting.", "", []),
    ("Other metal corrosion", "Silver tarnishes (Ag₂S from H₂S); copper green patina (basic copper carbonate); aluminium protected by Al₂O₃.", "placeholder", {"label": "Ag, Cu, Al corrosion"}, "Compare corrosion types.", "Silver blackens with sulphur compounds.", "Al self-protects; iron does not.", "Green on copper = CuCO₃·Cu(OH)₂ patina.", "", []),
    ("Economic cost of corrosion", "Corrosion damages bridges, cars, pipelines — billions spent on replacement and repair worldwide.", "placeholder", {"label": "Corrosion — economic impact"}, "Motivation for prevention.", "Rusted bridge structures need replacement.", "Prevention cheaper than replacement.", "Galvanisation and painting save money.", "", []),
    ("Compare refining and corrosion", "Refining purifies metal intentionally; corrosion destroys metal unintentionally — both involve electrochemistry.", "placeholder", {"label": "Refining vs corrosion"}, "Conceptual contrast.", "Electrolysis controls deposition in refining.", "Refining useful; corrosion harmful.", "Both involve ion movement and redox.", "", []),
    ("Exam — refining and corrosion", "Explain electrolytic refining of Cu → rusting equation and conditions → economic impact of corrosion.", "placeholder", {"label": "Exam: refining and corrosion template"}, "Structured answer.", "4Fe + 3O₂ + 2xH₂O → 2Fe₂O₃·xH₂O must-know.", "Refining diagram + rust equation + conditions.", "State both O₂ and H₂O needed for rust.", "", []),
])

DAY16 = _build_day(16, [
    ("Galvanisation", "Galvanisation coats iron with thin layer of zinc — Zn corrodes instead of Fe (sacrificial protection).", "formula_panel", {"formula": "Iron + Zinc coating → Galvanised iron", "note": "Zinc protects iron"}, "Primary prevention method.", "Galvanised buckets and roof sheets.", "Zn more reactive — sacrifices itself.", "Scratch exposes Fe — Zn still protects nearby.", "", ["galvanisation"]),
    ("Painting and oiling", "Paint, grease, or oil layer blocks air and moisture from reaching metal surface.", "placeholder", {"label": "Paint/oil — barrier protection"}, "Barrier method.", "Painted iron gates resist rust longer.", "Physical barrier prevents O₂ and H₂O contact.", "Must renew paint when chipped.", "", []),
    ("Alloying to prevent corrosion", "Alloying makes metal resistant to corrosion — stainless steel (Fe + Cr + Ni) resists rust.", "formula_panel", {"formula": "Stainless steel: Fe + Cr + Ni", "note": "Alloy resists corrosion"}, "Structural prevention.", "Stainless steel utensils do not rust.", "Chromium forms protective oxide layer.", "Alloying changes properties — also increases hardness.", "", []),
    ("Chromium plating", "Thin chromium layer on iron/nickel — shiny, hard, corrosion-resistant surface.", "placeholder", {"label": "Chromium plating — protection"}, "Electroplating prevention.", "Chrome-plated bathroom fittings.", "Cr layer prevents rust and looks polished.", "Different from galvanisation — Cr not sacrificial.", "", []),
    ("Sacrificial protection", "More reactive metal (Zn, Mg) connected to iron — corrodes preferentially protecting iron.", "formula_panel", {"formula": "Zn (sacrificial anode) protects Fe", "note": "Ship hulls use Mg blocks"}, "Electrochemical prevention.", "Magnesium blocks on ship hulls.", "Reactive metal sacrificed — cathodic protection.", "Used on pipelines and ships.", "", []),
    ("Storing reactive metals", "Na and K stored under kerosene; phosphorus under water — prevents reaction with air.", "placeholder", {"label": "Storage prevents corrosion/reaction"}, "Prevention by isolation.", "Na cuts stored in kerosene bottle.", "Exclude air and moisture.", "Same principle as painting — block environment.", "", []),
    ("Unit 3 exam — physical properties summary", "Metals: lustrous, malleable, ductile, sonorous, good conductors. Non-metals: opposite + graphite/iodine exceptions.", "formula_panel", {"formula": "Metals vs non-metals — 5+5 properties", "note": "Activities 3.1–3.4"}, "Revision card 1.", "Activity 3.1–3.4 cover all physical tests.", "Know all activities and exceptions.", "Graphite conducts; iodine lustrous.", "", []),
    ("Unit 3 exam — reactions summary", "Air: metal + O₂ → oxide. Water: Na/K/Ca cold; Fe steam. Acid: salt + H₂. Displacement: more reactive wins.", "formula_panel", {"formula": "O₂ | H₂O | Acid | Displacement", "note": "Four reaction types"}, "Revision card 2.", "Zn + CuSO₄ displacement classic.", "Reactivity series predicts all four.", "Cu no reaction with dilute acid or ZnSO₄.", "", []),
    ("Unit 3 exam — ions and extraction summary", "Electron transfer → ionic compounds. Properties: solid, high mp, conduct molten/aq. Extraction by reactivity.", "formula_panel", {"formula": "Ionic | Extraction | Corrosion", "note": "Revision card 3"}, "Revision card 3.", "Al electrolysis; Fe blast furnace.", "Solid ionic does NOT conduct.", "4Fe + 3O₂ + 2xH₂O → rust equation.", "", []),
    ("Unit 3 complete", "Unit 3 Metals and Non-metals complete — all 160 cards; proceed to Practice when unlocked.", "placeholder", {"label": "Unit 3 complete — 160 cards"}, "Completion card.", "200 MCQs in bank when available.", "Concepts done → practice.", "Review reactivity series, ionic properties, and rust prevention.", "", []),
])

DAY_BUILDERS = {
    1: lambda: DAY1,
    2: lambda: DAY2,
    3: lambda: DAY3,
    4: lambda: DAY4,
    5: lambda: DAY5,
    6: lambda: DAY6,
    7: lambda: DAY7,
    8: lambda: DAY8,
    9: lambda: DAY9,
    10: lambda: DAY10,
    11: lambda: DAY11,
    12: lambda: DAY12,
    13: lambda: DAY13,
    14: lambda: DAY14,
    15: lambda: DAY15,
    16: lambda: DAY16,
}

DAY_TITLES = {
    1: "Metals and Non-metals — Introduction",
    2: "Physical Properties of Metals — Lustre and Hardness",
    3: "Malleability, Ductility and Sonority",
    4: "Heat and Electrical Conductivity of Metals",
    5: "Physical Properties of Non-metals",
    6: "Metals Burned in Air — Metal Oxides",
    7: "Metals React with Water",
    8: "Metals React with Acids",
    9: "Displacement Reactions and Metal Salt Solutions",
    10: "The Reactivity Series",
    11: "How Metals and Non-metals React — Ions",
    12: "Properties of Ionic Compounds",
    13: "Occurrence of Metals — Ores and Enrichment",
    14: "Extracting Metals — Activity Series Methods",
    15: "Electrolytic Refining and Corrosion",
    16: "Prevention of Corrosion and Exam Review",
}
