"""Full concept card content for Harshit Chemistry Unit 4 — Days 1–16 (Ch 4 Carbon and its Compounds)."""

from __future__ import annotations


def _card(
    cid: str,
    name: str,
    simple: str,
    visual_type: str,
    visual_config: dict | None,
    why: str,
    example: str,
    remember: str,
    confusion: str = "",
    optional: str = "",
    glossary: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "name": name,
        "simple_answer": simple,
        "visual": {"type": visual_type, **(visual_config or {})},
        "why": why,
        "example": example,
        "remember": remember,
        "common_confusion": confusion,
        "optional_detail": optional,
        "glossary_terms": glossary or [],
    }


def _build_day(day: int, cards: list[tuple]) -> list[dict]:
    out = []
    for i, row in enumerate(cards, 1):
        name, simple, vtype, vcfg, why, ex, rem, *rest = row
        confusion = rest[0] if len(rest) > 0 else ""
        optional = rest[1] if len(rest) > 1 else ""
        gloss = rest[2] if len(rest) > 2 else []
        out.append(
            _card(
                f"u4_d{day}_c{i:02d}",
                name,
                simple,
                vtype,
                vcfg if isinstance(vcfg, dict) else {},
                why,
                ex,
                rem,
                confusion,
                optional,
                gloss if isinstance(gloss, list) else [],
            )
        )
    return out


DAY1 = _build_day(1, [
    ("What is carbon?", "Carbon is a non-metal element (atomic number 6) that forms the backbone of millions of organic compounds in living and non-living matter.", "placeholder", {"label": "Carbon — basis of organic chemistry"}, "Foundation of Ch 4 — carbon introduced first.", "Coal, diamond, graphite, and all living tissues contain carbon.", "C = element 6; organic chemistry is chemistry of carbon compounds.", "Not every compound with carbon is organic — CO₂ and carbonates are exceptions.", "", ["carbon"]),
    ("Why study carbon compounds?", "Carbon compounds are essential for food, fuel, medicines, plastics, and all life — making this chapter central to science and daily life.", "placeholder", {"label": "Carbon compounds in daily life"}, "Motivation for Ch 4.", "Petrol, proteins, sugar, and cotton are carbon-based.", "Carbon compounds touch every part of daily life.", "Organic chemistry studies carbon compounds; inorganic includes others.", "", []),
    ("Organic vs inorganic compounds", "Organic compounds contain carbon (usually C–H bonds); inorganic compounds include water, salts, and minerals — NCERT focuses on key organic families.", "formula_panel", {"formula": "Organic: C–H bonds (generally) | Inorganic: salts, minerals", "note": "Classification overview"}, "Classification framework for Ch 4.", "Methane CH₄ is organic; NaCl is inorganic.", "Organic = carbon compounds; exceptions like CO₂ noted later.", "Urea and CO are borderline cases — NCERT treats most C-compounds as organic.", "", []),
    ("Unique nature of carbon — preview", "Carbon is tetravalent (4 valence electrons) and shows catenation (self-linking) — together these explain millions of compounds.", "formula_panel", {"formula": "Tetravalency + Catenation → millions of compounds", "note": "Two key properties"}, "Preview of Day 14 deep dive.", "Carbon chains in proteins and petrol molecules.", "4 bonds + self-linking = huge variety.", "Silicon also catenates but less than carbon.", "", ["tetravalency", "catenation"]),
    ("Covalent bonding in carbon — preview", "Carbon shares electrons to complete its octet — forms covalent bonds with other carbon atoms and with H, O, N, halogens.", "placeholder", {"label": "Carbon forms covalent bonds"}, "Leads to Day 2 electron dot structures.", "In methane CH₄, carbon shares 4 electron pairs.", "Carbon shares electrons — does not form ions easily.", "Ionic bonding is rare for carbon — covalent dominates.", "", ["covalent bond"]),
    ("Sources of carbon compounds", "Carbon compounds come from living sources (plants, animals), fossil fuels (coal, petroleum), and laboratory synthesis.", "placeholder", {"label": "Sources — living, fossil, lab"}, "NCERT context for organic compounds.", "Petroleum distillation gives petrol, diesel, kerosene.", "Three sources: biosphere, fossils, synthesis.", "Fossil fuels are ancient carbon compounds.", "", []),
    ("Carbon in living organisms", "All living things are built from carbon compounds — carbohydrates, proteins, fats, and nucleic acids all contain carbon chains.", "placeholder", {"label": "Carbon in all life forms"}, "Biological importance.", "Glucose C₆H₁₂O₆ and amino acids are carbon compounds.", "Life = carbon chemistry.", "Carbon cycle links living and non-living carbon.", "", []),
    ("Fossil fuels and carbon", "Coal and petroleum are complex mixtures of carbon and hydrogen compounds formed over millions of years from ancient life.", "placeholder", {"label": "Fossil fuels — carbon + hydrogen"}, "Energy link to Ch 4.", "Burning petrol releases CO₂ and H₂O.", "Fossil fuels = stored carbon energy.", "Incomplete combustion of fuels produces CO and soot.", "", []),
    ("NCERT Chapter 4 scope", "Ch 4 covers bonding, allotropes, hydrocarbons, functional groups, reactions, ethanol, ethanoic acid, and soaps.", "placeholder", {"label": "Ch 4 roadmap — 16 days"}, "Orient learner to unit plan.", "Activities on burning, bromine water, and soap micelles.", "Bonding → structures → reactions → everyday chemistry.", "", "", []),
    ("Chapter 4 opening — jesc104", "NCERT Class 10 Science Chapter 4 (jesc104.pdf) introduces carbon's versatility before detailed bonding and reactions.", "placeholder", {"label": "jesc104 — Carbon and its Compounds"}, "PDF anchor for unit.", "Refer to NCERT for electron dot diagrams.", "Start with why carbon is special.", "Chapter builds from structure to applications.", "", []),
])

DAY2 = _build_day(2, [
    ("Covalent bond definition", "A covalent bond forms when two atoms share one or more pairs of electrons to achieve stable electron configuration.", "placeholder", {"label": "Covalent bond — shared electron pairs"}, "Core Day 2 concept.", "H–H in H₂ molecule shares one electron pair.", "Shared electrons = covalent bond.", "Sharing completes octet (or duplet for H).", "", ["covalent bond"]),
    ("Why carbon forms covalent bonds", "Carbon has 4 valence electrons — it shares electrons rather than losing or gaining four, forming strong covalent bonds.", "formula_panel", {"formula": "C: 2,4 → shares 4 electrons", "note": "Tetravalency drives covalency"}, "Mechanism for carbon bonding.", "Carbon never forms C⁴⁺ or C⁴⁻ in normal compounds.", "4 valence e⁻ → 4 covalent bonds.", "Carbon can form single, double, and triple bonds.", "", []),
    ("Tetravalency of carbon", "Tetravalency means carbon has a valency of four — it forms four covalent bonds in most compounds.", "formula_panel", {"formula": "Carbon valency = 4", "note": "Tetravalency"}, "Key property repeated in Ch 4.", "In CH₄, carbon bonds to four hydrogen atoms.", "4 bonds around carbon in methane.", "Tetravalency + catenation = versatility.", "", ["tetravalency"]),
    ("Electron dot structure of CH₄", "Methane CH₄: carbon shares one electron pair with each of four H atoms — four single covalent bonds.", "formula_panel", {"formula": "CH₄ — 4 C–H single bonds", "note": "Lewis structure of methane"}, "First NCERT Lewis structure.", "Main component of natural gas.", "C in centre; 4 H around; 4 shared pairs.", "Each bond is one shared pair (single bond).", "", ["methane"]),
    ("Electron dot structure of C₂H₆", "Ethane C₂H₆: two carbon atoms joined by a C–C single bond; each C also bonded to three H atoms.", "formula_panel", {"formula": "C₂H₆ — C–C + 6 C–H bonds", "note": "Lewis structure of ethane"}, "Catenation example in Lewis form.", "Ethane is second member of alkane series.", "Two C atoms single-bonded; 6 H total.", "C–C single bond = one shared pair.", "", ["ethane"]),
    ("Electron dot structure of O₂", "Oxygen O₂: each O atom shares two electron pairs with the other — a double bond (O=O).", "formula_panel", {"formula": "O₂ — O=O double bond", "note": "Lewis structure of oxygen"}, "NCERT diatomic molecule example.", "O₂ needed for combustion and respiration.", "Double bond = two shared pairs.", "O₂ has 6 valence electrons per atom.", "", []),
    ("Electron dot structure of N₂", "Nitrogen N₂: two N atoms share three electron pairs — a triple bond (N≡N), very stable molecule.", "formula_panel", {"formula": "N₂ — N≡N triple bond", "note": "Lewis structure of nitrogen"}, "Triple bond example from NCERT.", "N₂ makes up 78% of air.", "Triple bond = three shared pairs.", "N≡N is very strong — explains N₂ inertness.", "", []),
    ("Electron dot structure of CO₂", "Carbon dioxide CO₂: carbon forms double bonds with two oxygen atoms — O=C=O (linear molecule).", "formula_panel", {"formula": "CO₂ — O=C=O two double bonds", "note": "Lewis structure of carbon dioxide"}, "Carbon double bond example.", "Product of complete combustion of carbon compounds.", "C forms 2 double bonds; linear shape.", "CO₂ is inorganic — exception to organic rule.", "", []),
    ("Electron dot structure of H₂O", "Water H₂O: oxygen shares one electron pair with each of two H atoms — two O–H single bonds; two lone pairs on O.", "formula_panel", {"formula": "H₂O — 2 O–H bonds + 2 lone pairs", "note": "Lewis structure of water"}, "Common covalent compound.", "Product of complete combustion of hydrogen-containing fuels.", "O has 2 bonds + 2 lone pairs.", "Bent shape due to lone pairs — beyond dot structure scope.", "", []),
    ("Exam — drawing Lewis structures", "Count valence e⁻ → place least electronegative atom central → share pairs to complete octets → show lone pairs.", "placeholder", {"label": "Exam: Lewis structure steps"}, "Structured answer template.", "Draw CH₄, H₂O, CO₂ for practice.", "Share electrons until octet (duplet for H).", "Do not forget lone pairs on O and N.", "", []),
])

DAY3 = _build_day(3, [
    ("What are allotropes?", "Allotropes are different physical forms of the same element — same atoms, different arrangement and bonding.", "placeholder", {"label": "Allotropes — same element, different form"}, "Core Day 3 concept.", "Diamond and graphite are both pure carbon.", "Same element, different structure = allotropes.", "Allotropes differ in physical properties.", "", ["allotrope"]),
    ("Diamond — structure and properties", "Diamond: each carbon bonded to four others in a rigid 3D network — hardest natural substance, poor conductor, transparent.", "formula_panel", {"formula": "Diamond: tetrahedral C–C network", "note": "Hard, insulator, high melting point"}, "First carbon allotrope.", "Used in cutting tools and jewellery.", "4 bonds per C; no free electrons.", "Hardest natural material.", "", ["diamond"]),
    ("Graphite — structure and properties", "Graphite: carbon atoms in hexagonal layers held by weak forces — soft, slippery, good conductor (free electrons in layers).", "formula_panel", {"formula": "Graphite: layered hexagonal sheets", "note": "Soft, conductor, lubricant"}, "Second carbon allotrope.", "Pencil lead and dry cell electrodes.", "3 bonds per C; 1 free e⁻ per atom.", "Layers slide — soft and lubricating.", "", ["graphite"]),
    ("Diamond vs graphite comparison", "Diamond: hard, insulator, 4 bonds per C. Graphite: soft, conductor, 3 bonds per C + free electron.", "formula_panel", {"formula": "Diamond: hard, insulator | Graphite: soft, conductor", "note": "Same C — different properties"}, "Key NCERT exam comparison.", "Same element — opposite electrical behaviour.", "Structure determines properties.", "Both are pure carbon — different bonding arrangement.", "", []),
    ("Uses of diamond", "Diamond used in jewellery (hardness, lustre) and industrial cutting/drilling due to extreme hardness.", "placeholder", {"label": "Diamond — jewellery and cutting tools"}, "Application card.", "Diamond-tipped glass cutters.", "Hardness → cutting and decoration.", "Synthetic diamonds made for industry.", "", []),
    ("Uses of graphite", "Graphite used in pencil leads, lubricants, electrodes (dry cells), and as moderator in nuclear reactors.", "placeholder", {"label": "Graphite — pencils, electrodes, lubricant"}, "Application card.", "Pencil 'lead' is actually graphite.", "Conductivity + softness → electrodes and pencils.", "Graphite is non-metal that conducts — Ch 3 link.", "", []),
    ("Fullerene C₆₀", "Fullerene is an allotrope of carbon — cage-like molecule of 60 carbon atoms arranged like a football (soccer ball).", "formula_panel", {"formula": "C₆₀ — buckminsterfullerene", "note": "Third allotrope mentioned in NCERT"}, "Modern allotrope in syllabus.", "Discovered in 1985 — Nobel Prize 1996.", "60 C atoms in closed cage.", "Also called buckminsterfullerene.", "", ["fullerene"]),
    ("Why allotropes have different properties", "Different arrangement of atoms and different bonding (sp³ in diamond vs sp² in graphite) cause different physical properties.", "placeholder", {"label": "Structure → different properties"}, "Conceptual understanding.", "Diamond's 3D network vs graphite's layers.", "Bonding pattern determines hardness and conductivity.", "Chemical formula same (C) — structure differs.", "", []),
    ("Allotropes vs compounds", "Allotropes are forms of one element; compounds contain two or more different elements chemically combined.", "formula_panel", {"formula": "Allotrope: one element | Compound: two+ elements", "note": "Do not confuse"}, "Classification distinction.", "Diamond (allotrope) vs CO₂ (compound).", "Allotropes = same element only.", "O₂ and O₃ are allotropes of oxygen.", "", []),
    ("Exam — allotropes of carbon", "Define allotrope → diamond (hard, insulator, 4 bonds) → graphite (soft, conductor, layers) → C₆₀ fullerene → compare uses.", "placeholder", {"label": "Exam: carbon allotropes template"}, "Structured answer.", "Pencil lead = graphite; diamond ring = diamond.", "Three allotropes + properties + uses.", "Graphite conducts — important exception among non-metals.", "", []),
])

DAY4 = _build_day(4, [
    ("What are hydrocarbons?", "Hydrocarbons are compounds containing only carbon and hydrogen — the simplest organic compounds.", "formula_panel", {"formula": "Hydrocarbon = C + H only", "note": "Simplest organic compounds"}, "Core Day 4 concept.", "Methane CH₄ and ethene C₂H₄ are hydrocarbons.", "Only C and H atoms.", "All fossil fuels are mainly hydrocarbons.", "", ["hydrocarbon"]),
    ("Saturated hydrocarbons — alkanes", "Saturated hydrocarbons have only single C–C and C–H bonds — all carbons bonded to maximum H; called alkanes.", "formula_panel", {"formula": "Saturated = all single bonds", "note": "Alkanes — saturated hydrocarbons"}, "First hydrocarbon family.", "Methane, ethane, propane are saturated.", "Single bonds only = saturated.", "Saturated compounds are less reactive.", "", ["alkane", "saturated"]),
    ("General formula of alkanes", "Alkanes follow CₙH₂ₙ₊₂ — for n carbons, hydrogens = 2n + 2.", "formula_panel", {"formula": "CₙH₂ₙ₊₂", "note": "General formula — alkanes"}, "NCERT formula to memorise.", "Methane C₁H₄, ethane C₂H₆, propane C₃H₈.", "n carbons → 2n+2 hydrogens.", "C₁ = methane CH₄; C₂ = ethane C₂H₆.", "", []),
    ("Unsaturated hydrocarbons — introduction", "Unsaturated hydrocarbons contain double or triple C–C bonds — not all carbons have maximum hydrogen.", "formula_panel", {"formula": "Unsaturated = double or triple C–C bond", "note": "Alkenes and alkynes"}, "Contrast with saturated.", "Ethene has C=C double bond.", "Double/triple bond = unsaturated.", "Unsaturated compounds are more reactive.", "", ["unsaturated"]),
    ("Alkenes — general formula CₙH₂ₙ", "Alkenes are unsaturated hydrocarbons with one C=C double bond — general formula CₙH₂ₙ.", "formula_panel", {"formula": "CₙH₂ₙ", "note": "Alkenes — one double bond"}, "Second hydrocarbon family.", "Ethene C₂H₄ (ethylene) and propene C₃H₆.", "One double bond; 2n hydrogens.", "Ethene is simplest alkene.", "", ["alkene"]),
    ("Alkynes — general formula CₙH₂ₙ₋₂", "Alkynes are unsaturated hydrocarbons with one C≡C triple bond — general formula CₙH₂ₙ₋₂.", "formula_panel", {"formula": "CₙH₂ₙ₋₂", "note": "Alkynes — one triple bond"}, "Third hydrocarbon family.", "Ethyne C₂H₂ (acetylene) used in welding.", "One triple bond; 2n−2 hydrogens.", "Ethyne is simplest alkyne.", "", ["alkyne"]),
    ("Examples — methane to ethyne", "Methane CH₄ (alkane), ethene C₂H₄ (alkene), ethyne C₂H₂ (alkyne) — three families with two carbons.", "formula_panel", {"formula": "CH₄ | C₂H₄ | C₂H₂", "note": "Alkane, alkene, alkyne examples"}, "Side-by-side comparison.", "Natural gas, fruit ripening, welding torch.", "Same C count — different saturation.", "Suffix: -ane, -ene, -yne.", "", []),
    ("Single, double, and triple bonds", "Single bond (C–C): one shared pair. Double (C=C): two shared pairs. Triple (C≡C): three shared pairs.", "formula_panel", {"formula": "Single: 1 pair | Double: 2 pairs | Triple: 3 pairs", "note": "Bond types in hydrocarbons"}, "Bond type foundation.", "Ethane single; ethene double; ethyne triple.", "More shared pairs = shorter, stronger bond.", "Double/triple bonds cause unsaturation.", "", []),
    ("Compare saturated vs unsaturated", "Saturated: single bonds, CₙH₂ₙ₊₂, less reactive. Unsaturated: double/triple bonds, more reactive, decolourise bromine water.", "formula_panel", {"formula": "Saturated: CₙH₂ₙ₊₂ | Unsaturated: CₙH₂ₙ or CₙH₂ₙ₋₂", "note": "Key comparison"}, "Exam comparison table.", "Hexane saturated; hexene unsaturated.", "Single bonds vs double/triple.", "Bromine water test distinguishes unsaturated.", "", []),
    ("Exam — hydrocarbon classification", "Define hydrocarbon → saturated (alkanes CₙH₂ₙ₊₂) → unsaturated (alkenes CₙH₂ₙ, alkynes CₙH₂ₙ₋₂) → examples.", "placeholder", {"label": "Exam: hydrocarbon types template"}, "Structured answer.", "Give CH₄, C₂H₄, C₂H₂ as examples.", "Three families + general formulas + examples.", "Do not confuse alkene and alkyne formulas.", "", []),
])

DAY5 = _build_day(5, [
    ("Straight chain carbon compounds", "Straight chain compounds have carbon atoms linked in a continuous unbranched row — e.g. n-butane.", "placeholder", {"label": "Straight chain — unbranched C chain"}, "Core Day 5 concept.", "Pentane CH₃–CH₂–CH₂–CH₂–CH₃ is straight chain.", "Carbons in one continuous line.", "n- prefix means normal (straight) chain.", "", []),
    ("Branched chain carbon compounds", "Branched chains have a main chain with side groups (branches) attached — same formula, different structure.", "placeholder", {"label": "Branched chain — side groups"}, "Second structural type.", "Isobutane has a Y-shaped branch.", "Side chain branches off main chain.", "Branching changes physical properties slightly.", "", []),
    ("Ring (cyclic) carbon compounds", "Cyclic compounds have carbon atoms joined in a closed ring — e.g. cyclohexane C₆H₁₂.", "formula_panel", {"formula": "Cyclohexane C₆H₁₂ — 6-membered ring", "note": "Ring structure"}, "Third structural type.", "Benzene ring (introductory mention in NCERT).", "Carbons form closed loop.", "Ring compounds have different properties from chains.", "", []),
    ("Structural isomers — introduction", "Compounds with same molecular formula but different structural arrangement are structural isomers.", "formula_panel", {"formula": "Same formula, different structure", "note": "Structural isomerism"}, "NCERT isomerism concept.", "Butane and isobutane both C₄H₁₀.", "Same atoms, different connectivity.", "Isomerism adds to carbon's compound count.", "", ["isomer"]),
    ("Butane vs isobutane", "n-Butane: straight chain C₄H₁₀. Isobutane: branched C₄H₁₀ — same formula, different boiling points.", "formula_panel", {"formula": "C₄H₁₀ — butane and isobutane", "note": "Classic isomer pair"}, "NCERT memorable example.", "Lighter fluid may contain isobutane.", "Both C₄H₁₀; structure differs.", "Iso- prefix indicates branched isomer.", "", []),
    ("Pentane isomers", "Pentane C₅H₁₂ has three structural isomers: n-pentane, isopentane, and neopentane.", "formula_panel", {"formula": "C₅H₁₂ — 3 isomers", "note": "Pentane isomer count"}, "Extension of isomer concept.", "More carbons → more possible isomers.", "Three ways to arrange 5 carbons.", "Isomer count grows rapidly with carbon number.", "", []),
    ("Cyclohexane — ring example", "Cyclohexane C₆H₁₂ is a saturated ring of six carbon atoms — each C bonded to two C and two H.", "formula_panel", {"formula": "C₆H₁₂ — hexagonal ring", "note": "Cyclic saturated hydrocarbon"}, "Ring structure example.", "Six carbons in a ring — not straight chain.", "Ring = cyclic saturated hydrocarbon.", "Cyclo- prefix means ring.", "", []),
    ("Why carbon forms long chains", "Catenation — carbon atoms link to each other strongly and repeatedly, forming chains of any length.", "placeholder", {"label": "Catenation — C–C chain building"}, "Links to Day 14.", "Paraffin wax has very long carbon chains.", "C bonds to C repeatedly = chains.", "Carbon–carbon bonds are strong and stable.", "", ["catenation"]),
    ("Chains, branches, and rings together", "Carbon compounds can combine straight chains, branches, and rings — adding enormous structural diversity.", "placeholder", {"label": "Chains + branches + rings"}, "Synthesis of Day 5.", "Complex molecules like cholesterol have rings and branches.", "Three structural types multiply possibilities.", "Functional groups attach to any of these skeletons.", "", []),
    ("Exam — structural formulas", "Draw straight chain → branched isomer → state same molecular formula → cyclohexane ring example.", "placeholder", {"label": "Exam: chain and isomer template"}, "Structured answer.", "Butane vs isobutane C₄H₁₀ comparison.", "Structure diagram + formula + isomer name.", "Same formula does not mean same compound.", "", []),
])

DAY6 = _build_day(6, [
    ("Homologous series definition", "A homologous series is a family of compounds with same functional group and similar chemical properties; successive members differ by CH₂.", "formula_panel", {"formula": "Each member differs by –CH₂–", "note": "Homologous series"}, "Core Day 6 concept.", "Alkane series: CH₄, C₂H₆, C₃H₈, C₄H₁₀.", "Same group; differ by CH₂ unit.", "Members show gradual physical property change.", "", ["homologous series"]),
    ("Successive members differ by CH₂", "Each next member in a homologous series has one more CH₂ group — molecular mass increases by 14 u.", "formula_panel", {"formula": "Difference = CH₂ (14 u)", "note": "Between consecutive members"}, "Numerical pattern in series.", "Ethane C₂H₆ to propane C₃H₈ adds CH₂.", "Add CH₂ → next homologue.", "14 u mass difference between neighbours.", "", []),
    ("Similar chemical properties in a series", "All members of a homologous series react similarly because they have the same functional group.", "placeholder", {"label": "Same functional group → same reactions"}, "Chemical property pattern.", "All alkanes burn; all alcohols react with Na.", "Same functional group = same chemistry.", "Physical properties change gradually.", "", []),
    ("Gradual change in physical properties", "Boiling point and melting point increase gradually down a homologous series as molecular size increases.", "placeholder", {"label": "Boiling point increases down series"}, "Physical property trend.", "Methane gas; pentane liquid at room temp.", "Larger molecule → higher boiling point.", "First four alkanes: gas → liquid trend.", "", []),
    ("Alcohol functional group — OH", "Alcohols contain the hydroxyl functional group –OH attached to a carbon atom — e.g. ethanol C₂H₅OH.", "formula_panel", {"formula": "–OH (hydroxyl group)", "note": "Alcohol functional group"}, "First functional group.", "Ethanol in drinks; methanol in industrial use.", "–OH on carbon = alcohol.", "Do not confuse with hydroxide ion OH⁻.", "", ["alcohol"]),
    ("Aldehyde functional group — CHO", "Aldehydes contain the –CHO (formyl) group — carbonyl at end of chain — e.g. methanal HCHO.", "formula_panel", {"formula": "–CHO (aldehyde group)", "note": "Terminal carbonyl"}, "Second functional group.", "Formaldehyde HCHO preserves biological specimens.", "–CHO at chain end = aldehyde.", "Aldehyde vs ketone — position of C=O matters.", "", ["aldehyde"]),
    ("Ketone functional group — C=O", "Ketones contain C=O (carbonyl) group between two carbon atoms — not at chain end — e.g. propanone.", "formula_panel", {"formula": "C=O between two C atoms", "note": "Ketone — internal carbonyl"}, "Third functional group.", "Acetone (propanone) is a common solvent.", "C=O in middle of chain = ketone.", "Aldehyde: C=O at end; ketone: C=O in middle.", "", ["ketone"]),
    ("Carboxylic acid functional group — COOH", "Carboxylic acids contain –COOH (carboxyl) group — e.g. ethanoic acid CH₃COOH (acetic acid).", "formula_panel", {"formula": "–COOH (carboxyl group)", "note": "Carboxylic acid"}, "Fourth functional group.", "Vinegar contains ethanoic acid.", "–COOH = carboxylic acid.", "Acids turn blue litmus red — Ch 2 link.", "", ["carboxylic acid"]),
    ("Haloalkane functional group — X", "Haloalkanes (alkyl halides) have a halogen (F, Cl, Br, I) attached to carbon — e.g. CH₃Cl chloromethane.", "formula_panel", {"formula": "–Cl, –Br, –I on carbon", "note": "Haloalkane (halo group)"}, "Fifth functional group.", "CH₃Cl formed in methane + Cl₂ substitution.", "Halogen replaces H on carbon.", "Also called alkyl halides.", "", ["haloalkane"]),
    ("Exam — functional groups table", "List –OH (alcohol), –CHO (aldehyde), C=O (ketone), –COOH (carboxylic acid), –X (halo) with one example each.", "placeholder", {"label": "Exam: functional groups table"}, "Structured answer.", "Ethanol, ethanoic acid, CH₃Cl as examples.", "Group formula + name + example.", "Functional group determines chemical properties.", "", []),
])

DAY7 = _build_day(7, [
    ("IUPAC naming basics", "IUPAC system gives systematic names based on number of carbons (root) and functional group (suffix/prefix).", "placeholder", {"label": "IUPAC — systematic naming"}, "Core Day 7 concept.", "Ethanol = eth + an + ol (2C + alkane + alcohol).", "Root + suffix = IUPAC name.", "Common names also used in NCERT.", "", ["IUPAC"]),
    ("Root word from carbon count", "Root tells carbon count: meth- (1), eth- (2), prop- (3), but- (4), pent- (5), hex- (6).", "formula_panel", {"formula": "meth=1, eth=2, prop=3, but=4, pent=5, hex=6", "note": "Carbon root words"}, "Foundation of naming.", "Eth- in ethanol means 2 carbons.", "Root = longest carbon chain count.", "Memorise roots 1–6 for Class 10.", "", []),
    ("Suffix -ane for alkanes", "Saturated hydrocarbons use suffix -ane: methane, ethane, propane, butane.", "formula_panel", {"formula": "Suffix: -ane (saturated)", "note": "Alkane naming"}, "Alkane suffix rule.", "Propane C₃H₈ — prop + ane.", "-ane = all single bonds.", "n-butane vs isobutane — same suffix.", "", []),
    ("Suffix -ene for alkenes", "Alkenes use suffix -ene for C=C double bond: ethene, propene, butene.", "formula_panel", {"formula": "Suffix: -ene (one double bond)", "note": "Alkene naming"}, "Alkene suffix rule.", "Ethene C₂H₄ — eth + ene.", "-ene = one double bond.", "Ethene also called ethylene (common name).", "", []),
    ("Suffix -yne for alkynes", "Alkynes use suffix -yne for C≡C triple bond: ethyne, propyne.", "formula_panel", {"formula": "Suffix: -yne (one triple bond)", "note": "Alkyne naming"}, "Alkyne suffix rule.", "Ethyne C₂H₂ — eth + yne.", "-yne = one triple bond.", "Ethyne also called acetylene (common name).", "", []),
    ("Naming with functional groups", "Functional group suffix replaces -ane: -ol (alcohol), -oic acid (carboxylic), -al (aldehyde), -one (ketone).", "formula_panel", {"formula": "-ol | -oic acid | -al | -one", "note": "Functional group suffixes"}, "Combined naming rule.", "Ethanol = eth + an + ol; ethanoic acid = eth + an + oic acid.", "Suffix shows functional group.", "Longest chain including functional group carbon.", "", []),
    ("Examples — methanol, ethanol, ethanoic acid", "Methanol CH₃OH (1C alcohol); ethanol C₂H₅OH (2C alcohol); ethanoic acid CH₃COOH (2C acid).", "formula_panel", {"formula": "CH₃OH | C₂H₅OH | CH₃COOH", "note": "Named examples"}, "NCERT key named compounds.", "Methanol toxic; ethanol in beverages; vinegar = ethanoic acid.", "Count carbons in longest chain.", "Ethanoic acid also called acetic acid.", "", []),
    ("Common names vs IUPAC names", "NCERT uses both: ethene/ethylene, ethyne/acetylene, ethanoic acid/acetic acid.", "formula_panel", {"formula": "IUPAC and common names both valid", "note": "Know both in NCERT"}, "Exam naming flexibility.", "Write either name unless IUPAC specified.", "Learn pairs of common and IUPAC names.", "Exam may use either — know both.", "", []),
    ("Position of functional group", "When functional group can be at different positions, number the carbon chain to give lowest number to the group.", "placeholder", {"label": "Number chain — lowest locant"}, "Advanced naming rule.", "Propan-1-ol vs propan-2-ol — position matters.", "Number from end nearest functional group.", "Class 10 focuses on simple names.", "", []),
    ("Exam — nomenclature practice", "Identify root (C count) → identify functional group → add suffix → write full name with formula.", "placeholder", {"label": "Exam: IUPAC naming steps"}, "Structured answer template.", "Name C₃H₇OH as propanol.", "Root + suffix + functional group position.", "Check saturation: -ane, -ene, or -yne first.", "", []),
])

DAY8 = _build_day(8, [
    ("Combustion of carbon compounds", "Combustion is reaction with oxygen releasing heat and light — carbon compounds burn to give CO₂ and H₂O on complete combustion.", "formula_panel", {"formula": "Compound + O₂ → CO₂ + H₂O + heat", "note": "Complete combustion"}, "Core Day 8 concept.", "Burning candle, petrol in engine.", "Burn in O₂ → oxides + energy.", "Combustion is oxidation — adds oxygen.", "", ["combustion"]),
    ("Complete combustion", "Complete combustion in sufficient O₂ gives CO₂ and H₂O — clean blue flame, no soot.", "formula_panel", {"formula": "Complete: CO₂ + H₂O", "note": "Sufficient oxygen"}, "Ideal combustion outcome.", "Bunsen burner with air hole open — blue flame.", "Enough O₂ → CO₂ + H₂O only.", "Blue flame indicates complete combustion.", "", []),
    ("Incomplete combustion", "Incomplete combustion in limited O₂ gives carbon (soot), CO, and water — yellow smoky flame.", "formula_panel", {"formula": "Incomplete: C (soot) + CO + H₂O", "note": "Limited oxygen"}, "Second combustion outcome.", "Yellow candle flame has soot at top.", "Limited O₂ → soot and CO.", "CO is poisonous — see card below.", "", []),
    ("Combustion of methane", "Methane burns completely: CH₄ + 2O₂ → CO₂ + 2H₂O + heat and light.", "formula_panel", {"formula": "CH₄ + 2O₂ → CO₂ + 2H₂O", "note": "Methane combustion"}, "Key balanced equation.", "Natural gas stove burns methane.", "Balance C, H, O for full marks.", "Main component of LPG/natural gas.", "", []),
    ("Combustion of ethanol", "Ethanol burns with clean blue flame: C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O + heat.", "formula_panel", {"formula": "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O", "note": "Ethanol combustion"}, "Alcohol combustion example.", "Spirit lamp burns ethanol.", "Ethanol burns cleanly — used as fuel.", "Count O from –OH in ethanol.", "", []),
    ("Oxidation of alcohol to carboxylic acid", "Alcohols oxidise to carboxylic acids using oxidising agents like alkaline KMnO₄ or acidified K₂Cr₂O₇.", "formula_panel", {"formula": "Alcohol →[oxidation]→ Carboxylic acid", "note": "KMnO₄ or K₂Cr₂O₇"}, "Oxidation reaction in Ch 4.", "Ethanol oxidises to ethanoic acid.", "Add O → alcohol becomes acid.", "Oxidising agents are coloured — purple KMnO₄ decolourises.", "", []),
    ("Oxidising agents — KMnO₄ and K₂Cr₂O₇", "Potassium permanganate (KMnO₄) and potassium dichromate (K₂Cr₂O₇) are common oxidising agents in NCERT.", "formula_panel", {"formula": "KMnO₄ | K₂Cr₂O₇ — oxidising agents", "note": "Test for alcohol oxidation"}, "Reagents to know.", "Purple KMnO₄ decolourises when oxidising ethanol.", "These add oxygen to alcohols.", "Also test for unsaturation in some contexts.", "", []),
    ("Dangers of carbon monoxide", "CO from incomplete combustion is colourless, odourless, poisonous — binds to haemoglobin blocking O₂ transport.", "placeholder", {"label": "CO — poisonous gas"}, "Safety awareness.", "Faulty gas heaters can produce CO.", "Incomplete combustion → deadly CO.", "Ensure good ventilation when burning fuels.", "", []),
    ("Soot from incomplete combustion", "Soot is unburnt carbon particles from incomplete combustion — deposits on surfaces, causes air pollution.", "placeholder", {"label": "Soot — unburnt carbon particles"}, "Pollution link.", "Black deposit on bottom of cooking vessels.", "Yellow smoky flame → soot.", "Complete combustion prevents soot.", "", []),
    ("Exam — combustion equations", "Write complete combustion equation → balance → state products CO₂ + H₂O → contrast incomplete (soot, CO).", "placeholder", {"label": "Exam: combustion template"}, "Structured answer.", "CH₄ + 2O₂ → CO₂ + 2H₂O as model.", "Balanced equation + complete vs incomplete.", "Always balance and state conditions.", "", []),
])

DAY9 = _build_day(9, [
    ("Addition reaction definition", "Addition reaction: atoms add across a double or triple bond — unsaturated compound becomes saturated.", "formula_panel", {"formula": "Unsaturated + X–Y → saturated product", "note": "Addition reaction"}, "Core Day 9 concept.", "Ethene + H₂ → ethane is addition.", "Atoms add across C=C or C≡C.", "Product has more H attached to carbons.", "", ["addition reaction"]),
    ("Unsaturated compounds undergo addition", "Compounds with C=C or C≡C bonds open the multiple bond to add atoms — saturated compounds do not.", "placeholder", {"label": "Double/triple bond opens for addition"}, "Reactivity pattern.", "Ethene reacts; ethane does not (with H₂).", "Multiple bond = site of addition.", "Saturation increases after addition.", "", []),
    ("Ethene + H₂ → ethane (hydrogenation)", "Ethene reacts with hydrogen in presence of Ni/Pt catalyst: C₂H₄ + H₂ → C₂H₆ (hydrogenation).", "formula_panel", {"formula": "C₂H₄ + H₂ → C₂H₆", "note": "Hydrogenation — Ni/Pt catalyst"}, "Classic NCERT addition.", "Used to convert vegetable oils to fats.", "Double bond removed; alkene → alkane.", "Ni or Pt catalyst needed for H₂ addition.", "", []),
    ("Ethene + Br₂ → dibromoethane", "Ethene adds bromine: C₂H₄ + Br₂ → C₂H₄Br₂ (1,2-dibromoethane) — bromine adds across double bond.", "formula_panel", {"formula": "C₂H₄ + Br₂ → C₂H₄Br₂", "note": "Bromine addition to ethene"}, "Halogen addition example.", "Orange bromine decolourises when ethene added.", "Br₂ adds across C=C.", "Product is saturated — no double bond left.", "", []),
    ("Bromine water test for unsaturation", "Bromine water (orange) decolourises with unsaturated compounds — test for C=C double bond.", "formula_panel", {"formula": "Br₂ water + alkene → colourless", "note": "Test for unsaturation"}, "Key NCERT test.", "Ethene decolourises bromine water; ethane does not.", "Orange → colourless = unsaturated.", "Bromine water is Br₂ dissolved in water.", "", []),
    ("Why bromine water decolourises", "Bromine adds across the double bond in an addition reaction — orange Br₂ consumed, solution becomes colourless.", "placeholder", {"label": "Br₂ consumed in addition"}, "Mechanism explanation.", "Shake ethene with bromine water — instant decolourisation.", "Addition uses up coloured Br₂.", "No decolourisation with saturated alkanes.", "", []),
    ("Hydrogenation of vegetable oils", "Unsaturated vegetable oils hydrogenated to saturated fats using H₂ and Ni catalyst — margarine production.", "formula_panel", {"formula": "Oil + H₂ →[Ni] Fat (saturated)", "note": "Industrial hydrogenation"}, "Industrial application.", "Margarine from hydrogenated oils.", "Addition of H₂ across C=C in oils.", "Saturated fats have higher melting points.", "", []),
    ("Why saturated compounds do not undergo addition", "Saturated compounds have only single bonds — no double/triple bond to open, so addition cannot occur.", "placeholder", {"label": "No multiple bond — no addition"}, "Contrast with unsaturated.", "Ethane does not decolourise bromine water.", "Single bonds already saturated with H.", "Saturated compounds undergo substitution instead.", "", []),
    ("Addition vs substitution", "Addition: unsaturated + atoms across double bond. Substitution: saturated — one atom replaces another.", "formula_panel", {"formula": "Addition: unsaturated | Substitution: saturated", "note": "Two reaction types"}, "Key Ch 4 distinction.", "Ethene + Br₂ (addition); CH₄ + Cl₂ (substitution).", "Unsaturation → addition; saturation → substitution.", "Do not mix up reaction types in exams.", "", []),
    ("Exam — addition reactions", "Define addition → ethene + H₂ → ethane → ethene + Br₂ → bromine water test → hydrogenation of oils.", "placeholder", {"label": "Exam: addition reaction template"}, "Structured answer.", "Write C₂H₄ + Br₂ → C₂H₄Br₂ with decolourisation.", "Definition + two equations + bromine test.", "State catalyst for hydrogenation (Ni/Pt).", "", []),
])

DAY10 = _build_day(10, [
    ("Substitution reaction definition", "Substitution: one atom or group replaces another in a saturated compound — no change in saturation.", "formula_panel", {"formula": "Saturated + reagent → substituted product", "note": "Substitution reaction"}, "Core Day 10 concept.", "CH₄ + Cl₂ → CH₃Cl + HCl.", "One atom replaces another.", "Saturation level unchanged.", "", ["substitution reaction"]),
    ("Saturated compounds undergo substitution", "Alkanes and other saturated compounds react by substitution — H replaced by halogen or other group.", "placeholder", {"label": "Saturated → substitution"}, "Reactivity pattern.", "Methane chlorination is classic example.", "Replace H on saturated C.", "Multiple substitutions can occur.", "", []),
    ("CH₄ + Cl₂ → CH₃Cl + HCl (UV light)", "Methane reacts with chlorine in sunlight/UV: CH₄ + Cl₂ → CH₃Cl + HCl — H replaced by Cl.", "formula_panel", {"formula": "CH₄ + Cl₂ → CH₃Cl + HCl", "note": "Sunlight or UV required"}, "Classic NCERT substitution.", "Chloromethane formed in photochemical reaction.", "Cl replaces one H; HCl by-product.", "Sunlight/UV provides activation energy.", "", []),
    ("Role of sunlight or UV light", "Chlorination of methane needs sunlight or UV — light energy breaks Cl–Cl bond to start free radical chain reaction.", "placeholder", {"label": "Sunlight/UV activates Cl₂"}, "Condition for reaction.", "No reaction in dark; rapid in sunlight.", "Light initiates substitution.", "Without light, methane and Cl₂ do not react at room temp.", "", []),
    ("Multiple substitution possible", "Further substitution gives CH₂Cl₂, CHCl₃, CCl₄ if excess Cl₂ and light — H replaced one by one.", "formula_panel", {"formula": "CH₄ → CH₃Cl → CH₂Cl₂ → CHCl₃ → CCl₄", "note": "Progressive chlorination"}, "Extended substitution series.", "Carbon tetrachloride CCl₄ is final chlorination product.", "Each step replaces one more H.", "Products depend on Cl₂ amount and conditions.", "", []),
    ("Products of methane chlorination", "Chloromethane CH₃Cl (methyl chloride), dichloromethane CH₂Cl₂, chloroform CHCl₃, carbon tetrachloride CCl₄.", "formula_panel", {"formula": "CH₃Cl | CH₂Cl₂ | CHCl₃ | CCl₄", "note": "Chlorination products"}, "Named products list.", "Chloroform CHCl₃ was anaesthetic — now restricted.", "Know first product CH₃Cl for exam.", "Common names: chloroform, carbon tetrachloride.", "", []),
    ("Why alkanes undergo substitution", "Alkanes have strong C–H and C–C single bonds — they do not add across bonds; instead H is replaced.", "placeholder", {"label": "Alkanes — replace H, not add"}, "Mechanism overview.", "Methane saturated — substitution only.", "No double bond to add across.", "Substitution preserves saturation.", "", []),
    ("Chlorination vs bromination", "Similar substitution with Br₂: CH₄ + Br₂ → CH₃Br + HBr — also needs light; bromination similar to chlorination.", "formula_panel", {"formula": "CH₄ + Br₂ → CH₃Br + HBr", "note": "Bromination — also needs light"}, "Parallel halogen substitution.", "Bromomethane CH₃Br formed similarly.", "Same pattern with Br₂.", "Bromination slower than chlorination.", "", []),
    ("Substitution vs addition — summary", "Substitution: saturated, one atom replaced (CH₄ + Cl₂). Addition: unsaturated, atoms add across double bond (C₂H₄ + Br₂).", "formula_panel", {"formula": "Substitution: saturated | Addition: unsaturated", "note": "Ch 4 reaction summary"}, "Compare two reaction types.", "Know which compound undergoes which.", "Saturation determines reaction type.", "Most common exam mistake — mixing types.", "", []),
    ("Exam — substitution reactions", "Define substitution → CH₄ + Cl₂ → CH₃Cl + HCl (sunlight) → multiple products → contrast with addition.", "placeholder", {"label": "Exam: substitution template"}, "Structured answer.", "Write balanced equation with light condition.", "Definition + equation + condition + contrast.", "Always mention sunlight/UV for halogenation.", "", []),
])

DAY11 = _build_day(11, [
    ("Ethanol — structure C₂H₅OH", "Ethanol (ethyl alcohol) has formula C₂H₅OH — two-carbon alcohol with –OH functional group.", "formula_panel", {"formula": "C₂H₅OH — ethyl alcohol", "note": "2-carbon alcohol"}, "Core Day 11 compound.", "Present in alcoholic beverages (dilute).", "C₂H₅–OH structure.", "Also written as CH₃CH₂OH.", "", ["ethanol"]),
    ("Uses of ethanol", "Ethanol used as solvent, in medicines (tinctures), as fuel, and in beverages — versatile alcohol.", "placeholder", {"label": "Ethanol — solvent, fuel, medicine"}, "Application card.", "Iodine tincture is ethanol + iodine.", "Solvent + antiseptic + fuel.", "Industrial ethanol from fermentation.", "", []),
    ("Denatured alcohol", "Ethanol mixed with poisonous substances (methanol, pyridine) to make denatured alcohol — unfit for drinking, avoids tax.", "placeholder", {"label": "Denatured alcohol — poison added"}, "NCERT safety concept.", "Industrial ethanol sold as denatured spirit.", "Poison added to prevent misuse.", "Denatured alcohol still flammable — handle carefully.", "", []),
    ("Ethanoic acid — structure CH₃COOH", "Ethanoic acid (acetic acid) has formula CH₃COOH — two-carbon carboxylic acid, weak acid.", "formula_panel", {"formula": "CH₃COOH — acetic acid", "note": "2-carbon carboxylic acid"}, "Second key compound.", "5–8% solution in vinegar.", "CH₃–COOH; –COOH is carboxyl group.", "Also called acetic acid (common name).", "", ["ethanoic acid"]),
    ("Acetic acid in vinegar", "Vinegar is 5–8% ethanoic acid in water — sour taste and smell characteristic of carboxylic acids.", "placeholder", {"label": "Vinegar — dilute ethanoic acid"}, "Everyday connection.", "Salad dressing and pickling use vinegar.", "Sour taste = carboxylic acid.", "Glacial acetic acid is nearly pure — corrosive.", "", []),
    ("Esterification — overview", "Esterification: carboxylic acid reacts with alcohol in presence of conc. H₂SO₄ to form ester + water — sweet smell.", "formula_panel", {"formula": "Acid + Alcohol → Ester + H₂O", "note": "Esterification reaction"}, "Key reaction linking both compounds.", "Ethanoic acid + ethanol → ethyl ethanoate.", "Acid + alcohol → ester (sweet smell).", "Conc. H₂SO₄ is catalyst.", "", ["esterification"]),
    ("Sweet smell of esters", "Esters have pleasant fruity smell — used in perfumes and flavourings; formed in esterification.", "placeholder", {"label": "Esters — fruity sweet smell"}, "Sensory identification.", "Banana and apple flavours often esters.", "Sweet smell confirms ester formation.", "Ester name: alkyl alkanoate.", "", []),
    ("Sources of ethanol", "Ethanol produced by fermentation of sugars by yeast (anaerobic) and by hydration of ethene industrially.", "formula_panel", {"formula": "Glucose →[yeast] Ethanol + CO₂", "note": "Fermentation source"}, "Production methods.", "Beer and wine production uses fermentation.", "Fermentation: sugar → ethanol + CO₂.", "Industrial route: ethene + H₂O → ethanol.", "", []),
    ("Sources of ethanoic acid", "Ethanoic acid obtained by oxidation of ethanol or from bacterial fermentation of cider/vinegar.", "formula_panel", {"formula": "Ethanol →[oxidation] Ethanoic acid", "note": "Oxidation of ethanol"}, "Production link.", "Vinegar forms when wine exposed to air.", "Oxidise ethanol → ethanoic acid.", "Bacteria Acetobacter oxidises ethanol in vinegar production.", "", []),
    ("Exam — ethanol and ethanoic acid", "Give formulas C₂H₅OH and CH₃COOH → uses → denatured alcohol → esterification overview → vinegar.", "placeholder", {"label": "Exam: key carbon compounds template"}, "Structured answer.", "Both compounds with structure and one use each.", "Formula + use + esterification link.", "Know common and IUPAC names.", "", []),
])

DAY12 = _build_day(12, [
    ("Physical properties of ethanol", "Ethanol is colourless liquid, miscible with water, volatile, burns with blue flame — good solvent.", "placeholder", {"label": "Ethanol — liquid, soluble, volatile"}, "Day 12 properties.", "Medical spirit is ethanol + water.", "Liquid alcohol at room temperature.", "Low boiling point — evaporates easily.", "", []),
    ("Ethanol reacts with sodium", "Sodium reacts with ethanol to give sodium ethoxide and hydrogen: 2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂.", "formula_panel", {"formula": "2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂", "note": "Ethanol + sodium — pop test H₂"}, "Reaction with reactive metal.", "Sodium fizzes in ethanol — H₂ evolved.", "–OH H is slightly acidic — Na displaces H.", "Less vigorous than Na + water.", "", []),
    ("Dehydration of ethanol", "Ethanol dehydrates to ethene on heating with conc. H₂SO₄ at 443 K: C₂H₅OH → C₂H₄ + H₂O.", "formula_panel", {"formula": "C₂H₅OH →[443K, conc. H₂SO₄] C₂H₄ + H₂O", "note": "Dehydration — removes water"}, "Reverse of hydration.", "Remove H₂O from ethanol → ethene.", "Conc. H₂SO₄ absorbs water — catalyst.", "443 K (170°C) temperature required.", "", []),
    ("Ethanol burns cleanly", "Ethanol combustion: C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O — clean blue flame, used as eco-friendly fuel.", "formula_panel", {"formula": "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O", "note": "Clean combustion"}, "Fuel property.", "Bioethanol mixed with petrol (gasohol).", "Complete combustion — blue flame.", "Renewable fuel from fermentation.", "", []),
    ("Properties of ethanoic acid", "Ethanoic acid is colourless liquid with pungent smell, sour taste, turns blue litmus red — weak acid.", "placeholder", {"label": "Ethanoic acid — sour, weak acid"}, "Physical and chemical properties.", "Vinegar smell is ethanoic acid.", "Weak acid — partially ionises.", "Glacial = 99%+ pure — freezes in cold.", "", []),
    ("Ethanoic acid as weak acid", "Ethanoic acid ionises partially in water: CH₃COOH ⇌ CH₃COO⁻ + H⁺ — weak acid, pH around 3 for vinegar.", "formula_panel", {"formula": "CH₃COOH ⇌ CH₃COO⁻ + H⁺", "note": "Weak acid — partial ionisation"}, "Acid strength concept.", "Does not dissociate fully like HCl.", "Weak acid — reversible ionisation.", "Turns blue litmus red — Ch 2 link.", "", []),
    ("Esterification equation — ethanoic acid + ethanol", "Ethanoic acid + ethanol → ethyl ethanoate + water (conc. H₂SO₄ catalyst, heat).", "formula_panel", {"formula": "CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O", "note": "Ethyl ethanoate — sweet smell"}, "Full NCERT esterification equation.", "Fruity smell confirms ester formed.", "Product: ethyl ethanoate (ester).", "Heat and conc. H₂SO₄ required.", "", []),
    ("Role of conc. H₂SO₄ in esterification", "Conc. H₂SO₄ acts as catalyst and dehydrating agent — speeds reaction and removes water to shift equilibrium.", "placeholder", {"label": "H₂SO₄ — catalyst + dehydrating agent"}, "Mechanism role.", "Few drops of conc. H₂SO₄ added.", "Catalyst + removes H₂O product.", "Do not confuse with dilute H₂SO₄ in other reactions.", "", []),
    ("Ethyl ethanoate — the ester product", "Ethyl ethanoate CH₃COOC₂H₅ is the ester — pleasant smell used in nail polish remover and flavourings.", "formula_panel", {"formula": "CH₃COOC₂H₅ — ethyl ethanoate", "note": "Ester product name"}, "Named ester product.", "Sweet fruity smell in lab esterification.", "Name: ethyl (from ethanol) ethanoate (from ethanoic acid).", "Ester naming: alkyl + alkanoate.", "", []),
    ("Exam — properties and reactions", "Ethanol: Na reaction, dehydration, combustion. Ethanoic acid: weak acid, esterification equation with sweet smell.", "placeholder", {"label": "Exam: ethanol and acid properties"}, "Structured answer.", "Write esterification as key reaction.", "Two compounds + two reactions each.", "Include conditions (443 K, conc. H₂SO₄).", "", []),
])

DAY13 = _build_day(13, [
    ("Soap structure — RCOO⁻Na⁺", "Soap is sodium or potassium salt of long-chain carboxylic acid (fatty acid) — RCOO⁻Na⁺.", "formula_panel", {"formula": "RCOO⁻Na⁺ — soap molecule", "note": "Long hydrocarbon tail + ionic head"}, "Core Day 13 concept.", "Sodium stearate is common soap component.", "Hydrophobic tail + hydrophilic –COO⁻ head.", "R = long carbon chain (15–17 carbons).", "", ["soap"]),
    ("Saponification — making soap", "Soap made by heating fat/oil with NaOH: fat + NaOH → soap + glycerol (saponification).", "formula_panel", {"formula": "Fat + NaOH → Soap + Glycerol", "note": "Saponification reaction"}, "Soap production reaction.", "Traditional soap making from animal fat.", "Alkaline hydrolysis of ester in fat.", "Glycerol is useful by-product.", "", ["saponification"]),
    ("Micelle formation", "In water, soap molecules form micelles — hydrophobic tails inward, hydrophilic heads outward facing water.", "placeholder", {"label": "Micelle — tails in, heads out"}, "Key cleansing mechanism.", "Spherical cluster of soap molecules in water.", "Tails hide inside; heads on surface.", "Micelle forms above critical concentration.", "", ["micelle"]),
    ("Cleansing action of soap", "Soap micelles surround oily dirt — hydrophobic tails dissolve grease inside micelle; rinsed away by water.", "placeholder", {"label": "Soap micelle traps oil/grease"}, "How soap cleans.", "Oil on clothes removed by soap micelles.", "Emulsifies oil in water via micelles.", "Hydrophobic tail dissolves non-polar dirt.", "", []),
    ("Hard water and soap scum", "Hard water contains Ca²⁺ and Mg²⁺ ions — react with soap to form insoluble scum (curd), wasting soap.", "formula_panel", {"formula": "Soap + Ca²⁺/Mg²⁺ → Insoluble scum", "note": "Hard water problem"}, "Hard water issue.", "White curd in bath with hard water + soap.", "Ca/Mg ions precipitate soap.", "Scum is calcium/magnesium salt of fatty acid.", "", []),
    ("Why soap fails in hard water", "Ca²⁺ and Mg²⁺ replace Na⁺ in soap forming insoluble precipitate — less soap available for cleaning.", "placeholder", {"label": "Ions precipitate soap as scum"}, "Mechanism explanation.", "Boiling hard water — scale on kettle.", "Soap wasted forming scum first.", "Soft water (rainwater) lathers well with soap.", "", []),
    ("Detergent structure", "Detergents are sodium salts of long-chain sulphonic acids or ammonium salts — similar tail, different head group.", "formula_panel", {"formula": "RSO₃⁻Na⁺ — detergent (sulphonate)", "note": "Similar to soap, different head"}, "Contrast with soap.", "Washing powder contains synthetic detergents.", "Sulphonate head instead of carboxylate.", "Tail still long hydrocarbon chain.", "", ["detergent"]),
    ("Detergents work in hard water", "Detergents do not form scum with Ca²⁺/Mg²⁺ — soluble salts remain, effective in hard water.", "formula_panel", {"formula": "Detergent + hard water → no scum", "note": "Advantage over soap"}, "Key detergent advantage.", "Washing powder works in hard water areas.", "Ca/Mg salts of detergents stay soluble.", "Main reason detergents replaced soap for laundry.", "", []),
    ("Soap vs detergent comparison", "Soap: biodegradable, scum in hard water. Detergent: works in hard water, may persist in environment.", "formula_panel", {"formula": "Soap: scum in hard water | Detergent: no scum", "note": "Comparison table"}, "Exam comparison.", "Soap better for environment; detergent better in hard water.", "Know both advantages and disadvantages.", "Some detergents are non-biodegradable — pollution concern.", "", []),
    ("Exam — micelle and cleansing action", "Describe soap structure → micelle formation → hydrophobic tail dissolves grease → hard water scum → detergent advantage.", "placeholder", {"label": "Exam: soap micelle template"}, "Structured answer.", "Draw micelle with tails inward.", "Structure + micelle + hard water + detergent.", "Include saponification equation if asked.", "", []),
])

DAY14 = _build_day(14, [
    ("Catenation definition", "Catenation is the ability of carbon atoms to link to each other in long chains, branches, and rings.", "placeholder", {"label": "Catenation — C links to C"}, "Core Day 14 concept.", "Carbon chains in petrol, proteins, DNA.", "Self-linking of carbon atoms.", "Carbon catenates more than any other element.", "", ["catenation"]),
    ("Tetravalency enables versatility", "Carbon's four valence electrons allow four covalent bonds — single, double, triple, and bonds to many elements.", "formula_panel", {"formula": "4 valence e⁻ → 4 bonds → huge variety", "note": "Tetravalency"}, "Second key property.", "C can bond to C, H, O, N, S, halogens.", "Four bonds in many combinations.", "Tetravalency + catenation = millions of compounds.", "", ["tetravalency"]),
    ("Millions of carbon compounds", "Over 5 million carbon compounds known — more than all other elements combined — due to catenation and tetravalency.", "placeholder", {"label": "5+ million carbon compounds"}, "Scale of organic chemistry.", "Plastics, drugs, dyes, fuels — all carbon-based.", "Carbon chemistry dominates compound count.", "New compounds synthesised daily.", "", []),
    ("Self-linking of carbon atoms", "Carbon–carbon bonds are strong and stable — carbon chains can be very long without breaking.", "formula_panel", {"formula": "C–C bond — strong, stable chains", "note": "Basis of catenation"}, "Bond strength explanation.", "Polyethylene has thousands of linked carbons.", "Strong C–C bonds hold chains together.", "Silicon catenates but Si–Si weaker than C–C.", "", []),
    ("Single, double, triple bond variety", "Carbon forms single (C–C), double (C=C), and triple (C≡C) bonds — multiplying possible structures.", "formula_panel", {"formula": "Single | Double | Triple C–C bonds", "note": "Bond variety adds diversity"}, "Structural diversity source.", "Alkanes, alkenes, alkynes from bond types.", "Three bond types × long chains = huge variety.", "Double bonds enable addition reactions.", "", []),
    ("Functional groups add diversity", "Same carbon skeleton with different functional groups (–OH, –COOH, –CHO) gives entirely different compounds.", "placeholder", {"label": "Functional groups multiply compounds"}, "Chemical diversity source.", "Ethanol and dimethyl ether both C₂H₆O — different groups.", "Same formula possible with different groups.", "Functional group determines properties.", "", []),
    ("Isomerism adds more compounds", "Same molecular formula, different structures (isomers) — butane/isobutane, functional group isomers.", "formula_panel", {"formula": "Same formula, different structure = isomer", "note": "Isomerism increases compound count"}, "Structural diversity.", "C₄H₁₀ has two structural isomers.", "Isomerism multiplies possible compounds.", "Millions of compounds include all isomers.", "", []),
    ("Role of carbon in living organisms", "All biomolecules — carbohydrates, proteins, lipids, nucleic acids — are carbon compounds with complex chains and rings.", "placeholder", {"label": "Carbon — basis of all life"}, "Biological importance.", "DNA double helix is carbon backbone.", "Life chemistry = carbon chemistry.", "No life without carbon compounds.", "", []),
    ("Scope of organic chemistry", "Organic chemistry studies carbon compounds — synthesis, reactions, and applications in medicine, industry, and life.", "placeholder", {"label": "Organic chemistry scope"}, "Field overview.", "Pharmaceuticals, polymers, food additives.", "Carbon compounds = organic chemistry.", "Class 10 Ch 4 is introduction to organic chemistry.", "", []),
    ("Exam — why carbon is unique", "State tetravalency + catenation → chains/branches/rings → functional groups → isomerism → millions of compounds + life.", "placeholder", {"label": "Exam: carbon versatility template"}, "Structured answer.", "Link both properties to compound count.", "Two properties + three diversity sources + example.", "Do not forget catenation AND tetravalency together.", "", []),
])

DAY15 = _build_day(15, [
    ("Review — saturated vs unsaturated", "Saturated: CₙH₂ₙ₊₂, single bonds, substitution. Unsaturated: CₙH₂ₙ or CₙH₂ₙ₋₂, addition, bromine test.", "formula_panel", {"formula": "Saturated: CₙH₂ₙ₊₂ | Unsaturated: CₙH₂ₙ, CₙH₂ₙ₋₂", "note": "Review card 1"}, "Mixed review Day 15.", "Methane vs ethene comparison.", "Formulas + reactions + bromine test.", "Bromine water distinguishes unsaturated.", "", []),
    ("Review — functional groups", "–OH alcohol, –CHO aldehyde, C=O ketone, –COOH carboxylic acid, –X haloalkane — determine chemical properties.", "formula_panel", {"formula": "-OH | -CHO | C=O | -COOH | -X", "note": "Review card 2"}, "Functional group revision.", "Ethanol, ethanoic acid, CH₃Cl examples.", "Five groups with examples.", "Group determines homologous series.", "", []),
    ("Review — allotropes of carbon", "Diamond: hard, insulator, 4 bonds. Graphite: soft, conductor, layers. Fullerene C₆₀: cage structure.", "formula_panel", {"formula": "Diamond | Graphite | C₆₀", "note": "Review card 3"}, "Allotrope revision.", "Pencil lead = graphite; diamond ring.", "Three allotropes + key properties.", "Same element — different arrangement.", "", []),
    ("Review — homologous series", "Same functional group, differ by CH₂, similar chemical properties, gradual physical property change.", "formula_panel", {"formula": "Difference = CH₂ (14 u)", "note": "Review card 4"}, "Homologous series revision.", "Alkane series CH₄ to C₄H₁₀.", "CH₂ difference + similar chemistry.", "Boiling point increases down series.", "", []),
    ("Review — combustion", "Complete: CO₂ + H₂O (blue flame). Incomplete: soot + CO (yellow flame). CH₄ + 2O₂ → CO₂ + 2H₂O.", "formula_panel", {"formula": "Complete: CO₂ + H₂O | Incomplete: C + CO", "note": "Review card 5"}, "Combustion revision.", "Balanced methane combustion equation.", "Two types + equation + CO danger.", "Oxidation of alcohol also revision.", "", []),
    ("Review — addition vs substitution", "Addition: unsaturated (C₂H₄ + Br₂). Substitution: saturated (CH₄ + Cl₂, UV). Know conditions.", "formula_panel", {"formula": "Addition: C₂H₄ + Br₂ | Substitution: CH₄ + Cl₂", "note": "Review card 6"}, "Reaction type revision.", "Bromine water test for addition.", "Two equations + conditions.", "Sunlight needed for substitution.", "", []),
    ("Review — ethanol and ethanoic acid", "C₂H₅OH (solvent, fuel) and CH₃COOH (vinegar, weak acid) — esterification links them.", "formula_panel", {"formula": "C₂H₅OH + CH₃COOH → Ester + H₂O", "note": "Review card 7"}, "Key compounds revision.", "Esterification sweet smell test.", "Formulas + one reaction each.", "Denatured alcohol — poison added.", "", []),
    ("Review — soaps and detergents", "Soap RCOO⁻Na⁺, micelle cleans, scum in hard water. Detergent works in hard water — no scum.", "formula_panel", {"formula": "Soap: scum | Detergent: no scum", "note": "Review card 8"}, "Soap revision.", "Micelle: tails in, heads out.", "Structure + micelle + hard water.", "Saponification: fat + NaOH → soap.", "", []),
    ("Review — Lewis structures", "CH₄ (4 single), C₂H₆ (C–C + 6 C–H), O₂ (double), N₂ (triple), CO₂ (2 double), H₂O (2 single + lone pairs).", "formula_panel", {"formula": "CH₄ | C₂H₆ | O₂ | N₂ | CO₂ | H₂O", "note": "Review card 9"}, "Lewis structure revision.", "Draw all six for exam practice.", "Six key Lewis structures from NCERT.", "Show lone pairs on O and N.", "", []),
    ("Review — nomenclature", "Roots meth– to hex–; suffixes -ane, -ene, -yne, -ol, -oic acid; examples ethanol, ethanoic acid.", "formula_panel", {"formula": "Root + suffix = IUPAC name", "note": "Review card 10"}, "Nomenclature revision.", "Propene C₃H₆; propanol C₃H₇OH.", "Roots 1–6 + suffix rules.", "Common names also accepted.", "", []),
])

DAY16 = _build_day(16, [
    ("Exam — Lewis structures template", "Count valence e⁻ → central atom → share to complete octets → CH₄, H₂O, CO₂, O₂, N₂, C₂H₆.", "placeholder", {"label": "Exam: Lewis structures checklist"}, "Exam prep card 1.", "Practice drawing all six structures.", "Six structures from NCERT Ch 4.", "Duplet for H; octet for C, O, N.", "", []),
    ("Exam — hydrocarbon formulas", "Alkanes CₙH₂ₙ₊₂, alkenes CₙH₂ₙ, alkynes CₙH₂ₙ₋₂ — give examples CH₄, C₂H₄, C₂H₂.", "formula_panel", {"formula": "CₙH₂ₙ₊₂ | CₙH₂ₙ | CₙH₂ₙ₋₂", "note": "Exam prep card 2"}, "Formula revision.", "Three formulas with two-carbon examples.", "Memorise all three general formulas.", "Saturation indicated by H count.", "", []),
    ("Exam — reaction types summary", "Combustion (CO₂ + H₂O), addition (unsaturated + Br₂), substitution (CH₄ + Cl₂, UV), esterification (acid + alcohol).", "formula_panel", {"formula": "Combustion | Addition | Substitution | Esterification", "note": "Exam prep card 3"}, "Reaction summary.", "One equation per reaction type.", "Four reaction types with conditions.", "Match reaction to compound type.", "", []),
    ("Exam — functional groups table", "Tabulate –OH, –CHO, C=O, –COOH, –X with name, example, and one property each.", "placeholder", {"label": "Exam: functional groups revision"}, "Exam prep card 4.", "Ethanol, ethanoic acid, CH₃Cl as examples.", "Five-row table for full marks.", "Functional group = homologous series marker.", "", []),
    ("Exam — bromine water test", "Unsaturated compound + bromine water → decolourisation (addition). Saturated → no change.", "formula_panel", {"formula": "C₂H₄ + Br₂ → C₂H₄Br₂ (decolourises)", "note": "Exam prep card 5"}, "Test revision.", "Ethene positive; ethane negative.", "Orange → colourless = unsaturated.", "State addition reaction mechanism briefly.", "", []),
    ("Exam — esterification", "Acid + alcohol → ester + water; conc. H₂SO₄ catalyst; sweet smell confirms product.", "formula_panel", {"formula": "CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O", "note": "Exam prep card 6"}, "Esterification revision.", "Ethyl ethanoate — fruity smell.", "Full equation + conditions + smell test.", "Name ester product correctly.", "", []),
    ("Exam — soap micelle description", "Soap RCOO⁻Na⁺ → micelle in water → hydrophobic tail dissolves grease → hard water scum → detergent alternative.", "placeholder", {"label": "Exam: soap cleansing template"}, "Exam prep card 7.", "Describe micelle structure in words.", "Structure + mechanism + hard water.", "Include saponification if asked for preparation.", "", []),
    ("Exam — incomplete combustion", "Limited O₂ → soot (C) + CO + H₂O; CO poisonous; complete combustion gives CO₂ + H₂O only.", "formula_panel", {"formula": "Incomplete: C + CO | Complete: CO₂", "note": "Exam prep card 8"}, "Combustion exam point.", "Yellow flame = incomplete.", "Two products sets + CO hazard.", "Ventilation prevents CO poisoning.", "", []),
    ("Unit 4 exam — full revision summary", "Bonding → allotropes → hydrocarbons → functional groups → reactions → ethanol/acid → soaps → catenation/tetravalency.", "formula_panel", {"formula": "Structure → Reactions → Applications", "note": "Unit 4 revision map"}, "Revision card 9.", "160 concept cards cover all topics.", "Three pillars: structure, reactions, daily life.", "Link structure to reactivity in answers.", "", []),
    ("Unit 4 complete", "Unit 4 Carbon and its Compounds complete — all 160 cards; proceed to Practice when unlocked.", "placeholder", {"label": "Unit 4 complete — 160 cards"}, "Completion card.", "200 MCQs in bank when available.", "Concepts done → practice.", "Review Lewis structures, bromine test, and esterification for exams.", "", []),
])

DAY_BUILDERS = {
    1: lambda: DAY1,
    2: lambda: DAY2,
    3: lambda: DAY3,
    4: lambda: DAY4,
    5: lambda: DAY5,
    6: lambda: DAY6,
    7: lambda: DAY7,
    8: lambda: DAY8,
    9: lambda: DAY9,
    10: lambda: DAY10,
    11: lambda: DAY11,
    12: lambda: DAY12,
    13: lambda: DAY13,
    14: lambda: DAY14,
    15: lambda: DAY15,
    16: lambda: DAY16,
}

DAY_TITLES = {
    1: "Carbon and its Compounds — Introduction",
    2: "Bonding in Carbon — Covalency and Electron Dot Structures",
    3: "Allotropes of Carbon — Diamond, Graphite, Fullerene",
    4: "Saturated and Unsaturated Hydrocarbons",
    5: "Chains, Branches and Rings in Carbon Compounds",
    6: "Homologous Series and Functional Groups",
    7: "Nomenclature of Carbon Compounds",
    8: "Chemical Properties — Combustion and Oxidation",
    9: "Addition Reactions — Unsaturated Compounds",
    10: "Substitution Reactions — Saturated Compounds",
    11: "Important Carbon Compounds — Ethanol and Ethanoic Acid",
    12: "Properties of Ethanol and Ethanoic Acid",
    13: "Soaps and Detergents — Micelles and Cleansing Action",
    14: "Versatile Nature of Carbon — Catenation and Tetravalency",
    15: "Mixed Review — Hydrocarbons and Functional Groups",
    16: "Exam Prep — Reactions, Nomenclature and Everyday Chemistry",
}
