"""Full concept card content for Harshit Chemistry Unit 2 — Days 1–16 (Ch 2 Acids, Bases and Salts)."""

from __future__ import annotations


def _card(
    cid: str,
    name: str,
    simple: str,
    visual_type: str,
    visual_config: dict | None,
    why: str,
    example: str,
    remember: str,
    confusion: str = "",
    optional: str = "",
    glossary: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "name": name,
        "simple_answer": simple,
        "visual": {"type": visual_type, **(visual_config or {})},
        "why": why,
        "example": example,
        "remember": remember,
        "common_confusion": confusion,
        "optional_detail": optional,
        "glossary_terms": glossary or [],
    }


def _build_day(day: int, cards: list[tuple]) -> list[dict]:
    out = []
    for i, row in enumerate(cards, 1):
        name, simple, vtype, vcfg, why, ex, rem, *rest = row
        confusion = rest[0] if len(rest) > 0 else ""
        optional = rest[1] if len(rest) > 1 else ""
        gloss = rest[2] if len(rest) > 2 else []
        out.append(
            _card(
                f"u2_d{day}_c{i:02d}",
                name,
                simple,
                vtype,
                vcfg if isinstance(vcfg, dict) else {},
                why,
                ex,
                rem,
                confusion,
                optional,
                gloss if isinstance(gloss, list) else [],
            )
        )
    return out


DAY1 = _build_day(1, [
    ("What are acids?", "Acids are substances that taste sour, turn blue litmus red, and contain replaceable hydrogen.", "placeholder", {"label": "Acids — sour, litmus red"}, "Foundation of Ch 2 — acids introduced first.", "Lemon juice and vinegar taste sour because of acids.", "Sour taste + blue litmus → red = acid clues.", "Not all acids are safe to taste — lab acids are corrosive.", "", ["acid"]),
    ("What are bases?", "Bases are bitter, soapy to touch, turn red litmus blue, and include metal oxides/hydroxides.", "placeholder", {"label": "Bases — bitter, litmus blue"}, "Pair concept with acids.", "Soap solution feels slippery — basic.", "Bitter + soapy feel + red litmus → blue = base.", "Bases are not always solids — NaOH is aqueous base.", "", ["base"]),
    ("What are salts?", "Salts are ionic compounds formed when acid reacts with base — e.g. NaCl, CuSO₄, Na₂CO₃.", "formula_panel", {"formula": "Acid + Base → Salt + Water", "note": "Neutralisation product"}, "Third pillar of chapter title.", "Table salt NaCl from HCl + NaOH.", "Salt = product of acid-base reaction (usually).", "Not every salt comes from neutralisation — but most in Ch 2 do.", "", ["salt"]),
    ("Natural sources of acids", "Acids occur in fruits (citric), vinegar (acetic), curd (lactic), and stomach (HCl).", "placeholder", {"label": "Acids in nature and food"}, "NCERT everyday examples.", "Tamarind and orange contain acids.", "Many foods are naturally acidic.", "Natural acids are dilute; lab acids like conc. H₂SO₄ are dangerous.", "", []),
    ("Natural sources of bases", "Bases include lime water Ca(OH)₂, baking soda NaHCO₃, and antacids like milk of magnesia Mg(OH)₂.", "placeholder", {"label": "Bases in daily life"}, "Connect to later sections.", "Whitewash uses slaked lime — basic.", "Lime, antacids, and soap are common bases.", "Baking soda is hydrogencarbonate — amphoteric behaviour later.", "", []),
    ("Mineral acids vs organic acids", "Mineral acids (HCl, H₂SO₄, HNO₃) from minerals; organic acids (CH₃COOH, HCOOH) from living sources.", "formula_panel", {"formula": "Mineral: HCl, H₂SO₄, HNO₃ | Organic: CH₃COOH", "note": "Two acid families"}, "Classification in NCERT.", "Vinegar contains acetic acid CH₃COOH.", "Mineral = inorganic; organic = carbon-containing acid.", "Organic acids are generally weaker than mineral acids.", "", []),
    ("Strong vs weak acids (intro)", "Strong acids ionise completely in water (HCl, H₂SO₄, HNO₃); weak acids partially (CH₃COOH).", "formula_panel", {"formula": "Strong acid → H⁺ completely", "note": "Weak acid → partial H⁺"}, "Preview for pH section.", "Dilute HCl conducts well — many ions.", "Strong = full ionisation; weak = partial.", "Strength is not the same as concentration.", "", []),
    ("Alkalis", "Water-soluble bases are called alkalis — NaOH, KOH, Ca(OH)₂, NH₄OH dissolve to give OH⁻.", "formula_panel", {"formula": "Alkali = soluble base", "note": "NaOH, KOH, Ca(OH)₂"}, "NCERT term for soluble bases.", "NaOH pellets dissolve in water — alkali.", "All alkalis are bases; not all bases are alkalis.", "Mg(OH)₂ is a base but insoluble — not an alkali.", "", ["alkali"]),
    ("Indicators preview", "Substances that change colour in acid or base — litmus, turmeric, methyl orange, phenolphthalein.", "placeholder", {"label": "Indicators change colour"}, "Leads to Day 2 detail.", "Blue litmus turns red in acid.", "Indicators detect acid/base without tasting.", "Universal indicator shows full pH range — Day 11.", "", ["indicator"]),
    ("Chapter 2 roadmap", "Ch 2 covers acids, bases, salts, indicators, reactions, pH, everyday uses, and chemicals from common salt.", "placeholder", {"label": "Ch 2 roadmap — 16 days"}, "Orient learner to unit plan.", "Activity 2.1–2.4 in lab sections.", "Acids/bases → reactions → pH → salts → industry.", "", "", []),
])

DAY2 = _build_day(2, [
    ("What is an indicator?", "An indicator is a substance that shows different colours in acidic and basic media.", "placeholder", {"label": "Indicator — colour in acid/base"}, "Core Day 2 concept.", "Litmus paper distinguishes acid from base.", "One colour in acid, different in base.", "Indicator does not measure exact pH unless universal indicator.", "", ["indicator"]),
    ("Litmus — source and colours", "Litmus is a natural dye from lichen; turns red in acid, blue in base.", "formula_panel", {"formula": "Acid: blue → red | Base: red → blue", "note": "Litmus colour change"}, "Most common school indicator.", "Blue litmus paper dipped in HCl turns red.", "Blue litmus + acid → red; red litmus + base → blue.", "Purple/neutral litmus in distilled water.", "", ["litmus"]),
    ("Red litmus in base", "Red litmus paper turns blue in basic solution — confirms base.", "placeholder", {"label": "Red litmus → blue (base)"}, "Second half of litmus test.", "NaOH solution turns red litmus blue.", "Red → blue means basic.", "Red litmus stays red in acid — no change.", "", []),
    ("Blue litmus in acid", "Blue litmus paper turns red in acidic solution — confirms acid.", "placeholder", {"label": "Blue litmus → red (acid)"}, "First half of litmus test.", "Dilute HCl turns blue litmus red.", "Blue → red means acidic.", "Blue litmus stays blue in base.", "", []),
    ("Turmeric as indicator", "Turmeric (haldi) is natural indicator — yellow in neutral/acid, reddish-brown in base.", "formula_panel", {"formula": "Turmeric: yellow (acid) → red-brown (base)", "note": "Natural indicator"}, "NCERT home indicator example.", "Soap on turmeric stain turns red-brown.", "Turmeric paper detects base at home.", "Turmeric does not change in acid — stays yellow.", "", []),
    ("China rose (Gudhal) indicator", "China rose petal extract: dark pink in acid, green in base.", "placeholder", {"label": "China rose — pink/green"}, "Another NCERT natural indicator.", "Petals soaked in hot water give extract.", "Pink = acid; green = base.", "Not as common as litmus in exams.", "", []),
    ("Methyl orange", "Synthetic indicator methyl orange: red in strong acid, yellow in strong base, orange in neutral.", "formula_panel", {"formula": "Methyl orange: red (acid) → yellow (base)", "note": "Synthetic indicator"}, "NCERT synthetic indicator list.", "Used in titration to mark end point.", "Red in acid; yellow in base.", "Orange in near-neutral pH.", "", ["methyl orange"]),
    ("Phenolphthalein", "Phenolphthalein is colourless in acid, pink/fuchsia in base.", "formula_panel", {"formula": "Phenolphthalein: colourless (acid) → pink (base)", "note": "Synthetic indicator"}, "Standard titration indicator.", "NaOH turns phenolphthalein pink.", "Colourless in acid; pink in base.", "Very faint pink near pH 8 — endpoint in titration.", "", ["phenolphthalein"]),
    ("Natural vs synthetic indicators", "Natural: litmus, turmeric, china rose. Synthetic: methyl orange, phenolphthalein.", "placeholder", {"label": "Natural vs synthetic indicators"}, "Classification for exams.", "Litmus from lichen — natural.", "Natural from plants; synthetic made in lab.", "Both work on same principle — colour change.", "", []),
    ("Choosing an indicator", "Pick indicator whose colour change matches expected pH range of titration or test.", "placeholder", {"label": "Match indicator to pH range"}, "Practical exam skill.", "Phenolphthalein for strong acid–strong base titration.", "Indicator must change in range of reaction.", "Wrong indicator may miss endpoint.", "", []),
])

DAY3 = _build_day(3, [
    ("Activity 2.1 — acids in lab", "NCERT Activity 2.1: collect samples of HCl, H₂SO₄, HNO₃, CH₃COOH, NaOH, Ca(OH)₂, KOH, Mg(OH)₂, NH₄OH.", "placeholder", {"label": "Activity 2.1 — lab samples"}, "Central lab activity for Ch 2.", "Test each with litmus and indicators.", "Know the nine NCERT substances.", "Handle acids and bases with care — corrosive.", "", []),
    ("Hydrochloric acid HCl", "HCl is a strong mineral acid — colourless, pungent, turns blue litmus red.", "formula_panel", {"formula": "HCl → H⁺ + Cl⁻", "note": "Strong mineral acid"}, "First acid in Activity 2.1.", "Present in stomach for digestion.", "Strong acid; fully ionises in water.", "Never called hydrochloric acid(HCl) without 'acid'.", "", []),
    ("Sulphuric acid H₂SO₄", "H₂SO₄ is strong mineral acid — dense, oily, dibasic acid used in industry.", "formula_panel", {"formula": "H₂SO₄ → 2H⁺ + SO₄²⁻", "note": "Strong dibasic acid"}, "Second mineral acid in list.", "Car batteries contain dilute H₂SO₄.", "Two replaceable H⁺ per molecule.", "Concentrated H₂SO₄ is highly corrosive — add to water only.", "", []),
    ("Nitric acid HNO₃", "HNO₃ is strong mineral acid — used in fertilisers and explosives manufacture.", "formula_panel", {"formula": "HNO₃ → H⁺ + NO₃⁻", "note": "Strong mineral acid"}, "Third mineral acid.", "Reacts with metals; often gives NO₂ with copper.", "Strong acid; oxidising nature with metals.", "Not all metal + HNO₃ give H₂ — oxidising acid.", "", []),
    ("Acetic acid CH₃COOH", "CH₃COOH (ethanoic acid) is weak organic acid in vinegar (~4–5%).", "formula_panel", {"formula": "CH₃COOH ⇌ H⁺ + CH₃COO⁻", "note": "Weak organic acid"}, "Organic acid in Activity 2.1.", "Vinegar for cooking and pickling.", "Weak acid — partial ionisation.", "Vinegar is dilute acetic acid, not HCl.", "", []),
    ("Sodium hydroxide NaOH", "NaOH (caustic soda) is strong alkali — white pellets, corrosive, turns red litmus blue.", "formula_panel", {"formula": "NaOH → Na⁺ + OH⁻", "note": "Strong alkali"}, "First base in Activity 2.1.", "Used in soap and paper industry.", "Strong base; fully ionises.", "Caustic — never touch with wet hands.", "", []),
    ("Calcium hydroxide Ca(OH)₂", "Ca(OH)₂ (slaked lime) is alkali — used in whitewash and water treatment.", "formula_panel", {"formula": "Ca(OH)₂ → Ca²⁺ + 2OH⁻", "note": "Slaked lime — alkali"}, "Limewater is saturated Ca(OH)₂ solution.", "Turns milky with CO₂ — test for carbon dioxide.", "Less soluble than NaOH but still alkali.", "Limewater = Ca(OH)₂ aqueous, not CaO.", "", []),
    ("Potassium hydroxide KOH", "KOH (caustic potash) is strong alkali — similar to NaOH, used in soft soaps.", "formula_panel", {"formula": "KOH → K⁺ + OH⁻", "note": "Strong alkali"}, "Third alkali in list.", "Soft soap from KOH + fat.", "Strong soluble base.", "KOH and NaOH both strong — do not taste either.", "", []),
    ("Magnesium hydroxide Mg(OH)₂", "Mg(OH)₂ (milk of magnesia) is weakly soluble base — antacid for indigestion.", "formula_panel", {"formula": "Mg(OH)₂ ⇌ Mg²⁺ + 2OH⁻", "note": "Insoluble base — antacid"}, "Base but not alkali — insoluble.", "Neutralises excess stomach HCl.", "Base that is not alkali (insoluble).", "Milk of magnesia is suspension, not clear solution.", "", []),
    ("Ammonium hydroxide NH₄OH", "NH₄OH (ammonia solution) is weak alkali — pungent smell, cleaning agent.", "formula_panel", {"formula": "NH₄OH ⇌ NH₄⁺ + OH⁻", "note": "Weak alkali"}, "Last sample in Activity 2.1.", "Window cleaner contains ammonia.", "Weak base; pungent NH₃ smell.", "Formula NH₄OH represents aqueous ammonia.", "", []),
])

DAY4 = _build_day(4, [
    ("Acid + metal reaction (general)", "Acid reacts with metal to give salt and hydrogen gas.", "formula_panel", {"formula": "Acid + Metal → Salt + H₂ ↑", "note": "General reaction"}, "Core Day 4 pattern.", "Zn + HCl → ZnCl₂ + H₂.", "Metal displaces hydrogen from acid.", "Only metals above H in reactivity series with dilute acid.", "", []),
    ("Zinc and dilute HCl", "Zn + 2HCl → ZnCl₂ + H₂ — bubbles of hydrogen, zinc dissolves.", "formula_panel", {"formula": "Zn + 2HCl → ZnCl₂ + H₂", "note": "Salt + hydrogen"}, "Classic NCERT example.", "Activity from Ch 1 revisited in Ch 2 context.", "Zinc chloride + hydrogen gas.", "Copper does not react with dilute HCl.", "", []),
    ("Magnesium and dilute H₂SO₄", "Mg + H₂SO₄ → MgSO₄ + H₂ — vigorous reaction, hydrogen evolved.", "formula_panel", {"formula": "Mg + H₂SO₄ → MgSO₄ + H₂", "note": "Magnesium sulphate + H₂"}, "Second metal-acid example.", "Mg ribbon reacts faster than Zn.", "Same pattern: salt + H₂.", "Hot and fast — handle with tongs.", "", []),
    ("Iron and dilute acid", "Fe + 2HCl → FeCl₂ + H₂ — iron nails produce hydrogen slowly.", "formula_panel", {"formula": "Fe + 2HCl → FeCl₂ + H₂", "note": "Ferrous chloride + H₂"}, "Shows Fe above hydrogen.", "Pale green FeCl₂ solution forms.", "Iron displaces H from dilute acid.", "Fe with conc. HNO₃ may not give H₂ — passivation.", "", []),
    ("Testing for hydrogen gas", "Bring burning splint to mouth of tube — hydrogen burns with pop sound.", "placeholder", {"label": "H₂ test — pop sound"}, "Standard NCERT confirmatory test.", "Activity 2.2 hydrogen test.", "Pop sound = hydrogen confirmed.", "Oxygen relights splint — do not confuse.", "", []),
    ("Why hydrogen forms", "Acids contain replaceable H⁺; reactive metal displaces H as H₂ gas.", "formula_panel", {"formula": "2H⁺ + 2e⁻ → H₂", "note": "Metal supplies electrons"}, "Mechanism view.", "Zn loses electrons; H⁺ gains to form H₂.", "Metal + H⁺ → salt + H₂.", "Unreactive metals (Cu, Ag, Au) no reaction.", "", []),
    ("Reactivity series restriction", "Only metals above hydrogen in reactivity series react with dilute acids to give H₂.", "placeholder", {"label": "Metal must be above H"}, "Predicting reaction feasibility.", "Mg, Zn, Fe react; Cu does not.", "Cu + HCl → no reaction.", "Series order: Mg > Zn > Fe > H > Cu.", "", []),
    ("Salt name from acid", "From HCl → chloride salt; H₂SO₄ → sulphate; HNO₃ → nitrate; CH₃COOH → acetate.", "formula_panel", {"formula": "HCl → chloride | H₂SO₄ → sulphate", "note": "Acid determines salt name"}, "Naming products.", "Zn + HCl → zinc chloride.", "Anion from acid names the salt.", "Sulphuric acid always gives sulphate salts.", "", []),
    ("Safety with acid-metal reactions", "Use dilute acid, small metal pieces, test tube tilted, never add water to acid.", "placeholder", {"label": "Lab safety — acid + metal"}, "Practical safety card.", "Wear goggles; hydrogen is flammable.", "Dilute acid + small pieces + splint test.", "Never look directly into mouth of tube when testing gas.", "", []),
    ("Exam pattern — acid and metal", "Typical question: write equation, name salt, describe H₂ test with pop sound.", "placeholder", {"label": "Exam: acid + metal template"}, "Three-part answer structure.", "Zn + 2HCl → ZnCl₂ + H₂; pop with splint.", "Equation + salt name + H₂ test.", "Balance equation for full marks.", "", []),
])

DAY5 = _build_day(5, [
    ("Acid + carbonate (general)", "Acid reacts with metal carbonate to give salt, water, and carbon dioxide.", "formula_panel", {"formula": "Acid + Carbonate → Salt + H₂O + CO₂ ↑", "note": "General reaction"}, "Day 5 core pattern.", "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂.", "CO₂ gas evolves as bubbles.", "Three products — not same as acid + metal.", "", []),
    ("Acid + hydrogencarbonate", "Acid reacts with hydrogencarbonate (bicarbonate) to give salt, water, and CO₂.", "formula_panel", {"formula": "Acid + Hydrogencarbonate → Salt + H₂O + CO₂", "note": "Same products as carbonate"}, "Second Day 5 pattern.", "NaHCO₃ + HCl → NaCl + H₂O + CO₂.", "Baking soda fizzes with vinegar.", "Hydrogencarbonate also releases CO₂.", "NaHCO₃ is baking soda — Ch 2 later section.", "", []),
    ("Marble and dilute HCl", "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂ — marble effervesces.", "formula_panel", {"formula": "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂", "note": "Marble chips + acid"}, "NCERT classic demo.", "Chalk and marble both contain CaCO₃.", "Brisk bubbling = CO₂ evolution.", "Marble is CaCO₃ — same as limestone.", "", []),
    ("Sodium carbonate and acid", "Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂ — washing soda reacts with acid.", "formula_panel", {"formula": "Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂", "note": "Carbonate + acid"}, "Links to salts section later.", "CO₂ turns lime water milky.", "Sodium chloride + water + CO₂.", "Na₂CO₃ is washing soda (anhydrous form later).", "", []),
    ("Baking soda and vinegar", "NaHCO₃ + CH₃COOH → CH₃COONa + H₂O + CO₂ — kitchen reaction.", "formula_panel", {"formula": "NaHCO₃ + CH₃COOH → CH₃COONa + H₂O + CO₂", "note": "Baking soda + vinegar"}, "Everyday NCERT example.", "Cake rises from CO₂ in batter.", "Hydrogencarbonate + acid → CO₂.", "This CO₂ leavens bread and cakes.", "", []),
    ("Testing for carbon dioxide", "Pass CO₂ through lime water Ca(OH)₂ — turns milky due to CaCO₃ precipitate.", "formula_panel", {"formula": "CO₂ + Ca(OH)₂ → CaCO₃ + H₂O", "note": "Milky lime water = CO₂"}, "Standard NCERT confirmatory test.", "Activity 2.2 CO₂ test.", "Milky = CO₂ confirmed.", "Excess CO₂ clears milkiness — Ca(HCO₃)₂ forms.", "", []),
    ("Why CO₂ forms with carbonate", "H⁺ from acid reacts with CO₃²⁻ or HCO₃⁻ to release H₂CO₃ which decomposes to H₂O + CO₂.", "placeholder", {"label": "H⁺ + carbonate → CO₂"}, "Mechanism simplified.", "Effervescence is CO₂ escaping.", "Carbonate ion breaks down to CO₂ in acid.", "Same test (milky lime water) for all carbonate/acid reactions.", "", []),
    ("Compare acid+metal vs acid+carbonate", "Acid + metal → salt + H₂. Acid + carbonate → salt + H₂O + CO₂.", "formula_panel", {"formula": "Metal → H₂ | Carbonate → H₂O + CO₂", "note": "Different gases — different tests"}, "Exam distinction.", "Pop test for H₂; milky lime water for CO₂.", "Products differ — test accordingly.", "Do not confuse H₂ pop with CO₂ milky test.", "", []),
    ("Activity 2.2 context", "NCERT Activity 2.2: react acids with metal carbonates/hydrogencarbonates; test CO₂ with lime water.", "placeholder", {"label": "Activity 2.2 — CO₂ test"}, "Lab activity anchor.", "NaHCO₃ + HCl in test tube → bubble through limewater.", "Observe bubbles + milky limewater.", "Activity also includes acid + metal for H₂.", "", []),
    ("Exam template — acid and carbonate", "Write balanced equation + state CO₂ test (lime water turns milky) + name all products.", "placeholder", {"label": "Exam: acid + carbonate"}, "Structured answer.", "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂; milky limewater.", "Equation + CO₂ test + products.", "Include H₂O as product — often forgotten.", "", []),
])

DAY6 = _build_day(6, [
    ("Neutralisation definition", "Neutralisation is reaction between acid and base to form salt and water.", "formula_panel", {"formula": "Acid + Base → Salt + Water", "note": "Neutralisation reaction"}, "Central Day 6 concept.", "HCl + NaOH → NaCl + H₂O.", "Acid + base cancel each other's effects.", "Also a double displacement reaction.", "", ["neutralisation"]),
    ("NaOH and HCl", "NaOH + HCl → NaCl + H₂O — classic strong acid–strong base neutralisation.", "formula_panel", {"formula": "NaOH + HCl → NaCl + H₂O", "note": "Sodium chloride + water"}, "Most common NCERT example.", "Antacid neutralises stomach acid similarly.", "Salt + water only in products.", "Needs balancing: coefficients are 1:1:1:1.", "", []),
    ("H₂SO₄ and KOH", "H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O — dibasic acid needs two moles of base.", "formula_panel", {"formula": "H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O", "note": "Potassium sulphate + water"}, "Shows stoichiometry with dibasic acid.", "Two OH⁻ needed per H₂SO₄.", "Balance OH⁻ with H⁺ count.", "H₂SO₄ has two replaceable H.", "", []),
    ("Ca(OH)₂ and HCl", "Ca(OH)₂ + 2HCl → CaCl₂ + 2H₂O — lime neutralises acid.", "formula_panel", {"formula": "Ca(OH)₂ + 2HCl → CaCl₂ + 2H₂O", "note": "Calcium chloride + water"}, "Slaked lime as base.", "Farmers add lime to neutralise acidic soil.", "Two HCl per Ca(OH)₂ — two OH⁻.", "", "", []),
    ("NH₄OH and HNO₃", "NH₄OH + HNO₃ → NH₄NO₃ + H₂O — ammonium nitrate salt formed.", "formula_panel", {"formula": "NH₄OH + HNO₃ → NH₄NO₃ + H₂O", "note": "Ammonium nitrate + water"}, "Weak base + strong acid.", "Fertiliser ammonium nitrate from this salt.", "Same neutralisation pattern.", "NH₄NO₃ is important fertiliser salt.", "", []),
    ("Neutralisation is exothermic", "Neutralisation releases heat — test tube feels warm when acid and base mix.", "formula_panel", {"formula": "Acid + Base → Salt + Water + Heat", "note": "Exothermic reaction"}, "NCERT energy note.", "Hand on mixed NaOH + HCl feels warm.", "Heat released = exothermic.", "Not all students feel heat with dilute solutions.", "", []),
    ("H⁺ + OH⁻ → H₂O", "At ionic level: hydrogen ion from acid combines with hydroxide from base to form water.", "formula_panel", {"formula": "H⁺ + OH⁻ → H₂O", "note": "Ionic neutralisation"}, "Mechanism behind salt + water.", "Net ionic equation for all strong acid–strong base.", "Real neutralisation is H⁺ + OH⁻.", "Salt ions remain in solution (spectator ions).", "", []),
    ("Uses of neutralisation", "Antacids for indigestion, treating acidic soil with lime, factory waste treatment.", "placeholder", {"label": "Neutralisation in daily life"}, "Application card.", "Mg(OH)₂ neutralises excess HCl in stomach.", "Base added to excess acid (or vice versa).", "Wasps sting basic — vinegar (acid) relieves.", "", []),
    ("Activity 2.3 — neutralisation", "NCERT Activity 2.3: warm test tube when acid and base mixed — exothermic neutralisation.", "placeholder", {"label": "Activity 2.3 — warm tube"}, "Lab observation link.", "NaOH + HCl in test tube — feel warmth.", "Record temperature rise.", "Compare before mixing vs after.", "", []),
    ("Exam template — neutralisation", "Define neutralisation → general equation → specific example → note exothermic + H⁺ + OH⁻ → H₂O.", "placeholder", {"label": "Exam: neutralisation template"}, "Long-answer structure.", "5-mark: definition + equation + application + exothermic.", "Four-part answer scores well.", "Always balance the equation.", "", []),
])

DAY7 = _build_day(7, [
    ("Metallic oxides are basic", "Oxides of metals are generally basic — turn red litmus blue, react with acids.", "formula_panel", {"formula": "Metal oxide + Acid → Salt + Water", "note": "Basic oxide"}, "Day 7 theme.", "CuO + H₂SO₄ → CuSO₄ + H₂O.", "Metal oxides = basic oxides.", "Basic oxide reacts like a base with acid.", "", []),
    ("Copper oxide and sulphuric acid", "CuO + H₂SO₄ → CuSO₄ + H₂O — black CuO dissolves, blue solution forms.", "formula_panel", {"formula": "CuO + H₂SO₄ → CuSO₄ + H₂O", "note": "Copper sulphate + water"}, "NCERT Activity 2.4 example.", "Blue CuSO₄ solution after reaction.", "Basic oxide + acid → salt + water.", "Same pattern as neutralisation.", "", []),
    ("Calcium oxide and HCl", "CaO + 2HCl → CaCl₂ + H₂O — quick lime reacts with acid.", "formula_panel", {"formula": "CaO + 2HCl → CaCl₂ + H₂O", "note": "Calcium chloride + water"}, "Quick lime is basic oxide.", "Neutralises acid in industrial waste.", "CaO is basic — not amphoteric.", "", "", []),
    ("Magnesium oxide and acid", "MgO + 2HCl → MgCl₂ + H₂O — magnesium oxide neutralises acid.", "formula_panel", {"formula": "MgO + 2HCl → MgCl₂ + H₂O", "note": "From burning Mg — basic ash"}, "Links Ch 1 MgO to Ch 2.", "White MgO ash from Activity 1.1 is basic.", "Metal oxide from burning Mg reacts with acid.", "MgO dissolves in acid — ash is not inert.", "", []),
    ("Iron(III) oxide and acid", "Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O — rust component reacts with acid.", "formula_panel", {"formula": "Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O", "note": "Ferric chloride + water"}, "Rust is basic oxide mixture.", "Acid removes rust from iron — but also attacks iron.", "Metal oxide + acid pattern again.", "Fe₂O₃ is basic oxide of iron.", "", []),
    ("Why metal oxides are basic", "Metal oxides contain O²⁻ that accepts H⁺ from acid — behave like bases.", "placeholder", {"label": "O²⁻ accepts H⁺ from acid"}, "Conceptual reason.", "Na₂O, CaO, CuO all react with acids.", "Basic nature from oxide ion.", "Not all metal oxides — Al₂O₃ is amphoteric (advanced).", "", []),
    ("Basic oxide + acid = neutralisation", "Reaction of basic metal oxide with acid is a type of neutralisation — salt and water formed.", "formula_panel", {"formula": "Basic oxide + Acid → Salt + H₂O", "note": "Same as acid + base"}, "Unify Ch 2 reactions.", "CuO + H₂SO₄ same product pattern as Cu(OH)₂ + H₂SO₄.", "Oxide acts as base.", "No H₂ or CO₂ from oxide + acid.", "", []),
    ("Activity 2.4 — metal oxides", "NCERT Activity 2.4: react copper oxide with dilute H₂SO₄ — blue solution proves basic oxide.", "placeholder", {"label": "Activity 2.4 — CuO + acid"}, "Lab anchor.", "Black solid dissolves → blue CuSO₄.", "Observe colour change of solution.", "Heat may be needed to start CuO reaction.", "", []),
    ("Compare metal oxide vs metal with acid", "Metal + acid → salt + H₂. Metal oxide + acid → salt + H₂O (no gas).", "formula_panel", {"formula": "Metal → H₂ | Metal oxide → H₂O", "note": "Different products"}, "Exam distinction.", "CuO + H₂SO₄ gives no gas; Zn + H₂SO₄ gives H₂.", "Oxide already combined with oxygen.", "No pop test for oxide + acid.", "", []),
    ("Exam — metallic oxides and acids", "State metal oxides are basic → give general equation → CuO + H₂SO₄ example → link to neutralisation.", "placeholder", {"label": "Exam: metal oxide + acid"}, "Answer template.", "Basic oxide + acid → salt + water.", "Three-step structured answer.", "Name salt correctly: CuSO₄ = copper sulphate.", "", []),
])

DAY8 = _build_day(8, [
    ("Non-metallic oxides are acidic", "Oxides of non-metals are generally acidic — dissolve in water to form acids; react with bases.", "formula_panel", {"formula": "Non-metal oxide + Base → Salt + Water", "note": "Acidic oxide"}, "Day 8 theme — mirror of Day 7.", "CO₂ + Ca(OH)₂ → CaCO₃ + H₂O.", "Non-metal oxides = acidic oxides.", "Opposite of basic metal oxides.", "", []),
    ("Carbon dioxide and lime water", "CO₂ + Ca(OH)₂ → CaCO₃ + H₂O — lime water turns milky (also CO₂ test).", "formula_panel", {"formula": "CO₂ + Ca(OH)₂ → CaCO₃ + H₂O", "note": "Milky precipitate"}, "Most important NCERT example.", "Used to test CO₂ from carbonate + acid.", "Acidic oxide reacts with base.", "Same equation as CO₂ test — dual purpose.", "", []),
    ("Carbon dioxide and sodium hydroxide", "CO₂ + 2NaOH → Na₂CO₃ + H₂O — CO₂ absorbed by caustic soda.", "formula_panel", {"formula": "CO₂ + 2NaOH → Na₂CO₃ + H₂O", "note": "Sodium carbonate + water"}, "Industrial gas scrubbing.", "NaOH absorbs CO₂ in labs.", "Acidic oxide + strong base.", "Na₂CO₃ is washing soda family.", "", []),
    ("Sulphur dioxide and NaOH", "SO₂ + 2NaOH → Na₂SO₃ + H₂O — sulphur dioxide is acidic oxide.", "formula_panel", {"formula": "SO₂ + 2NaOH → Na₂SO₃ + H₂O", "note": "Sodium sulphite + water"}, "Air pollution chemistry link.", "SO₂ from burning sulphur-containing fuel.", "Non-metal oxide + base → salt + water.", "SO₂ causes acid rain when dissolved in rain.", "", []),
    ("SO₂ and lime water", "SO₂ + Ca(OH)₂ → CaSO₃ + H₂O — similar to CO₂ but different salt.", "formula_panel", {"formula": "SO₂ + Ca(OH)₂ → CaSO₃ + H₂O", "note": "Calcium sulphite"}, "Parallel to CO₂ reaction.", "Acid rain neutralised by limestone.", "Acidic oxide + Ca(OH)₂ pattern.", "CaSO₃ not milky like CaCO₃ — different test.", "", []),
    ("Acidic oxide + water", "Many non-metal oxides form acids in water: CO₂ → carbonic acid; SO₂ → sulphurous acid.", "formula_panel", {"formula": "CO₂ + H₂O → H₂CO₃", "note": "Acidic oxide forms acid in water"}, "Why they are called acidic oxides.", "Rain dissolves CO₂ — slightly acidic rain.", "Dissolve in water → acid.", "H₂CO₃ is weak acid — carbonated water.", "", []),
    ("Compare metal vs non-metal oxides", "Metal oxides basic (react with acid); non-metal oxides acidic (react with base).", "formula_panel", {"formula": "Metal oxide + Acid | Non-metal oxide + Base", "note": "Opposite behaviour"}, "Key Ch 2 comparison.", "CuO + H₂SO₄ vs CO₂ + Ca(OH)₂.", "Basic vs acidic oxides — opposite partners.", "Amphoteric oxides (Al₂O₃) are exception.", "", []),
    ("Acid rain connection", "SO₂ and NO₂ (non-metal oxides) dissolve in rain forming acids — acid rain damages buildings and plants.", "placeholder", {"label": "Acid rain — non-metal oxides"}, "Environmental application.", "Taj Mahal affected by acid rain.", "Non-metal oxides → acids in atmosphere.", "Limestone neutralises acid rain on statues.", "", []),
    ("Sulphur trioxide and water", "SO₃ + H₂O → H₂SO₄ — sulphur trioxide forms sulphuric acid in water.", "formula_panel", {"formula": "SO₃ + H₂O → H₂SO₄", "note": "Forms sulphuric acid"}, "Strong acid formation from oxide.", "Industrial contact process step.", "Highly acidic oxide in water.", "SO₃ is dangerous — reacts violently with water.", "", []),
    ("Exam — non-metallic oxides and bases", "State non-metal oxides are acidic → CO₂ + Ca(OH)₂ equation → milky test → compare with basic metal oxides.", "placeholder", {"label": "Exam: non-metal oxide + base"}, "Structured answer.", "Mirror answer to Day 7 metal oxides.", "CO₂ + Ca(OH)₂ is must-know equation.", "Identify acidic vs basic oxide from metal/non-metal.", "", []),
])

DAY9 = _build_day(9, [
    ("Common feature — H⁺ in acids", "All acids produce hydrogen ions H⁺ (or hydronium H₃O⁺) in aqueous solution.", "formula_panel", {"formula": "Acid → H⁺ + anion", "note": "H⁺ is common to all acids"}, "Day 9 unifying idea.", "HCl → H⁺ + Cl⁻ in water.", "Acids characterised by H⁺ in water.", "Dry acids (no water) do not show acidic properties.", "", []),
    ("Common feature — OH⁻ in bases", "All bases produce hydroxide ions OH⁻ in aqueous solution (or accept H⁺).", "formula_panel", {"formula": "Base → OH⁻ + cation", "note": "OH⁻ is common to all bases"}, "Pair with H⁺ in acids.", "NaOH → Na⁺ + OH⁻ in water.", "Bases characterised by OH⁻ in water.", "NH₃ + H₂O ⇌ NH₄⁺ + OH⁻ — ammonia accepts H⁺ from water.", "", []),
    ("Acids need water to show acidity", "Dry HCl gas does not turn blue litmus red — water needed to ionise and produce H⁺.", "placeholder", {"label": "Water needed for acid properties"}, "Critical NCERT point.", "HCl gas over dry litmus — no change.", "No water → no H⁺ → no acid behaviour.", "Acidic properties in aqueous solution only.", "", []),
    ("Bases need water for alkalinity", "NaOH solid must dissolve in water to produce OH⁻ and show basic properties.", "placeholder", {"label": "Water needed for base properties"}, "Symmetric to acids.", "NaOH pellets in water → red litmus blue.", "Dissolve in water → OH⁻ ions.", "Dry base may not affect dry litmus.", "", []),
    ("Hydronium ion H₃O⁺", "In water, H⁺ attaches to H₂O forming hydronium ion H₃O⁺ — actual species in solution.", "formula_panel", {"formula": "H⁺ + H₂O → H₃O⁺", "note": "Hydronium ion"}, "More accurate than free H⁺.", "HCl + H₂O → H₃O⁺ + Cl⁻.", "H₃O⁺ is H⁺ in aqueous acid.", "Textbook often writes H⁺ for simplicity.", "", []),
    ("Ionisation of acids", "Strong acids ionise completely; weak acids partially in water.", "formula_panel", {"formula": "HCl → H⁺ + Cl⁻ (complete)", "note": "CH₃COOH ⇌ H⁺ + CH₃COO⁻ (partial)"}, "Strength vs ionisation.", "Conductivity test: strong acid conducts better.", "More H⁺ = stronger conductivity.", "Ionisation degree differs; both produce H⁺.", "", []),
    ("Ionisation of bases", "Strong bases (NaOH, KOH) ionise completely; weak bases (NH₄OH) partially.", "formula_panel", {"formula": "NaOH → Na⁺ + OH⁻ (complete)", "note": "NH₄OH ⇌ NH₄⁺ + OH⁻ (partial)"}, "Parallel to acids.", "Ca(OH)₂ sparingly soluble — limited OH⁻.", "More OH⁻ = stronger base in water.", "Insoluble bases release few OH⁻ ions.", "", []),
    ("Electrical conductivity", "Acid and base solutions conduct electricity due to ions H⁺/OH⁻ — electrolytes.", "placeholder", {"label": "Ions conduct electricity"}, "Lab observation link.", "Bulb glows in HCl and NaOH solutions.", "Ions carry charge → conductivity.", "Pure water has very few ions — poor conductor.", "", []),
    ("What acids and bases have in common — summary", "Both are electrolytes in water; acids give H⁺, bases give OH⁻; both react to neutralise each other.", "formula_panel", {"formula": "Acid: H⁺ | Base: OH⁻ | Together: H₂O", "note": "Unifying Ch 2 idea"}, "Day 9 synthesis.", "H⁺ + OH⁻ → H₂O in every neutralisation.", "Ions in water explain all Ch 2 behaviour.", "Dry state ≠ aqueous behaviour.", "", []),
    ("Exam — common features", "Explain acids produce H⁺ and bases OH⁻ in water; water required; give HCl and NaOH examples.", "placeholder", {"label": "Exam: H⁺ and OH⁻ common features"}, "Answer template.", "Dry HCl no effect on litmus — key point.", "State need for water + ion equations.", "Distinguish strength from presence of H⁺.", "", []),
])

DAY10 = _build_day(10, [
    ("Acids in water — ion formation", "When acid dissolves in water, it releases H⁺ ions — responsible for all acidic properties.", "formula_panel", {"formula": "HA + H₂O → H₃O⁺ + A⁻", "note": "Acid ionisation in water"}, "Day 10 focus.", "H₂SO₄ → 2H⁺ + SO₄²⁻ in water.", "Water enables acid ionisation.", "Without water, no ionisation.", "", []),
    ("Bases in water — OH⁻ formation", "When base dissolves in water, it releases OH⁻ ions — responsible for basic properties.", "formula_panel", {"formula": "BOH → B⁺ + OH⁻", "note": "Base ionisation in water"}, "Pair concept.", "KOH → K⁺ + OH⁻.", "OH⁻ causes red litmus → blue.", "NH₃ uses water to produce OH⁻ indirectly.", "", []),
    ("Dilution of acids", "Dilution means adding water to make acid less concentrated — always add acid to water, never reverse.", "formula_panel", {"formula": "Add acid to water slowly", "note": "Never water to conc. acid"}, "Critical safety rule.", "Conc. H₂SO₄ + water safely: acid poured into water.", "Acid to water — with stirring.", "Water to conc. acid causes violent splashing — burns.", "", []),
    ("Why add acid to water", "Dilution is exothermic; adding acid to large volume of water absorbs heat safely.", "placeholder", {"label": "Heat released on dilution"}, "Safety explanation.", "Conc. H₂SO₄ dilution can boil and spatter.", "Large water volume spreads heat.", "Always use glass rod stirring while adding acid.", "", []),
    ("Concentrated vs dilute acid", "Concentrated = more acid particles per volume; dilute = more water — both can be strong acids.", "formula_panel", {"formula": "Concentrated ≠ Strong", "note": "Two different ideas"}, "Common confusion resolved.", "Conc. HCl and dilute HCl both strong — differ in concentration.", "Concentration ≠ strength.", "Strength = ionisation; concentration = amount dissolved.", "", []),
    ("Dilution and ion concentration", "Diluting acid reduces H⁺ concentration per unit volume — less corrosive but still acidic.", "placeholder", {"label": "Dilution lowers H⁺ concentration"}, "Quantitative idea without formulae.", "Dilute HCl safer for lab metal reactions.", "More water → fewer H⁺ per mL.", "Dilute acid still turns blue litmus red.", "", []),
    ("Strong acid dilution", "Even dilute strong acid fully ionised — every molecule gives H⁺, just fewer molecules present.", "formula_panel", {"formula": "Dilute HCl: still H⁺ + Cl⁻ fully", "note": "Strength unchanged by dilution"}, "Clarify strength vs dilution.", "0.1 M HCl still strong acid.", "Dilution changes concentration not strength.", "Weak acid stays weak when diluted.", "", []),
    ("Indicators and dilution", "Dilute acid still turns blue litmus red — indicator detects H⁺ presence not concentration alone.", "placeholder", {"label": "Dilute acid still acidic"}, "Observation link.", "Very dilute HCl still red litmus.", "Any H⁺ present → acidic to indicator.", "Universal indicator colour may shift with concentration.", "", []),
    ("Preparing dilute HCl in lab", "Add concentrated HCl slowly to water in beaker, stir with glass rod, wear goggles and lab coat.", "placeholder", {"label": "Lab: prepare dilute acid"}, "Practical procedure.", "Small volume acid into large volume water.", "Follow acid-to-water rule always.", "Work in fume cupboard for volatile acids.", "", []),
    ("Exam — dilution and ions", "Explain H⁺/OH⁻ in water; dilution definition; acid-to-water rule; distinguish concentration from strength.", "placeholder", {"label": "Exam: dilution and ions"}, "Combined Day 9–10 answer.", "Never add water to conc. H₂SO₄ — safety mark.", "Four concepts in one long answer.", "Include exothermic dilution note.", "", []),
])

DAY11 = _build_day(11, [
    ("pH scale definition", "pH scale measures acidity or alkalinity from 0 to 14 — pH 7 neutral, below 7 acid, above 7 base.", "formula_panel", {"formula": "pH 0–14 | 7 = neutral", "note": "pH scale"}, "Central Day 11 concept.", "Pure water pH 7 at 25°C.", "Lower pH = more acidic; higher = more basic.", "pH is logarithmic scale — each unit is 10× change.", "", ["pH"]),
    ("pH of acids", "Acids have pH less than 7 — stronger acids have lower pH (closer to 0).", "formula_panel", {"formula": "Acid: pH < 7", "note": "Stronger acid → lower pH"}, "Apply scale to acids.", "Stomach acid pH ~1–2.", "pH 0–6 = acidic range.", "Do not say pH 0 for all strong acids in school lab.", "", []),
    ("pH of bases", "Bases have pH greater than 7 — stronger bases have higher pH (closer to 14).", "formula_panel", {"formula": "Base: pH > 7", "note": "Stronger base → higher pH"}, "Apply scale to bases.", "NaOH solution pH ~14.", "pH 8–14 = basic range.", "Mild bases pH 8–10; strong bases 12–14.", "", []),
    ("Universal indicator", "Universal indicator is mixture showing different colours across pH 0–14 — full spectrum.", "placeholder", {"label": "Universal indicator — full pH"}, "NCERT pH measurement tool.", "Green at pH 7; red in strong acid; purple in strong base.", "One indicator for entire pH range.", "Different from litmus which is red/blue only.", "", ["universal indicator"]),
    ("pH paper", "pH paper dipped in solution gives colour matched to chart for approximate pH value.", "placeholder", {"label": "pH paper and colour chart"}, "Practical measurement.", "Compare wet paper colour to standard chart.", "Quick field pH test.", "Less precise than pH meter.", "", []),
    ("Strength vs pH", "Stronger acid has lower pH at same concentration; stronger base has higher pH.", "formula_panel", {"formula": "Strong HCl pH < weak CH₃COOH pH", "note": "Same concentration compared"}, "Link strength to pH.", "0.1 M HCl pH ~1; 0.1 M CH₃COOH pH ~3.", "More H⁺ ionisation → lower pH.", "Concentration also affects pH — control variables.", "", []),
    ("Neutral pH 7", "pH 7 is neutral — equal H⁺ and OH⁻; pure water and salt solutions may be neutral.", "formula_panel", {"formula": "pH 7 = [H⁺] = [OH⁻]", "note": "Neutral solution"}, "Reference point on scale.", "Distilled water pH 7 (at 25°C).", "Not acidic, not basic.", "Rain water pH slightly below 7 due to dissolved CO₂.", "", []),
    ("pH and H⁺ concentration", "Lower pH means higher H⁺ concentration — pH measures hydrogen ion concentration.", "formula_panel", {"formula": "More H⁺ → lower pH", "note": "Inverse relationship"}, "Conceptual link.", "pH 3 has more H⁺ than pH 5.", "pH tells how acidic quantitatively.", "Formula pH = -log[H⁺] — beyond Class 10 scope.", "", []),
    ("Mixing acid and base — pH change", "Adding base to acid raises pH toward 7; adding acid to base lowers pH toward 7.", "placeholder", {"label": "Neutralisation shifts pH to 7"}, "Titration pH idea.", "Excess NaOH added to HCl → pH rises above 7.", "Neutralisation moves pH toward 7.", "At exact equivalence, strong acid + strong base → pH 7.", "", []),
    ("Exam — pH scale", "Define pH scale 0–14; pH 7 neutral; universal indicator; compare strong vs weak acid pH.", "placeholder", {"label": "Exam: pH scale template"}, "Answer structure.", "Include stomach pH ~2 as example.", "Definition + scale + indicator + example.", "State acid < 7, base > 7 clearly.", "", []),
])

DAY12 = _build_day(12, [
    ("pH in soil", "Plants need specific soil pH; acidic soil treated with lime Ca(OH)₂; basic soil with organic matter.", "placeholder", {"label": "Soil pH for crops"}, "NCERT everyday application.", "Tea coffee grow in acidic soil; cabbage in neutral.", "Farmer adjusts soil pH for crop.", "Litmus can test soil solution pH roughly.", "", []),
    ("pH in stomach", "Stomach produces HCl pH ~1–2 for digestion; excess acid causes indigestion — treated with antacids.", "formula_panel", {"formula": "Stomach pH ~1–2 (HCl)", "note": "Antacid raises pH"}, "Health application.", "Mg(OH)₂ or NaHCO₃ neutralises excess acid.", "Mild base antacid relieves pain.", "Antacid does not stop normal digestion permanently.", "", []),
    ("pH in mouth", "Tooth decay starts when mouth pH drops below 5.5 — bacteria produce acids from food.", "formula_panel", {"formula": "Tooth enamel decays below pH 5.5", "note": "Brush to neutralise acids"}, "Dental health link.", "Sugary food → acid → cavity.", "Keep mouth pH above 5.5.", "Toothpaste is basic — neutralises mouth acid.", "", []),
    ("Bee sting vs wasp sting", "Bee sting acidic (formic acid) — treat with baking soda (base); wasp sting basic — treat with vinegar (acid).", "formula_panel", {"formula": "Bee: acid → base | Wasp: base → acid", "note": "Opposite treatments"}, "Classic NCERT comparison.", "Baking soda paste on bee sting.", "Neutralise opposite to sting type.", "Both stings painful — wrong treatment won't help.", "", []),
    ("Self-defence by animals", "Ants and bees inject acid; stingray and many insects inject base — neutralisation explains treatment.", "placeholder", {"label": "Animal stings — acid or base"}, "Biology-chemistry link.", "Nettle hair injects methanoic acid — dock leaf base relieves.", "Know sting type → choose acid or base remedy.", "Not all insect bites are acid — identify first.", "", []),
    ("pH of river water", "Living organisms sensitive to pH; factory waste can change river pH and kill fish.", "placeholder", {"label": "River pH and pollution"}, "Environmental application.", "Acidic factory effluent lowers river pH.", "Monitor pH to protect aquatic life.", "Neutralise waste before discharge.", "", []),
    ("pH in food preservation", "pH affects bacteria growth; acidic foods (pickles, citrus) preserve better.", "placeholder", {"label": "Acidic pH preserves food"}, "Food science link.", "Pickle in vinegar — low pH prevents spoilage.", "Low pH inhibits bacterial growth.", "Not all preservation is pH alone — also salt and sugar.", "", []),
    ("Hydrangea flower colour", "NCERT mentions soil pH affects flower colour — acidic soil blue flowers, basic soil pink.", "placeholder", {"label": "Soil pH changes flower colour"}, "Interesting NCERT example.", "Gardeners adjust soil pH for colour.", "pH affects plant pigment availability.", "Memorable exam example.", "", []),
    ("Measuring pH at home", "Litmus, turmeric, universal indicator paper can estimate pH of soil, water, and food samples.", "placeholder", {"label": "Home pH testing"}, "Practical citizen science.", "Turmeric on soap — red-brown confirms base.", "Simple indicators for everyday checks.", "pH meter most accurate — not home usual.", "", []),
    ("Exam — pH in everyday life", "Give three examples: soil pH + lime, stomach + antacid, bee/wasp sting + treatment; explain each.", "placeholder", {"label": "Exam: everyday pH examples"}, "5-mark application question.", "Three NCERT examples minimum for full marks.", "Each example: situation + pH + remedy.", "Bee vs wasp opposite treatment — favourite exam trap.", "", []),
])

DAY13 = _build_day(13, [
    ("What is a salt?", "Salt is ionic compound formed from acid-base reaction, named by cation + anion — NaCl, ZnSO₄, CuSO₄.", "formula_panel", {"formula": "Salt = Cation + Anion", "note": "e.g. Na⁺Cl⁻"}, "Day 13 introduction.", "NaCl from HCl + NaOH.", "Positive + negative ion combined.", "Salts can be acidic, basic, or neutral — Day 14.", "", ["salt"]),
    ("Family of salts — NaCl", "Sodium chloride NaCl from HCl + NaOH — table salt, essential for life and industry.", "formula_panel", {"formula": "HCl + NaOH → NaCl + H₂O", "note": "Common salt"}, "Start of salt family.", "Preservation and seasoning.", "Chloride from HCl; sodium from NaOH.", "NaCl source for chlor-alkali industry — Day 15.", "", []),
    ("Zinc sulphate ZnSO₄", "ZnSO₄ from H₂SO₄ + Zn or ZnO + H₂SO₄ — white crystals used in medicine and agriculture.", "formula_panel", {"formula": "Zn + H₂SO₄ → ZnSO₄ + H₂", "note": "Or ZnO + H₂SO₄ → ZnSO₄ + H₂O"}, "Salt from sulphuric acid family.", "Zinc sulphate eye drops.", "Sulphate from H₂SO₄.", "Same salt from metal or basic oxide route.", "", []),
    ("Copper sulphate CuSO₄", "CuSO₄·5H₂O is blue vitriol — from CuO + H₂SO₄; used in agriculture and electroplating.", "formula_panel", {"formula": "CuO + H₂SO₄ → CuSO₄ + H₂O", "note": "Blue crystals"}, "Distinctive blue salt.", "Fungicide in farming.", "Copper sulphate — sulphate family.", "Water of crystallisation — Day 16.", "", []),
    ("Sodium sulphate Na₂SO₄", "Na₂SO₄ from H₂SO₄ + Na₂CO₃ or NaOH — white solid, detergent industry.", "formula_panel", {"formula": "H₂SO₄ + Na₂CO₃ → Na₂SO₄ + H₂O + CO₂", "note": "Sodium sulphate"}, "Sulphate salt example.", "By-product of chemical industry.", "Sulphate from sulphuric acid.", "Different from sodium sulphite Na₂SO₃.", "", []),
    ("Calcium chloride CaCl₂", "CaCl₂ from HCl + CaCO₃ or CaO + HCl — de-icing roads, drying agent.", "formula_panel", {"formula": "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂", "note": "Calcium chloride"}, "Chloride family salt.", "Hygroscopic — absorbs moisture.", "Chloride from hydrochloric acid.", "Used to melt ice on roads.", "", []),
    ("Potassium nitrate KNO₃", "KNO₃ from HNO₃ + KOH — fertiliser and gunpowder component.", "formula_panel", {"formula": "HNO₃ + KOH → KNO₃ + H₂O", "note": "Potassium nitrate"}, "Nitrate family salt.", "Nitrate fertiliser for plants.", "Nitrate from nitric acid.", "Also called saltpetre historically.", "", []),
    ("Naming salts", "Salt name: metal/non-metal cation + acid radical — chloride, sulphate, nitrate, acetate.", "formula_panel", {"formula": "HCl → chloride | H₂SO₄ → sulphate | HNO₃ → nitrate", "note": "Acid determines anion name"}, "Naming rule.", "CuSO₄ = copper sulphate.", "Cation first, then anion.", "Use -ate for acids with -ic (sulphuric → sulphate).", "", []),
    ("Salts from different acids", "Same metal gives different salts with different acids: Zn + HCl → ZnCl₂; Zn + H₂SO₄ → ZnSO₄.", "placeholder", {"label": "Same metal, different salts"}, "Compare salt family.", "Acid anion determines salt type.", "Metal cation same; anion changes.", "Exam: write two salts of zinc with two acids.", "", []),
    ("Exam — salts introduction", "Define salt → formation from neutralisation → name three salts with equations → family from HCl, H₂SO₄, HNO₃.", "placeholder", {"label": "Exam: salts introduction"}, "Long-answer template.", "NaCl, ZnSO₄, CuSO₄ as examples.", "Definition + formation + examples.", "Include balanced equations.", "", []),
])

DAY14 = _build_day(14, [
    ("pH of salt solutions — overview", "Salt solutions can be neutral, acidic, or basic depending on strength of acid and base that formed them.", "formula_panel", {"formula": "Strong acid + Strong base → Neutral salt", "note": "pH ≈ 7"}, "Day 14 core idea.", "NaCl solution pH 7.", "Parent acid and base strength matters.", "Not all salts are neutral.", "", []),
    ("Strong acid + strong base salt", "Salts from strong acid and strong base are neutral — pH 7 — e.g. NaCl, KNO₃.", "formula_panel", {"formula": "HCl + NaOH → NaCl (pH 7)", "note": "Neutral salt solution"}, "First combination.", "NaCl aqueous — no excess H⁺ or OH⁻.", "Neither ion hydrolyses significantly.", "K₂SO₄ from H₂SO₄ + KOH also neutral.", "", []),
    ("Strong acid + weak base salt", "Salts from strong acid and weak base are acidic — pH below 7 — e.g. NH₄Cl.", "formula_panel", {"formula": "HCl + NH₄OH → NH₄Cl (pH < 7)", "note": "Acidic salt solution"}, "Second combination.", "NH₄Cl solution turns blue litmus red slightly.", "NH₄⁺ ion causes acidity in water.", "Ammonium salts are acidic.", "", []),
    ("Weak acid + strong base salt", "Salts from weak acid and strong base are basic — pH above 7 — e.g. CH₃COONa.", "formula_panel", {"formula": "CH₃COOH + NaOH → CH₃COONa (pH > 7)", "note": "Basic salt solution"}, "Third combination.", "Sodium acetate — basic solution.", "CH₃COO⁻ ion causes basicity in water.", "Acetate salts are basic.", "", []),
    ("Weak acid + weak base salt", "Salts from weak acid and weak base — pH depends on relative strength — near 7 often.", "formula_panel", {"formula": "CH₃COOH + NH₄OH → CH₃COONH₄", "note": "pH near 7 (both weak)"}, "Fourth combination.", "Ammonium acetate — approximately neutral.", "Both ions hydrolyse — pH near 7.", "Less emphasis in Class 10 exams.", "", []),
    ("Testing salt solution pH", "Use universal indicator or pH paper on salt solution — compare to pH 7 reference.", "placeholder", {"label": "Test salt with pH paper"}, "Practical verification.", "NaCl green (7); NH₄Cl orange-red (<7).", "Indicator shows acidic/basic/neutral salt.", "Must dissolve salt in water first.", "", []),
    ("Sodium chloride — neutral", "NaCl from HCl + NaOH — strong acid + strong base — aqueous solution pH 7.", "formula_panel", {"formula": "NaCl(aq) pH = 7", "note": "Neutral salt"}, "Most common neutral example.", "Table salt solution neither acidic nor basic.", "Gold standard neutral salt.", "Ions Na⁺ and Cl⁻ do not affect pH.", "", []),
    ("Ammonium chloride — acidic", "NH₄Cl from HCl + NH₄OH — strong acid + weak base — solution pH below 7.", "formula_panel", {"formula": "NH₄Cl(aq) pH < 7", "note": "Acidic salt"}, "Most common acidic salt example.", "Used in cough medicine and batteries.", "NH₄⁺ from weak base parent causes acidity.", "Do not confuse with NH₄OH which is base.", "", []),
    ("Sodium carbonate — basic", "Na₂CO₃ (washing soda) — basic salt — pH above 7; used for cleaning.", "formula_panel", {"formula": "Na₂CO₃(aq) pH > 7", "note": "Basic salt"}, "Common basic salt — from weak acid CO₂/H₂CO₃.", "Washing soda cleans grease in basic medium.", "Carbonate ion CO₃²⁻ makes solution basic.", "Na₂CO₃ not from single neutralisation — from NaOH + CO₂.", "", []),
    ("Exam — pH of salts", "Four combinations table: strong+strong neutral, strong acid+weak base acidic, weak acid+strong base basic; give examples.", "placeholder", {"label": "Exam: salt pH table"}, "Table-format answer scores well.", "NaCl, NH₄Cl, CH₃COONa as three examples.", "Memorise four combinations + one example each.", "Parent weakness determines salt pH.", "", []),
])

DAY15 = _build_day(15, [
    ("Common salt NaCl — industry source", "NaCl (common salt) is raw material for chlor-alkali industry — produces NaOH, Cl₂, H₂.", "formula_panel", {"formula": "2NaCl + 2H₂O → 2NaOH + Cl₂ + H₂", "note": "Chlor-alkali process (electrolysis)"}, "Day 15 industrial theme.", "Brine electrolysis in factories.", "Salt + water → three valuable products.", "Electrolysis of aqueous NaCl (brine).", "", []),
    ("Sodium hydroxide from chlor-alkali", "NaOH (caustic soda) from chlor-alkali — used in soap, paper, textiles, and drain cleaners.", "formula_panel", {"formula": "NaOH — caustic soda", "note": "From NaCl electrolysis"}, "First chlor-alkali product.", "White pellets absorb moisture from air.", "Major industrial alkali.", "Handle with care — corrosive.", "", []),
    ("Chlorine from chlor-alkali", "Cl₂ from chlor-alkali — used in water purification, PVC, bleaches, and disinfectants.", "formula_panel", {"formula": "Cl₂ — greenish gas", "note": "Water treatment"}, "Second product.", "Municipal water chlorination kills bacteria.", "Greenish-yellow gas — poisonous.", "Never mix bleach with acid — toxic Cl₂.", "", []),
    ("Hydrogen from chlor-alkali", "H₂ from chlor-alkali — used as fuel, in margarine hardening, and ammonia manufacture.", "formula_panel", {"formula": "H₂ — by-product of brine electrolysis", "note": "Clean fuel potential"}, "Third product.", "H₂ collected at cathode during electrolysis.", "Valuable fuel gas.", "Pop test applies to this H₂ too.", "", []),
    ("Bleaching powder Ca(OCl)₂", "Bleaching powder calcium oxychloride Ca(OCl)₂ — from Cl₂ + slaked lime; bleaches cotton and disinfects water.", "formula_panel", {"formula": "Ca(OCl)₂ — bleaching powder", "note": "Cl₂ + Ca(OH)₂ → bleaching powder"}, "NCERT must-know chemical.", "Used to bleach cotton in textile industry.", "Chlorine content gives bleaching power.", "Store away from acids — releases Cl₂.", "", []),
    ("Baking soda NaHCO₃", "Sodium hydrogencarbonate NaHCO₃ — baking soda; reacts with acid to release CO₂; antacid; fire extinguisher.", "formula_panel", {"formula": "NaHCO₃ + H⁺ → Na⁺ + H₂O + CO₂", "note": "Baking soda"}, "Everyday chemical from salt industry.", "Cakes rise from CO₂ in oven heat + acid.", "Mild base — neutralises stomach acid.", "Heating alone also decomposes: NaHCO₃ → Na₂CO₃ + H₂O + CO₂.", "", []),
    ("Washing soda Na₂CO₃·10H₂O", "Sodium carbonate decahydrate Na₂CO₃·10H₂O — washing soda; cleaning agent; removes hardness.", "formula_panel", {"formula": "Na₂CO₃·10H₂O — washing soda", "note": "10 water molecules of crystallisation"}, "Links to Day 16 water of crystallisation.", "Cleans greasy clothes in basic solution.", "Basic salt — pH > 7 in solution.", "Anhydrous Na₂CO₃ vs decahydrate — 10 H₂O.", "", []),
    ("Plaster of Paris CaSO₄·½H₂O", "Calcium sulphate hemihydrate CaSO₄·½H₂O — plaster of Paris; sets with water to gypsum.", "formula_panel", {"formula": "CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O", "note": "Plaster of Paris → gypsum"}, "Medical casts and construction.", "Broken bone cast hardens as gypsum.", "Heat gypsum to get plaster of Paris.", "Setting is hydration back to gypsum.", "", []),
    ("Gypsum CaSO₄·2H₂O", "Gypsum CaSO₄·2H₂O — calcium sulphate dihydrate; heated to make plaster of Paris.", "formula_panel", {"formula": "CaSO₄·2H₂O — gypsum", "note": "Heat → CaSO₄·½H₂O (POP)"}, "Pair with plaster of Paris.", "Gypsum board in buildings.", "Dihydrate form stable at room temperature.", "POP + water → gypsum (setting reaction).", "", []),
    ("Exam — chemicals from common salt", "Chlor-alkali products (NaOH, Cl₂, H₂) + bleaching powder + baking soda + washing soda + gypsum/POP with uses.", "placeholder", {"label": "Exam: chemicals from NaCl"}, "5-mark industrial chemistry question.", "List each chemical + one use minimum.", "Start from NaCl brine electrolysis.", "Include equations where asked.", "", []),
])

DAY16 = _build_day(16, [
    ("Water of crystallisation definition", "Fixed number of water molecules attached in crystal structure of some salts — e.g. CuSO₄·5H₂O.", "formula_panel", {"formula": "CuSO₄·5H₂O", "note": "5 H₂O per formula unit"}, "Day 16 core concept.", "Water part of crystal lattice.", "Dot formula shows water of crystallisation.", "Different from wet salt — water is chemically bound.", "", ["water of crystallisation"]),
    ("Copper sulphate pentahydrate", "CuSO₄·5H₂O — blue vitriol — blue crystals due to water of crystallisation.", "formula_panel", {"formula": "CuSO₄·5H₂O — blue", "note": "5 water molecules"}, "Classic NCERT example.", "Blue crystals in lab reagent bottle.", "Five H₂O per CuSO₄ unit.", "Anhydrous CuSO₄ is white — not blue.", "", []),
    ("Heating blue copper sulphate", "Heat CuSO₄·5H₂O → white anhydrous CuSO₄ + water droplets on cool tube wall.", "formula_panel", {"formula": "CuSO₄·5H₂O → CuSO₄ + 5H₂O", "note": "Heat removes water"}, "NCERT Activity — test for water.", "Colour change blue → white on heating.", "Water driven off by heat.", "Reversible — add water, turns blue again.", "", []),
    ("Anhydrous copper sulphate test for water", "White anhydrous CuSO₄ turns blue on adding water — used to test for presence of water.", "placeholder", {"label": "Anhydrous CuSO₄ — water test"}, "Qualitative test for water.", "Drop water on white powder — turns blue.", "Blue again = water present.", "Used as desiccant to absorb water vapour.", "", []),
    ("Dry crystals vs hydrated crystals", "Dry crystals may still contain water of crystallisation — 'dry' means no free liquid water on surface.", "placeholder", {"label": "Dry ≠ anhydrous"}, "Common confusion resolved.", "Blue CuSO₄ crystals feel dry but contain 5H₂O.", "Water of crystallisation is inside crystal.", "Anhydrous = no water in formula at all.", "", []),
    ("Glauber's salt Na₂SO₄·10H₂O", "Sodium sulphate decahydrate Na₂SO₄·10H₂O — loses water on heating; used in medicine historically.", "formula_panel", {"formula": "Na₂SO₄·10H₂O", "note": "10 H₂O — Glauber's salt"}, "Second NCERT hydrated salt.", "Large transparent crystals.", "Ten water molecules per unit.", "Related to washing soda hydrate.", "", []),
    ("Washing soda and water of crystallisation", "Na₂CO₃·10H₂O — washing soda — 10 water molecules; effloresces in dry air.", "formula_panel", {"formula": "Na₂CO₃·10H₂O", "note": "Washing soda decahydrate"}, "Links Day 15 and Day 16.", "Powdery white when water lost to air.", "Efflorescence = losing surface water.", "Anhydrous Na₂CO₃ more soluble handling in industry.", "", []),
    ("Efflorescence", "Some hydrated salts lose water of crystallisation on exposure to dry air — powdery surface forms.", "placeholder", {"label": "Efflorescence — loses water to air"}, "Property of hydrated salts.", "Washing soda left open becomes powdery.", "Water escapes to atmosphere.", "Opposite of hygroscopic (absorbs water).", "", []),
    ("Gypsum and plaster water of crystallisation", "Gypsum CaSO₄·2H₂O has 2 H₂O; plaster CaSO₄·½H₂O has half H₂O — interconvert on heat/hydrate.", "formula_panel", {"formula": "Gypsum: 2H₂O | POP: ½H₂O", "note": "Heat and hydrate cycle"}, "Industrial crystallisation example.", "POP sets by rejoining water as gypsum.", "Different hydration levels same salt.", "Heating gypsum drives off 1.5 H₂O to make POP.", "", []),
    ("Unit 2 complete", "Unit 2 Acids, Bases and Salts complete — all 160 cards; proceed to Practice when unlocked.", "placeholder", {"label": "Unit 2 complete — 160 cards"}, "Completion card.", "200 MCQs in bank when available.", "Concepts done → practice.", "Review pH, neutralisation, and industrial chemicals.", "", []),
])

DAY_BUILDERS = {
    1: lambda: DAY1,
    2: lambda: DAY2,
    3: lambda: DAY3,
    4: lambda: DAY4,
    5: lambda: DAY5,
    6: lambda: DAY6,
    7: lambda: DAY7,
    8: lambda: DAY8,
    9: lambda: DAY9,
    10: lambda: DAY10,
    11: lambda: DAY11,
    12: lambda: DAY12,
    13: lambda: DAY13,
    14: lambda: DAY14,
    15: lambda: DAY15,
    16: lambda: DAY16,
}

DAY_TITLES = {
    1: "Acids, Bases and Salts — Introduction",
    2: "Indicators — Litmus, Turmeric and Synthetic",
    3: "Acids and Bases in the Laboratory (Activity 2.1)",
    4: "Acids React with Metals",
    5: "Acids with Carbonates and Hydrogencarbonates",
    6: "Neutralisation Reactions",
    7: "Metallic Oxides and Acids",
    8: "Non-metallic Oxides and Bases",
    9: "What Acids and Bases Have in Common",
    10: "Acids and Bases in Water — Ions and Dilution",
    11: "pH Scale and Strength of Acids/Bases",
    12: "Importance of pH in Everyday Life",
    13: "Salts — Introduction and Family of Salts",
    14: "pH of Salts",
    15: "Chemicals from Common Salt",
    16: "Water of Crystallisation and Dry Crystals",
}
