"""Full concept card content for Harshit Physics Unit 2 — Days 1–16 (Ch 10)."""

from __future__ import annotations


def _card(
    cid: str,
    name: str,
    simple: str,
    visual_type: str,
    visual_config: dict | None,
    why: str,
    example: str,
    remember: str,
    confusion: str = "",
    optional: str = "",
    glossary: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "name": name,
        "simple_answer": simple,
        "visual": {"type": visual_type, **(visual_config or {})},
        "why": why,
        "example": example,
        "remember": remember,
        "common_confusion": confusion,
        "optional_detail": optional,
        "glossary_terms": glossary or [],
    }


def _build_day(day: int, cards: list[tuple]) -> list[dict]:
    out = []
    for i, row in enumerate(cards, 1):
        name, simple, vtype, vcfg, why, ex, rem, *rest = row
        confusion = rest[0] if len(rest) > 0 else ""
        optional = rest[1] if len(rest) > 1 else ""
        gloss = rest[2] if len(rest) > 2 else []
        out.append(
            _card(
                f"u2_d{day}_c{i:02d}",
                name,
                simple,
                vtype,
                vcfg if isinstance(vcfg, dict) else {},
                why,
                ex,
                rem,
                confusion,
                optional,
                gloss if isinstance(gloss, list) else [],
            )
        )
    return out


DAY1 = _build_day(
    1,
    [
        (
            "Human eye as a sense organ",
            "The human eye is one of the most valuable sense organs. It uses light to show us the colourful world around us.",
            "eye_structure",
            {"highlight": "overview"},
            "Among all senses, sight gives the richest picture of our surroundings.",
            "Close your eyes — you can guess objects by touch or sound, but not their colours.",
            "The eye needs light to see colours and shapes.",
            "The eye does not produce light — it receives it.",
            "",
            ["human eye"],
        ),
        (
            "Eye like a camera",
            "The eye is like a camera: its lens system forms an image on a light-sensitive screen called the retina.",
            "eye_structure",
            {"highlight": "camera_analogy"},
            "The camera analogy helps link Ch 9 lenses to how we see.",
            "A camera lens focuses light onto a sensor; the eye lens focuses onto the retina.",
            "Lens + light-sensitive screen = basic eye model.",
            "The brain, not the eye alone, gives final meaning to the image.",
            "",
            ["retina"],
        ),
        (
            "Cornea — front window",
            "Light enters the eye through the cornea — a thin transparent membrane forming the front bulge of the eyeball.",
            "eye_structure",
            {"highlight": "cornea"},
            "Most refraction of incoming light happens at the cornea's outer surface.",
            "The cornea is the clear front part you see in the mirror.",
            "Cornea = first refracting surface; most bending happens here.",
            "Do not confuse cornea with the crystalline lens deeper inside.",
            "",
            ["cornea"],
        ),
        (
            "Eyeball size",
            "The eyeball is roughly spherical with a diameter of about 2.3 cm.",
            "eye_structure",
            {"highlight": "eyeball"},
            "Scale helps you draw NCERT-style eye diagrams proportionally.",
            "Model eyes in textbooks are drawn about 2–2.5 cm wide.",
            "Eyeball ≈ 2.3 cm diameter.",
            "",
            "",
            [],
        ),
        (
            "Iris and pupil",
            "Behind the cornea lies the iris — a dark muscular diaphragm that controls pupil size and regulates light entering the eye.",
            "eye_structure",
            {"highlight": "iris_pupil"},
            "Too much light can strain the retina; the pupil adjusts the beam.",
            "In bright sun your pupil shrinks; in dim light it widens.",
            "Iris controls pupil size → controls light amount.",
            "The pupil is the opening, not the coloured iris ring itself.",
            "",
            ["iris", "pupil"],
        ),
        (
            "Crystalline lens",
            "The eye lens is crystalline and jelly-like. It gives finer focal adjustment so objects at different distances focus on the retina.",
            "eye_structure",
            {"highlight": "lens"},
            "The lens fine-tunes focus after the cornea does most refraction.",
            "Reading a book vs looking at a distant tree — lens shape changes slightly.",
            "Eye lens = fine focus adjustment.",
            "Eye lens is not the same as spectacle lenses outside the eye.",
            "",
            ["eye lens"],
        ),
        (
            "Inverted image on retina",
            "The eye lens forms an inverted real image of the object on the retina.",
            "eye_structure",
            {"highlight": "inverted_image"},
            "Real inverted images are normal for converging lens systems.",
            "Like a camera, the retinal image is upside down.",
            "Retinal image is inverted; brain uprights it.",
            "Inverted on retina does not mean we see the world upside down.",
            "",
            ["inverted image"],
        ),
        (
            "Retina and light-sensitive cells",
            "The retina is a delicate membrane with enormous numbers of light-sensitive cells that activate when illuminated.",
            "eye_structure",
            {"highlight": "retina"},
            "These cells convert light into signals the brain can read.",
            "Damage to retina can cause partial or complete vision loss.",
            "Retina = screen + sensors.",
            "",
            "",
            ["retina"],
        ),
        (
            "Optic nerve and brain",
            "Activated retinal cells generate electrical signals sent to the brain via the optic nerve. The brain interprets them so we perceive objects correctly.",
            "eye_structure",
            {"highlight": "optic_nerve"},
            "Seeing is a brain process built on eye signals.",
            "Blind spot tests show the brain fills gaps in vision.",
            "Eye collects light; brain creates perception.",
            "The optic nerve carries signals — not light itself.",
            "",
            ["optic nerve"],
        ),
        (
            "Colours need open eyes",
            "With eyes closed you may identify objects by smell, taste, sound or touch — but not their colours. Colour vision needs light entering the eye.",
            "eye_light_path",
            {"mode": "full_path", "highlight": "eye"},
            "Links colour perception to the physics of light detection.",
            "Try naming shirt colour with eyes shut — you guess, you do not see colour.",
            "Colour vision requires light on the retina.",
            "",
            "",
            [],
        ),
    ],
)

DAY2 = _build_day(
    2,
    [
        (
            "Power of accommodation",
            "Accommodation is the ability of the eye lens to adjust its focal length so both near and distant objects focus clearly on the retina.",
            "eye_accommodation",
            {"mode": "overview"},
            "Without accommodation we could not read and look far away in quick succession.",
            "Glancing from notebook to classroom board uses accommodation.",
            "Accommodation = focal length adjustment by eye lens.",
            "Accommodation is not the same as moving the eyeball.",
            "",
            ["accommodation"],
        ),
        (
            "Ciliary muscles",
            "Ciliary muscles change the curvature of the eye lens. When they contract or relax, the lens becomes thicker or thinner.",
            "eye_accommodation",
            {"highlight": "ciliary"},
            "Muscle action is the mechanism behind accommodation.",
            "Reading closely — ciliary muscles contract.",
            "Ciliary muscles → lens curvature changes.",
            "",
            "",
            ["ciliary muscles"],
        ),
        (
            "Distant vision — relaxed muscles",
            "When ciliary muscles are relaxed, the eye lens becomes thin, focal length increases, and distant objects are seen clearly.",
            "eye_accommodation",
            {"mode": "distant"},
            "Far vision uses a thinner, longer-focal-length lens.",
            "Looking at mountains on a clear day — muscles relaxed.",
            "Relaxed muscles → thin lens → distant objects clear.",
            "",
            "",
            [],
        ),
        (
            "Near vision — contracted muscles",
            "For nearby objects, ciliary muscles contract, lens curvature increases, lens becomes thicker, and focal length decreases.",
            "eye_accommodation",
            {"mode": "near"},
            "Near work needs a shorter focal length.",
            "Reading a phone screen — muscles contracted.",
            "Contracted muscles → thick lens → near objects clear.",
            "",
            "",
            [],
        ),
        (
            "Minimum focal length limit",
            "The eye lens cannot decrease its focal length below a certain minimum. Objects closer than the near point appear blurred or strain the eye.",
            "eye_accommodation",
            {"highlight": "limit"},
            "Explains why very close text blurs.",
            "Hold a page 5 cm from eyes — text blurs and eyes feel strained.",
            "There is a closest distance the eye can focus comfortably.",
            "",
            "",
            [],
        ),
        (
            "Least distance of distinct vision",
            "The least distance of distinct vision is the minimum distance at which objects can be seen distinctly without strain — also called the near point.",
            "formula_panel",
            {"formula": "Near point ≈ 25 cm (normal young adult)", "label": "Least distance of distinct vision"},
            "NCERT uses 25 cm as the standard near point in problems.",
            "Hold a book about 25 cm away for comfortable reading.",
            "Near point ≈ 25 cm for normal young adult.",
            "Do not confuse 25 cm with 25 m.",
            "",
            ["near point"],
        ),
        (
            "Far point of normal eye",
            "The far point is the farthest distance up to which the eye can see clearly. For a normal eye it is infinity.",
            "eye_accommodation",
            {"mode": "distant", "highlight": "far_point"},
            "Normal eyes need no correction for distant objects.",
            "Stars (except brightness limits) are effectively at infinity.",
            "Normal far point = infinity.",
            "Far point is not 25 cm — that is the near point.",
            "",
            ["far point"],
        ),
        (
            "Range of normal vision",
            "A normal eye sees objects clearly from about 25 cm (near point) to infinity (far point).",
            "eye_accommodation",
            {"mode": "range"},
            "Defines the comfort zone before defects appear.",
            "Classroom board and notebook both fall in this range for healthy eyes.",
            "Normal range: 25 cm to ∞.",
            "",
            "",
            [],
        ),
        (
            "Cataract",
            "In old age the crystalline lens may become milky and cloudy — a condition called cataract, causing partial or complete loss of vision.",
            "eye_structure",
            {"highlight": "cataract"},
            "Cataract is a lens opacity, not a refractive power defect like myopia.",
            "Cloudy vision in elderly relatives may be cataract.",
            "Cataract = cloudy lens; surgery can restore vision.",
            "Cataract is not corrected by ordinary spectacles alone.",
            "",
            ["cataract"],
        ),
        (
            "Cataract surgery",
            "Vision can often be restored through cataract surgery replacing the cloudy lens.",
            "eye_structure",
            {"highlight": "cataract", "mode": "surgery"},
            "Modern surgery returns functional sight when the retina is healthy.",
            "Doctors implant an artificial lens during cataract surgery.",
            "Cataract surgery replaces the cloudy lens.",
            "",
            "",
            [],
        ),
    ],
)

DAY3 = _build_day(
    3,
    [
        (
            "Refractive defects of vision",
            "Sometimes the eye loses its power of accommodation or has shape/lens issues. Vision becomes blurred — these are refractive defects.",
            "vision_defect",
            {"defect": "overview"},
            "Blurred vision often has a physical cause that lenses can correct.",
            "Difficulty reading the board from the back row may signal myopia.",
            "Refractive defects = focus problem, often fixable with lenses.",
            "",
            "",
            [],
        ),
        (
            "Three common defects",
            "The three main refractive defects in NCERT are myopia (near-sightedness), hypermetropia (far-sightedness), and presbyopia.",
            "vision_defect",
            {"defect": "three_types"},
            "Exam questions often ask to identify and correct each type.",
            "Spectacles use concave, convex, or bifocal lenses for these.",
            "Myopia, hypermetropia, presbyopia — know each pattern.",
            "Astigmatism is beyond basic Class 10 scope.",
            "",
            [],
        ),
        (
            "Myopia — near-sightedness",
            "A myopic person sees nearby objects clearly but distant objects appear blurred. The far point is nearer than infinity.",
            "vision_defect",
            {"defect": "myopia"},
            "Myopia limits clear distance vision.",
            "Student cannot read the far blackboard but reads books fine.",
            "Myopia = clear near, blurred far.",
            "",
            "",
            ["myopia"],
        ),
        (
            "Myopic image position",
            "In a myopic eye, the image of a distant object forms in front of the retina, not on it.",
            "vision_defect",
            {"defect": "myopia", "highlight": "image_front"},
            "Focus falls short of the retinal screen.",
            "Ray diagram shows rays meeting before reaching retina.",
            "Distant object image → in front of retina.",
            "Image in front of retina is myopia, not hypermetropia.",
            "",
            ["myopia"],
        ),
        (
            "Causes of myopia",
            "Myopia may arise from excessive curvature of the eye lens or elongation of the eyeball.",
            "vision_defect",
            {"defect": "myopia", "highlight": "causes"},
            "Both cause rays to converge too strongly for distant objects.",
            "Longer eyeball or overly curved lens bends light too much.",
            "Too strong convergence → myopia.",
            "",
            "",
            [],
        ),
        (
            "Myopia correction — concave lens",
            "Myopia is corrected with a concave (diverging) lens of suitable power that spreads rays so the image lands on the retina.",
            "vision_defect",
            {"defect": "myopia", "highlight": "correction"},
            "Concave lens moves the focus backward onto the retina.",
            "Minus-power spectacles for distance viewing.",
            "Myopia → concave lens.",
            "Convex lens worsens myopia — do not use it.",
            "",
            ["concave lens"],
        ),
        (
            "Hypermetropia — far-sightedness",
            "A hypermetropic person sees distant objects clearly but nearby objects are blurred. The near point is beyond 25 cm.",
            "vision_defect",
            {"defect": "hypermetropia"},
            "Reading strain is a classic hypermetropia sign.",
            "Person holds newspaper farther than 25 cm to read.",
            "Hypermetropia = clear far, blurred near.",
            "",
            "",
            ["hypermetropia"],
        ),
        (
            "Hypermetropic image position",
            "For a nearby object, a hypermetropic eye focuses the image behind the retina.",
            "vision_defect",
            {"defect": "hypermetropia", "highlight": "image_behind"},
            "Focus falls beyond the retinal screen for close work.",
            "Close book rays meet behind the retina without correction.",
            "Near object image → behind retina.",
            "",
            "",
            [],
        ),
        (
            "Causes of hypermetropia",
            "Hypermetropia arises when the eye lens focal length is too long or the eyeball is too small.",
            "vision_defect",
            {"defect": "hypermetropia", "highlight": "causes"},
            "Weak convergence for nearby objects causes behind-retina focus.",
            "Shorter eyeball length is one NCERT cause.",
            "Too little convergence → hypermetropia.",
            "",
            "",
            [],
        ),
        (
            "Hypermetropia correction — convex lens",
            "Hypermetropia is corrected with a convex (converging) lens that adds focusing power so the image forms on the retina.",
            "vision_defect",
            {"defect": "hypermetropia", "highlight": "correction"},
            "Convex lens brings the focus forward onto the retina.",
            "Plus-power reading glasses supply extra convergence.",
            "Hypermetropia → convex lens.",
            "Concave lens is for myopia, not hypermetropia.",
            "",
            ["convex lens"],
        ),
    ],
)

DAY4 = _build_day(
    4,
    [
        (
            "Presbyopia",
            "Presbyopia is the gradual loss of accommodation with age — the near point recedes and nearby objects are hard to see clearly.",
            "vision_defect",
            {"defect": "presbyopia"},
            "Most older adults need reading glasses even if distance vision was fine.",
            "Grandparent holds phone at arm's length to read messages.",
            "Presbyopia = age-related near vision loss.",
            "Presbyopia is not the same as myopia.",
            "",
            ["presbyopia"],
        ),
        (
            "Cause of presbyopia",
            "Presbyopia arises from weakening ciliary muscles and reduced flexibility of the eye lens with age.",
            "eye_accommodation",
            {"highlight": "age"},
            "Mechanism is reduced accommodation, not necessarily eyeball length.",
            "Lens stiffens — cannot thicken enough for near focus.",
            "Weaker ciliary muscles + stiff lens → presbyopia.",
            "",
            "",
            [],
        ),
        (
            "Combined myopia and hypermetropia",
            "Some people have both myopia and hypermetropia — they may need bifocal lenses.",
            "vision_defect",
            {"defect": "bifocal"},
            "Different distances need opposite corrections.",
            "Upper lens for distance, lower for reading in bifocals.",
            "Both defects → bifocal spectacles possible.",
            "",
            "",
            ["bifocal lens"],
        ),
        (
            "Bifocal lens design",
            "A common bifocal has a concave upper part for distant vision and a convex lower part for near vision.",
            "vision_defect",
            {"defect": "bifocal", "highlight": "parts"},
            "Each zone supplies the correction needed for that viewing distance.",
            "Look through top for board, bottom for notebook.",
            "Top concave (far), bottom convex (near).",
            "Do not swap upper and lower lens types.",
            "",
            ["bifocal lens"],
        ),
        (
            "Contact lenses and surgery",
            "Refractive defects can also be corrected with contact lenses or surgical interventions (modern option beyond basic spectacles).",
            "vision_defect",
            {"defect": "overview", "mode": "modern"},
            "Same physics — different way to place corrective lenses.",
            "LASIK reshapes cornea; contacts sit on the eye surface.",
            "Spectacles are not the only correction method.",
            "",
            "",
            [],
        ),
        (
            "Lens power and focal length",
            "Lens power P = 1/f when f is in metres. Unit is dioptre (D). Corrective lenses are chosen by required power.",
            "formula_panel",
            {"formula": "P = 1/f (f in m)", "label": "Power of lens"},
            "Numericals link spectacle prescription to focal length.",
            "P = −2 D means f = −0.5 m (concave).",
            "Power in dioptres = reciprocal of f in metres.",
            "Convert cm to m before using P = 1/f.",
            "",
            ["dioptre"],
        ),
        (
            "Myopia numerical idea",
            "If far point is at distance x, a concave lens should make parallel rays appear to come from x so retina receives a clear image.",
            "formula_panel",
            {"formula": "Use lens formula with far point", "label": "Myopia correction"},
            "Connects ray optics from Ch 9 to eye defects.",
            "Far point 1.2 m → concave lens of suitable power.",
            "Concave lens shifts apparent far point to infinity.",
            "",
            "",
            [],
        ),
        (
            "Hypermetropia numerical idea",
            "If near point is at N instead of 25 cm, convex lens adds power to focus objects at 25 cm on the retina.",
            "formula_panel",
            {"formula": "Near point correction with convex lens", "label": "Hypermetropia"},
            "Standard NCERT exercise uses near point shift.",
            "Near point 1 m → convex lens for reading at 25 cm.",
            "Convex lens reduces effective near point to normal.",
            "",
            "",
            [],
        ),
        (
            "Eye donation message",
            "Donated eyes after death can restore vision for corneal blind people — one pair may help up to four recipients.",
            "eye_structure",
            {"highlight": "donation"},
            "NCERT encourages eye donation as social responsibility.",
            "Eye banks collect and distribute donated corneas.",
            "Eye donation can cure corneal blindness.",
            "",
            "",
            [],
        ),
        (
            "Eye donation facts",
            "Spectacle wearers and cataract-operated people can still donate. Eyes must be collected within 4–6 hours after death.",
            "eye_structure",
            {"highlight": "donation", "mode": "facts"},
            "Practical facts NCERT lists for awareness.",
            "Inform nearest eye bank quickly after a death.",
            "4–6 hour window; simple 10–15 minute removal.",
            "",
            "",
            [],
        ),
    ],
)

DAY5 = _build_day(
    5,
    [
        (
            "Triangular glass prism",
            "A prism has two triangular bases and three rectangular lateral faces inclined to each other.",
            "prism_refraction",
            {"highlight": "prism_shape"},
            "Unlike a glass slab, prism faces are not parallel.",
            "NCERT Activity 10.1 uses a triangular prism.",
            "Prism = inclined refracting surfaces.",
            "",
            "",
            ["prism"],
        ),
        (
            "Angle of the prism",
            "The angle between two lateral faces of a prism is called the angle of the prism (∠A in diagrams).",
            "prism_refraction",
            {"highlight": "angle_A"},
            "This angle sets how much light deviates overall.",
            "Marked at the apex between the two refracting faces.",
            "Angle of prism = ∠A at apex.",
            "",
            "",
            ["angle of prism"],
        ),
        (
            "Incident ray PE",
            "In prism diagrams PE is the incident ray striking the first face AB of the prism.",
            "prism_refraction",
            {"highlight": "incident"},
            "First refraction happens at face AB (air to glass).",
            "Activity 10.1 draws line PE inclined to face AB.",
            "PE = incident ray.",
            "",
            "",
            [],
        ),
        (
            "Refracted ray EF",
            "Inside the prism EF is the refracted ray bending towards the normal at the first surface (air → glass).",
            "prism_refraction",
            {"highlight": "refracted"},
            "Glass is optically denser — ray bends toward normal on entry.",
            "Pin alignment locates EF through the prism.",
            "Air to glass → bend toward normal.",
            "",
            "",
            ["refraction"],
        ),
        (
            "Emergent ray FS",
            "FS is the emergent ray leaving the second face AC (glass → air), bending away from the normal.",
            "prism_refraction",
            {"highlight": "emergent"},
            "Second refraction separates direction from incident ray.",
            "Emergent ray is not parallel to incident ray in a prism.",
            "Glass to air → bend away from normal.",
            "",
            "",
            [],
        ),
        (
            "Angles i, r, e",
            "∠i is angle of incidence, ∠r angle of refraction at first face, ∠e angle of emergence at second face — all measured from normals.",
            "prism_refraction",
            {"highlight": "angles"},
            "Same normal rule as Ch 9 refraction.",
            "Draw perpendiculars at E and F to each face.",
            "Measure angles from normal, not from surface.",
            "Angle from surface is a common exam mistake.",
            "",
            ["angle of incidence"],
        ),
        (
            "Angle of deviation D",
            "Because of the prism shape, the emergent ray is bent at angle ∠D from the original incident direction.",
            "prism_refraction",
            {"highlight": "deviation"},
            "Deviation measures how much the light path turns overall.",
            "Activity 10.1 asks you to mark and measure ∠D.",
            "∠D = angle of deviation.",
            "Deviation is not the same as ∠A alone.",
            "",
            ["angle of deviation"],
        ),
        (
            "Prism vs glass slab",
            "In a parallel-sided slab emergent ray is parallel to incident (lateral shift only). A prism turns the ray because faces are inclined.",
            "glass_slab",
            {"mode": "compare_prism"},
            "Inclined faces cause net deviation — key difference.",
            "Slab: parallel in/out; prism: direction changes.",
            "Parallel faces → no net deviation; prism → deviation D.",
            "",
            "",
            [],
        ),
        (
            "Pin method for prism",
            "Fix pins P,Q on incident line; look through second face and align pins R,S with images of P,Q to trace the ray path.",
            "prism_refraction",
            {"mode": "activity"},
            "Standard school lab method for ray tracing.",
            "Remove prism and join pin marks to complete diagram.",
            "Pin alignment locates real ray path.",
            "",
            "",
            [],
        ),
        (
            "Refraction at two faces",
            "Light refracts twice — entering and leaving the prism. Both bends combine to produce deviation D.",
            "prism_refraction",
            {"highlight": "two_faces"},
            "Always analyse entry and exit separately.",
            "First face: toward normal; second face: away from normal.",
            "Two refractions → net deviation.",
            "",
            "",
            [],
        ),
    ],
)

DAY6 = _build_day(
    6,
    [
        (
            "Dispersion",
            "Dispersion is the splitting of white light into its component colours.",
            "dispersion_spectrum",
            {"highlight": "dispersion"},
            "White sunlight contains all visible colours combined.",
            "Prism + narrow sunlight beam → colour band.",
            "Dispersion = split white light into colours.",
            "Dispersion is not the same as scattering.",
            "",
            ["dispersion"],
        ),
        (
            "Spectrum",
            "The band of coloured components of a light beam is called its spectrum.",
            "dispersion_spectrum",
            {"highlight": "spectrum"},
            "Each colour travels slightly differently through the prism.",
            "Rainbow arc is a natural spectrum.",
            "Spectrum = ordered colour band.",
            "",
            "",
            ["spectrum"],
        ),
        (
            "VIBGYOR order",
            "The sequence of colours in the visible spectrum is Violet, Indigo, Blue, Green, Yellow, Orange, Red — VIBGYOR.",
            "dispersion_spectrum",
            {"highlight": "vibgyor"},
            "Memorise order from short to long wavelength end.",
            "Violet at one end, red at the other in NCERT Fig 10.5.",
            "VIBGYOR — violet to red.",
            "Indigo is included in NCERT sequence.",
            "",
            ["VIBGYOR"],
        ),
        (
            "Red bends least",
            "Red light bends the least when passing through a prism; violet bends the most.",
            "dispersion_spectrum",
            {"highlight": "bending"},
            "Different colours have different refractive indices in glass.",
            "Red ray stays closest to original direction.",
            "Red least, violet most deviation.",
            "Do not swap red and violet bending.",
            "",
            [],
        ),
        (
            "Why colours separate",
            "Different colours bend through different angles, so each emerges along a different path and becomes distinct.",
            "dispersion_spectrum",
            {"mode": "separate_paths"},
            "Separation is due to wavelength-dependent refraction.",
            "Each colour has its own emergent direction.",
            "Different angles → separate colours.",
            "",
            "",
            [],
        ),
        (
            "Activity 10.2 setup",
            "Sunlight through a narrow slit gives a beam of white light on a prism face; turn prism until colours appear on a screen.",
            "dispersion_spectrum",
            {"mode": "activity"},
            "Slit makes a narrow beam for clear spectrum.",
            "Cardboard slit + prism + nearby screen.",
            "Narrow white beam → prism → spectrum on screen.",
            "",
            "",
            [],
        ),
        (
            "Newton's first prism experiment",
            "Isaac Newton used a glass prism to obtain the spectrum of sunlight — first systematic demonstration of dispersion.",
            "dispersion_spectrum",
            {"highlight": "newton"},
            "Historical anchor for white light composition.",
            "Newton showed sunlight itself contains all spectrum colours.",
            "Newton split sunlight into spectrum.",
            "",
            "",
            [],
        ),
        (
            "Second prism — no further split",
            "Newton could not split a single spectrum colour further with another similar prism — each colour is pure in that sense.",
            "dispersion_spectrum",
            {"mode": "newton_split"},
            "Proves spectrum colours are fundamental components here.",
            "Pure red through prism stays red.",
            "Single spectrum colour does not split again.",
            "",
            "",
            [],
        ),
        (
            "Recombination of white light",
            "Newton placed a second identical prism inverted so all colours passed through it and white light emerged again.",
            "dispersion_spectrum",
            {"mode": "recombine"},
            "Shows white light = superposition of spectrum colours.",
            "Two prisms: split then merge back to white.",
            "Inverted second prism recombines colours → white.",
            "",
            "",
            [],
        ),
        (
            "White light definition",
            "Any light giving a spectrum similar to sunlight is often called white light in NCERT.",
            "dispersion_spectrum",
            {"highlight": "white"},
            "White is not a single wavelength — it is a mixture.",
            "Sunlight, LED white, and recombined prism light qualify.",
            "White light contains all visible colours.",
            "White paint reflects mix; it is not a spectrum colour.",
            "",
            ["white light"],
        ),
    ],
)

DAY7 = _build_day(
    7,
    [
        (
            "Rainbow as natural spectrum",
            "A rainbow is a natural spectrum in the sky after rain, caused by dispersion of sunlight by water droplets.",
            "rainbow",
            {"highlight": "overview"},
            "Connects prism physics to weather optics.",
            "Arc of colours opposite the Sun after a shower.",
            "Rainbow = dispersion + droplet optics.",
            "",
            "",
            ["rainbow"],
        ),
        (
            "Rainbow direction",
            "A rainbow is always formed in a direction opposite to the Sun.",
            "rainbow",
            {"highlight": "direction"},
            "Stand with Sun behind you to see rainbow ahead.",
            "Morning rainbow appears west if Sun is in east.",
            "Rainbow opposite the Sun.",
            "",
            "",
            [],
        ),
        (
            "Water droplet as prism",
            "Tiny water droplets act like small prisms — they refract and disperse incident sunlight.",
            "rainbow",
            {"highlight": "droplet"},
            "Spherical droplets both refract and reflect light.",
            "Mist from waterfall can show mini rainbows.",
            "Droplets refract + disperse sunlight.",
            "",
            "",
            [],
        ),
        (
            "Internal reflection in droplet",
            "Inside a raindrop light reflects internally before refracting out again — this helps separate colours toward the observer.",
            "rainbow",
            {"highlight": "reflection"},
            "One internal bounce is key in NCERT Fig 10.8.",
            "Light enters droplet, reflects inside, exits refracting.",
            "Internal reflection + refraction → rainbow.",
            "",
            "",
            [],
        ),
        (
            "Second refraction out of droplet",
            "Light refracts again when leaving the raindrop, further spreading colours to the observer's eye.",
            "rainbow",
            {"highlight": "exit"},
            "Exit refraction adds to colour separation.",
            "Different colours reach eye along different paths.",
            "Exit refraction sends colours to observer.",
            "",
            "",
            [],
        ),
        (
            "Waterfall rainbow",
            "On a sunny day you can see a rainbow through waterfall spray with the Sun behind you.",
            "rainbow",
            {"mode": "waterfall"},
            "Same physics as sky rainbow on smaller scale.",
            "Garden hose spray with backlit Sun shows colours.",
            "Spray + Sun behind → rainbow.",
            "",
            "",
            [],
        ),
        (
            "Atmospheric refraction intro",
            "Atmospheric refraction is bending of light by Earth's atmosphere when refractive index changes gradually.",
            "atmospheric_refraction",
            {"mode": "intro"},
            "Air density changes with height and temperature.",
            "Hot air above fire bends light — objects shimmer.",
            "Changing air density → refraction.",
            "",
            "",
            ["atmospheric refraction"],
        ),
        (
            "Hot air shimmer",
            "Hot air above a fire is less dense with slightly lower refractive index; apparent object position wavers — local atmospheric refraction.",
            "atmospheric_refraction",
            {"mode": "hot_air"},
            "Small-scale demo of unstable refraction.",
            "Road mirage on hot days uses similar idea.",
            "Hot rising air bends light unpredictably.",
            "",
            "",
            [],
        ),
        (
            "Twinkling of stars",
            "Stars twinkle because starlight refracts continuously through moving air layers before reaching Earth.",
            "atmospheric_refraction",
            {"mode": "twinkle"},
            "Star appears to shift and flicker in brightness.",
            "Clear night — bright stars seem to sparkle.",
            "Moving air → changing star position/brightness.",
            "",
            "",
            ["twinkling"],
        ),
        (
            "Apparent star position",
            "Atmosphere bends starlight toward the normal so a star near the horizon appears slightly higher than its actual position.",
            "atmospheric_refraction",
            {"highlight": "star_position"},
            "Explains Fig 10.9 apparent vs actual star.",
            "Horizon stars look lifted slightly upward.",
            "Apparent position above actual near horizon.",
            "",
            "",
            [],
        ),
    ],
)

DAY8 = _build_day(
    8,
    [
        (
            "Why stars flicker in brightness",
            "As the path of starlight varies slightly, the amount entering the eye changes — star sometimes brighter, sometimes fainter.",
            "atmospheric_refraction",
            {"mode": "brightness"},
            "Twinkling combines position shift and intensity change.",
            "Sirius near horizon twinkles more than at zenith.",
            "Varying path → flickering brightness.",
            "",
            "",
            [],
        ),
        (
            "Stars as point sources",
            "Stars are so distant they act like point-sized sources; small path changes produce noticeable twinkling.",
            "atmospheric_refraction",
            {"highlight": "point_source"},
            "Extended sources average out fluctuations.",
            "Single tiny source flickers easily.",
            "Point source → visible twinkle.",
            "",
            "",
            [],
        ),
        (
            "Planets do not twinkle",
            "Planets are closer and seen as extended sources; variations from many points average out — no noticeable twinkle.",
            "atmospheric_refraction",
            {"mode": "planets"},
            "Classic NCERT compare question with stars.",
            "Jupiter appears steady while nearby stars sparkle.",
            "Extended source → twinkling cancels out.",
            "Planets are not point sources to our eye.",
            "",
            [],
        ),
        (
            "Advance sunrise",
            "The Sun is visible about 2 minutes before actual sunrise because atmospheric refraction bends sunlight over the horizon.",
            "atmospheric_refraction",
            {"mode": "sunrise"},
            "We see Sun before geometric crossing of horizon.",
            "Fig 10.10 shows actual vs apparent Sun position.",
            "Advance sunrise ≈ 2 minutes.",
            "",
            "",
            ["advance sunrise"],
        ),
        (
            "Delayed sunset",
            "Similarly, we see the Sun for about 2 minutes after actual sunset due to atmospheric refraction.",
            "atmospheric_refraction",
            {"mode": "sunset"},
            "Symmetric effect to advance sunrise.",
            "Sun appears above horizon after it physically set.",
            "Delayed sunset ≈ 2 minutes.",
            "",
            "",
            [],
        ),
        (
            "Flattened Sun disc",
            "The apparent flattening of the Sun's disc at sunrise and sunset is also due to atmospheric refraction.",
            "atmospheric_refraction",
            {"highlight": "flattened"},
            "Different parts of disc refract differently near horizon.",
            "Oval Sun at horizon in photographs.",
            "Horizon Sun looks flattened — refraction effect.",
            "",
            "",
            [],
        ),
        (
            "Scattering of light",
            "Scattering sends light in new directions when it hits particles — different from refraction through uniform media.",
            "scattering_sky",
            {"mode": "intro"},
            "Explains sky colour without a prism.",
            "Headlight beam visible in fog due to scattering.",
            "Scattering redirects light by particles.",
            "Scattering ≠ dispersion (splitting by wavelength in prism).",
            "",
            ["scattering"],
        ),
        (
            "Colloidal vs true solution",
            "Light path is not visible in a true solution but becomes visible in colloidal solutions with larger particles.",
            "tyndall_effect",
            {"mode": "colloid"},
            "Particle size determines whether path shows.",
            "Milk dilute in water shows Tyndall effect.",
            "Larger particles → visible beam path.",
            "",
            "",
            ["Tyndall effect"],
        ),
        (
            "Tyndall effect",
            "When fine particles scatter light, the beam path becomes visible — Tyndall effect (Class IX revision).",
            "tyndall_effect",
            {"highlight": "beam"},
            "Seen in smoke-filled room with sunbeam through hole.",
            "Forest canopy: mist scatters sunlight into visible rays.",
            "Tyndall = visible path due to scattering.",
            "",
            "",
            ["Tyndall effect"],
        ),
        (
            "Scattering particle size",
            "Very fine particles scatter mainly blue; larger particles scatter longer wavelengths and may appear white.",
            "scattering_sky",
            {"highlight": "particle_size"},
            "Size selects which wavelengths scatter more.",
            "Fine smoke bluish; thick cloud white.",
            "Small particles → blue; large → white scatter.",
            "",
            "",
            [],
        ),
    ],
)

DAY9 = _build_day(
    9,
    [
        (
            "Why sky is blue",
            "Air molecules and fine particles are smaller than visible wavelengths and scatter shorter blue wavelengths more strongly than red.",
            "scattering_sky",
            {"highlight": "blue_sky"},
            "Most iconic scattering application.",
            "Clear noon sky looks blue away from the Sun.",
            "Fine particles scatter blue more → blue sky.",
            "Sky is not blue due to reflection from oceans alone.",
            "",
            [],
        ),
        (
            "Red wavelength advantage",
            "Red light has wavelength about 1.8 times greater than blue — scatters less, travels farther through air.",
            "scattering_sky",
            {"highlight": "wavelength"},
            "Explains red sun and red traffic lights in fog.",
            "Compare red and blue laser in dusty air — blue spreads more.",
            "Longer λ (red) scatters less than blue.",
            "",
            "",
            [],
        ),
        (
            "No atmosphere — dark sky",
            "Without atmosphere there would be no scattering; the sky would look dark and stars visible even daytime (as on Moon).",
            "scattering_sky",
            {"mode": "no_atmosphere"},
            "Astronauts see dark sky at high altitude too.",
            "Moon photos show black sky in daylight.",
            "No air → no scatter → dark sky.",
            "",
            "",
            [],
        ),
        (
            "Dark sky at high altitude",
            "Passengers at very high altitude see darker sky because scattering is less prominent there.",
            "scattering_sky",
            {"mode": "high_altitude"},
            "Less air above means less blue scatter.",
            "Airplane window view — sky deep blue to black.",
            "High altitude → less scattering → darker sky.",
            "",
            "",
            [],
        ),
        (
            "Red sun at sunrise/sunset",
            "When Sun is near horizon, light travels longer through air; blue scatters away and red reaches our eyes — red Sun.",
            "scattering_sky",
            {"mode": "red_sun"},
            "Long path removes blue from direct sunlight.",
            "Orange-red Sun at horizon vs white-yellow at noon.",
            "Long air path → red sunset/sunrise.",
            "",
            "",
            [],
        ),
        (
            "Red danger signals",
            "Red light is least scattered by fog or smoke so it remains visible at distance — used for danger signals.",
            "scattering_sky",
            {"highlight": "red_signal"},
            "Safety design uses scattering physics.",
            "Red traffic and warning lights penetrate haze better.",
            "Red scatters least → visible far in fog.",
            "",
            "",
            [],
        ),
        (
            "Deep sea colour",
            "NCERT mentions deep sea water colour also relates to selective absorption and scattering of light.",
            "scattering_sky",
            {"mode": "sea"},
            "Light penetration decreases with depth.",
            "Deep ocean appears dark blue-green.",
            "Water also affects light by scatter/absorption.",
            "",
            "",
            [],
        ),
        (
            "Image distance in normal eye",
            "When object distance increases, the eye lens adjusts so image stays on the retina — image distance in eye remains effectively constant.",
            "eye_accommodation",
            {"mode": "image_distance"},
            "Common conceptual question in exercises.",
            "Look from book to far wall — lens changes, retina position fixed.",
            "Retinal image location stays on retina via accommodation.",
            "Image distance in eye is not like a fixed camera sensor moving.",
            "",
            "",
            [],
        ),
        (
            "Why not see closer than 25 cm",
            "Normal eye cannot decrease focal length below limit — objects closer than near point form blurred image or cause strain.",
            "eye_accommodation",
            {"highlight": "limit"},
            "Links accommodation limit to near point.",
            "Hold finger 10 cm away — blur without strain.",
            "Minimum focal length → near point at 25 cm.",
            "",
            "",
            [],
        ),
        (
            "Blackboard last row problem",
            "A student who cannot read the distant blackboard likely has myopia — corrected with a concave lens.",
            "vision_defect",
            {"defect": "myopia", "mode": "application"},
            "Typical NCERT application question.",
            "Far board blurry, near notes clear → myopia.",
            "Distant blur → myopia → concave lens.",
            "",
            "",
            [],
        ),
    ],
)

# Days 10–16 extend applications, mixed review, and exam-style anchors
DAY10 = _build_day(
    10,
    [
        ("Prism activity safety", "Trace prism outlines on paper; use pins carefully; sunlight through slit should be narrow — avoid looking directly at the Sun.", "prism_refraction", {"mode": "safety"}, "Eye safety matches Unit 1 light rules.", "Use slit to limit beam intensity on screen.", "Never stare at direct Sun.", "", "", []),
        ("Dispersion vs scattering", "Dispersion splits white light into colours by refraction in a prism. Scattering redirects colours by particles in air — different mechanisms.", "dispersion_spectrum", {"mode": "compare_scatter"}, "Exam questions often confuse these.", "Prism rainbow vs blue sky.", "Dispersion = prism split; scattering = particle redirect.", "Do not say blue sky is dispersion.", "", []),
        ("Myopia lens power sign", "Concave lenses have negative power in dioptres; myopia correction uses negative P.", "formula_panel", {"formula": "Concave → P negative", "label": "Sign convention"}, "Sign tells lens type quickly.", "−2 D spectacles for myopia.", "Myopia correction → negative power.", "", "", []),
        ("Hypermetropia lens power sign", "Convex lenses have positive power; hypermetropia correction uses positive P.", "formula_panel", {"formula": "Convex → P positive", "label": "Sign convention"}, "Pairs with myopia sign rule.", "+ reading glasses for farsighted near work.", "Hypermetropia → positive power.", "", "", []),
        ("Bifocal power combination", "Bifocals combine negative (upper) and positive (lower) powers for different viewing distances.", "vision_defect", {"defect": "bifocal", "mode": "powers"}, "Each zone has its own P value.", "Prescription shows different powers top vs bottom.", "Two powers in one frame.", "", "", []),
        ("Cornea vs lens refraction share", "Most refraction occurs at cornea; lens only fine-tunes — both together focus on retina.", "eye_structure", {"highlight": "refraction_split"}, "Explains where spectacle lenses act vs internal parts.", "Laser eye surgery often reshapes cornea.", "Cornea = main bend; lens = fine tune.", "", "", []),
        ("Retina as real image screen", "Retina receives real inverted image like a camera sensor — brightness must be controlled by pupil.", "eye_structure", {"highlight": "retina_screen"}, "Connects Ch 9 real images to biology.", "Camera and eye both use real images.", "Retina = real image plane.", "", "", []),
        ("Electrical signals not light", "Optic nerve carries electrical impulses, not light rays, to the brain.", "eye_structure", {"highlight": "signals"}, "Sensory transduction step.", "Blind spot where nerve exits has no sensors.", "Retina converts light → signals.", "", "", []),
        ("Presbyopia vs hypermetropia", "Both affect near vision but presbyopia is age-related stiffness; hypermetropia is focal length/eyeball size issue at any age.", "vision_defect", {"defect": "presbyopia", "mode": "compare"}, "Different causes — may coexist in elderly.", "Old age reading glasses may be presbyopia alone or combined.", "Presbyopia = age; hypermetropia = focus geometry.", "", "", []),
        ("Eye donation exclusions", "People with AIDS, hepatitis B/C, rabies, certain infections cannot donate eyes; identities stay confidential.", "eye_structure", {"highlight": "donation", "mode": "rules"}, "NCERT lists medical exclusions.", "Eye bank screens all donations.", "Medical safety rules for donation.", "", "", []),
    ],
)

DAY11 = _build_day(
    11,
    [
        ("Angle of prism vs deviation", "Larger prism angle generally increases deviation for the same material — linked but not identical quantities.", "prism_refraction", {"highlight": "compare_angles"}, "Numericals may give both.", "Measure ∠A and ∠D in activity.", "∠A at apex; ∠D between incident and emergent directions.", "", "", []),
        ("Emergent ray not parallel", "Unlike glass slab, prism emergent ray is tilted from incident direction by ∠D.", "prism_refraction", {"highlight": "deviation"}, "Core distinction from Ch 9 slab.", "Compare slab and prism diagrams side by side.", "Prism turns light overall.", "", "", []),
        ("Violet at one end of spectrum", "In standard NCERT diagram violet deviates most — appears at one end of the band.", "dispersion_spectrum", {"highlight": "violet"}, "Identify ends by bending amount.", "Violet fringe where deviation is maximum.", "Violet = most bent.", "", "", []),
        ("Red at other end", "Red deviates least — found at the opposite end of the spectrum from violet.", "dispersion_spectrum", {"highlight": "red"}, "Complete VIBGYOR orientation.", "Red fringe closest to original white beam direction.", "Red = least bent.", "", "", []),
        ("Spectrum purity", "Newton showed individual spectrum colours could not be split further by an identical prism.", "dispersion_spectrum", {"mode": "purity"}, "Conceptual limit of dispersion.", "Single-colour beam stays one colour through second prism.", "Spectrum colours are elementary here.", "", "", []),
        ("White light recombination proof", "Recombined spectrum forming white light proves white light is a mixture of colours.", "dispersion_spectrum", {"mode": "recombine"}, "Key conclusion of Newton's experiment.", "Two-prism demo in advanced demos.", "White = sum of spectrum colours.", "", "", []),
        ("Rainbow always arc", "Rainbow appears as arc because only certain droplet angles send separated colours to your eye.", "rainbow", {"mode": "arc"}, "Geometric collection of droplets matters.", "Full circle possible from aeroplane.", "Specific angle for rainbow visibility.", "", "", []),
        ("Primary rainbow path", "NCERT describes one internal reflection in droplet for rainbow — simplifies full optics.", "rainbow", {"highlight": "reflection"}, "Enough for Class 10 explanation.", "Fig 10.8 ray path through droplet.", "Enter → reflect inside → exit.", "", "", []),
        ("Sun behind observer", "For rainbow, sunlight must strike droplets with observer facing away from Sun.", "rainbow", {"highlight": "direction"}, "Geometry rule for spotting rainbows.", "Turn back to Sun, look at rain cloud.", "Sun at your back for rainbow.", "", "", []),
        ("Atmospheric refraction continuous", "Starlight passes through layers of changing density — refraction is continuous, not at one surface.", "atmospheric_refraction", {"mode": "layers"}, "Unlike prism faces.", "Gradient in air density with height.", "Gradual index change → bending.", "", "", []),
    ],
)

DAY12 = _build_day(
    12,
    [
        ("Twinkling more at horizon", "Stars near horizon twinkle more because light path through atmosphere is longer and less stable.", "atmospheric_refraction", {"mode": "horizon"}, "Observational astronomy note.", "Polaris near zenith steadies vs horizon stars.", "Longer air path → more twinkle.", "", "", []),
        ("Actual vs apparent sunrise diagram", "Fig 10.10: apparent Sun above horizon while actual Sun still below — due to refraction.", "atmospheric_refraction", {"mode": "diagram"}, "Draw for exam explanations.", "Label actual and apparent positions.", "Apparent Sun lifted by refraction.", "", "", []),
        ("2-minute time difference", "Both advance sunrise and delayed sunset give about 2 minutes extra daylight visibility.", "atmospheric_refraction", {"highlight": "two_minutes"}, "Quantitative NCERT fact.", "Memorise for short answers.", "≈2 min early and ≈2 min late.", "", "", []),
        ("Planets as extended source math idea", "Many point sources on planet disk average out flicker — net brightness stable.", "atmospheric_refraction", {"mode": "planets_detail"}, "Qualitative averaging argument.", "Venus disk visible in telescope — extended.", "Average of many points stabilizes image.", "", "", []),
        ("Hot air less dense", "Hot air is lighter with slightly lower refractive index than cooler air above.", "atmospheric_refraction", {"mode": "hot_air"}, "Density links to index.", "Shimmer above radiator.", "Hot air → lower n.", "", "", []),
        ("Molecules scatter blue", "N₂ and O₂ molecules scatter blue end of spectrum more effectively.", "scattering_sky", {"highlight": "molecules"}, "Molecular scale scattering.", "No particles needed — air molecules enough.", "Air molecules scatter short λ more.", "", "", []),
        ("Tyndall in forest", "Sunbeams through misty forest canopy show Tyndall scattering by tiny water droplets.", "tyndall_effect", {"mode": "forest"}, "Classic nature example.", "Morning mist in woods.", "Mist droplets scatter sunlight.", "", "", []),
        ("Smoke-filled room demo", "Fine beam through hole in dark smoke-filled room makes path visible — Tyndall.", "tyndall_effect", {"mode": "smoke"}, "Classroom demonstration reference.", "Dusty room + sun slit.", "Scattering makes beam visible.", "", "", []),
        ("White scattered light", "When scattering particles are large enough, scattered light may appear white.", "scattering_sky", {"highlight": "white_scatter"}, "Explains thick clouds looking white.", "Cumulus clouds scatter all colours.", "Large particles → white scatter.", "", "", []),
        ("Blue vs red scatter summary", "Fine particles → blue sky; long path removes blue from Sun → red Sun; red used in danger lights.", "scattering_sky", {"mode": "summary"}, "Revision card tying phenomena together.", "Three applications one principle.", "Scatter depends on λ and path length.", "", "", []),
    ],
)

DAY13 = _build_day(
    13,
    [
        ("Accommodation exam definition", "Define accommodation as eye lens adjusting focal length via ciliary muscles for near and far objects.", "eye_accommodation", {"mode": "definition"}, "1-mark definition question.", "Quote NCERT wording in exams.", "Accommodation = focal length adjustment.", "", "", ["accommodation"]),
        ("Near point exam value", "State near point ≈ 25 cm and far point infinity for normal young adult eye.", "formula_panel", {"formula": "25 cm to ∞", "label": "Normal vision range"}, "Frequent MCQ target.", "Option trap: 25 m vs 25 cm.", "25 cm near, ∞ far.", "", "", []),
        ("Myopia far point question type", "Given far point distance, identify concave lens and compute power using P=1/f with proper signs.", "vision_defect", {"defect": "myopia", "mode": "numerical"}, "Links Ch 9 lens formula.", "Far point 80 cm example in exercises.", "Concave lens; watch cm→m.", "", "", []),
        ("Hypermetropia near point question", "Given abnormal near point N, find convex lens power to read at 25 cm.", "vision_defect", {"defect": "hypermetropia", "mode": "numerical"}, "Standard exercise pattern.", "Near point 1 m problem in NCERT.", "Convex adds convergence.", "", "", []),
        ("Bifocal prescription idea", "Different lens powers for distance (concave part) and near (convex part) in one spectacle.", "vision_defect", {"defect": "bifocal", "mode": "exam"}, "Describe zones in long answers.", "Draw bifocal sketch with labels.", "Two corrections one lens.", "", "", []),
        ("Prism ray labeling exam", "Label PE, EF, FS, ∠i, ∠r, ∠e, ∠A, ∠D on prism diagram.", "prism_refraction", {"mode": "labels"}, "Diagram question preparation.", "Activity 10.1 diagram practice.", "All symbols from Fig 10.4.", "", "", []),
        ("Dispersion definition exam", "Dispersion: splitting of white light into component colours.", "dispersion_spectrum", {"mode": "definition"}, "One-line definition.", "Match word to prism activity.", "Dispersion = colour split.", "", "", ["dispersion"]),
        ("VIBGYOR exam order", "Write spectrum order VIBGYOR from shorter to longer wavelength side in standard diagram.", "dispersion_spectrum", {"highlight": "vibgyor"}, "Sequence MCQs common.", "Memorise acronym.", "VIBGYOR order.", "", "", []),
        ("Rainbow long answer", "Explain rainbow: dispersion + refraction + internal reflection in water droplets, opposite Sun.", "rainbow", {"mode": "exam"}, "3-mark question template.", "Use Fig 10.8 steps.", "Droplet prism + reflect + refract.", "", "", []),
        ("Twinkling long answer", "Explain twinkling: atmospheric refraction in turbulent air, point source stars, changing path and brightness.", "atmospheric_refraction", {"mode": "exam"}, "Compare with planets paragraph.", "Star vs planet subsection.", "Unstable refraction + point source.", "", "", []),
    ],
)

DAY14 = _build_day(
    14,
    [
        ("Advance sunrise explanation", "Atmospheric refraction bends Sun's rays over horizon so we see Sun before geometric sunrise.", "atmospheric_refraction", {"mode": "sunrise_exam"}, "2-mark question.", "Draw horizon line with actual/apparent Sun.", "Light bends in atmosphere early visibility.", "", "", []),
        ("Blue sky explanation", "Fine air molecules scatter blue light strongly; scattered blue enters eyes from all directions.", "scattering_sky", {"mode": "exam_blue"}, "3-mark favourite question.", "Without atmosphere sky dark.", "Selective scatter of short wavelengths.", "", "", []),
        ("Red sunset explanation", "At horizon Sun's light travels long path; blue scattered away, red predominates.", "scattering_sky", {"mode": "exam_red"}, "Pair with blue sky answer.", "Sun appears red orange at horizon.", "Long path removes blue.", "", "", []),
        ("Tyndall definition", "Tyndall effect: scattering of light by colloidal particles makes beam path visible.", "tyndall_effect", {"mode": "definition"}, "Link Class IX colloids.", "Milk, smoke, mist examples.", "Visible path = Tyndall.", "", "", []),
        ("Colloidal particle size link", "Colloidal particles larger than true solution particles — scatter enough to show path.", "tyndall_effect", {"mode": "size"}, "Revision from Class IX.", "True solution: invisible path.", "Colloid size enables scattering.", "", "", []),
        ("Danger signal red reason", "Red least scattered in fog — remains visible at distance for warnings.", "scattering_sky", {"highlight": "red_signal"}, "Application question.", "Traffic lights in smog.", "Least scatter → red signals.", "", "", []),
        ("Astronaut dark sky", "At high altitude / space little scattering — sky looks dark not blue.", "scattering_sky", {"mode": "astronaut"}, "Exercise Q12 answer idea.", "ISS photos show black sky.", "Insufficient air to scatter blue.", "", "", []),
        ("Ciliary muscles MCQ anchor", "Change in eye lens focal length is caused by ciliary muscles — not pupil or iris alone.", "eye_accommodation", {"highlight": "ciliary"}, "Matches NCERT exercise Q4.", "Pupil controls light amount only.", "Ciliary → lens shape.", "", "", []),
        ("Retina image MCQ anchor", "Human eye forms image at retina — not cornea or pupil.", "eye_structure", {"highlight": "retina"}, "Exercise Q2.", "Image on light-sensitive layer.", "Retina = image location.", "", "", []),
        ("Accommodation MCQ anchor", "Adjusting focal length for different distances is accommodation — not presbyopia or myopia.", "eye_accommodation", {"mode": "mcq"}, "Exercise Q1.", "Normal focusing ability name.", "Accommodation term.", "", "", []),
    ],
)

DAY15 = _build_day(
    15,
    [
        ("Chapter map overview", "Ch 10 flow: Eye → defects → prism → dispersion → rainbow → atmospheric refraction → scattering.", "eye_structure", {"highlight": "overview", "mode": "map"}, "Big-picture revision.", "Six NCERT sections in order.", "Follow section order for revision.", "", "", []),
        ("Link to Ch 9 lenses", "Spectacle lenses use same convex/concave rules from Ch 9; eye lens is a living convex lens.", "lens_labels", {"highlight": "link"}, "Cross-chapter connection.", "Lens ray rules apply to corrections.", "Ch 9 lens physics → eye correction.", "", "", []),
        ("Real image on retina revisited", "Eye lens converges rays to real inverted image — like convex lens beyond F.", "eye_structure", {"highlight": "inverted_image"}, "Unified optics story.", "Same as camera convex lens.", "Real inverted retinal image.", "", "", []),
        ("Pupil vs lens function", "Pupil regulates light intensity; lens regulates focus — different roles.", "eye_structure", {"highlight": "iris_pupil"}, "Avoid mixing in MCQs.", "Bright day small pupil still needs accommodation for distance.", "Pupil = amount; lens = focus.", "", "", []),
        ("Myopia concave ray idea", "Concave diverges rays before eye so eye's converging system forms image on retina.", "vision_defect", {"defect": "myopia", "mode": "ray"}, "Qualitative correction diagram.", "Fig 10.2(c) style.", "Diverge first then eye converges.", "", "", []),
        ("Hypermetropia convex ray idea", "Convex converges rays before eye to help focus nearby objects on retina.", "vision_defect", {"defect": "hypermetropia", "mode": "ray"}, "Fig 10.3(c) style.", "Extra convergence for near work.", "Convex assists near focus.", "", "", []),
        ("Prism dispersion connection", "Dispersion happens because refractive index varies with colour — violet slows/bends most.", "dispersion_spectrum", {"mode": "cause"}, "Deeper why for dispersion.", "Different n for each colour.", "Wavelength-dependent n.", "", "", []),
        ("Rainbow vs prism spectrum", "Both show dispersion but rainbow also needs reflection inside droplets and specific viewing geometry.", "rainbow", {"mode": "compare_prism"}, "Compare natural vs lab spectrum.", "Prism on desk vs sky arc.", "Rainbow adds reflection + geometry.", "", "", []),
        ("Star altitude and twinkling", "Stars at zenith twinkle less; near horizon path is longer and turbulence stronger.", "atmospheric_refraction", {"mode": "altitude"}, "Observation tip.", "Look up vs near horizon.", "Zenith more stable.", "", "", []),
        ("Scattering vs reflection", "Scattering spreads light in many directions by particles; mirror reflection follows definite angle law.", "scattering_sky", {"mode": "compare_reflection"}, "Concept clarity.", "Cloud vs mirror.", "Scattering ≠ specular reflection.", "", "", []),
    ],
)

DAY16 = _build_day(
    16,
    [
        ("Unit 2 mastery checklist — eye", "Name cornea, iris, pupil, lens, retina, optic nerve and each function.", "eye_structure", {"highlight": "overview", "mode": "checklist"}, "Self-test before practice.", "Draw labelled eye diagram from memory.", "Six main parts + functions.", "", "", []),
        ("Unit 2 mastery — defects", "For myopia, hypermetropia, presbyopia: state symptom, image position, lens correction.", "vision_defect", {"defect": "three_types", "mode": "checklist"}, "Table revision.", "Three-row comparison chart.", "Defect → image error → lens.", "", "", []),
        ("Unit 2 mastery — prism", "Draw prism ray path; mark i, r, e, A, D; state air→glass and glass→air bending.", "prism_refraction", {"mode": "checklist"}, "Diagram drill.", "Timed sketch from Activity 10.1.", "Two refractions + deviation.", "", "", []),
        ("Unit 2 mastery — dispersion", "Define dispersion and spectrum; write VIBGYOR; state red least violet most bent.", "dispersion_spectrum", {"mode": "checklist"}, "Spectrum recall.", "Recite VIBGYOR aloud.", "Dispersion + order + bending.", "", "", []),
        ("Unit 2 mastery — rainbow", "Explain droplet as prism, internal reflection, observer with Sun behind.", "rainbow", {"mode": "checklist"}, "Natural phenomenon template.", "30-second oral answer.", "Droplet path summary.", "", "", []),
        ("Unit 2 mastery — atmosphere", "Explain twinkling, non-twinkling planets, advance sunrise, delayed sunset.", "atmospheric_refraction", {"mode": "checklist"}, "Atmosphere section recap.", "Four short paragraphs practice.", "Four atmospheric effects.", "", "", []),
        ("Unit 2 mastery — scattering", "Explain Tyndall effect, blue sky, red Sun, red danger signals.", "scattering_sky", {"mode": "checklist"}, "Scattering section recap.", "Link each phenomenon to scatter size/λ.", "Four scattering applications.", "", "", []),
        ("Common exam pitfalls", "Mixing 25 cm vs 25 m; swapping concave/convex corrections; confusing dispersion with scattering.", "formula_panel", {"formula": "Checklist", "label": "Exam pitfalls"}, "Last-minute error avoid.", "Read MCQ options carefully.", "Three classic traps.", "", "", []),
        ("Safety reminders", "Never look directly at the Sun; prism activities use slit beams only.", "eye_light_path", {"mode": "safety"}, "Same safety culture as Unit 1.", "Teacher supervision for Sun demos.", "Protect eyes in all light labs.", "", "", []),
        ("Ready for practice", "You have covered 160 concept cards on the Human Eye and the Colourful World — use Practice to check understanding.", "eye_structure", {"highlight": "overview", "mode": "complete"}, "Bridge to Stage 2 practice.", "15 questions per session from 200-question bank.", "Concepts first, then practice.", "", "", []),
    ],
)

DAY_BUILDERS = {
    1: lambda: DAY1,
    2: lambda: DAY2,
    3: lambda: DAY3,
    4: lambda: DAY4,
    5: lambda: DAY5,
    6: lambda: DAY6,
    7: lambda: DAY7,
    8: lambda: DAY8,
    9: lambda: DAY9,
    10: lambda: DAY10,
    11: lambda: DAY11,
    12: lambda: DAY12,
    13: lambda: DAY13,
    14: lambda: DAY14,
    15: lambda: DAY15,
    16: lambda: DAY16,
}

DAY_TITLES = {
    1: "The Human Eye — Introduction",
    2: "Power of Accommodation",
    3: "Defects of Vision — Myopia and Hypermetropia",
    4: "Presbyopia, Lenses and Eye Donation",
    5: "Refraction Through a Prism",
    6: "Dispersion of White Light",
    7: "Rainbow and Atmospheric Refraction",
    8: "Scattering and the Colourful Sky",
    9: "Applications and NCERT Exercises",
    10: "Prism and Defects — Mixed Review",
    11: "Spectrum and Rainbow — Deep Dive",
    12: "Atmosphere and Scattering — Deep Dive",
    13: "Exam-style Diagrams and Definitions",
    14: "Long-answer Preparation",
    15: "Cross-links and Concept Maps",
    16: "Unit 2 Mastery Checklist",
}
