#!/usr/bin/env python3
"""Generate HarshitPhysics/unit1/logic_schema.json — Days 1–16 (160 concept cards)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from physics_unit1_days_5_16 import DAY_BUILDERS  # noqa: E402

OUT = ROOT / "HarshitPhysics" / "unit1" / "logic_schema.json"


def _card(
    cid: str,
    name: str,
    simple: str,
    visual_type: str,
    visual_config: dict | None,
    why: str,
    example: str,
    remember: str,
    confusion: str = "",
    optional: str = "",
    glossary: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "name": name,
        "simple_answer": simple,
        "visual": {"type": visual_type, **(visual_config or {})},
        "why": why,
        "example": example,
        "remember": remember,
        "common_confusion": confusion,
        "optional_detail": optional,
        "glossary_terms": glossary or [],
    }


DAY1 = [
    _card(
        "u1_d1_c01",
        "Luminous objects",
        "A luminous object produces its own light. You see it because light travels from the object to your eyes.",
        "light_source_model",
        {"highlight": "source"},
        "Light must be emitted before anything can be seen in darkness.",
        "The Sun, a burning candle, and a glowing bulb are luminous.",
        "Luminous means the object is the light source — not just bright-looking.",
        "A white wall in daylight is not luminous; it reflects sunlight.",
        "Luminous objects are primary sources of light in a scene.",
        ["luminous object", "light source"],
    ),
    _card(
        "u1_d1_c02",
        "Non-luminous objects",
        "Non-luminous objects do not make their own light. We see them when light from another source reflects off them.",
        "light_source_model",
        {"highlight": "reflector"},
        "Most things around you — books, walls, the Moon — are seen by reflected light.",
        "The Moon looks bright at night but shines by reflected sunlight.",
        "Non-luminous ≠ invisible. Reflection makes them visible.",
        "The Moon is not a light source; it reflects the Sun's light.",
        "",
        ["non-luminous", "reflected light"],
    ),
    _card(
        "u1_d1_c03",
        "Light source",
        "A light source is where light begins in a situation. It may be natural (Sun) or artificial (torch).",
        "light_source_model",
        {"highlight": "arrow_from_source"},
        "Tracing from source → object → eye helps explain any seeing situation.",
        "In a room, the bulb is usually the main light source.",
        "Always ask: where did the light start?",
        "",
        "",
        ["light source"],
    ),
    _card(
        "u1_d1_c04",
        "Reflected light",
        "When light hits a surface and bounces back, that bounced light is reflected light.",
        "straight_ray",
        {"mode": "reflect", "highlight": "reflected_ray"},
        "Reflected light from non-luminous objects enters your eye so you can see them.",
        "You see your face in a mirror because of reflected light.",
        "Reflection sends light back; it does not create new light.",
        "Reflection is not the same as refraction (bending through a medium).",
        "",
        ["reflected light", "reflection"],
    ),
    _card(
        "u1_d1_c05",
        "Light entering the eye",
        "Vision happens when light from an object enters your eye and forms a signal for your brain.",
        "eye_light_path",
        {"highlight": "eye"},
        "No light entering the eye means no image — even if the object is there.",
        "Light from a page reflects into your eyes when you read.",
        "See the path: source → object → eye.",
        "The eye detects light; it does not send light out to see (unlike a common cartoon idea).",
        "",
        ["vision"],
    ),
    _card(
        "u1_d1_c06",
        "Seeing in darkness",
        "In complete darkness there is no light to enter your eye, so objects cannot be seen — even if they are present.",
        "eye_light_path",
        {"mode": "dark"},
        "Light is necessary for sight in the usual way we describe Class 10 optics.",
        "In a closed dark room, a book on the table is invisible until you switch on a lamp.",
        "Darkness means insufficient light reaching the eye.",
        "Some animals see with very little light, but you still need some light to enter the eye.",
        "",
        ["darkness"],
    ),
    _card(
        "u1_d1_c07",
        "Straight-line propagation",
        "In a uniform medium, light travels in straight lines. This is called rectilinear propagation.",
        "straight_ray",
        {"mode": "straight", "highlight": "ray"},
        "Straight paths explain sharp shadows and why rays are drawn as straight lines.",
        "Sunlight through a small window makes a sharp bright patch on the floor.",
        "Light rays are drawn straight until reflection or refraction changes direction.",
        "Diffraction (bending around tiny openings) is a higher-class topic — not used in basic ray diagrams.",
        "At very small scales light behaves as a wave; in Class 10 we use the ray model.",
        ["rectilinear propagation", "ray"],
    ),
    _card(
        "u1_d1_c08",
        "Ray of light",
        "A ray is a straight line with an arrow showing the direction light travels. It is a useful model, not a thin physical beam.",
        "straight_ray",
        {"mode": "single_ray", "highlight": "arrow"},
        "Rays help us predict reflection and refraction without drawing every wave.",
        "An arrow from a bulb to a book shows light travelling toward the book.",
        "One arrow = one direction of light travel.",
        "A ray is a diagram tool; a real torch sends a wide beam of many rays.",
        "",
        ["ray of light"],
    ),
    _card(
        "u1_d1_c09",
        "Beam of light",
        "A beam is a collection of many rays travelling together, often from a torch or sunlight through clouds.",
        "straight_ray",
        {"mode": "beam", "highlight": "multiple_rays"},
        "Beams become easier to understand when you imagine many parallel rays side by side.",
        "A laser pointer in fog shows a visible beam because dust scatters light.",
        "A beam = many rays; a ray diagram often shows one representative ray.",
        "Do not look directly at the Sun or aim lasers at eyes — safety first.",
        "Laser demos should be teacher-supervised only.",
        ["beam of light"],
    ),
    _card(
        "u1_d1_c10",
        "Source → object → eye",
        "To explain seeing: light leaves a source, hits an object (often by reflection), then enters your eye.",
        "eye_light_path",
        {"mode": "full_path", "highlight": "path"},
        "This three-step model works for most everyday and NCERT situations.",
        "Sun → Moon (reflect) → your eye: you see the Moon.",
        "Draw the full path before deciding where an image forms.",
        "For a luminous object you may skip reflection off the object itself.",
        "",
        ["light path"],
    ),
]

DAY2 = [
    _card(
        "u1_d2_c01",
        "Reflecting surface",
        "A reflecting surface sends light back instead of absorbing it. Polished mirrors reflect strongly; rough surfaces scatter light.",
        "plane_mirror_reflection",
        {"highlight": "surface"},
        "Only the reflecting side of a mirror matters for ray diagrams.",
        "A calm pond reflects trees; a rough wall scatters light in many directions.",
        "Shiny and smooth surfaces give clearer reflections.",
        "All surfaces reflect some light — even dull ones (otherwise we could not see them).",
        "",
        ["reflecting surface"],
    ),
    _card(
        "u1_d2_c02",
        "Incident ray",
        "The incident ray is the incoming light ray that strikes a surface. The arrow points toward the surface.",
        "plane_mirror_reflection",
        {"highlight": "incident"},
        "Every reflection story starts with identifying the incident ray.",
        "Light from a torch hitting a mirror is drawn as the incident ray.",
        "Incident = incoming; arrow points to the surface.",
        "Do not confuse incident with reflected — direction of arrow matters.",
        "",
        ["incident ray"],
    ),
    _card(
        "u1_d2_c03",
        "Reflected ray",
        "The reflected ray leaves the surface after reflection. Its arrow points away from the surface.",
        "plane_mirror_reflection",
        {"highlight": "reflected"},
        "The reflected ray shows where light goes after bouncing.",
        "In a mirror you see objects because reflected rays enter your eye.",
        "Reflected ray arrow points away from the mirror.",
        "The reflected ray is not the same as the incident ray continued through the mirror.",
        "",
        ["reflected ray"],
    ),
    _card(
        "u1_d2_c04",
        "Point of incidence",
        "The point of incidence is the exact spot on the surface where the incident ray meets it.",
        "plane_mirror_reflection",
        {"highlight": "incidence_point"},
        "Angles and the normal are always drawn at this point.",
        "Where a laser dot hits a mirror is the point of incidence.",
        "Mark this point before drawing the normal.",
        "",
        "",
        ["point of incidence"],
    ),
    _card(
        "u1_d2_c05",
        "The normal",
        "The normal is an imaginary line perpendicular to the surface at the point of incidence.",
        "normal_angle",
        {"highlight": "normal"},
        "Angles of incidence and reflection are measured from the normal, not from the surface.",
        "At the spot where a ray hits a mirror, draw a dashed line at 90° to the mirror.",
        "Measure reflection angles from the normal, not from the mirror.",
        "The normal and the reflecting surface are different lines.",
        "",
        ["normal"],
    ),
    _card(
        "u1_d2_c06",
        "Angle of incidence",
        "The angle of incidence is measured between the incident ray and the normal at the point of incidence.",
        "normal_angle",
        {"highlight": "angle_i"},
        "It tells how steeply light arrives compared to the normal.",
        "A ray hitting head-on (along the normal) has zero angle of incidence.",
        "Use the arc between incident ray and normal — not the surface.",
        "Measuring from the mirror surface gives the wrong angle (common error).",
        "",
        ["angle of incidence"],
    ),
    _card(
        "u1_d2_c07",
        "Angle of reflection",
        "The angle of reflection is measured between the reflected ray and the normal at the point of incidence.",
        "normal_angle",
        {"highlight": "angle_r"},
        "It describes how steeply light leaves after reflection.",
        "If incidence is 30° from the normal, reflection is also 30° on the other side.",
        "Same side rule: both angles are measured from the normal on opposite sides of it.",
        "Do not measure reflection angle from the mirror surface.",
        "",
        ["angle of reflection"],
    ),
    _card(
        "u1_d2_c08",
        "First law of reflection",
        "The angle of incidence equals the angle of reflection, when both are measured from the normal.",
        "normal_angle",
        {"highlight": "equal_angles", "show_labels": True},
        "This law lets you predict the direction of the reflected ray.",
        "A ray at 40° to the normal reflects at 40° on the other side of the normal.",
        "i = r (both measured from the normal).",
        "Equal angles refer to incidence and reflection — not incident and refracted rays.",
        "",
        ["first law of reflection"],
    ),
    _card(
        "u1_d2_c09",
        "Second law of reflection",
        "The incident ray, the normal at the point of incidence, and the reflected ray all lie in the same plane.",
        "plane_mirror_reflection",
        {"highlight": "same_plane", "mode": "3d_hint"},
        "All three belong to one flat sheet — you draw them on one diagram plane.",
        "When you tilt the mirror, the whole ray diagram plane tilts with it.",
        "Same plane means one 2D diagram is enough for plane mirrors.",
        "",
        "",
        ["second law of reflection"],
    ),
    _card(
        "u1_d2_c10",
        "Plane-mirror image properties",
        "A plane mirror gives a virtual, erect image the same size as the object, as far behind the mirror as the object is in front.",
        "plane_mirror_reflection",
        {"mode": "image_properties", "highlight": "virtual_image"},
        "These properties explain why your mirror reflection looks life-sized and upright.",
        "You appear to stand as far behind the mirror as you stand in front of it.",
        "Virtual + erect + same size + laterally inverted.",
        "Virtual does not mean invisible — you see it, but light does not actually come from behind the mirror.",
        "",
        ["virtual image", "plane mirror"],
    ),
]

DAY3 = [
    _card(
        "u1_d3_c01",
        "Spherical reflecting surface",
        "A spherical mirror is part of a sphere's surface. Its curve affects how parallel rays converge or spread.",
        "spherical_mirror_labels",
        {"mirror_type": "concave", "highlight": "curved_surface"},
        "Curvature determines whether rays come together or spread apart.",
        "A shiny inside of a spoon is roughly a concave spherical surface.",
        "Spherical = part of a sphere; not flat like a plane mirror.",
        "",
        "",
        ["spherical mirror"],
    ),
    _card(
        "u1_d3_c02",
        "Concave mirror",
        "A concave mirror curves inward (reflecting surface faces the centre of the sphere). It tends to converge parallel rays.",
        "spherical_mirror_labels",
        {"mirror_type": "concave", "highlight": "reflecting_inward"},
        "Converging mirrors can form real images on a screen.",
        "The inner surface of a spoon facing you acts like a concave mirror.",
        "Concave = cave-like = curves in.",
        "Do not look at the Sun with a concave mirror — concentrated light can harm eyes.",
        "NCERT paper-burning demo: teacher demonstration only, never unsupervised.",
        ["concave mirror"],
    ),
    _card(
        "u1_d3_c03",
        "Convex mirror",
        "A convex mirror curves outward. Parallel rays reflect as if coming from a point behind the mirror — they diverge.",
        "spherical_mirror_labels",
        {"mirror_type": "convex", "highlight": "reflecting_outward"},
        "Diverging mirrors give wide views — useful for safety mirrors.",
        "The outer bulge of a spoon is like a convex mirror.",
        "Convex = bulges out toward the object.",
        "Convex mirrors always give virtual, erect, diminished images for real objects.",
        "",
        ["convex mirror"],
    ),
    _card(
        "u1_d3_c04",
        "Reflecting side",
        "Only the shiny, inner or outer curved face reflects strongly. The back of a mirror is usually painted and non-reflecting.",
        "spherical_mirror_labels",
        {"highlight": "reflecting_side"},
        "Ray diagrams always use the reflecting side of the mirror arc.",
        "In NCERT diagrams the shaded side is non-reflecting.",
        "Draw rays hitting the polished arc, not the back.",
        "",
        "",
        ["reflecting surface"],
    ),
    _card(
        "u1_d3_c05",
        "Pole (P)",
        "The pole P is the centre point of the mirror's reflecting surface. It lies on the mirror itself.",
        "spherical_mirror_labels",
        {"highlight": "P"},
        "P is often chosen as the origin in sign conventions.",
        "The middle of a spherical mirror strip is the pole.",
        "P is on the mirror; C is not on the mirror.",
        "Do not confuse P with F or C.",
        "",
        ["pole", "P"],
    ),
    _card(
        "u1_d3_c06",
        "Centre of curvature (C)",
        "C is the centre of the sphere of which the mirror forms a part. It lies on the principal axis, not on the mirror.",
        "spherical_mirror_labels",
        {"highlight": "C"},
        "Distance PC equals the radius of curvature R.",
        "For a concave mirror, C is in front of the reflecting surface.",
        "C is outside the mirror surface.",
        "For convex mirrors, C is behind the mirror.",
        "",
        ["centre of curvature", "C"],
    ),
    _card(
        "u1_d3_c07",
        "Radius of curvature (R)",
        "R is the radius of the sphere. For the mirror, PC = R.",
        "spherical_mirror_labels",
        {"highlight": "R", "show_R_segment": True},
        "R links the mirror's size to its focusing strength.",
        "If PC is 12 cm, then R = 12 cm.",
        "R = 2f for small-aperture spherical mirrors.",
        "Do not use R and f as the same number without checking R = 2f.",
        "",
        ["radius of curvature", "R"],
    ),
    _card(
        "u1_d3_c08",
        "Principal axis",
        "The principal axis is the straight line through P and C, perpendicular to the mirror at P.",
        "spherical_mirror_labels",
        {"highlight": "principal_axis"},
        "Most standard rays are drawn parallel to or through points on this axis.",
        "Imagine a line through the middle of a spherical mirror strip.",
        "Principal axis passes through P and C.",
        "",
        "",
        ["principal axis"],
    ),
    _card(
        "u1_d3_c09",
        "Aperture",
        "The aperture is the diameter of the reflecting surface. NCERT often uses small-aperture mirrors where R = 2f holds well.",
        "spherical_mirror_labels",
        {"highlight": "aperture"},
        "Small aperture keeps the spherical mirror formula simple in Class 10.",
        "The width MN of the mirror opening is the aperture in diagrams.",
        "Large mirrors break the small-angle approximation used in school formulas.",
        "",
        "",
        ["aperture"],
    ),
    _card(
        "u1_d3_c10",
        "Mirror-type identification",
        "Concave: reflecting surface faces inward. Convex: reflecting surface bulges outward. Compare which side is shiny.",
        "spherical_mirror_labels",
        {"mode": "compare", "highlight": "both_types"},
        "Correct identification picks the right ray rules and image properties.",
        "Shiny inside of spoon ≈ concave; shiny outside bulge ≈ convex.",
        "Ask: does the mirror surface hug the centre or push away from it?",
        "Students often swap concave and convex — check the reflecting side.",
        "",
        ["concave mirror", "convex mirror"],
    ),
]

DAY4 = [
    _card(
        "u1_d4_c01",
        "Principal focus (F)",
        "F is the point on the principal axis where rays parallel to the axis converge (concave) or appear to diverge from (convex).",
        "mirror_focus_ray",
        {"mirror_type": "concave", "highlight": "F"},
        "F is where parallel beams are focused or seem to spread from.",
        "Sunlight parallel to the axis meets near F for a concave mirror.",
        "Label F on the principal axis between P and C for concave mirrors.",
        "F is not the same as C — F is midway between P and C when R = 2f.",
        "",
        ["principal focus", "F"],
    ),
    _card(
        "u1_d4_c02",
        "Focal length (f)",
        "Focal length f is the distance from pole P to principal focus F along the principal axis.",
        "mirror_focus_ray",
        {"highlight": "f_segment"},
        "f measures how strongly a mirror converges or diverges light.",
        "If PF = 6 cm, then f = 6 cm (for that mirror).",
        "f is measured from P to F — not from C to F unless you know R = 2f.",
        "",
        "",
        ["focal length", "f"],
    ),
    _card(
        "u1_d4_c03",
        "Real focus",
        "For a concave mirror, parallel rays actually meet at F after reflection. The focus is real — light converges there.",
        "mirror_focus_ray",
        {"mirror_type": "concave", "highlight": "real_focus"},
        "Real focus allows a hot spot on paper — teacher demo only, never at the Sun unsupervised.",
        "Sharp bright spot on paper when sunlight is parallel to the axis.",
        "Real focus = rays actually cross.",
        "Real focus does not mean the image is always erect.",
        "Sun-concentration activities require adult supervision; use simulations when possible.",
        ["real focus"],
    ),
    _card(
        "u1_d4_c04",
        "Virtual focus",
        "For a convex mirror, reflected rays do not actually meet; they appear to come from F behind the mirror.",
        "mirror_focus_ray",
        {"mirror_type": "convex", "highlight": "virtual_focus"},
        "Virtual focus is found by extending reflected rays backward as dotted lines.",
        "Convex rear-view mirrors seem to have a focus behind the glass.",
        "Virtual focus — extend rays backward to locate F.",
        "Virtual focus is still a useful diagram point even though light does not cross there.",
        "",
        ["virtual focus"],
    ),
    _card(
        "u1_d4_c05",
        "Converging mirror",
        "A converging mirror brings parallel rays closer together. Concave mirrors are converging mirrors.",
        "mirror_focus_ray",
        {"mirror_type": "concave", "highlight": "converging"},
        "Converging mirrors can project real images onto screens.",
        "Parallel rays from a distant object meet near F of a concave mirror.",
        "Concave = converging.",
        "",
        "",
        ["converging mirror"],
    ),
    _card(
        "u1_d4_c06",
        "Diverging mirror",
        "A diverging mirror spreads parallel rays apart. Convex mirrors are diverging mirrors.",
        "mirror_focus_ray",
        {"mirror_type": "convex", "highlight": "diverging"},
        "Diverging mirrors give wider fields of view with smaller images.",
        "Parallel rays reflect as if coming from F behind a convex mirror.",
        "Convex = diverging.",
        "",
        "",
        ["diverging mirror"],
    ),
    _card(
        "u1_d4_c07",
        "Parallel incident rays",
        "Rays from a very distant object are nearly parallel to the principal axis when they reach the mirror.",
        "mirror_focus_ray",
        {"highlight": "parallel_incident"},
        "Parallel rays are the standard starting ray in mirror diagrams.",
        "Sunlight on a mirror is often drawn as parallel rays.",
        "Parallel to axis → reflects through F (concave) or appears from F (convex).",
        "",
        "",
        ["parallel rays"],
    ),
    _card(
        "u1_d4_c08",
        "Reflected-ray behaviour",
        "After reflection, concave rays converge toward F; convex rays spread so backward extensions meet at F behind the mirror.",
        "mirror_focus_ray",
        {"mode": "both", "highlight": "reflected"},
        "Knowing the pattern lets you sketch images quickly.",
        "Compare concave and convex diagrams side by side.",
        "Draw reflected arrows away from mirror; extend backward for convex.",
        "Do not bend rays toward the wrong focus type.",
        "",
        ["reflected ray"],
    ),
    _card(
        "u1_d4_c09",
        "Relationship R = 2f",
        "For spherical mirrors of small aperture, radius of curvature R equals twice the focal length: R = 2f.",
        "mirror_focus_ray",
        {"highlight": "R_2f", "show_segments": True},
        "Links measurable R to the useful quantity f in problems.",
        "If f = 5 cm, then R = 10 cm and PC = 10 cm.",
        "R = 2f → F lies midway between P and C.",
        "Using f when you mean R (or vice versa) is a common numerical error.",
        "",
        ["R = 2f"],
    ),
    _card(
        "u1_d4_c10",
        "Position of F between P and C",
        "For a concave mirror, F lies on the principal axis between pole P and centre C — closer to P.",
        "mirror_focus_ray",
        {"mirror_type": "concave", "highlight": "P_F_C"},
        "Order on axis: P — F — C for concave mirrors.",
        "When marking a mirror setup, place F halfway between P and C if R = 2f.",
        "P–F–C order on the same side as the object for concave mirrors.",
        "F is not at C unless f = R/2 still places F between them when R = 2f.",
        "",
        ["principal axis"],
    ),
]


def build_schema() -> dict:
    days = [
        {"day": 1, "stage": 1, "title": "How We See and Represent Light", "active": True, "release": 1, "concepts": DAY1},
        {"day": 2, "stage": 1, "title": "Reflection and Plane Mirrors", "active": True, "release": 1, "concepts": DAY2},
        {"day": 3, "stage": 1, "title": "Spherical Mirrors", "active": True, "release": 1, "concepts": DAY3},
        {"day": 4, "stage": 1, "title": "Focus and Mirror Ray Behaviour", "active": True, "release": 1, "concepts": DAY4},
    ]
    for day_num, (title, builder) in sorted(DAY_BUILDERS.items()):
        days.append(
            {
                "day": day_num,
                "stage": 1,
                "title": title,
                "active": True,
                "release": (day_num - 1) // 4 + 1,
                "concepts": builder(),
            }
        )

    return {
        "meta": {
            "student": "Harshit Sai",
            "unit_id": 1,
            "unit_title": "Light – Reflection and Refraction",
            "ncert": "Class 10 Science, Chapter 9",
            "stage1_days": 16,
            "stage2_days": 4,
            "concept_cards_total": 160,
            "mcq_total": 40,
            "release_active": 4,
            "session_kind_concepts": "harshit_physics_unit1_concepts",
            "session_kind_mcq": "harshit_physics_unit1_mcq",
        },
        "glossary": [
            {"term": "luminous object", "definition": "An object that produces its own light."},
            {"term": "non-luminous", "definition": "An object seen by reflected light, not by its own emission."},
            {"term": "ray of light", "definition": "A straight line showing direction of light travel."},
            {"term": "normal", "definition": "A line perpendicular to a surface at the point of incidence."},
            {"term": "angle of incidence", "definition": "Angle between incident ray and normal."},
            {"term": "angle of reflection", "definition": "Angle between reflected ray and normal."},
            {"term": "virtual image", "definition": "An image from which rays appear to come; rays do not actually meet there."},
            {"term": "concave mirror", "definition": "Spherical mirror with inward-curving reflecting surface."},
            {"term": "convex mirror", "definition": "Spherical mirror with outward-bulging reflecting surface."},
            {"term": "pole (P)", "definition": "Centre point of the mirror surface."},
            {"term": "centre of curvature (C)", "definition": "Centre of the sphere; lies on principal axis."},
            {"term": "principal focus (F)", "definition": "Point where parallel rays converge or appear to diverge from."},
            {"term": "focal length (f)", "definition": "Distance from pole P to principal focus F."},
            {"term": "radius of curvature (R)", "definition": "Radius of the sphere; PC = R; often R = 2f."},
            {"term": "real image", "definition": "Formed where light rays actually meet; can appear on a screen."},
            {"term": "refraction", "definition": "Bending of light when it passes between two media."},
            {"term": "refractive index (n)", "definition": "Ratio c/v; no unit; higher n means slower light."},
            {"term": "convex lens", "definition": "Thicker at middle; converges light; f positive."},
            {"term": "concave lens", "definition": "Thinner at middle; diverges light; f negative."},
            {"term": "power of lens (P)", "definition": "P = 1/f with f in metres; unit dioptre (D)."},
            {"term": "magnification (m)", "definition": "Ratio of image size to object size; sign shows orientation."},
        ],
        "days": days,
    }


def main() -> None:
    schema = build_schema()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(schema, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    active_cards = sum(len(d["concepts"]) for d in schema["days"] if d.get("active"))
    print(f"Wrote {OUT} — {active_cards} active concept cards (Days 1–16)")


if __name__ == "__main__":
    main()
